* Baruch 1

** Baruch 1:1

Et hæc verba libri quæ scripsit Baruch filius Neriæ, filii Maasiæ, filii Sedeciæ, filii Sedei, filii Helciæ, in Babylonia,

** Baruch 1:2

in anno quinto, in septimo die mensis, in tempore quo ceperunt Chaldæi Jerusalem, et succenderunt eam igni.

** Baruch 1:3

Et legit Baruch verba libri hujus ad aures Jechoniæ filii Joakim regis Juda, et ad aures universi populi venientis ad librum,

** Baruch 1:4

et ad aures potentium, filiorum regum, et ad aures presbyterorum, et ad aures populi, a minimo usque ad maximum eorum, omnium habitantium in Babylonia, ad flumen Sodi.

** Baruch 1:5

Qui audientes plorabant, et jejunabant, et orabant in conspectu Domini.

** Baruch 1:6

Et collegerunt pecuniam, secundum quod potuit uniuscujusque manus,

** Baruch 1:7

et miserunt in Jerusalem ad Joakim filium Helciæ filii Salom sacerdotem, et ad sacerdotes, et ad omnem populum qui inventi sunt cum eo in Jerusalem :

** Baruch 1:8

cum acciperet vasa templi Domini, quæ ablata fuerant de templo, revocare in terram Juda, decima die mensis Sivan, vasa argentea quæ fecit Sedecias filius Josiæ rex Juda,

** Baruch 1:9

posteaquam cepisset Nabuchodonosor rex Babylonis Jechoniam, et principes, et cunctos potentes, et populum terræ, ab Jerusalem, et duxit eos vinctos in Babylonem.

** Baruch 1:10

Et dixerunt : Ecce misimus ad vos pecunias, de quibus emite holocautomata et thus : et facite manna, et offerte pro peccato, ad aram Domini Dei nostri :

** Baruch 1:11

et orate pro vita Nabuchodonosor regis Babylonis, et pro vita Baltassar filii ejus, ut sint dies eorum sicut dies cæli super terram :

** Baruch 1:12

et ut det Dominus virtutem nobis, et illuminet oculos nostros, ut vivamus sub umbra Nabuchodonosor regis Babylonis, et sub umbra Baltassar filii ejus, et serviamus eis multis diebus, et inveniamus gratiam in conspectu eorum.

** Baruch 1:13

Et pro nobis ipsis orate ad Dominum Deum nostrum, quia peccavimus Domino Deo nostro, et non est aversus furor ejus a nobis usque in hunc diem.

** Baruch 1:14

Et legite librum istum quem misimus ad vos recitari in templo Domini, in die solemni et in die opportuno :

** Baruch 1:15

et dicetis : <div eID="gen26655" type="x-p"/> <lg sID="gen26656"/> <l level="1" sID="gen26657"/>Domino Deo nostro justitia, <l eID="gen26657" level="1"/> <l level="1" sID="gen26658"/>nobis autem confusio faciei nostræ, <l eID="gen26658" level="1"/> <l level="1" sID="gen26659"/>sicut est dies hæc omni Juda, <l eID="gen26659" level="1"/> <l level="1" sID="gen26660"/>et habitantibus in Jerusalem : <l eID="gen26660" level="1"/>

** Baruch 1:16

regibus nostris, et principibus nostris, <l eID="gen26661" level="1"/> <l level="1" sID="gen26662"/>et sacerdotibus nostris, et prophetis nostris, <l eID="gen26662" level="1"/> <l level="1" sID="gen26663"/>et patribus nostris. <l eID="gen26663" level="1"/>

** Baruch 1:17

Peccavimus ante Dominum Deum nostrum, <l eID="gen26664" level="1"/> <l level="1" sID="gen26665"/>et non credidimus, diffidentes in eum : <l eID="gen26665" level="1"/>

** Baruch 1:18

et non fuimus subjectibiles illi, <l eID="gen26666" level="1"/> <l level="1" sID="gen26667"/>et non audivimus vocem Domini Dei nostri, <l eID="gen26667" level="1"/> <l level="1" sID="gen26668"/>ut ambularemus in mandatis ejus, quæ dedit nobis. <l eID="gen26668" level="1"/>

** Baruch 1:19

A die qua eduxit patres nostros de terra Ægypti, <l eID="gen26669" level="1"/> <l level="1" sID="gen26670"/>usque ad diem hanc, <l eID="gen26670" level="1"/> <l level="1" sID="gen26671"/>eramus incredibiles ad Dominum Deum nostrum : <l eID="gen26671" level="1"/> <l level="1" sID="gen26672"/>et dissipati recessimus, ne audiremus vocem ipsius : <l eID="gen26672" level="1"/>

** Baruch 1:20

et adhæserunt nobis multa mala et maledictiones <l eID="gen26673" level="1"/> <l level="1" sID="gen26674"/>quæ constituit Dominus Moysi servo suo, <l eID="gen26674" level="1"/> <l level="1" sID="gen26675"/>qui eduxit patres nostros de terra Ægypti, <l eID="gen26675" level="1"/> <l level="1" sID="gen26676"/>dare nobis terram fluentem lac et mel, sicut hodierna die. <l eID="gen26676" level="1"/>

** Baruch 1:21

Et non audivimus vocem Domini Dei nostri, <l eID="gen26677" level="1"/> <l level="1" sID="gen26678"/>secundum omnia verba prophetarum quos misit ad nos : <l eID="gen26678" level="1"/>

** Baruch 1:22

et abivimus unusquisque in sensum cordis nostri maligni, <l eID="gen26679" level="1"/> <l level="1" sID="gen26680"/>operari diis alienis, <l eID="gen26680" level="1"/> <l level="1" sID="gen26681"/>facientes mala ante oculos Domini Dei nostri.  <chapter eID="Bar.1"/>

* Baruch 2

** Baruch 2:1

Propter quod statuit Dominus Deus noster verbum suum, <l eID="gen26682" level="1"/> <l level="1" sID="gen26683"/>quod locutus est ad nos, <l eID="gen26683" level="1"/> <l level="1" sID="gen26684"/>et ad judices nostros qui judicaverunt Israël, <l eID="gen26684" level="1"/> <l level="1" sID="gen26685"/>et ad reges nostros, et ad principes nostros, <l eID="gen26685" level="1"/> <l level="1" sID="gen26686"/>et ad omnem Israël et Juda : <l eID="gen26686" level="1"/>

** Baruch 2:2

ut adduceret Dominus super nos mala magna, <l eID="gen26687" level="1"/> <l level="1" sID="gen26688"/>quæ non sunt facta sub cælo <l eID="gen26688" level="1"/> <l level="1" sID="gen26689"/>quemadmodum facta sunt in Jerusalem, <l eID="gen26689" level="1"/> <l level="1" sID="gen26690"/>secundum quæ scripta sunt in lege Moysi, <l eID="gen26690" level="1"/>

** Baruch 2:3

et manducaret homo carnes filii sui et carnes filiæ suæ. <l eID="gen26691" level="1"/>

** Baruch 2:4

Et dedit eos sub manu regum omnium qui sunt in circuitu nostro, <l eID="gen26692" level="1"/> <l level="1" sID="gen26693"/>in improperium et in desolationem in omnibus populis <l eID="gen26693" level="1"/> <l level="1" sID="gen26694"/>in quibus nos dispersit Dominus : <l eID="gen26694" level="1"/>

** Baruch 2:5

et facti sumus subtus, et non supra, <l eID="gen26695" level="1"/> <l level="1" sID="gen26696"/>quia peccavimus Domino Deo nostro, <l eID="gen26696" level="1"/> <l level="1" sID="gen26697"/>non obaudiendo voci ipsius. <l eID="gen26697" level="1"/>

** Baruch 2:6

Domino Deo nostro justitia, <l eID="gen26698" level="1"/> <l level="1" sID="gen26699"/>nobis autem et patribus nostris confusio faciei, <l eID="gen26699" level="1"/> <l level="1" sID="gen26700"/>sicut est dies hæc : <l eID="gen26700" level="1"/>

** Baruch 2:7

quia locutus est Dominus super nos omnia mala hæc <l eID="gen26701" level="1"/> <l level="1" sID="gen26702"/>quæ venerunt super nos : <l eID="gen26702" level="1"/>

** Baruch 2:8

et non sumus deprecati faciem Domini Dei nostri, <l eID="gen26703" level="1"/> <l level="1" sID="gen26704"/>ut reverteremur unusquisque nostrum a viis nostris pessimis. <l eID="gen26704" level="1"/>

** Baruch 2:9

Et vigilavit Dominus in malis, <l eID="gen26705" level="1"/> <l level="1" sID="gen26706"/>et adduxit ea super nos : <l eID="gen26706" level="1"/> <l level="1" sID="gen26707"/>quia justus est Dominus in omnibus operibus suis <l eID="gen26707" level="1"/> <l level="1" sID="gen26708"/>quæ mandavit nobis, <l eID="gen26708" level="1"/>

** Baruch 2:10

et non audivimus vocem ipsius <l eID="gen26709" level="1"/> <l level="1" sID="gen26710"/>ut iremus in præceptis Domini, <l eID="gen26710" level="1"/> <l level="1" sID="gen26711"/>quæ dedit ante faciem nostram. <l eID="gen26711" level="1"/>

** Baruch 2:11

Et nunc, Domine Deus Israël, <l eID="gen26712" level="1"/> <l level="1" sID="gen26713"/>qui eduxisti populum tuum de terra Ægypti <l eID="gen26713" level="1"/> <l level="1" sID="gen26714"/>in manu valida, et in signis, et in prodigiis, <l eID="gen26714" level="1"/> <l level="1" sID="gen26715"/>et in virtute tua magna, et in brachio excelso, <l eID="gen26715" level="1"/> <l level="1" sID="gen26716"/>et fecisti tibi nomen sicut est dies iste : <l eID="gen26716" level="1"/>

** Baruch 2:12

peccavimus, impie egimus, <l eID="gen26717" level="1"/> <l level="1" sID="gen26718"/>inique gessimus, Domine Deus noster, <l eID="gen26718" level="1"/> <l level="1" sID="gen26719"/>in omnibus justitiis tuis. <l eID="gen26719" level="1"/>

** Baruch 2:13

Avertatur ira tua a nobis, <l eID="gen26720" level="1"/> <l level="1" sID="gen26721"/>quia derelicti sumus pauci inter gentes ubi dispersisti nos. <l eID="gen26721" level="1"/>

** Baruch 2:14

Exaudi, Domine, preces nostras et orationes nostras, <l eID="gen26722" level="1"/> <l level="1" sID="gen26723"/>et educ nos propter te, <l eID="gen26723" level="1"/> <l level="1" sID="gen26724"/>et da nobis invenire gratiam ante faciem eorum qui nos abduxerunt : <l eID="gen26724" level="1"/>

** Baruch 2:15

ut sciat omnis terra quia tu es Dominus Deus noster, <l eID="gen26725" level="1"/> <l level="1" sID="gen26726"/>et quia nomen tuum invocatum est super Israël, <l eID="gen26726" level="1"/> <l level="1" sID="gen26727"/>et super genus ipsius. <l eID="gen26727" level="1"/>

** Baruch 2:16

Respice, Domine, de domo sancta tua in nos, <l eID="gen26728" level="1"/> <l level="1" sID="gen26729"/>et inclina aurem tuam, et exaudi nos. <l eID="gen26729" level="1"/>

** Baruch 2:17

Aperi oculos tuos et vide : <l eID="gen26730" level="1"/> <l level="1" sID="gen26731"/>quia non mortui qui sunt in inferno, <l eID="gen26731" level="1"/> <l level="1" sID="gen26732"/>quorum spiritus acceptus est a visceribus suis, <l eID="gen26732" level="1"/> <l level="1" sID="gen26733"/>dabunt honorem et justificationem Domino : <l eID="gen26733" level="1"/>

** Baruch 2:18

sed anima quæ tristis est super magnitudine mali, <l eID="gen26734" level="1"/> <l level="1" sID="gen26735"/>et incedit curva et infirma, <l eID="gen26735" level="1"/> <l level="1" sID="gen26736"/>et oculi deficientes, et anima esuriens, <l eID="gen26736" level="1"/> <l level="1" sID="gen26737"/>dat tibi gloriam et justitiam Domino. <l eID="gen26737" level="1"/>

** Baruch 2:19

Quia non secundum justitias patrum nostrorum <l eID="gen26738" level="1"/> <l level="1" sID="gen26739"/>nos fundimus preces et petimus misericordiam <l eID="gen26739" level="1"/> <l level="1" sID="gen26740"/>ante conspectum tuum, Domine Deus noster : <l eID="gen26740" level="1"/>

** Baruch 2:20

sed quia misisti iram tuam et furorem tuum super nos, <l eID="gen26741" level="1"/> <l level="1" sID="gen26742"/>sicut locutus es in manu puerorum tuorum prophetarum, <l eID="gen26742" level="1"/> <l level="1" sID="gen26743"/>dicens :

** Baruch 2:21

Sic dicit Dominus : <l eID="gen26743" level="1"/> <l level="1" sID="gen26744"/>Inclinate humerum vestrum et cervicem vestram, <l eID="gen26744" level="1"/> <l level="1" sID="gen26745"/>et opera facite regi Babylonis, <l eID="gen26745" level="1"/> <l level="1" sID="gen26746"/>et sedebitis in terra quam dedi patribus vestris. <l eID="gen26746" level="1"/>

** Baruch 2:22

Quod si non audieritis vocem Domini Dei vestri, <l eID="gen26747" level="1"/> <l level="1" sID="gen26748"/>operari regi Babyloniæ, <l eID="gen26748" level="1"/> <l level="1" sID="gen26749"/>defectionem vestram faciam de civitatibus Juda, <l eID="gen26749" level="1"/> <l level="1" sID="gen26750"/>et a foris Jerusalem, <l eID="gen26750" level="1"/>

** Baruch 2:23

et auferam a vobis vocem jucunditatis et vocem gaudii, <l eID="gen26751" level="1"/> <l level="1" sID="gen26752"/>et vocem sponsi et vocem sponsæ, <l eID="gen26752" level="1"/> <l level="1" sID="gen26753"/>et erit omnis terra sine vestigio ab inhabitantibus eam. <l eID="gen26753" level="1"/>

** Baruch 2:24

Et non audierunt vocem tuam, <l eID="gen26754" level="1"/> <l level="1" sID="gen26755"/>ut operarentur regi Babylonis : <l eID="gen26755" level="1"/> <l level="1" sID="gen26756"/>et statuisti verba tua, <l eID="gen26756" level="1"/> <l level="1" sID="gen26757"/>quæ locutus es in manibus puerorum tuorum prophetarum, <l eID="gen26757" level="1"/> <l level="1" sID="gen26758"/>ut transferrentur ossa regum nostrorum <l eID="gen26758" level="1"/> <l level="1" sID="gen26759"/>et ossa patrum nostrorum de loco suo : <l eID="gen26759" level="1"/>

** Baruch 2:25

et ecce projecta sunt in calore solis et in gelu noctis, <l eID="gen26760" level="1"/> <l level="1" sID="gen26761"/>et mortui sunt in doloribus pessimis, <l eID="gen26761" level="1"/> <l level="1" sID="gen26762"/>in fame et in gladio, et in emissione. <l eID="gen26762" level="1"/>

** Baruch 2:26

Et posuisti templum in quo invocatum est nomen tuum in ipso <l eID="gen26763" level="1"/> <l level="1" sID="gen26764"/>sicut hæc dies, <l eID="gen26764" level="1"/> <l level="1" sID="gen26765"/>propter iniquitatem domus Israël et domus Juda. <l eID="gen26765" level="1"/>

** Baruch 2:27

Et fecisti in nobis, Domine Deus noster, <l eID="gen26766" level="1"/> <l level="1" sID="gen26767"/>secundum omnem bonitatem tuam <l eID="gen26767" level="1"/> <l level="1" sID="gen26768"/>et secundum omnem miserationem tuam illam magnam : <l eID="gen26768" level="1"/>

** Baruch 2:28

sicut locutus es in manu pueri tui Moysi, <l eID="gen26769" level="1"/> <l level="1" sID="gen26770"/>in die qua præcepisti ei scribere legem tuam coram filiis Israël, <l eID="gen26770" level="1"/>

** Baruch 2:29

dicens : Si non audieritis vocem meam, <l eID="gen26771" level="1"/> <l level="1" sID="gen26772"/>multitudo hæc magna convertetur in minimam inter gentes, <l eID="gen26772" level="1"/> <l level="1" sID="gen26773"/>quo ego eos dispergam : <l eID="gen26773" level="1"/>

** Baruch 2:30

quia scio quod me non audiet populus : <l eID="gen26774" level="1"/> <l level="1" sID="gen26775"/>populus est enim dura cervice. <l eID="gen26775" level="1"/> <l level="1" sID="gen26776"/>Et convertetur ad cor suum in terra captivitatis suæ, <l eID="gen26776" level="1"/>

** Baruch 2:31

et scient quia ego sum Dominus Deus eorum : <l eID="gen26777" level="1"/> <l level="1" sID="gen26778"/>et dabo eis cor, et intelligent ; <l eID="gen26778" level="1"/> <l level="1" sID="gen26779"/>aures, et audient : <l eID="gen26779" level="1"/>

** Baruch 2:32

et laudabunt me in terra captivitatis suæ, <l eID="gen26780" level="1"/> <l level="1" sID="gen26781"/>et memores erunt nominis mei, <l eID="gen26781" level="1"/>

** Baruch 2:33

et avertent se a dorso suo duro, <l eID="gen26782" level="1"/> <l level="1" sID="gen26783"/>et a malignitatibus suis : <l eID="gen26783" level="1"/> <l level="1" sID="gen26784"/>quia reminiscentur viam patrum suorum, <l eID="gen26784" level="1"/> <l level="1" sID="gen26785"/>qui peccaverunt in me. <l eID="gen26785" level="1"/>

** Baruch 2:34

Et revocabo illos in terram quam juravi patribus eorum, <l eID="gen26786" level="1"/> <l level="1" sID="gen26787"/>Abraham, Isaac, et Jacob : <l eID="gen26787" level="1"/> <l level="1" sID="gen26788"/>et dominabuntur ejus, et multiplicabo eos, <l eID="gen26788" level="1"/> <l level="1" sID="gen26789"/>et non minorabuntur : <l eID="gen26789" level="1"/>

** Baruch 2:35

et statuam illis testamentum alterum sempiternum, <l eID="gen26790" level="1"/> <l level="1" sID="gen26791"/>ut sim illis in Deum, <l eID="gen26791" level="1"/> <l level="1" sID="gen26792"/>et ipsi erunt mihi in populum : <l eID="gen26792" level="1"/> <l level="1" sID="gen26793"/>et non movebo amplius populum meum, filios Israël, <l eID="gen26793" level="1"/> <l level="1" sID="gen26794"/>a terra quam dedi illis.  <chapter eID="Bar.2"/>

* Baruch 3

** Baruch 3:1

Et nunc, Domine omnipotens, Deus Israël, <l eID="gen26795" level="1"/> <l level="1" sID="gen26796"/>anima in angustiis, et spiritus anxius clamat ad te. <l eID="gen26796" level="1"/>

** Baruch 3:2

Audi, Domine, et miserere, <l eID="gen26797" level="1"/> <l level="1" sID="gen26798"/>quia Deus es misericors : <l eID="gen26798" level="1"/> <l level="1" sID="gen26799"/>et miserere nostri, quia peccavimus ante te : <l eID="gen26799" level="1"/>

** Baruch 3:3

quia tu sedes in sempiternum, <l eID="gen26800" level="1"/> <l level="1" sID="gen26801"/>et nos, peribimus in ævum ? <l eID="gen26801" level="1"/>

** Baruch 3:4

Domine omnipotens, Deus Israël, <l eID="gen26802" level="1"/> <l level="1" sID="gen26803"/>audi nunc orationem mortuorum Israël, <l eID="gen26803" level="1"/> <l level="1" sID="gen26804"/>et filiorum ipsorum qui peccaverunt ante te, <l eID="gen26804" level="1"/> <l level="1" sID="gen26805"/>et non audierunt vocem Domini Dei sui, <l eID="gen26805" level="1"/> <l level="1" sID="gen26806"/>et agglutinata sunt nobis mala. <l eID="gen26806" level="1"/>

** Baruch 3:5

Noli meminisse iniquitatum patrum nostrorum, <l eID="gen26807" level="1"/> <l level="1" sID="gen26808"/>sed memento manus tuæ et nominis tui in tempore isto : <l eID="gen26808" level="1"/>

** Baruch 3:6

quia tu es Dominus Deus noster, <l eID="gen26809" level="1"/> <l level="1" sID="gen26810"/>et laudabimus te, Domine : <l eID="gen26810" level="1"/>

** Baruch 3:7

quia propter hoc dedisti timorem tuum in cordibus nostris, <l eID="gen26811" level="1"/> <l level="1" sID="gen26812"/>et ut invocemus nomen tuum, <l eID="gen26812" level="1"/> <l level="1" sID="gen26813"/>et laudemus te in captivitate nostra, <l eID="gen26813" level="1"/> <l level="1" sID="gen26814"/>quia convertimur ab iniquitate patrum nostrorum, <l eID="gen26814" level="1"/> <l level="1" sID="gen26815"/>qui peccaverunt ante te. <l eID="gen26815" level="1"/>

** Baruch 3:8

Et ecce nos in captivitate nostra sumus hodie, <l eID="gen26816" level="1"/> <l level="1" sID="gen26817"/>qua nos dispersisti in improperium, <l eID="gen26817" level="1"/> <l level="1" sID="gen26818"/>et in maledictum, et in peccatum, <l eID="gen26818" level="1"/> <l level="1" sID="gen26819"/>secundum omnes iniquitates patrum nostrorum, <l eID="gen26819" level="1"/> <l level="1" sID="gen26820"/>qui recesserunt a te, Domine Deus noster. <l eID="gen26820" level="1"/>

** Baruch 3:9

Audi, Israël, mandata vitæ : <l eID="gen26821" level="1"/> <l level="1" sID="gen26822"/>auribus percipe, ut scias prudentiam. <l eID="gen26822" level="1"/>

** Baruch 3:10

Quid est, Israël, quod in terra inimicorum es, <l eID="gen26823" level="1"/>

** Baruch 3:11

inveterasti in terra aliena, <l eID="gen26824" level="1"/> <l level="1" sID="gen26825"/>coinquinatus es cum mortuis, <l eID="gen26825" level="1"/> <l level="1" sID="gen26826"/>deputatus es cum descendentibus in infernum ? <l eID="gen26826" level="1"/>

** Baruch 3:12

Dereliquisti fontem sapientiæ : <l eID="gen26827" level="1"/>

** Baruch 3:13

nam si in via Dei ambulasses, <l eID="gen26828" level="1"/> <l level="1" sID="gen26829"/>habitasses utique in pace sempiterna. <l eID="gen26829" level="1"/>

** Baruch 3:14

Disce ubi sit prudentia, <l eID="gen26830" level="1"/> <l level="1" sID="gen26831"/>ubi sit virtus, ubi sit intellectus, <l eID="gen26831" level="1"/> <l level="1" sID="gen26832"/>ut scias simul ubi sit longiturnitas vitæ et victus, <l eID="gen26832" level="1"/> <l level="1" sID="gen26833"/>ubi sit lumen oculorum, et pax. <l eID="gen26833" level="1"/>

** Baruch 3:15

Quis invenit locum ejus ? <l eID="gen26834" level="1"/> <l level="1" sID="gen26835"/>et quis intravit in thesauros ejus ? <l eID="gen26835" level="1"/>

** Baruch 3:16

Ubi sunt principes gentium, <l eID="gen26836" level="1"/> <l level="1" sID="gen26837"/>et qui dominantur super bestias quæ sunt super terram ? <l eID="gen26837" level="1"/>

** Baruch 3:17

qui in avibus cæli ludunt, <l eID="gen26838" level="1"/>

** Baruch 3:18

qui argentum thesaurizant, et aurum, <l eID="gen26839" level="1"/> <l level="1" sID="gen26840"/>in quo confidunt homines, <l eID="gen26840" level="1"/> <l level="1" sID="gen26841"/>et non est finis acquisitionis eorum ? <l eID="gen26841" level="1"/> <l level="1" sID="gen26842"/>qui argentum fabricant, et solliciti sunt, <l eID="gen26842" level="1"/> <l level="1" sID="gen26843"/>nec est inventio operum illorum ? <l eID="gen26843" level="1"/>

** Baruch 3:19

Exterminati sunt, et ad inferos descenderunt, <l eID="gen26844" level="1"/> <l level="1" sID="gen26845"/>et alii loco eorum surrexerunt. <l eID="gen26845" level="1"/>

** Baruch 3:20

Juvenes viderunt lumen, et habitaverunt super terram, <l eID="gen26846" level="1"/> <l level="1" sID="gen26847"/>viam autem disciplinæ ignoraverunt, <l eID="gen26847" level="1"/>

** Baruch 3:21

neque intellexerunt semitas ejus, <l eID="gen26848" level="1"/> <l level="1" sID="gen26849"/>neque filii eorum susceperunt eam : <l eID="gen26849" level="1"/> <l level="1" sID="gen26850"/>a facie ipsorum longe facta est ; <l eID="gen26850" level="1"/>

** Baruch 3:22

non est audita in terra Chanaan, <l eID="gen26851" level="1"/> <l level="1" sID="gen26852"/>neque visa est in Theman. <l eID="gen26852" level="1"/>

** Baruch 3:23

Filii quoque Agar, qui exquirunt prudentiam quæ de terra est, <l eID="gen26853" level="1"/> <l level="1" sID="gen26854"/>negotiatores Merrhæ et Theman, <l eID="gen26854" level="1"/> <l level="1" sID="gen26855"/>et fabulatores, et exquisitores prudentiæ et intelligentiæ : <l eID="gen26855" level="1"/> <l level="1" sID="gen26856"/>viam autem sapientiæ nescierunt, <l eID="gen26856" level="1"/> <l level="1" sID="gen26857"/>neque commemorati sunt semitas ejus. <l eID="gen26857" level="1"/>

** Baruch 3:24

O Israël, quam magna est domus Dei, <l eID="gen26858" level="1"/> <l level="1" sID="gen26859"/>et ingens locus possessionis ejus ! <l eID="gen26859" level="1"/>

** Baruch 3:25

magnus est, et non habet finem : <l eID="gen26860" level="1"/> <l level="1" sID="gen26861"/>excelsus, et immensus. <l eID="gen26861" level="1"/>

** Baruch 3:26

Ibi fuerunt gigantes nominati illi, qui ab initio fuerunt, <l eID="gen26862" level="1"/> <l level="1" sID="gen26863"/>statura magna, scientes bellum. <l eID="gen26863" level="1"/>

** Baruch 3:27

Non hos elegit Dominus, <l eID="gen26864" level="1"/> <l level="1" sID="gen26865"/>neque viam disciplinæ invenerunt : <l eID="gen26865" level="1"/> <l level="1" sID="gen26866"/>propterea perierunt, <l eID="gen26866" level="1"/>

** Baruch 3:28

et quoniam non habuerunt sapientiam, <l eID="gen26867" level="1"/> <l level="1" sID="gen26868"/>interierunt propter suam insipientiam. <l eID="gen26868" level="1"/>

** Baruch 3:29

Quis ascendit in cælum, et accepit eam, <l eID="gen26869" level="1"/> <l level="1" sID="gen26870"/>et eduxit eam de nubibus ? <l eID="gen26870" level="1"/>

** Baruch 3:30

Quis transfretavit mare, et invenit illam, et attulit illam super aurum electum ? <l eID="gen26871" level="1"/>

** Baruch 3:31

Non est qui possit scire vias ejus, <l eID="gen26872" level="1"/> <l level="1" sID="gen26873"/>neque qui exquirat semitas ejus : <l eID="gen26873" level="1"/>

** Baruch 3:32

sed qui scit universa novit eam, <l eID="gen26874" level="1"/> <l level="1" sID="gen26875"/>et adinvenit eam prudentia sua <l eID="gen26875" level="1"/> <l level="1" sID="gen26876"/>qui præparavit terram in æterno tempore : <l eID="gen26876" level="1"/> <l level="1" sID="gen26877"/>et replevit eam pecudibus et quadrupedibus <l eID="gen26877" level="1"/>

** Baruch 3:33

qui emittit lumen, et vadit, <l eID="gen26878" level="1"/> <l level="1" sID="gen26879"/>et vocavit illud, et obedit illi in tremore. <l eID="gen26879" level="1"/>

** Baruch 3:34

Stellæ autem dederunt lumen in custodiis suis, <l eID="gen26880" level="1"/> <l level="1" sID="gen26881"/>et lætatæ sunt : <l eID="gen26881" level="1"/>

** Baruch 3:35

vocatæ sunt, et dixerunt : Adsumus, <l eID="gen26882" level="1"/> <l level="1" sID="gen26883"/>et luxerunt ei cum jucunditate, qui fecit illas. <l eID="gen26883" level="1"/>

** Baruch 3:36

Hic est Deus noster, <l eID="gen26884" level="1"/> <l level="1" sID="gen26885"/>et non æstimabitur alius adversus eum. <l eID="gen26885" level="1"/>

** Baruch 3:37

Hic adinvenit omnem viam disciplinæ, <l eID="gen26886" level="1"/> <l level="1" sID="gen26887"/>et tradidit illam Jacob puero suo, <l eID="gen26887" level="1"/> <l level="1" sID="gen26888"/>et Israël dilecto suo. <l eID="gen26888" level="1"/>

** Baruch 3:38

Post hæc in terris visus est, <l eID="gen26889" level="1"/> <l level="1" sID="gen26890"/>et cum hominibus conversatus est.  <chapter eID="Bar.3"/>

* Baruch 4

** Baruch 4:1

Hic liber mandatorum Dei, <l eID="gen26891" level="1"/> <l level="1" sID="gen26892"/>et lex quæ est in æternum : <l eID="gen26892" level="1"/> <l level="1" sID="gen26893"/>omnes qui tenent eam pervenient ad vitam : <l eID="gen26893" level="1"/> <l level="1" sID="gen26894"/>qui autem dereliquerunt eam, in mortem. <l eID="gen26894" level="1"/>

** Baruch 4:2

Convertere, Jacob, et apprehende eam : <l eID="gen26895" level="1"/> <l level="1" sID="gen26896"/>ambula per viam ad splendorem ejus contra lumen ejus. <l eID="gen26896" level="1"/>

** Baruch 4:3

Ne tradas alteri gloriam tuam, <l eID="gen26897" level="1"/> <l level="1" sID="gen26898"/>et dignitatem tuam genti alienæ. <l eID="gen26898" level="1"/>

** Baruch 4:4

Beati sumus, Israël, <l eID="gen26899" level="1"/> <l level="1" sID="gen26900"/>quia quæ Deo placent manifesta sunt nobis. <l eID="gen26900" level="1"/>

** Baruch 4:5

Animæquior esto, populus Dei, memorabilis Israël : <l eID="gen26901" level="1"/>

** Baruch 4:6

venundati estis gentibus non in perditionem : <l eID="gen26902" level="1"/> <l level="1" sID="gen26903"/>sed propter quod in ira ad iracundiam provocastis Deum, <l eID="gen26903" level="1"/> <l level="1" sID="gen26904"/>traditi estis adversariis. <l eID="gen26904" level="1"/>

** Baruch 4:7

Exacerbastis enim eum qui fecit vos, Deum æternum, <l eID="gen26905" level="1"/> <l level="1" sID="gen26906"/>immolantes dæmoniis, et non Deo. <l eID="gen26906" level="1"/>

** Baruch 4:8

Obliti enim estis Deum qui nutrivit vos, <l eID="gen26907" level="1"/> <l level="1" sID="gen26908"/>et contristastis nutricem vestram Jerusalem. <l eID="gen26908" level="1"/>

** Baruch 4:9

Vidit enim iracundiam a Deo venientem vobis, et dixit : <l eID="gen26909" level="1"/> <l level="1" sID="gen26910"/>Audite, confines Sion : <l eID="gen26910" level="1"/> <l level="1" sID="gen26911"/>adduxit enim mihi Deus luctum magnum. <l eID="gen26911" level="1"/>

** Baruch 4:10

Vidi enim captivitatem populi mei, <l eID="gen26912" level="1"/> <l level="1" sID="gen26913"/>filiorum meorum et filiarum, <l eID="gen26913" level="1"/> <l level="1" sID="gen26914"/>quam superduxit illis Æternus. <l eID="gen26914" level="1"/>

** Baruch 4:11

Nutrivi enim illos cum jucunditate ; <l eID="gen26915" level="1"/> <l level="1" sID="gen26916"/>dimisi autem illos cum fletu et luctu. <l eID="gen26916" level="1"/>

** Baruch 4:12

Nemo gaudeat super me viduam et desolatam : <l eID="gen26917" level="1"/> <l level="1" sID="gen26918"/>a multis derelicta sum propter peccata filiorum meorum, <l eID="gen26918" level="1"/> <l level="1" sID="gen26919"/>quia declinaverunt a lege Dei. <l eID="gen26919" level="1"/>

** Baruch 4:13

Justitias autem ipsius nescierunt, <l eID="gen26920" level="1"/> <l level="1" sID="gen26921"/>nec ambulaverunt per vias mandatorum Dei, <l eID="gen26921" level="1"/> <l level="1" sID="gen26922"/>neque per semitas veritatis ejus cum justitia ingressi sunt. <l eID="gen26922" level="1"/>

** Baruch 4:14

Veniant confines Sion, <l eID="gen26923" level="1"/> <l level="1" sID="gen26924"/>et memorentur captivitatem filiorum et filiarum mearum, <l eID="gen26924" level="1"/> <l level="1" sID="gen26925"/>quam superduxit illis Æternus. <l eID="gen26925" level="1"/>

** Baruch 4:15

Adduxit enim super illos gentem de longinquo, <l eID="gen26926" level="1"/> <l level="1" sID="gen26927"/>gentem improbam, et alterius linguæ, <l eID="gen26927" level="1"/>

** Baruch 4:16

qui non sunt reveriti senem, <l eID="gen26928" level="1"/> <l level="1" sID="gen26929"/>neque puerorum miserti sunt, <l eID="gen26929" level="1"/> <l level="1" sID="gen26930"/>et abduxerunt dilectos viduæ, <l eID="gen26930" level="1"/> <l level="1" sID="gen26931"/>et a filiis unicam desolaverunt. <l eID="gen26931" level="1"/>

** Baruch 4:17

Ego autem, quid possum adjuvare vos ? <l eID="gen26932" level="1"/>

** Baruch 4:18

qui enim adduxit super vos mala, <l eID="gen26933" level="1"/> <l level="1" sID="gen26934"/>ipse vos eripiet de manibus inimicorum vestrorum. <l eID="gen26934" level="1"/>

** Baruch 4:19

Ambulate, filii, ambulate : <l eID="gen26935" level="1"/> <l level="1" sID="gen26936"/>ego enim derelicta sum sola. <l eID="gen26936" level="1"/>

** Baruch 4:20

Exui me stola pacis, <l eID="gen26937" level="1"/> <l level="1" sID="gen26938"/>indui autem me sacco obsecrationis, <l eID="gen26938" level="1"/> <l level="1" sID="gen26939"/>et clamabo ad Altissimum in diebus meis. <l eID="gen26939" level="1"/>

** Baruch 4:21

Animæquiores estote, filii ; clamate ad Dominum, <l eID="gen26940" level="1"/> <l level="1" sID="gen26941"/>et eripiet vos de manu principum inimicorum. <l eID="gen26941" level="1"/>

** Baruch 4:22

Ego enim speravi in æternum salutem vestram, <l eID="gen26942" level="1"/> <l level="1" sID="gen26943"/>et venit mihi gaudium a Sancto, super misericordia <l eID="gen26943" level="1"/> <l level="1" sID="gen26944"/>quæ veniet vobis ab æterno salutari nostro. <l eID="gen26944" level="1"/>

** Baruch 4:23

Emisi enim vos cum luctu et ploratu : <l eID="gen26945" level="1"/> <l level="1" sID="gen26946"/>reducet autem vos mihi Dominus <l eID="gen26946" level="1"/> <l level="1" sID="gen26947"/>cum gaudio et jucunditate in sempiternum. <l eID="gen26947" level="1"/>

** Baruch 4:24

Sicut enim viderunt vicinæ Sion captivitatem vestram a Deo, <l eID="gen26948" level="1"/> <l level="1" sID="gen26949"/>sic videbunt et in celeritate salutem vestram a Deo, <l eID="gen26949" level="1"/> <l level="1" sID="gen26950"/>quæ superveniet vobis cum honore magno et splendore æterno. <l eID="gen26950" level="1"/>

** Baruch 4:25

Filii, patienter sustinete iram quæ supervenit vobis : <l eID="gen26951" level="1"/> <l level="1" sID="gen26952"/>persecutus est enim te inimicus tuus : <l eID="gen26952" level="1"/> <l level="1" sID="gen26953"/>sed cito videbis perditionem ipsius, <l eID="gen26953" level="1"/> <l level="1" sID="gen26954"/>et super cervices ipsius ascendes. <l eID="gen26954" level="1"/>

** Baruch 4:26

Delicati mei ambulaverunt vias asperas : <l eID="gen26955" level="1"/> <l level="1" sID="gen26956"/>ducti sunt enim ut grex direptus ab inimicis. <l eID="gen26956" level="1"/>

** Baruch 4:27

Animæquiores estote, filii, et proclamate ad Dominum : <l eID="gen26957" level="1"/> <l level="1" sID="gen26958"/>erit enim memoria vestra ab eo qui duxit vos. <l eID="gen26958" level="1"/>

** Baruch 4:28

Sicut enim fuit sensus vester ut erraretis a Deo, <l eID="gen26959" level="1"/> <l level="1" sID="gen26960"/>decies tantum iterum convertentes requiretis eum : <l eID="gen26960" level="1"/>

** Baruch 4:29

qui enim induxit vobis mala, <l eID="gen26961" level="1"/> <l level="1" sID="gen26962"/>ipse rursum adducet vobis sempiternam jucunditatem cum salute vestra. <l eID="gen26962" level="1"/>

** Baruch 4:30

Animæquior esto, Jerusalem : <l eID="gen26963" level="1"/> <l level="1" sID="gen26964"/>exhortatur enim te, qui te nominavit. <l eID="gen26964" level="1"/>

** Baruch 4:31

Nocentes peribunt, qui te vexaverunt : <l eID="gen26965" level="1"/> <l level="1" sID="gen26966"/>et qui gratulati sunt in tua ruina, punientur. <l eID="gen26966" level="1"/>

** Baruch 4:32

Civitates quibus servierunt filii tui, punientur, <l eID="gen26967" level="1"/> <l level="1" sID="gen26968"/>et quæ accepit filios tuos. <l eID="gen26968" level="1"/>

** Baruch 4:33

Sicut enim gavisa est in tua ruina, et lætata est in casu tuo, <l eID="gen26969" level="1"/> <l level="1" sID="gen26970"/>sic contristabitur in sua desolatione, <l eID="gen26970" level="1"/>

** Baruch 4:34

et amputabitur exsultatio multitudinis ejus, <l eID="gen26971" level="1"/> <l level="1" sID="gen26972"/>et gaudimonium ejus erit in luctum. <l eID="gen26972" level="1"/>

** Baruch 4:35

Ignis enim superveniet ei ab Æterno in longiturnis diebus, <l eID="gen26973" level="1"/> <l level="1" sID="gen26974"/>et habitabitur a dæmoniis in multitudine temporis. <l eID="gen26974" level="1"/>

** Baruch 4:36

Circumspice, Jerusalem, ad orientem, <l eID="gen26975" level="1"/> <l level="1" sID="gen26976"/>et vide jucunditatem a Deo tibi venientem. <l eID="gen26976" level="1"/>

** Baruch 4:37

Ecce enim veniunt filii tui, quos dimisisti dispersos : <l eID="gen26977" level="1"/> <l level="1" sID="gen26978"/>veniunt collecti ab oriente usque ad occidentem, in verbo Sancti, <l eID="gen26978" level="1"/> <l level="1" sID="gen26979"/>gaudentes in honorem Dei.  <chapter eID="Bar.4"/>

* Baruch 5

** Baruch 5:1

Exue te, Jerusalem, stola luctus et vexationis tuæ, <l eID="gen26980" level="1"/> <l level="1" sID="gen26981"/>et indue te decore, et honore ejus, <l eID="gen26981" level="1"/> <l level="1" sID="gen26982"/>quæ a Deo tibi est, sempiternæ gloriæ. <l eID="gen26982" level="1"/>

** Baruch 5:2

Circumdabit te Deus diploide justitiæ, <l eID="gen26983" level="1"/> <l level="1" sID="gen26984"/>et imponet mitram capiti honoris æterni. <l eID="gen26984" level="1"/>

** Baruch 5:3

Deus enim ostendet splendorem suum in te, <l eID="gen26985" level="1"/> <l level="1" sID="gen26986"/>omni qui sub cælo est. <l eID="gen26986" level="1"/>

** Baruch 5:4

Nominabitur enim tibi nomen tuum a Deo in sempiternum : <l eID="gen26987" level="1"/> <l level="1" sID="gen26988"/>pax justitiæ, et honor pietatis. <l eID="gen26988" level="1"/>

** Baruch 5:5

Exsurge, Jerusalem, et sta in excelso : <l eID="gen26989" level="1"/> <l level="1" sID="gen26990"/>et circumspice ad orientem, <l eID="gen26990" level="1"/> <l level="1" sID="gen26991"/>et vide collectos filios tuos ab oriente sole usque ad occidentem, <l eID="gen26991" level="1"/> <l level="1" sID="gen26992"/>in verbo Sancti, <l eID="gen26992" level="1"/> <l level="1" sID="gen26993"/>gaudentes Dei memoria. <l eID="gen26993" level="1"/>

** Baruch 5:6

Exierunt enim abs te pedibus ducti ab inimicis : <l eID="gen26994" level="1"/> <l level="1" sID="gen26995"/>adducet autem illos Dominus ad te portatos in honore <l eID="gen26995" level="1"/> <l level="1" sID="gen26996"/>sicut filios regni : <l eID="gen26996" level="1"/>

** Baruch 5:7

constituit enim Deus <l eID="gen26997" level="1"/> <l level="1" sID="gen26998"/>humiliare omnem montem excelsum et rupes perennes, <l eID="gen26998" level="1"/> <l level="1" sID="gen26999"/>et convalles replere in æqualitatem terræ, <l eID="gen26999" level="1"/> <l level="1" sID="gen27000"/>ut ambulet Israël diligenter in honorem Dei. <l eID="gen27000" level="1"/>

** Baruch 5:8

Obumbraverunt autem et silvæ, <l eID="gen27001" level="1"/> <l level="1" sID="gen27002"/>et omne lignum suavitatis Israël <l eID="gen27002" level="1"/> <l level="1" sID="gen27003"/>ex mandato Dei. <l eID="gen27003" level="1"/>

** Baruch 5:9

Adducet enim Deus Israël cum jucunditate in lumine majestatis suæ, <l eID="gen27004" level="1"/> <l level="1" sID="gen27005"/>cum misericordia et justitia quæ est ex ipso. <l eID="gen27005" level="1"/><lg eID="gen26656"/> <chapter eID="Bar.5"/>

* Baruch 6

** Baruch 6:1

Propter peccata quæ peccastis ante Deum, abducemini in Babyloniam captivi a Nabuchodonosor rege Babylonis.

** Baruch 6:2

Ingressi itaque in Babylonem, eritis ibi annis plurimis, et temporibus longis, usque ad generationes septem : post hoc autem educam vos inde cum pace.

** Baruch 6:3

Nunc autem videbitis in Babylonia deos aureos et argenteos, et lapideos et ligneos, in humeris portari, ostentantes metum gentibus.

** Baruch 6:4

Videte ergo ne et vos similes efficiamini factis alienis, et metuatis, et metus vos capiat in ipsis.

** Baruch 6:5

Visa itaque turba de retro et ab ante, adorantes dicite in cordibus vestris : Te oportet adorari, Domine.

** Baruch 6:6

Angelus enim meus vobiscum est : ipse autem exquiram animas vestras.

** Baruch 6:7

Nam lingua ipsorum polita a fabro ; ipsa etiam inaurata et inargentata : falsa sunt, et non possunt loqui.

** Baruch 6:8

Et sicut virgini amanti ornamenta, ita accepto auro fabricati sunt.

** Baruch 6:9

Coronas certe aureas habent super capita sua dii illorum : unde subtrahunt sacerdotes ab eis aurum et argentum, et erogant illud in semetipsos.

** Baruch 6:10

Dant autem et ex ipso prostitutis, et meretrices ornant : et iterum cum receperint illud a meretricibus, ornant deos suos.

** Baruch 6:11

Hi autem non liberantur ab ærugine et tinea.

** Baruch 6:12

Opertis autem illis veste purpurea, extergunt faciem ipsorum propter pulverem domus qui est plurimus inter eos.

** Baruch 6:13

Sceptrum autem habet ut homo, sicut judex regionis, qui in se peccantem non interficit.

** Baruch 6:14

Habet etiam in manu gladium et securim, se autem de bello et a latronibus non liberat. Unde vobis notum sit quia non sunt dii :

** Baruch 6:15

non ergo timueritis eos. Sicut enim vas hominis confractum inutile efficitur, tales sunt et dii illorum.

** Baruch 6:16

Constitutis illis in domo, oculi eorum pleni sunt pulvere a pedibus introëuntium.

** Baruch 6:17

Et sicut alicui qui regem offendit circumseptæ sunt januæ, aut sicut ad sepulchrum adductum mortuum : ita tutantur sacerdotes ostia clausuris et seris, ne a latronibus expolientur.

** Baruch 6:18

Lucernas accendunt illis, et quidem multas, ex quibus nullam videre possunt : sunt autem sicut trabes in domo.

** Baruch 6:19

Corda vero eorum dicunt elingere serpentes qui de terra sunt, dum comedunt eos, et vestimentum ipsorum, et non sentiunt.

** Baruch 6:20

Nigræ fiunt facies eorum a fumo qui in domo fit.

** Baruch 6:21

Supra corpus eorum et supra caput eorum volant noctuæ, et hirundines, et aves etiam, similiter et cattæ.

** Baruch 6:22

Unde sciatis quia non sunt dii : ne ergo timueritis eos.  <div eID="gen27006" type="x-p"/>

** Baruch 6:23

Aurum etiam quod habent ad speciem est : nisi aliquis exterserit æruginem, non fulgebunt : neque enim dum conflarentur, sentiebant.

** Baruch 6:24

Ex omni pretio empta sunt, in quibus spiritus non inest ipsis.

** Baruch 6:25

Sine pedibus, in humeris portantur, ostentantes ignobilitatem suam hominibus : confundantur etiam qui colunt ea.

** Baruch 6:26

Propterea si ceciderint in terram, a semetipsis non consurgunt : neque si quis eum statuerit rectum, per semetipsum stabit : sed sicut mortuis munera eorum illis apponentur.

** Baruch 6:27

Hostias illorum vendunt sacerdotes ipsorum, et abutuntur : similiter et mulieres eorum decerpentes, neque infirmo, neque mendicanti, aliquid impertiunt.

** Baruch 6:28

De sacrificiis eorum fœtæ et menstruatæ contingunt. Sciens itaque ex his quia non sunt dii, ne timeatis eos.

** Baruch 6:29

Unde enim vocantur dii ? quia mulieres apponunt diis argenteis, et aureis, et ligneis :

** Baruch 6:30

et in domibus eorum sacerdotes sedent habentes tunicas scissas, et capita et barbam rasam, quorum capita nuda sunt.

** Baruch 6:31

Rugiunt autem clamantes contra deos suos sicut in cœna mortui.

** Baruch 6:32

Vestimenta eorum auferunt sacerdotes, et vestiunt uxores suas et filios suos.

** Baruch 6:33

Neque si quid mali patiuntur ab aliquo, neque si quid boni, poterunt retribuere : neque regem constituere possunt, neque auferre.

** Baruch 6:34

Similiter neque dare divitias possunt, neque malum retribuere. Si quis illis votum voverit et non reddiderit, neque hoc requirunt.

** Baruch 6:35

Hominem a morte non liberant, neque infirmum a potentiori eripiunt.

** Baruch 6:36

Hominem cæcum ad visum non restituunt ; de necessitate hominem non liberabunt.

** Baruch 6:37

Viduæ non miserebuntur, neque orphanis benefacient.

** Baruch 6:38

Lapidibus de monte similes sunt dii illorum, lignei, et lapidei, et aurei, et argentei : qui autem colunt ea, confundentur.

** Baruch 6:39

Quomodo ergo æstimandum est aut dicendum illos esse deos ?

** Baruch 6:40

Adhuc enim ipsis Chaldæis non honorantibus ea : qui cum audierint mutum non posse loqui, offerunt illud ad Bel, postulantes ab eo loqui :

** Baruch 6:41

quasi possint sentire qui non habent motum ! Et ipsi, cum intellexerint, relinquent ea : sensum enim non habent ipsi dii illorum.

** Baruch 6:42

Mulieres autem circumdatæ funibus in viis sedent, succendentes ossa olivarum :

** Baruch 6:43

cum autem aliqua ex ipsis, attracta ab aliquo transeunte, dormierit cum eo, proximæ suæ exprobrat quod ea non sit digna habita, sicut ipsa, neque funis ejus diruptus sit.

** Baruch 6:44

Omnia autem quæ illi fiunt, falsa sunt : quomodo æstimandum aut dicendum est illos esse deos ?  <div eID="gen27007" type="x-p"/>

** Baruch 6:45

A fabris autem et ab aurificibus facta sunt : nihil aliud erunt, nisi id quod volunt esse sacerdotes.

** Baruch 6:46

Artifices etiam ipsi, qui ea faciunt, non sunt multi temporis : numquid ergo possunt ea, quæ fabricata sunt ab ipsis, esse dii ?

** Baruch 6:47

Reliquerunt autem falsa et opprobrium postea futuris.

** Baruch 6:48

Nam cum supervenerit illis prælium et mala, cogitant sacerdotes apud se ubi se abscondant cum illis.

** Baruch 6:49

Quomodo ergo sentiri debeant quoniam dii sunt, qui nec de bello se liberant, neque de malis se eripiunt ?

** Baruch 6:50

Nam cum sint lignea, inaurata et inargentata, scietur postea quia falsa sunt ab universis gentibus et regibus : quæ manifesta sunt quia non sunt dii, sed opera manuum hominum, et nullum Dei opus cum illis.

** Baruch 6:51

Unde ergo notum est quia non sunt dii, sed opera manuum hominum, et nullum Dei opus in ipsis est.

** Baruch 6:52

Regem regioni non suscitant, neque pluviam hominibus dabunt.

** Baruch 6:53

Judicium quoque non discernent, neque regiones liberabunt ab injuria, quia nihil possunt, sicut corniculæ inter medium cæli et terræ.

** Baruch 6:54

Etenim cum inciderit ignis in domum deorum ligneorum, argenteorum et aureorum, sacerdotes quidem ipsorum fugient, et liberabuntur : ipsi vero sicut trabes in medio comburentur.

** Baruch 6:55

Regi autem et bello non resistent. Quomodo ergo æstimandum est aut recipiendum quia dii sunt ?

** Baruch 6:56

Non a furibus, neque a latronibus se liberabunt dii lignei, et lapidei, et inaurati, et inargentati : quibus hi qui fortiores sunt,

** Baruch 6:57

aurum et argentum, et vestimentum quo operti sunt, auferent illis, et abibunt, nec sibi auxilium ferent.  <div eID="gen27008" type="x-p"/>

** Baruch 6:58

Itaque melius est esse regem ostentantem virtutem suam, aut vas in domo utile, in quo gloriabitur qui possidet illud, vel ostium in domo, quod custodit quæ in ipsa sunt, quam falsi dii.

** Baruch 6:59

Sol quidem et luna ac sidera, cum sint splendida et emissa ad utilitates, obaudiunt :

** Baruch 6:60

similiter et fulgur cum apparuerit, perspicuum est : idipsum autem et spiritus in omni regione spirat :

** Baruch 6:61

et nubes, quibus cum imperatum fuerit a Deo perambulare universum orbem, perficiunt quod imperatum est eis :

** Baruch 6:62

ignis etiam missus desuper, ut consumat montes et silvas, facit quod præceptum est ei : hæc autem neque speciebus, neque virtutibus, uni eorum similia sunt.

** Baruch 6:63

Unde neque existimandum est, neque dicendum illos esse deos, quando non possunt neque judicium judicare, neque quidquam facere hominibus.

** Baruch 6:64

Scientes itaque quia non sunt dii, ne ergo timueritis eos.

** Baruch 6:65

Neque enim regibus maledicent, neque benedicent.

** Baruch 6:66

Signa etiam in cælo gentibus non ostendunt : neque ut sol lucebunt, neque illuminabunt ut luna.

** Baruch 6:67

Bestiæ meliores sunt illis, quæ possunt fugere sub tectum ac prodesse sibi.

** Baruch 6:68

Nullo itaque modo nobis est manifestum quia sunt dii : propter quod ne timeatis eos.  <div eID="gen27009" type="x-p"/>

** Baruch 6:69

Nam sicut in cucumerario formido nihil custodit, ita sunt dii illorum lignei, et argentei, et inaurati.

** Baruch 6:70

Eodem modo et in horto spina alba, supra quam omnis avis sedet, similiter et mortuo projecto in tenebris, similes sunt dii illorum lignei, et inaurati, et inargentati.

** Baruch 6:71

A purpura quoque et murice, quæ supra illos tineant, scietis itaque quia non sunt dii : ipsi etiam postremo comeduntur, et erunt opprobrium in regione.

** Baruch 6:72

Melior est homo justus qui non habet simulacra, nam erit longe ab opprobriis.  <div eID="gen27010" type="x-p"/> <chapter eID="Bar.6"/> <div eID="gen26654" osisID="Bar" type="book"/>

