* Habakkuk 1

** Habakkuk 1:1

Onus quod vidit Habacuc propheta.  <div eID="gen31118" type="x-p"/>

** Habakkuk 1:2

Usquequo, Domine, clamabo, <l eID="gen31120" level="1"/> <l level="1" sID="gen31121"/>et non exaudies ? <l eID="gen31121" level="1"/> <l level="1" sID="gen31122"/>vociferabor ad te, vim patiens, <l eID="gen31122" level="1"/> <l level="1" sID="gen31123"/>et non salvabis ? <l eID="gen31123" level="1"/>

** Habakkuk 1:3

Quare ostendisti mihi iniquitatem et laborem, <l eID="gen31124" level="1"/> <l level="1" sID="gen31125"/>videre prædam et injustitiam contra me ? <l eID="gen31125" level="1"/> <l level="1" sID="gen31126"/>Et factum est judicium, et contradictio potentior. <l eID="gen31126" level="1"/>

** Habakkuk 1:4

Propter hoc lacerata est lex, <l eID="gen31127" level="1"/> <l level="1" sID="gen31128"/>et non pervenit usque ad finem judicium ; <l eID="gen31128" level="1"/> <l level="1" sID="gen31129"/>quia impius prævalet adversus justum, <l eID="gen31129" level="1"/> <l level="1" sID="gen31130"/>propterea egreditur judicium perversum. <l eID="gen31130" level="1"/>

** Habakkuk 1:5

Aspicite in gentibus, et videte ; <l eID="gen31131" level="1"/> <l level="1" sID="gen31132"/>admiramini, et obstupescite : <l eID="gen31132" level="1"/> <l level="1" sID="gen31133"/>quia opus factum est in diebus vestris, <l eID="gen31133" level="1"/> <l level="1" sID="gen31134"/>quod nemo credet cum narrabitur. <l eID="gen31134" level="1"/>

** Habakkuk 1:6

Quia ecce ego suscitabo Chaldæos, <l eID="gen31135" level="1"/> <l level="1" sID="gen31136"/>gentem amaram et velocem, <l eID="gen31136" level="1"/> <l level="1" sID="gen31137"/>ambulantem super latitudinem terræ, <l eID="gen31137" level="1"/> <l level="1" sID="gen31138"/>ut possideat tabernacula non sua. <l eID="gen31138" level="1"/>

** Habakkuk 1:7

Horribilis et terribilis est : <l eID="gen31139" level="1"/> <l level="1" sID="gen31140"/>ex semetipsa judicium et onus ejus egredietur. <l eID="gen31140" level="1"/>

** Habakkuk 1:8

Leviores pardis equi ejus, <l eID="gen31141" level="1"/> <l level="1" sID="gen31142"/>et velociores lupis vespertinis : <l eID="gen31142" level="1"/> <l level="1" sID="gen31143"/>et diffundentur equites ejus : <l eID="gen31143" level="1"/> <l level="1" sID="gen31144"/>equites namque ejus de longe venient ; <l eID="gen31144" level="1"/> <l level="1" sID="gen31145"/>volabunt quasi aquila festinans ad comedendum. <l eID="gen31145" level="1"/>

** Habakkuk 1:9

Omnes ad prædam venient, <l eID="gen31146" level="1"/> <l level="1" sID="gen31147"/>facies eorum ventus urens ; <l eID="gen31147" level="1"/> <l level="1" sID="gen31148"/>et congregabit quasi arenam captivitatem. <l eID="gen31148" level="1"/>

** Habakkuk 1:10

Et ipse de regibus triumphabit, <l eID="gen31149" level="1"/> <l level="1" sID="gen31150"/>et tyranni ridiculi ejus erunt ; <l eID="gen31150" level="1"/> <l level="1" sID="gen31151"/>ipse super omnem munitionem ridebit, <l eID="gen31151" level="1"/> <l level="1" sID="gen31152"/>et comportabit aggerem, et capiet eam. <l eID="gen31152" level="1"/>

** Habakkuk 1:11

Tunc mutabitur spiritus, et pertransibit, et corruet : <l eID="gen31153" level="1"/> <l level="1" sID="gen31154"/>hæc est fortitudo ejus dei sui. <l eID="gen31154" level="1"/>

** Habakkuk 1:12

Numquid non tu a principio, <l eID="gen31155" level="1"/> <l level="1" sID="gen31156"/>Domine, Deus meus, sancte meus, <l eID="gen31156" level="1"/> <l level="1" sID="gen31157"/>et non moriemur ? <l eID="gen31157" level="1"/> <l level="1" sID="gen31158"/>Domine, in judicium posuisti eum, <l eID="gen31158" level="1"/> <l level="1" sID="gen31159"/>et fortem, ut corriperes, fundasti eum. <l eID="gen31159" level="1"/>

** Habakkuk 1:13

Mundi sunt oculi tui, ne videas malum, <l eID="gen31160" level="1"/> <l level="1" sID="gen31161"/>et respicere ad iniquitatem non poteris. <l eID="gen31161" level="1"/> <l level="1" sID="gen31162"/>Quare respicis super iniqua agentes, <l eID="gen31162" level="1"/> <l level="1" sID="gen31163"/>et taces devorante impio justiorem se ? <l eID="gen31163" level="1"/>

** Habakkuk 1:14

Et facies homines quasi pisces maris, <l eID="gen31164" level="1"/> <l level="1" sID="gen31165"/>et quasi reptile non habens principem. <l eID="gen31165" level="1"/>

** Habakkuk 1:15

Totum in hamo sublevavit, <l eID="gen31166" level="1"/> <l level="1" sID="gen31167"/>traxit illud in sagena sua, <l eID="gen31167" level="1"/> <l level="1" sID="gen31168"/>et congregavit in rete suum. <l eID="gen31168" level="1"/> <l level="1" sID="gen31169"/>Super hoc lætabitur, et exsultabit. <l eID="gen31169" level="1"/>

** Habakkuk 1:16

Propterea immolabit sagenæ suæ, <l eID="gen31170" level="1"/> <l level="1" sID="gen31171"/>et sacrificabit reti suo, <l eID="gen31171" level="1"/> <l level="1" sID="gen31172"/>quia in ipsis incrassata est pars ejus, <l eID="gen31172" level="1"/> <l level="1" sID="gen31173"/>et cibus ejus electus. <l eID="gen31173" level="1"/>

** Habakkuk 1:17

Propter hoc ergo expandit sagenam suam, <l eID="gen31174" level="1"/> <l level="1" sID="gen31175"/>et semper interficere gentes non parcet.  <chapter eID="Hab.1"/>

* Habakkuk 2

** Habakkuk 2:1

Super custodiam meam stabo, <l eID="gen31176" level="1"/> <l level="1" sID="gen31177"/>et figam gradum super munitionem : <l eID="gen31177" level="1"/> <l level="1" sID="gen31178"/>et contemplabor ut videam quid dicatur mihi, <l eID="gen31178" level="1"/> <l level="1" sID="gen31179"/>et quid respondeam ad arguentem me. <l eID="gen31179" level="1"/> <lg eID="gen31119"/>

** Habakkuk 2:2

Et respondit mihi Dominus, et dixit : <div eID="gen31180" type="x-p"/> <lg sID="gen31181"/> <l level="1" sID="gen31182"/>Scribe visum, et explana eum super tabulas, <l eID="gen31182" level="1"/> <l level="1" sID="gen31183"/>ut percurrat qui legerit eum. <l eID="gen31183" level="1"/>

** Habakkuk 2:3

Quia adhuc visus procul ; <l eID="gen31184" level="1"/> <l level="1" sID="gen31185"/>et apparebit in finem, et non mentietur : <l eID="gen31185" level="1"/> <l level="1" sID="gen31186"/>si moram fecerit, exspecta illum, <l eID="gen31186" level="1"/> <l level="1" sID="gen31187"/>quia veniens veniet, et non tardabit. <l eID="gen31187" level="1"/>

** Habakkuk 2:4

Ecce qui incredulus est, non erit recta anima ejus in semetipso ; <l eID="gen31188" level="1"/> <l level="1" sID="gen31189"/>justus autem in fide sua vivet. <l eID="gen31189" level="1"/>

** Habakkuk 2:5

Et quomodo vinum potantem decipit, <l eID="gen31190" level="1"/> <l level="1" sID="gen31191"/>sic erit vir superbus, et non decorabitur : <l eID="gen31191" level="1"/> <l level="1" sID="gen31192"/>qui dilatavit quasi infernus animam suam, <l eID="gen31192" level="1"/> <l level="1" sID="gen31193"/>et ipse quasi mors, et non adimpletur : <l eID="gen31193" level="1"/> <l level="1" sID="gen31194"/>et congregabit ad se omnes gentes, <l eID="gen31194" level="1"/> <l level="1" sID="gen31195"/>et coacervabit ad se omnes populos. <l eID="gen31195" level="1"/>

** Habakkuk 2:6

Numquid non omnes isti super eum parabolam sument, <l eID="gen31196" level="1"/> <l level="1" sID="gen31197"/>et loquelam ænigmatum ejus, et dicetur : <l eID="gen31197" level="1"/> <l level="1" sID="gen31198"/>Væ ei qui multiplicat non sua ? <l eID="gen31198" level="1"/> <l level="1" sID="gen31199"/>usquequo et aggravat contra se densum lutum ? <l eID="gen31199" level="1"/>

** Habakkuk 2:7

Numquid non repente consurgent qui mordeant te, <l eID="gen31200" level="1"/> <l level="1" sID="gen31201"/>et suscitabuntur lacerantes te, <l eID="gen31201" level="1"/> <l level="1" sID="gen31202"/>et eris in rapinam eis ? <l eID="gen31202" level="1"/>

** Habakkuk 2:8

Quia tu spoliasti gentes multas, <l eID="gen31203" level="1"/> <l level="1" sID="gen31204"/>spoliabunt te omnes qui reliqui fuerint de populis, <l eID="gen31204" level="1"/> <l level="1" sID="gen31205"/>propter sanguinem hominis, <l eID="gen31205" level="1"/> <l level="1" sID="gen31206"/>et iniquitatem terræ, civitatis, et omnium habitantium in ea. <l eID="gen31206" level="1"/>

** Habakkuk 2:9

Væ qui congregat avaritiam malam domui suæ, <l eID="gen31207" level="1"/> <l level="1" sID="gen31208"/>ut sit in excelso nidus ejus, <l eID="gen31208" level="1"/> <l level="1" sID="gen31209"/>et liberari se putat de manu mali ! <l eID="gen31209" level="1"/>

** Habakkuk 2:10

Cogitasti confusionem domui tuæ ; <l eID="gen31210" level="1"/> <l level="1" sID="gen31211"/>concidisti populos multos, <l eID="gen31211" level="1"/> <l level="1" sID="gen31212"/>et peccavit anima tua. <l eID="gen31212" level="1"/>

** Habakkuk 2:11

Quia lapis de pariete clamabit, <l eID="gen31213" level="1"/> <l level="1" sID="gen31214"/>et lignum, quod inter juncturas ædificiorum est, respondebit. <l eID="gen31214" level="1"/>

** Habakkuk 2:12

Væ qui ædificat civitatem in sanguinibus, <l eID="gen31215" level="1"/> <l level="1" sID="gen31216"/>et præparat urbem in iniquitate ! <l eID="gen31216" level="1"/>

** Habakkuk 2:13

Numquid non hæc sunt a Domino exercituum ? <l eID="gen31217" level="1"/> <l level="1" sID="gen31218"/>laborabunt enim populi in multo igne, <l eID="gen31218" level="1"/> <l level="1" sID="gen31219"/>et gentes in vacuum, et deficient. <l eID="gen31219" level="1"/>

** Habakkuk 2:14

Quia replebitur terra, ut cognoscant gloriam Domini, <l eID="gen31220" level="1"/> <l level="1" sID="gen31221"/>quasi aquæ operientes mare. <l eID="gen31221" level="1"/>

** Habakkuk 2:15

Væ qui potum dat amico suo mittens fel suum, <l eID="gen31222" level="1"/> <l level="1" sID="gen31223"/>et inebrians ut aspiciat nuditatem ejus ! <l eID="gen31223" level="1"/>

** Habakkuk 2:16

Repletus es ignominia pro gloria ; <l eID="gen31224" level="1"/> <l level="1" sID="gen31225"/>bibe tu quoque, et consopire. <l eID="gen31225" level="1"/> <l level="1" sID="gen31226"/>Circumdabit te calix dexteræ Domini, <l eID="gen31226" level="1"/> <l level="1" sID="gen31227"/>et vomitus ignominiæ super gloriam tuam. <l eID="gen31227" level="1"/>

** Habakkuk 2:17

Quia iniquitas Libani operiet te, <l eID="gen31228" level="1"/> <l level="1" sID="gen31229"/>et vastitas animalium deterrebit eos <l eID="gen31229" level="1"/> <l level="1" sID="gen31230"/>de sanguinibus hominum, <l eID="gen31230" level="1"/> <l level="1" sID="gen31231"/>et iniquitate terræ, et civitatis, et omnium habitantium in ea. <l eID="gen31231" level="1"/>

** Habakkuk 2:18

Quid prodest sculptile, quia sculpsit illud fictor suus, <l eID="gen31232" level="1"/> <l level="1" sID="gen31233"/>conflatile, et imaginem falsam ? <l eID="gen31233" level="1"/> <l level="1" sID="gen31234"/>quia speravit in figmento fictor ejus, ut faceret simulacra muta. <l eID="gen31234" level="1"/>

** Habakkuk 2:19

Væ qui dicit ligno : Expergiscere ; <l eID="gen31235" level="1"/> <l level="1" sID="gen31236"/>Surge, lapidi tacenti ! <l eID="gen31236" level="1"/> <l level="1" sID="gen31237"/>Numquid ipse docere poterit ? <l eID="gen31237" level="1"/> <l level="1" sID="gen31238"/>ecce iste coopertus est auro et argento, <l eID="gen31238" level="1"/> <l level="1" sID="gen31239"/>et omnis spiritus non est in visceribus ejus. <l eID="gen31239" level="1"/>

** Habakkuk 2:20

Dominus autem in templo sancto suo : <l eID="gen31240" level="1"/> <l level="1" sID="gen31241"/>sileat a facie ejus omnis terra ! <l eID="gen31241" level="1"/><lg eID="gen31181"/> <chapter eID="Hab.2"/>

* Habakkuk 3

** Habakkuk 3:1

Oratio Habacuc prophetæ, pro ignorantiis.  <div eID="gen31242" type="x-p"/>

** Habakkuk 3:2

Domine, audivi auditionem tuam, et timui. <l eID="gen31244" level="1"/> <l level="1" sID="gen31245"/>Domine, opus tuum, in medio annorum vivifica illud ; <l eID="gen31245" level="1"/> <l level="1" sID="gen31246"/>in medio annorum notum facies : <l eID="gen31246" level="1"/> <l level="1" sID="gen31247"/>cum iratus fueris, misericordiæ recordaberis. <l eID="gen31247" level="1"/>

** Habakkuk 3:3

Deus ab austro veniet, <l eID="gen31248" level="1"/> <l level="1" sID="gen31249"/>et Sanctus de monte Pharan : <l eID="gen31249" level="1"/> <l level="1" sID="gen31250"/>operuit cælos gloria ejus, <l eID="gen31250" level="1"/> <l level="1" sID="gen31251"/>et laudis ejus plena est terra. <l eID="gen31251" level="1"/>

** Habakkuk 3:4

Splendor ejus ut lux erit, <l eID="gen31252" level="1"/> <l level="1" sID="gen31253"/>cornua in manibus ejus : <l eID="gen31253" level="1"/> <l level="1" sID="gen31254"/>ibi abscondita est fortitudo ejus. <l eID="gen31254" level="1"/>

** Habakkuk 3:5

Ante faciem ejus ibit mors, <l eID="gen31255" level="1"/> <l level="1" sID="gen31256"/>et egredietur diabolus ante pedes ejus. <l eID="gen31256" level="1"/>

** Habakkuk 3:6

Stetit, et mensus est terram ; <l eID="gen31257" level="1"/> <l level="1" sID="gen31258"/>aspexit, et dissolvit gentes, <l eID="gen31258" level="1"/> <l level="1" sID="gen31259"/>et contriti sunt montes sæculi : <l eID="gen31259" level="1"/> <l level="1" sID="gen31260"/>incurvati sunt colles mundi ab itineribus æternitatis ejus. <l eID="gen31260" level="1"/>

** Habakkuk 3:7

Pro iniquitate vidi tentoria Æthiopiæ ; <l eID="gen31261" level="1"/> <l level="1" sID="gen31262"/>turbabuntur pelles terræ Madian. <l eID="gen31262" level="1"/>

** Habakkuk 3:8

Numquid in fluminibus iratus es, Domine ? <l eID="gen31263" level="1"/> <l level="1" sID="gen31264"/>aut in fluminibus furor tuus ? <l eID="gen31264" level="1"/> <l level="1" sID="gen31265"/>vel in mari indignatio tua ? <l eID="gen31265" level="1"/> <l level="1" sID="gen31266"/>Qui ascendes super equos tuos, et quadrigæ tuæ salvatio. <l eID="gen31266" level="1"/>

** Habakkuk 3:9

Suscitans suscitabis arcum tuum, <l eID="gen31267" level="1"/> <l level="1" sID="gen31268"/>juramenta tribubus quæ locutus es ; <l eID="gen31268" level="1"/> <l level="1" sID="gen31269"/>fluvios scindes terræ. <l eID="gen31269" level="1"/>

** Habakkuk 3:10

Viderunt te, et doluerunt montes ; <l eID="gen31270" level="1"/> <l level="1" sID="gen31271"/>gurges aquarum transiit : <l eID="gen31271" level="1"/> <l level="1" sID="gen31272"/>dedit abyssus vocem suam ; <l eID="gen31272" level="1"/> <l level="1" sID="gen31273"/>altitudo manus suas levavit. <l eID="gen31273" level="1"/>

** Habakkuk 3:11

Sol et luna steterunt in habitaculo suo : <l eID="gen31274" level="1"/> <l level="1" sID="gen31275"/>in luce sagittarum tuarum ibunt, <l eID="gen31275" level="1"/> <l level="1" sID="gen31276"/>in splendore fulgurantis hastæ tuæ. <l eID="gen31276" level="1"/>

** Habakkuk 3:12

In fremitu conculcabis terram ; <l eID="gen31277" level="1"/> <l level="1" sID="gen31278"/>in furore obstupefacies gentes. <l eID="gen31278" level="1"/>

** Habakkuk 3:13

Egressus es in salutem populi tui, <l eID="gen31279" level="1"/> <l level="1" sID="gen31280"/>in salutem cum christo tuo : <l eID="gen31280" level="1"/> <l level="1" sID="gen31281"/>percussisti caput de domo impii, <l eID="gen31281" level="1"/> <l level="1" sID="gen31282"/>denudasti fundamentum ejus usque ad collum. <l eID="gen31282" level="1"/>

** Habakkuk 3:14

Maledixisti sceptris ejus, <l eID="gen31283" level="1"/> <l level="1" sID="gen31284"/>capiti bellatorum ejus, <l eID="gen31284" level="1"/> <l level="1" sID="gen31285"/>venientibus ut turbo ad dispergendum me : <l eID="gen31285" level="1"/> <l level="1" sID="gen31286"/>exsultatio eorum, sicut ejus qui devorat pauperem in abscondito. <l eID="gen31286" level="1"/>

** Habakkuk 3:15

Viam fecisti in mari equis tuis, <l eID="gen31287" level="1"/> <l level="1" sID="gen31288"/>in luto aquarum multarum. <l eID="gen31288" level="1"/>

** Habakkuk 3:16

Audivi, et conturbatus est venter meus ; <l eID="gen31289" level="1"/> <l level="1" sID="gen31290"/>a voce contremuerunt labia mea. <l eID="gen31290" level="1"/> <l level="1" sID="gen31291"/>Ingrediatur putredo in ossibus meis, <l eID="gen31291" level="1"/> <l level="1" sID="gen31292"/>et subter me scateat : <l eID="gen31292" level="1"/> <l level="1" sID="gen31293"/>ut requiescam in die tribulationis, <l eID="gen31293" level="1"/> <l level="1" sID="gen31294"/>ut ascendam ad populum accinctum nostrum. <l eID="gen31294" level="1"/>

** Habakkuk 3:17

Ficus enim non florebit, <l eID="gen31295" level="1"/> <l level="1" sID="gen31296"/>et non erit germen in vineis ; <l eID="gen31296" level="1"/> <l level="1" sID="gen31297"/>mentietur opus olivæ, <l eID="gen31297" level="1"/> <l level="1" sID="gen31298"/>et arva non afferent cibum : <l eID="gen31298" level="1"/> <l level="1" sID="gen31299"/>abscindetur de ovili pecus, <l eID="gen31299" level="1"/> <l level="1" sID="gen31300"/>et non erit armentum in præsepibus. <l eID="gen31300" level="1"/>

** Habakkuk 3:18

Ego autem in Domino gaudebo ; <l eID="gen31301" level="1"/> <l level="1" sID="gen31302"/>et exsultabo in Deo Jesu meo. <l eID="gen31302" level="1"/>

** Habakkuk 3:19

Deus Dominus fortitudo mea, <l eID="gen31303" level="1"/> <l level="1" sID="gen31304"/>et ponet pedes meos quasi cervorum : <l eID="gen31304" level="1"/> <l level="1" sID="gen31305"/>et super excelsa mea deducet me <l eID="gen31305" level="1"/> <l level="1" sID="gen31306"/>victor in psalmis canentem. <l eID="gen31306" level="1"/> <lg eID="gen31243"/> <chapter eID="Hab.3"/> <div eID="gen31117" osisID="Hab" type="book"/>

