* Haggai 1

** Haggai 1:1

In anno secundo Darii regis, in mense sexto, in die una mensis, factum est verbum Domini in manu Aggæi prophetæ, ad Zorobabel, filium Salathiel, ducem Juda, et ad Jesum, filium Josedec, sacerdotem magnum, dicens :

** Haggai 1:2

Hæc ait Dominus exercituum, dicens : Populus iste dicit : Nondum venit tempus domus Domini ædificandæ.

** Haggai 1:3

Et factum est verbum Domini in manu Aggæi prophetæ, dicens :  <div eID="gen31498" type="x-p"/>

** Haggai 1:4

Numquid tempus vobis est ut habitetis in domibus laqueatis, <l eID="gen31500" level="1"/> <l level="1" sID="gen31501"/>et domus ista deserta ? <l eID="gen31501" level="1"/>

** Haggai 1:5

Et nunc hæc dicit Dominus exercituum : <l eID="gen31502" level="1"/> <l level="1" sID="gen31503"/>Ponite corda vestra super vias vestras. <l eID="gen31503" level="1"/>

** Haggai 1:6

Seminastis multum, et intulistis parum ; <l eID="gen31504" level="1"/> <l level="1" sID="gen31505"/>comedistis, et non estis satiati ; <l eID="gen31505" level="1"/> <l level="1" sID="gen31506"/>bibistis, et non estis inebriati ; <l eID="gen31506" level="1"/> <l level="1" sID="gen31507"/>operuistis vos, et non estis calefacti ; <l eID="gen31507" level="1"/> <l level="1" sID="gen31508"/>et qui mercedes congregavit, misit eas in sacculum pertusum. <l eID="gen31508" level="1"/>

** Haggai 1:7

Hæc dicit Dominus exercituum : <l eID="gen31509" level="1"/> <l level="1" sID="gen31510"/>Ponite corda vestra super vias vestras ; <l eID="gen31510" level="1"/>

** Haggai 1:8

ascendite in montem, portate ligna, et ædificate domum : <l eID="gen31511" level="1"/> <l level="1" sID="gen31512"/>et acceptabilis mihi erit, et glorificabor, dicit Dominus. <l eID="gen31512" level="1"/>

** Haggai 1:9

Respexistis ad amplius, et ecce factum est minus ; <l eID="gen31513" level="1"/> <l level="1" sID="gen31514"/>et intulistis in domum, et exsufflavi illud : <l eID="gen31514" level="1"/> <l level="1" sID="gen31515"/>quam ob causam ? dicit Dominus exercituum : <l eID="gen31515" level="1"/> <l level="1" sID="gen31516"/>quia domus mea deserta est, <l eID="gen31516" level="1"/> <l level="1" sID="gen31517"/>et vos festinatis unusquisque in domum suam. <l eID="gen31517" level="1"/>

** Haggai 1:10

Propter hoc super vos prohibiti sunt cæli ne darent rorem, <l eID="gen31518" level="1"/> <l level="1" sID="gen31519"/>et terra prohibita est ne daret germen suum : <l eID="gen31519" level="1"/>

** Haggai 1:11

et vocavi siccitatem super terram, et super montes, <l eID="gen31520" level="1"/> <l level="1" sID="gen31521"/>et super triticum, et super vinum, et super oleum, <l eID="gen31521" level="1"/> <l level="1" sID="gen31522"/>et quæcumque profert humus, <l eID="gen31522" level="1"/> <l level="1" sID="gen31523"/>et super homines, et super jumenta, <l eID="gen31523" level="1"/> <l level="1" sID="gen31524"/>et super omnem laborem manuum.

** Haggai 1:12

Et audivit Zorobabel, filius Salathiel, et Jesus, filius Josedec, sacerdos magnus, et omnes reliquiæ populi, vocem Domini Dei sui, et verba Aggæi prophetæ, sicut misit eum Dominus Deus eorum ad eos, et timuit populus a facie Domini.

** Haggai 1:13

Et dixit Aggæus, nuntius Domini de nuntiis Domini, populo dicens : Ego vobiscum sum, dicit Dominus.

** Haggai 1:14

Et suscitavit Dominus spiritum Zorobabel, filii Salathiel, ducis Juda, et spiritum Jesu, filii Josedec, sacerdotis magni, et spiritum reliquorum de omni populo : et ingressi sunt, et faciebant opus in domo Domini exercituum, Dei sui. <l eID="gen31524" level="1"/><lg eID="gen31499"/> <chapter eID="Hag.1"/>

* Haggai 2

** Haggai 2:1

In die vigesima et quarta mensis, in sexto mense, in anno secundo Darii regis.  <div eID="gen31525" type="x-p"/>

** Haggai 2:2

In septimo mense, vigesima et prima mensis, factum est verbum Domini in manu Aggæi prophetæ, dicens :

** Haggai 2:3

Loquere ad Zorobabel, filium Salathiel, ducem Juda, et ad Jesum, filium Josedec, sacerdotem magnum, et ad reliquos populi, dicens :  <div eID="gen31526" type="x-p"/>

** Haggai 2:4

Quis in vobis est derelictus, <l eID="gen31528" level="1"/> <l level="1" sID="gen31529"/>qui vidit domum istam in gloria sua prima ? <l eID="gen31529" level="1"/> <l level="1" sID="gen31530"/>et quid vos videtis hanc nunc ? <l eID="gen31530" level="1"/> <l level="1" sID="gen31531"/>numquid non ita est, quasi non sit in oculis vestris ? <l eID="gen31531" level="1"/>

** Haggai 2:5

Et nunc confortare, Zorobabel, dicit Dominus ; <l eID="gen31532" level="1"/> <l level="1" sID="gen31533"/>et confortare, Jesu, fili Josedec, sacerdos magne ; <l eID="gen31533" level="1"/> <l level="1" sID="gen31534"/>et confortare, omnis populus terræ, dicit Dominus exercituum : <l eID="gen31534" level="1"/> <l level="1" sID="gen31535"/>et facite (quoniam ego vobiscum sum, dicit Dominus exercituum) <l eID="gen31535" level="1"/>

** Haggai 2:6

verbum quod pepigi vobiscum cum egrederemini de terra Ægypti : <l eID="gen31536" level="1"/> <l level="1" sID="gen31537"/>et spiritus meus erit in medio vestrum : nolite timere. <l eID="gen31537" level="1"/>

** Haggai 2:7

Quia hæc dicit Dominus exercituum : <l eID="gen31538" level="1"/> <l level="1" sID="gen31539"/>Adhuc unum modicum est, <l eID="gen31539" level="1"/> <l level="1" sID="gen31540"/>et ego commovebo cælum, et terram, et mare, et aridam. <l eID="gen31540" level="1"/>

** Haggai 2:8

Et movebo omnes gentes, <l eID="gen31541" level="1"/> <l level="1" sID="gen31542"/>et veniet desideratus cunctis gentibus : <l eID="gen31542" level="1"/> <l level="1" sID="gen31543"/>et implebo domum istam gloria, <l eID="gen31543" level="1"/> <l level="1" sID="gen31544"/>dicit Dominus exercituum. <l eID="gen31544" level="1"/>

** Haggai 2:9

Meum est argentum, et meum est aurum, <l eID="gen31545" level="1"/> <l level="1" sID="gen31546"/>dicit Dominus exercituum. <l eID="gen31546" level="1"/>

** Haggai 2:10

Magna erit gloria domus istius novissimæ plus quam primæ, <l eID="gen31547" level="1"/> <l level="1" sID="gen31548"/>dicit Dominus exercituum : <l eID="gen31548" level="1"/> <l level="1" sID="gen31549"/>et in loco isto dabo pacem, <l eID="gen31549" level="1"/> <l level="1" sID="gen31550"/>dicit Dominus exercituum. <l eID="gen31550" level="1"/> <lg eID="gen31527"/>

** Haggai 2:11

In vigesima et quarta noni mensis, in anno secundo Darii regis, factum est verbum Domini ad Aggæum prophetam, dicens :

** Haggai 2:12

Hæc dicit Dominus exercituum : Interroga sacerdotes legem, dicens :

** Haggai 2:13

Si tulerit homo carnem sanctificatam in ora vestimenti sui, et tetigerit de summitate ejus panem, aut pulmentum, aut vinum, aut oleum, aut omnem cibum, numquid sanctificabitur ? Respondentes autem sacerdotes, dixerunt : Non.

** Haggai 2:14

Et dixit Aggæus : Si tetigerit pollutus in anima ex omnibus his, numquid contaminabitur ? Et responderunt sacerdotes, et dixerunt : Contaminabitur.

** Haggai 2:15

Et respondit Aggæus, et dixit : <div eID="gen31551" type="x-p"/> <lg sID="gen31552"/> <l level="1" sID="gen31553"/>Sic populus iste, <l eID="gen31553" level="1"/> <l level="1" sID="gen31554"/>et sic gens ista ante faciem meam, dicit Dominus, <l eID="gen31554" level="1"/> <l level="1" sID="gen31555"/>et sic omne opus manuum eorum : <l eID="gen31555" level="1"/> <l level="1" sID="gen31556"/>et omnia quæ obtulerunt ibi, contaminata erunt. <l eID="gen31556" level="1"/>

** Haggai 2:16

Et nunc ponite corda vestra a die hac et supra, <l eID="gen31557" level="1"/> <l level="1" sID="gen31558"/>antequam poneretur lapis super lapidem in templo Domini. <l eID="gen31558" level="1"/>

** Haggai 2:17

Cum accederetis ad acervum viginti modiorum, <l eID="gen31559" level="1"/> <l level="1" sID="gen31560"/>et fierent decem ; <l eID="gen31560" level="1"/> <l level="1" sID="gen31561"/>et intraretis ad torcular, ut exprimeretis quinquaginta lagenas, <l eID="gen31561" level="1"/> <l level="1" sID="gen31562"/>et fiebant viginti. <l eID="gen31562" level="1"/>

** Haggai 2:18

Percussi vos vento urente, et aurugine, <l eID="gen31563" level="1"/> <l level="1" sID="gen31564"/>et grandine omnia opera manuum vestrarum : <l eID="gen31564" level="1"/> <l level="1" sID="gen31565"/>et non fuit in vobis qui reverteretur ad me, dicit Dominus. <l eID="gen31565" level="1"/>

** Haggai 2:19

Ponite corda vestra ex die ista, et in futurum, <l eID="gen31566" level="1"/> <l level="1" sID="gen31567"/>a die vigesima et quarta noni mensis : <l eID="gen31567" level="1"/> <l level="1" sID="gen31568"/>a die qua fundamenta jacta sunt templi Domini, <l eID="gen31568" level="1"/> <l level="1" sID="gen31569"/>ponite super cor vestrum. <l eID="gen31569" level="1"/>

** Haggai 2:20

Numquid jam semen in germine est, <l eID="gen31570" level="1"/> <l level="1" sID="gen31571"/>et adhuc vinea, et ficus, <l eID="gen31571" level="1"/> <l level="1" sID="gen31572"/>et malogranatum, et lignum olivæ non floruit ? ex die ista benedicam. <l eID="gen31572" level="1"/> <lg eID="gen31552"/>

** Haggai 2:21

Et factum est verbum Domini secundo ad Aggæum in vigesima et quarta mensis, dicens :

** Haggai 2:22

Loquere ad Zorobabel ducem Juda, dicens : <div eID="gen31573" type="x-p"/> <lg sID="gen31574"/> <l level="1" sID="gen31575"/>Ego movebo cælum pariter et terram, <l eID="gen31575" level="1"/>

** Haggai 2:23

et subvertam solium regnorum, <l eID="gen31576" level="1"/> <l level="1" sID="gen31577"/>et conteram fortitudinem regni gentium : <l eID="gen31577" level="1"/> <l level="1" sID="gen31578"/>et subvertam quadrigam et ascensorem ejus, <l eID="gen31578" level="1"/> <l level="1" sID="gen31579"/>et descendent equi, et ascensores eorum, <l eID="gen31579" level="1"/> <l level="1" sID="gen31580"/>vir in gladio fratris sui. <l eID="gen31580" level="1"/>

** Haggai 2:24

In die illa, dicit Dominus exercituum, assumam te, <l eID="gen31581" level="1"/> <l level="1" sID="gen31582"/>Zorobabel, fili Salathiel, serve meus, dicit Dominus : <l eID="gen31582" level="1"/> <l level="1" sID="gen31583"/>et ponam te quasi signaculum, <l eID="gen31583" level="1"/> <l level="1" sID="gen31584"/>quia te elegi, dicit Dominus exercituum. <l eID="gen31584" level="1"/> <lg eID="gen31574"/> <chapter eID="Hag.2"/> <div eID="gen31497" osisID="Hag" type="book"/>

