* Hosea 1

** Hosea 1:1

Verbum Domini, quod factum est ad Osee, filium Beeri, in diebus Oziæ, Joathan, Achaz, Ezechiæ, regum Juda ; et in diebus Jeroboam, filii Joas, regis Israël.  <div eID="gen29143" type="x-p"/>

** Hosea 1:2

Principium loquendi Domino in Osee. Et dixit Dominus ad Osee : Vade, sume tibi uxorem fornicationum, et fac tibi filios fornicationum, quia fornicans fornicabitur terra a Domino.

** Hosea 1:3

Et abiit, et accepit Gomer, filiam Debelaim : et concepit, et peperit ei filium.

** Hosea 1:4

Et dixit Dominus ad eum : Voca nomen ejus Jezrahel, quoniam adhuc modicum, et visitabo sanguinem Jezrahel super domum Jehu, et quiescere faciam regnum domus Israël.

** Hosea 1:5

Et in illa die conteram arcum Israël in valle Jezrahel.

** Hosea 1:6

Et concepit adhuc, et peperit filiam. Et dixit ei : Voca nomen ejus, Absque misericordia, quia non addam ultra misereri domui Israël, sed oblivione obliviscar eorum.

** Hosea 1:7

Et domui Juda miserebor, et salvabo eos in Domino Deo suo ; et non salvabo eos in arcu et gladio, et in bello, et in equis, et in equitibus.

** Hosea 1:8

Et ablactavit eam quæ erat Absque misericordia. Et concepit, et peperit filium.

** Hosea 1:9

Et dixit : Voca nomen ejus, Non populus meus, quia vos non populus meus, et ego non ero vester.

** Hosea 1:10

Et erit numerus filiorum Israël quasi arena maris, quæ sine mensura est, et non numerabitur. Et erit in loco ubi dicetur eis : Non populus meus vos : dicetur eis : Filii Dei viventis.

** Hosea 1:11

Et congregabuntur filii Juda et filii Israël pariter ; et ponent sibimet caput unum, et ascendent de terra, quia magnus dies Jezrahel.  <chapter eID="Hos.1"/> <div eID="gen29144" type="x-p"/>

* Hosea 2

** Hosea 2:1

Dicite fratribus vestris : Populus meus ; et sorori vestræ : Misericordiam consecuta.  <div eID="gen29145" type="x-p"/>

** Hosea 2:2

Judicate matrem vestram, judicate, <l eID="gen29147" level="1"/> <l level="1" sID="gen29148"/>quoniam ipsa non uxor mea, <l eID="gen29148" level="1"/> <l level="1" sID="gen29149"/>et ego non vir ejus. <l eID="gen29149" level="1"/> <l level="1" sID="gen29150"/>Auferat fornicationes suas a facie sua, <l eID="gen29150" level="1"/> <l level="1" sID="gen29151"/>et adulteria sua de medio uberum suorum ; <l eID="gen29151" level="1"/>

** Hosea 2:3

ne forte expoliem eam nudam, <l eID="gen29152" level="1"/> <l level="1" sID="gen29153"/>et statuam eam secundum diem nativitatis suæ, <l eID="gen29153" level="1"/> <l level="1" sID="gen29154"/>et ponam eam quasi solitudinem, <l eID="gen29154" level="1"/> <l level="1" sID="gen29155"/>et statuam eam velut terram inviam, <l eID="gen29155" level="1"/> <l level="1" sID="gen29156"/>et interficiam eam siti. <l eID="gen29156" level="1"/>

** Hosea 2:4

Et filiorum illius non miserebor, <l eID="gen29157" level="1"/> <l level="1" sID="gen29158"/>quoniam filii fornicationum sunt. <l eID="gen29158" level="1"/>

** Hosea 2:5

Quia fornicata est mater eorum, <l eID="gen29159" level="1"/> <l level="1" sID="gen29160"/>confusa est quæ concepit eos ; <l eID="gen29160" level="1"/> <l level="1" sID="gen29161"/>quia dixit : Vadam post amatores meos, <l eID="gen29161" level="1"/> <l level="1" sID="gen29162"/>qui dant panes mihi, et aquas meas, <l eID="gen29162" level="1"/> <l level="1" sID="gen29163"/>lanam meam, et linum meum, <l eID="gen29163" level="1"/> <l level="1" sID="gen29164"/>oleum meum, et potum meum. <l eID="gen29164" level="1"/>

** Hosea 2:6

Propter hoc ecce ego sepiam viam tuam spinis, <l eID="gen29165" level="1"/> <l level="1" sID="gen29166"/>et sepiam eam maceria, et semitas suas non inveniet. <l eID="gen29166" level="1"/>

** Hosea 2:7

Et sequetur amatores suos, et non apprehendet eos ; <l eID="gen29167" level="1"/> <l level="1" sID="gen29168"/>et quæret eos, et non inveniet : <l eID="gen29168" level="1"/> <l level="1" sID="gen29169"/>et dicet : Vadam, et revertar ad virum meum priorem, <l eID="gen29169" level="1"/> <l level="1" sID="gen29170"/>quia bene mihi erat tunc magis quam nunc. <l eID="gen29170" level="1"/>

** Hosea 2:8

Et hæc nescivit, quia ego dedi ei frumentum, et vinum, et oleum, <l eID="gen29171" level="1"/> <l level="1" sID="gen29172"/>et argentum multiplicavi ei, et aurum, <l eID="gen29172" level="1"/> <l level="1" sID="gen29173"/>quæ fecerunt Baal. <l eID="gen29173" level="1"/>

** Hosea 2:9

Idcirco convertar, et sumam frumentum meum in tempore suo, <l eID="gen29174" level="1"/> <l level="1" sID="gen29175"/>et vinum meum in tempore suo. <l eID="gen29175" level="1"/> <l level="1" sID="gen29176"/>Et liberabo lanam meam et linum meum, <l eID="gen29176" level="1"/> <l level="1" sID="gen29177"/>quæ operiebant ignominiam ejus. <l eID="gen29177" level="1"/>

** Hosea 2:10

Et nunc revelabo stultitiam ejus in oculis amatorum ejus ; <l eID="gen29178" level="1"/> <l level="1" sID="gen29179"/>et vir non eruet eam de manu mea ; <l eID="gen29179" level="1"/>

** Hosea 2:11

et cessare faciam omne gaudium ejus, <l eID="gen29180" level="1"/> <l level="1" sID="gen29181"/>solemnitatem ejus, neomeniam ejus, sabbatum ejus, <l eID="gen29181" level="1"/> <l level="1" sID="gen29182"/>et omnia festa tempora ejus. <l eID="gen29182" level="1"/>

** Hosea 2:12

Et corrumpam vineam ejus, et ficum ejus, <l eID="gen29183" level="1"/> <l level="1" sID="gen29184"/>de quibus dixit : Mercedes hæ meæ sunt, <l eID="gen29184" level="1"/> <l level="1" sID="gen29185"/>quas dederunt mihi amatores mei ; <l eID="gen29185" level="1"/> <l level="1" sID="gen29186"/>et ponam eam in saltum, <l eID="gen29186" level="1"/> <l level="1" sID="gen29187"/>et comedet eam bestia agri. <l eID="gen29187" level="1"/>

** Hosea 2:13

Et visitabo super eam dies Baalim, <l eID="gen29188" level="1"/> <l level="1" sID="gen29189"/>quibus accendebat incensum, <l eID="gen29189" level="1"/> <l level="1" sID="gen29190"/>et ornabatur in aure sua, et monili suo. <l eID="gen29190" level="1"/> <l level="1" sID="gen29191"/>Et ibat post amatores suos, <l eID="gen29191" level="1"/> <l level="1" sID="gen29192"/>et mei obliviscebatur, dicit Dominus. <l eID="gen29192" level="1"/>

** Hosea 2:14

Propter hoc ecce ego lactabo eam, <l eID="gen29193" level="1"/> <l level="1" sID="gen29194"/>et ducam eam in solitudinem, <l eID="gen29194" level="1"/> <l level="1" sID="gen29195"/>et loquar ad cor ejus. <l eID="gen29195" level="1"/>

** Hosea 2:15

Et dabo ei vinitores ejus ex eodem loco, <l eID="gen29196" level="1"/> <l level="1" sID="gen29197"/>et vallem Achor, ad aperiendam spem ; <l eID="gen29197" level="1"/> <l level="1" sID="gen29198"/>et canet ibi juxta dies juventutis suæ, <l eID="gen29198" level="1"/> <l level="1" sID="gen29199"/>et juxta dies ascensionis suæ de terra Ægypti. <l eID="gen29199" level="1"/>

** Hosea 2:16

Et erit in die illa, ait Dominus : <l eID="gen29200" level="1"/> <l level="1" sID="gen29201"/>vocabit me, Vir meus, <l eID="gen29201" level="1"/> <l level="1" sID="gen29202"/>et non vocabit me ultra Baali. <l eID="gen29202" level="1"/>

** Hosea 2:17

Et auferam nomina Baalim de ore ejus, <l eID="gen29203" level="1"/> <l level="1" sID="gen29204"/>et non recordabitur ultra nominis eorum. <l eID="gen29204" level="1"/>

** Hosea 2:18

Et percutiam cum eis fœdus in die illa, cum bestia agri, <l eID="gen29205" level="1"/> <l level="1" sID="gen29206"/>et cum volucre cæli, et cum reptili terræ ; <l eID="gen29206" level="1"/> <l level="1" sID="gen29207"/>et arcum, et gladium, et bellum conteram de terra, <l eID="gen29207" level="1"/> <l level="1" sID="gen29208"/>et dormire eos faciam fiducialiter. <l eID="gen29208" level="1"/>

** Hosea 2:19

Et sponsabo te mihi in sempiternum ; <l eID="gen29209" level="1"/> <l level="1" sID="gen29210"/>et sponsabo te mihi in justitia, et judicio, <l eID="gen29210" level="1"/> <l level="1" sID="gen29211"/>et in misericordia, et in miserationibus. <l eID="gen29211" level="1"/>

** Hosea 2:20

Et sponsabo te mihi in fide ; <l eID="gen29212" level="1"/> <l level="1" sID="gen29213"/>et scies quia ego Dominus. <l eID="gen29213" level="1"/>

** Hosea 2:21

Et erit in die illa : <l eID="gen29214" level="1"/> <l level="1" sID="gen29215"/>exaudiam, dicit Dominus, exaudiam cælos, <l eID="gen29215" level="1"/> <l level="1" sID="gen29216"/>et illi exaudient terram. <l eID="gen29216" level="1"/>

** Hosea 2:22

Et terra exaudiet triticum, et vinum, et oleum, <l eID="gen29217" level="1"/> <l level="1" sID="gen29218"/>et hæc exaudient Jezrahel. <l eID="gen29218" level="1"/>

** Hosea 2:23

Et seminabo eam mihi in terra, <l eID="gen29219" level="1"/> <l level="1" sID="gen29220"/>et miserebor ejus quæ fuit Absque misericordia. <l eID="gen29220" level="1"/>

** Hosea 2:24

Et dicam Non populo meo : Populus meus es tu ; <l eID="gen29221" level="1"/> <l level="1" sID="gen29222"/>et ipse dicet : Deus meus es tu. <l eID="gen29222" level="1"/><lg eID="gen29146"/> <chapter eID="Hos.2"/>

* Hosea 3

** Hosea 3:1

Et dixit Dominus ad me : Adhuc vade, et dilige mulierem dilectam amico et adulteram, sicut diligit Dominus filios Israël, et ipsi respiciunt ad deos alienos, et diligunt vinacia uvarum.

** Hosea 3:2

Et fodi eam mihi quindecim argenteis, et coro hordei, et dimidio coro hordæi.

** Hosea 3:3

Et dixi ad eam : Dies multos exspectabis me ; non fornicaberis, et non eris viro ; sed et ego exspectabo te.

** Hosea 3:4

Quia dies multos sedebunt filii Israël sine rege, et sine principe, et sine sacrificio, et sine altari, et sine ephod, et sine theraphim.

** Hosea 3:5

Et post hæc revertentur filii Israël, et quærent Dominum Deum suum, et David regem suum : et pavebunt ad Dominum, et ad bonum ejus, in novissimo dierum.  <chapter eID="Hos.3"/>

* Hosea 4

** Hosea 4:1

Audite verbum Domini, filii Israël, <l eID="gen29225" level="1"/> <l level="1" sID="gen29226"/>quia judicium Domino cum habitatoribus terræ : <l eID="gen29226" level="1"/> <l level="1" sID="gen29227"/>non est enim veritas, et non est misericordia, <l eID="gen29227" level="1"/> <l level="1" sID="gen29228"/>et non est scientia Dei in terra. <l eID="gen29228" level="1"/>

** Hosea 4:2

Maledictum, et mendacium, <l eID="gen29229" level="1"/> <l level="1" sID="gen29230"/>et homicidium, et furtum, et adulterium inundaverunt, <l eID="gen29230" level="1"/> <l level="1" sID="gen29231"/>et sanguis sanguinem tetigit. <l eID="gen29231" level="1"/>

** Hosea 4:3

Propter hoc lugebit terra, <l eID="gen29232" level="1"/> <l level="1" sID="gen29233"/>et infirmabitur omnis qui habitat in ea, <l eID="gen29233" level="1"/> <l level="1" sID="gen29234"/>in bestia agri, et in volucre cæli ; <l eID="gen29234" level="1"/> <l level="1" sID="gen29235"/>sed et pisces maris congregabuntur. <l eID="gen29235" level="1"/>

** Hosea 4:4

Verumtamen unusquisque non judicet, <l eID="gen29236" level="1"/> <l level="1" sID="gen29237"/>et non arguatur vir : <l eID="gen29237" level="1"/> <l level="1" sID="gen29238"/>populus enim tuus sicut hi qui contradicunt sacerdoti. <l eID="gen29238" level="1"/>

** Hosea 4:5

Et corrues hodie, <l eID="gen29239" level="1"/> <l level="1" sID="gen29240"/>et corruet etiam propheta tecum. <l eID="gen29240" level="1"/> <l level="1" sID="gen29241"/>Nocte tacere feci matrem tuam. <l eID="gen29241" level="1"/>

** Hosea 4:6

Conticuit populus meus, <l eID="gen29242" level="1"/> <l level="1" sID="gen29243"/>eo quod non habuerit scientiam : <l eID="gen29243" level="1"/> <l level="1" sID="gen29244"/>quia tu scientiam repulisti, <l eID="gen29244" level="1"/> <l level="1" sID="gen29245"/>repellam te, ne sacerdotio fungaris mihi ; <l eID="gen29245" level="1"/> <l level="1" sID="gen29246"/>et oblita es legis Dei tui, <l eID="gen29246" level="1"/> <l level="1" sID="gen29247"/>obliviscar filiorum tuorum et ego. <l eID="gen29247" level="1"/>

** Hosea 4:7

Secundum multitudinem eorum sic peccaverunt mihi : <l eID="gen29248" level="1"/> <l level="1" sID="gen29249"/>gloriam eorum in ignominiam commutabo. <l eID="gen29249" level="1"/>

** Hosea 4:8

Peccata populi mei comedent, <l eID="gen29250" level="1"/> <l level="1" sID="gen29251"/>et ad iniquitatem eorum sublevabunt animas eorum. <l eID="gen29251" level="1"/>

** Hosea 4:9

Et erit sicut populus, sic sacerdos ; <l eID="gen29252" level="1"/> <l level="1" sID="gen29253"/>et visitabo super eum vias ejus, <l eID="gen29253" level="1"/> <l level="1" sID="gen29254"/>et cogitationes ejus reddam ei. <l eID="gen29254" level="1"/>

** Hosea 4:10

Et comedent, et non saturabuntur ; <l eID="gen29255" level="1"/> <l level="1" sID="gen29256"/>fornicati sunt, et non cessaverunt : <l eID="gen29256" level="1"/> <l level="1" sID="gen29257"/>quoniam Dominum dereliquerunt in non custodiendo. <l eID="gen29257" level="1"/>

** Hosea 4:11

Fornicatio, et vinum, et ebrietas auferunt cor. <l eID="gen29258" level="1"/>

** Hosea 4:12

Populus meus in ligno suo interrogavit, <l eID="gen29259" level="1"/> <l level="1" sID="gen29260"/>et baculus ejus annuntiavit ei ; <l eID="gen29260" level="1"/> <l level="1" sID="gen29261"/>spiritus enim fornicationum decepit eos, <l eID="gen29261" level="1"/> <l level="1" sID="gen29262"/>et fornicati sunt a Deo suo. <l eID="gen29262" level="1"/>

** Hosea 4:13

Super capita montium sacrificabant, <l eID="gen29263" level="1"/> <l level="1" sID="gen29264"/>et super colles ascendebant thymiama ; <l eID="gen29264" level="1"/> <l level="1" sID="gen29265"/>subtus quercum, et populum, et terebinthum, <l eID="gen29265" level="1"/> <l level="1" sID="gen29266"/>quia bona erat umbra ejus ; <l eID="gen29266" level="1"/> <l level="1" sID="gen29267"/>ideo fornicabuntur filiæ vestræ, <l eID="gen29267" level="1"/> <l level="1" sID="gen29268"/>et sponsæ vestræ adulteræ erunt. <l eID="gen29268" level="1"/>

** Hosea 4:14

Non visitabo super filias vestras cum fuerint fornicatæ, <l eID="gen29269" level="1"/> <l level="1" sID="gen29270"/>et super sponsas vestras cum adulteraverint, <l eID="gen29270" level="1"/> <l level="1" sID="gen29271"/>quoniam ipsi cum meretricibus conversabantur, <l eID="gen29271" level="1"/> <l level="1" sID="gen29272"/>et cum effeminatis sacrificabant ; <l eID="gen29272" level="1"/> <l level="1" sID="gen29273"/>et populus non intelligens vapulabit. <l eID="gen29273" level="1"/>

** Hosea 4:15

Si fornicaris tu, Israël, <l eID="gen29274" level="1"/> <l level="1" sID="gen29275"/>non delinquat saltem Juda ; <l eID="gen29275" level="1"/> <l level="1" sID="gen29276"/>et nolite ingredi in Galgala, <l eID="gen29276" level="1"/> <l level="1" sID="gen29277"/>et ne ascenderitis in Bethaven, <l eID="gen29277" level="1"/> <l level="1" sID="gen29278"/>neque juraveritis : Vivit Dominus ! <l eID="gen29278" level="1"/>

** Hosea 4:16

Quoniam sicut vacca lasciviens declinavit Israël ; <l eID="gen29279" level="1"/> <l level="1" sID="gen29280"/>nunc pascet eos Dominus, quasi agnum in latitudine. <l eID="gen29280" level="1"/>

** Hosea 4:17

Particeps idolorum Ephraim : dimitte eum. <l eID="gen29281" level="1"/>

** Hosea 4:18

Separatum est convivium eorum ; <l eID="gen29282" level="1"/> <l level="1" sID="gen29283"/>fornicatione fornicati sunt : <l eID="gen29283" level="1"/> <l level="1" sID="gen29284"/>dilexerunt afferre ignominiam protectores ejus. <l eID="gen29284" level="1"/>

** Hosea 4:19

Ligavit eum spiritus in alis suis, <l eID="gen29285" level="1"/> <l level="1" sID="gen29286"/>et confundentur a sacrificiis suis.  <chapter eID="Hos.4"/>

* Hosea 5

** Hosea 5:1

Audite hoc, sacerdotes, <l eID="gen29287" level="1"/> <l level="1" sID="gen29288"/>et attendite, domus Israël, <l eID="gen29288" level="1"/> <l level="1" sID="gen29289"/>et domus regis, auscultate : <l eID="gen29289" level="1"/> <l level="1" sID="gen29290"/>quia vobis judicium est, <l eID="gen29290" level="1"/> <l level="1" sID="gen29291"/>quoniam laqueus facti estis speculationi, <l eID="gen29291" level="1"/> <l level="1" sID="gen29292"/>et rete expansum super Thabor. <l eID="gen29292" level="1"/>

** Hosea 5:2

Et victimas declinastis in profundum ; <l eID="gen29293" level="1"/> <l level="1" sID="gen29294"/>et ego eruditor omnium eorum. <l eID="gen29294" level="1"/>

** Hosea 5:3

Ego scio Ephraim, <l eID="gen29295" level="1"/> <l level="1" sID="gen29296"/>et Israël non est absconditus a me : <l eID="gen29296" level="1"/> <l level="1" sID="gen29297"/>quia nunc fornicatus est Ephraim ; <l eID="gen29297" level="1"/> <l level="1" sID="gen29298"/>contaminatus est Israël. <l eID="gen29298" level="1"/>

** Hosea 5:4

Non dabunt cogitationes suas ut revertantur ad Deum suum, <l eID="gen29299" level="1"/> <l level="1" sID="gen29300"/>quia spiritus fornicationum in medio eorum, <l eID="gen29300" level="1"/> <l level="1" sID="gen29301"/>et Dominum non cognoverunt. <l eID="gen29301" level="1"/>

** Hosea 5:5

Et respondebit arrogantia Israël in facie ejus, <l eID="gen29302" level="1"/> <l level="1" sID="gen29303"/>et Israël et Ephraim ruent in iniquitate sua : <l eID="gen29303" level="1"/> <l level="1" sID="gen29304"/>ruet etiam Judas cum eis. <l eID="gen29304" level="1"/>

** Hosea 5:6

In gregibus suis et in armentis suis vadent ad quærendum Dominum, <l eID="gen29305" level="1"/> <l level="1" sID="gen29306"/>et non invenient : <l eID="gen29306" level="1"/> <l level="1" sID="gen29307"/>ablatus est ab eis. <l eID="gen29307" level="1"/>

** Hosea 5:7

In Dominum prævaricati sunt, <l eID="gen29308" level="1"/> <l level="1" sID="gen29309"/>quia filios alienos genuerunt : <l eID="gen29309" level="1"/> <l level="1" sID="gen29310"/>nunc devorabit eos mensis, cum partibus suis. <l eID="gen29310" level="1"/>

** Hosea 5:8

Clangite buccina in Gabaa, <l eID="gen29311" level="1"/> <l level="1" sID="gen29312"/>tuba in Rama ; <l eID="gen29312" level="1"/> <l level="1" sID="gen29313"/>ululate in Bethaven, <l eID="gen29313" level="1"/> <l level="1" sID="gen29314"/>post tergum tuum, Benjamin. <l eID="gen29314" level="1"/>

** Hosea 5:9

Ephraim in desolatione erit in die correptionis ; <l eID="gen29315" level="1"/> <l level="1" sID="gen29316"/>in tribubus Israël ostendi fidem. <l eID="gen29316" level="1"/>

** Hosea 5:10

Facti sunt principes Juda quasi assumentes terminum ; <l eID="gen29317" level="1"/> <l level="1" sID="gen29318"/>super eos effundam quasi aquam iram meam. <l eID="gen29318" level="1"/>

** Hosea 5:11

Calumniam patiens est Ephraim, fractus judicio, <l eID="gen29319" level="1"/> <l level="1" sID="gen29320"/>quoniam cœpit abire post sordes. <l eID="gen29320" level="1"/>

** Hosea 5:12

Et ego quasi tinea Ephraim, <l eID="gen29321" level="1"/> <l level="1" sID="gen29322"/>et quasi putredo domui Juda. <l eID="gen29322" level="1"/>

** Hosea 5:13

Et vidit Ephraim languorem suum, <l eID="gen29323" level="1"/> <l level="1" sID="gen29324"/>et Juda vinculum suum ; <l eID="gen29324" level="1"/> <l level="1" sID="gen29325"/>et abiit Ephraim ad Assur, <l eID="gen29325" level="1"/> <l level="1" sID="gen29326"/>et misit ad regem ultorem : <l eID="gen29326" level="1"/> <l level="1" sID="gen29327"/>et ipse non poterit sanare vos, <l eID="gen29327" level="1"/> <l level="1" sID="gen29328"/>nec solvere poterit a vobis vinculum. <l eID="gen29328" level="1"/>

** Hosea 5:14

Quoniam ego quasi leæna Ephraim, <l eID="gen29329" level="1"/> <l level="1" sID="gen29330"/>et quasi catulus leonis domui Juda. <l eID="gen29330" level="1"/> <l level="1" sID="gen29331"/>Ego, ego capiam, et vadam ; <l eID="gen29331" level="1"/> <l level="1" sID="gen29332"/>tollam, et non est qui eruat. <l eID="gen29332" level="1"/>

** Hosea 5:15

Vadens revertar ad locum meum, <l eID="gen29333" level="1"/> <l level="1" sID="gen29334"/>donec deficiatis, et quæratis faciem meam.  <chapter eID="Hos.5"/>

* Hosea 6

** Hosea 6:1

In tribulatione sua mane consurgent ad me : <l eID="gen29335" level="1"/> <l level="1" sID="gen29336"/>Venite, et revertamur ad Dominum, <l eID="gen29336" level="1"/>

** Hosea 6:2

quia ipse cepit, et sanabit nos ; <l eID="gen29337" level="1"/> <l level="1" sID="gen29338"/>percutiet, et curabit nos. <l eID="gen29338" level="1"/>

** Hosea 6:3

Vivificabit nos post duos dies ; <l eID="gen29339" level="1"/> <l level="1" sID="gen29340"/>in die tertia suscitabit nos, <l eID="gen29340" level="1"/> <l level="1" sID="gen29341"/>et vivemus in conspectu ejus. <l eID="gen29341" level="1"/> <l level="1" sID="gen29342"/>Sciemus, sequemurque ut cognoscamus Dominum : <l eID="gen29342" level="1"/> <l level="1" sID="gen29343"/>quasi diluculum præparatus est egressus ejus, <l eID="gen29343" level="1"/> <l level="1" sID="gen29344"/>et veniet quasi imber nobis temporaneus et serotinus terræ. <l eID="gen29344" level="1"/>

** Hosea 6:4

Quid faciam tibi, Ephraim ? <l eID="gen29345" level="1"/> <l level="1" sID="gen29346"/>quid faciam tibi, Juda ? <l eID="gen29346" level="1"/> <l level="1" sID="gen29347"/>misericordia vestra quasi nubes matutina, <l eID="gen29347" level="1"/> <l level="1" sID="gen29348"/>et quasi ros mane pertransiens. <l eID="gen29348" level="1"/>

** Hosea 6:5

Propter hoc dolavi in prophetis ; <l eID="gen29349" level="1"/> <l level="1" sID="gen29350"/>occidi eos in verbis oris mei : <l eID="gen29350" level="1"/> <l level="1" sID="gen29351"/>et judicia tua quasi lux egredientur. <l eID="gen29351" level="1"/>

** Hosea 6:6

Quia misericordiam volui, et non sacrificium ; <l eID="gen29352" level="1"/> <l level="1" sID="gen29353"/>et scientiam Dei plus quam holocausta. <l eID="gen29353" level="1"/>

** Hosea 6:7

Ipsi autem sicut Adam transgressi sunt pactum : <l eID="gen29354" level="1"/> <l level="1" sID="gen29355"/>ibi prævaricati sunt in me. <l eID="gen29355" level="1"/>

** Hosea 6:8

Galaad civitas operantium idolum, <l eID="gen29356" level="1"/> <l level="1" sID="gen29357"/>supplantata sanguine. <l eID="gen29357" level="1"/>

** Hosea 6:9

Et quasi fauces virorum latronum, <l eID="gen29358" level="1"/> <l level="1" sID="gen29359"/>particeps sacerdotum, in via interficientium pergentes de Sichem : <l eID="gen29359" level="1"/> <l level="1" sID="gen29360"/>quia scelus operati sunt. <l eID="gen29360" level="1"/>

** Hosea 6:10

In domo Israël vidi horrendum : <l eID="gen29361" level="1"/> <l level="1" sID="gen29362"/>ibi fornicationes Ephraim, <l eID="gen29362" level="1"/> <l level="1" sID="gen29363"/>contaminatus est Israël. <l eID="gen29363" level="1"/>

** Hosea 6:11

Sed et Juda, pone messem tibi, <l eID="gen29364" level="1"/> <l level="1" sID="gen29365"/>cum convertero captivitatem populi mei.  <chapter eID="Hos.6"/>

* Hosea 7

** Hosea 7:1

Cum sanare vellem Israël, <l eID="gen29366" level="1"/> <l level="1" sID="gen29367"/>revelata est iniquitas Ephraim, <l eID="gen29367" level="1"/> <l level="1" sID="gen29368"/>et malitia Samariæ, <l eID="gen29368" level="1"/> <l level="1" sID="gen29369"/>quia operati sunt mendacium ; <l eID="gen29369" level="1"/> <l level="1" sID="gen29370"/>et fur ingressus est spolians, <l eID="gen29370" level="1"/> <l level="1" sID="gen29371"/>latrunculus foris. <l eID="gen29371" level="1"/>

** Hosea 7:2

Et ne forte dicant in cordibus suis, <l eID="gen29372" level="1"/> <l level="1" sID="gen29373"/>omnem malitiam eorum me recordatum, <l eID="gen29373" level="1"/> <l level="1" sID="gen29374"/>nunc circumdederunt eos adinventiones suæ : <l eID="gen29374" level="1"/> <l level="1" sID="gen29375"/>coram facie mea factæ sunt. <l eID="gen29375" level="1"/>

** Hosea 7:3

In malitia sua lætificaverunt regem, <l eID="gen29376" level="1"/> <l level="1" sID="gen29377"/>et in mendaciis suis principes. <l eID="gen29377" level="1"/>

** Hosea 7:4

Omnes adulterantes, <l eID="gen29378" level="1"/> <l level="1" sID="gen29379"/>quasi clibanus succensus a coquente ; <l eID="gen29379" level="1"/> <l level="1" sID="gen29380"/>quievit paululum civitas a commistione fermenti, <l eID="gen29380" level="1"/> <l level="1" sID="gen29381"/>donec fermentaretur totum. <l eID="gen29381" level="1"/>

** Hosea 7:5

Dies regis nostri : cœperunt principes furere a vino ; <l eID="gen29382" level="1"/> <l level="1" sID="gen29383"/>extendit manum suam cum illusoribus. <l eID="gen29383" level="1"/>

** Hosea 7:6

Quia applicuerunt quasi clibanum cor suum, <l eID="gen29384" level="1"/> <l level="1" sID="gen29385"/>cum insidiaretur eis ; <l eID="gen29385" level="1"/> <l level="1" sID="gen29386"/>tota nocte dormivit coquens eos : <l eID="gen29386" level="1"/> <l level="1" sID="gen29387"/>mane ipse succensus quasi ignis flammæ. <l eID="gen29387" level="1"/>

** Hosea 7:7

Omnes calefacti sunt quasi clibanus, <l eID="gen29388" level="1"/> <l level="1" sID="gen29389"/>et devoraverunt judices suos : <l eID="gen29389" level="1"/> <l level="1" sID="gen29390"/>omnes reges eorum ceciderunt ; <l eID="gen29390" level="1"/> <l level="1" sID="gen29391"/>non est qui clamat in eis ad me. <l eID="gen29391" level="1"/>

** Hosea 7:8

Ephraim in populis ipse commiscebatur ; <l eID="gen29392" level="1"/> <l level="1" sID="gen29393"/>Ephraim factus est subcinericius panis, qui non reversatur. <l eID="gen29393" level="1"/>

** Hosea 7:9

Comederunt alieni robur ejus, et ipse nescivit ; <l eID="gen29394" level="1"/> <l level="1" sID="gen29395"/>sed et cani effusi sunt in eo, et ipse ignoravit. <l eID="gen29395" level="1"/>

** Hosea 7:10

Et humiliabitur superbia Israël in facie ejus ; <l eID="gen29396" level="1"/> <l level="1" sID="gen29397"/>nec reversi sunt ad Dominum Deum suum, <l eID="gen29397" level="1"/> <l level="1" sID="gen29398"/>et non quæsierunt eum in omnibus his. <l eID="gen29398" level="1"/>

** Hosea 7:11

Et factus est Ephraim quasi columba seducta non habens cor. <l eID="gen29399" level="1"/> <l level="1" sID="gen29400"/>Ægyptum invocabant ; ad Assyrios abierunt. <l eID="gen29400" level="1"/>

** Hosea 7:12

Et cum profecti fuerint, <l eID="gen29401" level="1"/> <l level="1" sID="gen29402"/>expandam super eos rete meum : <l eID="gen29402" level="1"/> <l level="1" sID="gen29403"/>quasi volucrem cæli detraham eos ; <l eID="gen29403" level="1"/> <l level="1" sID="gen29404"/>cædam eos secundum auditionem cœtus eorum. <l eID="gen29404" level="1"/>

** Hosea 7:13

Væ eis, quoniam recesserunt a me ! <l eID="gen29405" level="1"/> <l level="1" sID="gen29406"/>vastabuntur, quia prævaricati sunt in me, <l eID="gen29406" level="1"/> <l level="1" sID="gen29407"/>et ego redemi eos, <l eID="gen29407" level="1"/> <l level="1" sID="gen29408"/>et ipsi locuti sunt contra me mendacia. <l eID="gen29408" level="1"/>

** Hosea 7:14

Et non clamaverunt ad me in corde suo, <l eID="gen29409" level="1"/> <l level="1" sID="gen29410"/>sed ululabant in cubilibus suis : <l eID="gen29410" level="1"/> <l level="1" sID="gen29411"/>super triticum et vinum ruminabant ; <l eID="gen29411" level="1"/> <l level="1" sID="gen29412"/>recesserunt a me. <l eID="gen29412" level="1"/>

** Hosea 7:15

Et ego erudivi eos, et confortavi brachia eorum, <l eID="gen29413" level="1"/> <l level="1" sID="gen29414"/>et in me cogitaverunt malitiam. <l eID="gen29414" level="1"/>

** Hosea 7:16

Reversi sunt ut essent absque jugo ; <l eID="gen29415" level="1"/> <l level="1" sID="gen29416"/>facti sunt quasi arcus dolosus : <l eID="gen29416" level="1"/> <l level="1" sID="gen29417"/>cadent in gladio principes eorum, a furore linguæ suæ. <l eID="gen29417" level="1"/> <l level="1" sID="gen29418"/>Ista subsannatio eorum in terra Ægypti.  <chapter eID="Hos.7"/>

* Hosea 8

** Hosea 8:1

In gutture tuo sit tuba <l eID="gen29419" level="1"/> <l level="1" sID="gen29420"/>quasi aquila super domum Domini, <l eID="gen29420" level="1"/> <l level="1" sID="gen29421"/>pro eo quod transgressi sunt fœdus meum, <l eID="gen29421" level="1"/> <l level="1" sID="gen29422"/>et legem meam prævaricati sunt. <l eID="gen29422" level="1"/>

** Hosea 8:2

Me invocabunt : Deus meus, <l eID="gen29423" level="1"/> <l level="1" sID="gen29424"/>cognovimus te Israël. <l eID="gen29424" level="1"/>

** Hosea 8:3

Projecit Israël bonum : <l eID="gen29425" level="1"/> <l level="1" sID="gen29426"/>inimicus persequetur eum. <l eID="gen29426" level="1"/>

** Hosea 8:4

Ipsi regnaverunt, et non ex me ; <l eID="gen29427" level="1"/> <l level="1" sID="gen29428"/>principes exstiterunt, et non cognovi : <l eID="gen29428" level="1"/> <l level="1" sID="gen29429"/>argentum suum et aurum suum fecerunt sibi idola, <l eID="gen29429" level="1"/> <l level="1" sID="gen29430"/>ut interirent. <l eID="gen29430" level="1"/>

** Hosea 8:5

Projectus est vitulus tuus, Samaria ; <l eID="gen29431" level="1"/> <l level="1" sID="gen29432"/>iratus est furor meus in eos. <l eID="gen29432" level="1"/> <l level="1" sID="gen29433"/>Usquequo non poterunt emundari ? <l eID="gen29433" level="1"/>

** Hosea 8:6

Quia ex Israël et ipse est : <l eID="gen29434" level="1"/> <l level="1" sID="gen29435"/>artifex fecit illum, et non est deus ; <l eID="gen29435" level="1"/> <l level="1" sID="gen29436"/>quoniam in aranearum telas erit vitulus Samariæ. <l eID="gen29436" level="1"/>

** Hosea 8:7

Quia ventum seminabunt, <l eID="gen29437" level="1"/> <l level="1" sID="gen29438"/>et turbinem metent : <l eID="gen29438" level="1"/> <l level="1" sID="gen29439"/>culmus stans non est in eo ; <l eID="gen29439" level="1"/> <l level="1" sID="gen29440"/>germen non faciet farinam : <l eID="gen29440" level="1"/> <l level="1" sID="gen29441"/>quod etsi fecerit, alieni comedent eam. <l eID="gen29441" level="1"/>

** Hosea 8:8

Devoratus est Israël ; <l eID="gen29442" level="1"/> <l level="1" sID="gen29443"/>nunc factus est in nationibus quasi vas immundum. <l eID="gen29443" level="1"/>

** Hosea 8:9

Quia ipsi ascenderunt ad Assur, <l eID="gen29444" level="1"/> <l level="1" sID="gen29445"/>onager solitarius sibi ; <l eID="gen29445" level="1"/> <l level="1" sID="gen29446"/>Ephraim munera dederunt amatoribus. <l eID="gen29446" level="1"/>

** Hosea 8:10

Sed et cum mercede conduxerint nationes, <l eID="gen29447" level="1"/> <l level="1" sID="gen29448"/>nunc congregabo eos, <l eID="gen29448" level="1"/> <l level="1" sID="gen29449"/>et quiescent paulisper ab onere regis et principum. <l eID="gen29449" level="1"/>

** Hosea 8:11

Quia multiplicavit Ephraim altaria ad peccandum ; <l eID="gen29450" level="1"/> <l level="1" sID="gen29451"/>factæ sunt ei aræ in delictum. <l eID="gen29451" level="1"/>

** Hosea 8:12

Scribam ei multiplices leges meas, <l eID="gen29452" level="1"/> <l level="1" sID="gen29453"/>quæ velut alienæ computatæ sunt. <l eID="gen29453" level="1"/>

** Hosea 8:13

Hostias offerent, <l eID="gen29454" level="1"/> <l level="1" sID="gen29455"/>immolabunt carnes et comedent, <l eID="gen29455" level="1"/> <l level="1" sID="gen29456"/>et Dominus non suscipiet eas : <l eID="gen29456" level="1"/> <l level="1" sID="gen29457"/>nunc recordabitur iniquitatis eorum, <l eID="gen29457" level="1"/> <l level="1" sID="gen29458"/>et visitabit peccata eorum : <l eID="gen29458" level="1"/> <l level="1" sID="gen29459"/>ipsi in Ægyptum convertentur. <l eID="gen29459" level="1"/>

** Hosea 8:14

Et oblitus est Israël factoris sui, <l eID="gen29460" level="1"/> <l level="1" sID="gen29461"/>et ædificavit delubra ; <l eID="gen29461" level="1"/> <l level="1" sID="gen29462"/>et Judas multiplicavit urbes munitas ; <l eID="gen29462" level="1"/> <l level="1" sID="gen29463"/>et mittam ignem in civitates ejus, <l eID="gen29463" level="1"/> <l level="1" sID="gen29464"/>et devorabit ædes illius.  <chapter eID="Hos.8"/>

* Hosea 9

** Hosea 9:1

Noli lætari, Israël ; <l eID="gen29465" level="1"/> <l level="1" sID="gen29466"/>noli exsultare sicut populi : <l eID="gen29466" level="1"/> <l level="1" sID="gen29467"/>quia fornicatus es a Deo tuo ; <l eID="gen29467" level="1"/> <l level="1" sID="gen29468"/>dilexisti mercedem super omnes areas tritici. <l eID="gen29468" level="1"/>

** Hosea 9:2

Area et torcular non pascet eos, <l eID="gen29469" level="1"/> <l level="1" sID="gen29470"/>et vinum mentietur eis : <l eID="gen29470" level="1"/>

** Hosea 9:3

non habitabunt in terra Domini. <l eID="gen29471" level="1"/> <l level="1" sID="gen29472"/>Reversus est Ephraim in Ægyptum, <l eID="gen29472" level="1"/> <l level="1" sID="gen29473"/>et in Assyriis pollutum comedit. <l eID="gen29473" level="1"/>

** Hosea 9:4

Non libabunt Domino vinum, <l eID="gen29474" level="1"/> <l level="1" sID="gen29475"/>et non placebunt ei. <l eID="gen29475" level="1"/> <l level="1" sID="gen29476"/>Sacrificia eorum quasi panis lugentium ; <l eID="gen29476" level="1"/> <l level="1" sID="gen29477"/>omnes qui comedent eum, contaminabuntur : <l eID="gen29477" level="1"/> <l level="1" sID="gen29478"/>quia panis eorum animæ ipsorum : <l eID="gen29478" level="1"/> <l level="1" sID="gen29479"/>non intrabit in domum Domini. <l eID="gen29479" level="1"/>

** Hosea 9:5

Quid facietis in die solemni, <l eID="gen29480" level="1"/> <l level="1" sID="gen29481"/>in die festivitatis Domini ? <l eID="gen29481" level="1"/>

** Hosea 9:6

Ecce enim profecti sunt a vastitate : <l eID="gen29482" level="1"/> <l level="1" sID="gen29483"/>Ægyptus congregabit eos ; <l eID="gen29483" level="1"/> <l level="1" sID="gen29484"/>Memphis sepeliet eos : <l eID="gen29484" level="1"/> <l level="1" sID="gen29485"/>desiderabile argentum eorum urtica hæreditabit, <l eID="gen29485" level="1"/> <l level="1" sID="gen29486"/>lappa in tabernaculis eorum. <l eID="gen29486" level="1"/>

** Hosea 9:7

Venerunt dies visitationis, <l eID="gen29487" level="1"/> <l level="1" sID="gen29488"/>venerunt dies retributionis. <l eID="gen29488" level="1"/> <l level="1" sID="gen29489"/>Scitote, Israël, <l eID="gen29489" level="1"/> <l level="1" sID="gen29490"/>stultum prophetam, <l eID="gen29490" level="1"/> <l level="1" sID="gen29491"/>insanum virum spiritualem, <l eID="gen29491" level="1"/> <l level="1" sID="gen29492"/>propter multitudinem iniquitatis tuæ, <l eID="gen29492" level="1"/> <l level="1" sID="gen29493"/>et multitudinem amentiæ. <l eID="gen29493" level="1"/>

** Hosea 9:8

Speculator Ephraim cum Deo meo, <l eID="gen29494" level="1"/> <l level="1" sID="gen29495"/>propheta laqueus ruinæ factus est super omnes vias ejus ; <l eID="gen29495" level="1"/> <l level="1" sID="gen29496"/>insania in domo Dei ejus. <l eID="gen29496" level="1"/>

** Hosea 9:9

Profunde peccaverunt, sicut in diebus Gabaa. <l eID="gen29497" level="1"/> <l level="1" sID="gen29498"/>Recordabitur iniquitatis eorum, <l eID="gen29498" level="1"/> <l level="1" sID="gen29499"/>et visitabit peccata eorum. <l eID="gen29499" level="1"/>

** Hosea 9:10

Quasi uvas in deserto inveni Israël, <l eID="gen29500" level="1"/> <l level="1" sID="gen29501"/>quasi prima poma ficulneæ in cacumine ejus vidi patres eorum : <l eID="gen29501" level="1"/> <l level="1" sID="gen29502"/>ipsi autem intraverunt ad Beelphegor, <l eID="gen29502" level="1"/> <l level="1" sID="gen29503"/>et abalienati sunt in confusionem, <l eID="gen29503" level="1"/> <l level="1" sID="gen29504"/>et facti sunt abominabiles sicut ea quæ dilexerunt. <l eID="gen29504" level="1"/>

** Hosea 9:11

Ephraim quasi avis avolavit ; <l eID="gen29505" level="1"/> <l level="1" sID="gen29506"/>gloria eorum a partu, et ab utero, et a conceptu. <l eID="gen29506" level="1"/>

** Hosea 9:12

Quod etsi enutrierint filios suos, <l eID="gen29507" level="1"/> <l level="1" sID="gen29508"/>absque liberis eos faciam in hominibus ; <l eID="gen29508" level="1"/> <l level="1" sID="gen29509"/>sed et væ eis cum recessero ab eis ! <l eID="gen29509" level="1"/>

** Hosea 9:13

Ephraim, ut vidi, Tyrus erat fundata in pulchritudine ; <l eID="gen29510" level="1"/> <l level="1" sID="gen29511"/>et Ephraim educet ad interfectorem filios suos. <l eID="gen29511" level="1"/>

** Hosea 9:14

Da eis, Domine. Quid dabis eis ? <l eID="gen29512" level="1"/> <l level="1" sID="gen29513"/>da eis vulvam sine liberis, et ubera arentia. <l eID="gen29513" level="1"/>

** Hosea 9:15

Omnes nequitiæ eorum in Galgal, <l eID="gen29514" level="1"/> <l level="1" sID="gen29515"/>quia ibi exosos habui eos. <l eID="gen29515" level="1"/> <l level="1" sID="gen29516"/>Propter malitiam adinventionum eorum, <l eID="gen29516" level="1"/> <l level="1" sID="gen29517"/>de domo mea ejiciam eos ; <l eID="gen29517" level="1"/> <l level="1" sID="gen29518"/>non addam ut diligam eos : <l eID="gen29518" level="1"/> <l level="1" sID="gen29519"/>omnes principes eorum recedentes. <l eID="gen29519" level="1"/>

** Hosea 9:16

Percussus est Ephraim ; <l eID="gen29520" level="1"/> <l level="1" sID="gen29521"/>radix eorum exsiccata est : <l eID="gen29521" level="1"/> <l level="1" sID="gen29522"/>fructum nequaquam facient, <l eID="gen29522" level="1"/> <l level="1" sID="gen29523"/>quod etsi genuerint, <l eID="gen29523" level="1"/> <l level="1" sID="gen29524"/>interficiam amantissima uteri eorum. <l eID="gen29524" level="1"/>

** Hosea 9:17

Abjiciet eos Deus meus, quia non audierunt eum, <l eID="gen29525" level="1"/> <l level="1" sID="gen29526"/>et erunt vagi in nationibus.  <chapter eID="Hos.9"/>

* Hosea 10

** Hosea 10:1

Vitis frondosa Israël, <l eID="gen29527" level="1"/> <l level="1" sID="gen29528"/>fructus adæquatus est ei : <l eID="gen29528" level="1"/> <l level="1" sID="gen29529"/>secundum multitudinem fructus sui multiplicavit altaria, <l eID="gen29529" level="1"/> <l level="1" sID="gen29530"/>juxta ubertatem terræ suæ exuberavit simulacris. <l eID="gen29530" level="1"/>

** Hosea 10:2

Divisum est cor eorum, nunc interibunt ; <l eID="gen29531" level="1"/> <l level="1" sID="gen29532"/>ipse confringet simulacra eorum, <l eID="gen29532" level="1"/> <l level="1" sID="gen29533"/>depopulabitur aras eorum. <l eID="gen29533" level="1"/>

** Hosea 10:3

Quia nunc dicent : Non est rex nobis, <l eID="gen29534" level="1"/> <l level="1" sID="gen29535"/>non enim timemus Dominum ; <l eID="gen29535" level="1"/> <l level="1" sID="gen29536"/>et rex quid faciet nobis ? <l eID="gen29536" level="1"/>

** Hosea 10:4

Loquimini verba visionis inutilis, et ferietis fœdus ; <l eID="gen29537" level="1"/> <l level="1" sID="gen29538"/>et germinabit quasi amaritudo judicium super sulcos agri. <l eID="gen29538" level="1"/>

** Hosea 10:5

Vaccas Bethaven coluerunt habitatores Samariæ ; <l eID="gen29539" level="1"/> <l level="1" sID="gen29540"/>quia luxit super eum populus ejus, <l eID="gen29540" level="1"/> <l level="1" sID="gen29541"/>et æditui ejus super eum exsultaverunt <l eID="gen29541" level="1"/> <l level="1" sID="gen29542"/>in gloria ejus, quia migravit ab eo. <l eID="gen29542" level="1"/>

** Hosea 10:6

Siquidem et ipse in Assur delatus est, <l eID="gen29543" level="1"/> <l level="1" sID="gen29544"/>munus regi ultori. <l eID="gen29544" level="1"/> <l level="1" sID="gen29545"/>Confusio Ephraim capiet, <l eID="gen29545" level="1"/> <l level="1" sID="gen29546"/>et confundetur Israël in voluntate sua. <l eID="gen29546" level="1"/>

** Hosea 10:7

Transire fecit Samaria regem suum <l eID="gen29547" level="1"/> <l level="1" sID="gen29548"/>quasi spumam super faciem aquæ. <l eID="gen29548" level="1"/>

** Hosea 10:8

Et disperdentur excelsa idoli, peccatum Israël ; <l eID="gen29549" level="1"/> <l level="1" sID="gen29550"/>lappa et tribulus ascendet super aras eorum : <l eID="gen29550" level="1"/> <l level="1" sID="gen29551"/>et dicent montibus : Operite nos, <l eID="gen29551" level="1"/> <l level="1" sID="gen29552"/>et collibus : Cadite super nos. <l eID="gen29552" level="1"/>

** Hosea 10:9

Ex diebus Gabaa peccavit Israël ; <l eID="gen29553" level="1"/> <l level="1" sID="gen29554"/>ibi steterunt. <l eID="gen29554" level="1"/> <l level="1" sID="gen29555"/>Non comprehendet eos in Gabaa <l eID="gen29555" level="1"/> <l level="1" sID="gen29556"/>prælium super filios iniquitatis. <l eID="gen29556" level="1"/>

** Hosea 10:10

Juxta desiderium meum corripiam eos : <l eID="gen29557" level="1"/> <l level="1" sID="gen29558"/>congregabuntur super eos populi, <l eID="gen29558" level="1"/> <l level="1" sID="gen29559"/>cum corripientur propter duas iniquitates suas. <l eID="gen29559" level="1"/>

** Hosea 10:11

Ephraim vitula docta diligere trituram, <l eID="gen29560" level="1"/> <l level="1" sID="gen29561"/>et ego transivi super pulchritudinem colli ejus : <l eID="gen29561" level="1"/> <l level="1" sID="gen29562"/>ascendam super Ephraim, <l eID="gen29562" level="1"/> <l level="1" sID="gen29563"/>arabit Judas ; <l eID="gen29563" level="1"/> <l level="1" sID="gen29564"/>confringet sibi sulcos Jacob. <l eID="gen29564" level="1"/>

** Hosea 10:12

Seminate vobis in justitia, <l eID="gen29565" level="1"/> <l level="1" sID="gen29566"/>et metite in ore misericordiæ. <l eID="gen29566" level="1"/> <l level="1" sID="gen29567"/>Innovate vobis novale ; <l eID="gen29567" level="1"/> <l level="1" sID="gen29568"/>tempus autem requirendi Dominum, <l eID="gen29568" level="1"/> <l level="1" sID="gen29569"/>cum venerit qui docebit vos justitiam. <l eID="gen29569" level="1"/>

** Hosea 10:13

Arastis impietatem, <l eID="gen29570" level="1"/> <l level="1" sID="gen29571"/>iniquitatem messuistis : <l eID="gen29571" level="1"/> <l level="1" sID="gen29572"/>comedistis frugem mendacii, <l eID="gen29572" level="1"/> <l level="1" sID="gen29573"/>quia confisus es in viis tuis, <l eID="gen29573" level="1"/> <l level="1" sID="gen29574"/>in multitudine fortium tuorum. <l eID="gen29574" level="1"/>

** Hosea 10:14

Consurget tumultus in populo tuo ; <l eID="gen29575" level="1"/> <l level="1" sID="gen29576"/>et omnes munitiones tuæ vastabuntur, <l eID="gen29576" level="1"/> <l level="1" sID="gen29577"/>sicut vastatus est Salmana a domo ejus qui judicavit Baal <l eID="gen29577" level="1"/> <l level="1" sID="gen29578"/>in die prælii, matre super filios allisa. <l eID="gen29578" level="1"/>

** Hosea 10:15

Sic fecit vobis Bethel, <l eID="gen29579" level="1"/> <l level="1" sID="gen29580"/>a facie malitiæ nequitiarum vestrarum.  <chapter eID="Hos.10"/>

* Hosea 11

** Hosea 11:1

Sicut mane transiit, pertransiit rex Israël. <l eID="gen29581" level="1"/> <l level="1" sID="gen29582"/>Quia puer Israël, et dilexi eum ; <l eID="gen29582" level="1"/> <l level="1" sID="gen29583"/>et ex Ægypto vocavi filium meum. <l eID="gen29583" level="1"/>

** Hosea 11:2

Vocaverunt eos, sic abierunt a facie eorum ; <l eID="gen29584" level="1"/> <l level="1" sID="gen29585"/>Baalim immolabant, et simulacris sacrificabant. <l eID="gen29585" level="1"/>

** Hosea 11:3

Et ego quasi nutritius Ephraim : <l eID="gen29586" level="1"/> <l level="1" sID="gen29587"/>portabam eos in brachiis meis, <l eID="gen29587" level="1"/> <l level="1" sID="gen29588"/>et nescierunt quod curarem eos. <l eID="gen29588" level="1"/>

** Hosea 11:4

In funiculis Adam traham eos, <l eID="gen29589" level="1"/> <l level="1" sID="gen29590"/>in vinculis caritatis ; <l eID="gen29590" level="1"/> <l level="1" sID="gen29591"/>et ero eis quasi exaltans jugum super maxillas eorum, <l eID="gen29591" level="1"/> <l level="1" sID="gen29592"/>et declinavi ad eum ut vesceretur. <l eID="gen29592" level="1"/>

** Hosea 11:5

Non revertetur in terram Ægypti, et Assur ipse rex ejus, <l eID="gen29593" level="1"/> <l level="1" sID="gen29594"/>quoniam noluerunt converti. <l eID="gen29594" level="1"/>

** Hosea 11:6

Cœpit gladius in civitatibus ejus, <l eID="gen29595" level="1"/> <l level="1" sID="gen29596"/>et consumet electos ejus, <l eID="gen29596" level="1"/> <l level="1" sID="gen29597"/>et comedet capita eorum. <l eID="gen29597" level="1"/>

** Hosea 11:7

Et populus meus pendebit ad reditum meum ; <l eID="gen29598" level="1"/> <l level="1" sID="gen29599"/>jugum autem imponetur eis simul, quod non auferetur. <l eID="gen29599" level="1"/>

** Hosea 11:8

Quomodo dabo te, Ephraim ? <l eID="gen29600" level="1"/> <l level="1" sID="gen29601"/>protegam te, Israël ? <l eID="gen29601" level="1"/> <l level="1" sID="gen29602"/>Quomodo dabo te sicut Adama, <l eID="gen29602" level="1"/> <l level="1" sID="gen29603"/>ponam te ut Seboim ? <l eID="gen29603" level="1"/> <l level="1" sID="gen29604"/>Conversum est in me cor meum, <l eID="gen29604" level="1"/> <l level="1" sID="gen29605"/>pariter conturbata est pœnitudo mea. <l eID="gen29605" level="1"/>

** Hosea 11:9

Non faciam furorem iræ meæ ; <l eID="gen29606" level="1"/> <l level="1" sID="gen29607"/>non convertar ut disperdam Ephraim, <l eID="gen29607" level="1"/> <l level="1" sID="gen29608"/>quoniam Deus ego, et non homo ; <l eID="gen29608" level="1"/> <l level="1" sID="gen29609"/>in medio tui sanctus, <l eID="gen29609" level="1"/> <l level="1" sID="gen29610"/>et non ingrediar civitatem. <l eID="gen29610" level="1"/>

** Hosea 11:10

Post Dominum ambulabunt ; <l eID="gen29611" level="1"/> <l level="1" sID="gen29612"/>quasi leo rugiet, <l eID="gen29612" level="1"/> <l level="1" sID="gen29613"/>quia ipse rugiet, <l eID="gen29613" level="1"/> <l level="1" sID="gen29614"/>et formidabunt filii maris. <l eID="gen29614" level="1"/>

** Hosea 11:11

Et avolabunt quasi avis ex Ægypto, <l eID="gen29615" level="1"/> <l level="1" sID="gen29616"/>et quasi columba de terra Assyriorum : <l eID="gen29616" level="1"/> <l level="1" sID="gen29617"/>et collocabo eos in domibus suis, dicit Dominus. <l eID="gen29617" level="1"/>

** Hosea 11:12

Circumdedit me in negatione Ephraim, <l eID="gen29618" level="1"/> <l level="1" sID="gen29619"/>et in dolo domus Israël ; <l eID="gen29619" level="1"/> <l level="1" sID="gen29620"/>Judas autem testis descendit cum Deo, <l eID="gen29620" level="1"/> <l level="1" sID="gen29621"/>et cum sanctis fidelis.  <chapter eID="Hos.11"/>

* Hosea 12

** Hosea 12:1

Ephraim pascit ventum, <l eID="gen29622" level="1"/> <l level="1" sID="gen29623"/>et sequitur æstum ; <l eID="gen29623" level="1"/> <l level="1" sID="gen29624"/>tota die mendacium et vastitatem multiplicat : <l eID="gen29624" level="1"/> <l level="1" sID="gen29625"/>et fœdus cum Assyriis iniit, <l eID="gen29625" level="1"/> <l level="1" sID="gen29626"/>et oleum in Ægyptum ferebat. <l eID="gen29626" level="1"/>

** Hosea 12:2

Judicium ergo Domini cum Juda, <l eID="gen29627" level="1"/> <l level="1" sID="gen29628"/>et visitatio super Jacob : <l eID="gen29628" level="1"/> <l level="1" sID="gen29629"/>juxta vias ejus, et juxta adinventiones ejus reddet ei. <l eID="gen29629" level="1"/>

** Hosea 12:3

In utero supplantavit fratrem suum, <l eID="gen29630" level="1"/> <l level="1" sID="gen29631"/>et in fortitudine sua directus est cum angelo. <l eID="gen29631" level="1"/>

** Hosea 12:4

Et invaluit ad angelum, et confortatus est ; <l eID="gen29632" level="1"/> <l level="1" sID="gen29633"/>flevit, et rogavit eum. <l eID="gen29633" level="1"/> <l level="1" sID="gen29634"/>In Bethel invenit eum, <l eID="gen29634" level="1"/> <l level="1" sID="gen29635"/>et ibi locutus est nobiscum. <l eID="gen29635" level="1"/>

** Hosea 12:5

Et Dominus Deus exercituum, <l eID="gen29636" level="1"/> <l level="1" sID="gen29637"/>Dominus memoriale ejus. <l eID="gen29637" level="1"/>

** Hosea 12:6

Et tu ad Deum tuum converteris ; <l eID="gen29638" level="1"/> <l level="1" sID="gen29639"/>misericordiam et judicium custodi, <l eID="gen29639" level="1"/> <l level="1" sID="gen29640"/>et spera in Deo tuo semper. <l eID="gen29640" level="1"/>

** Hosea 12:7

Chanaan, in manu ejus statera dolosa, <l eID="gen29641" level="1"/> <l level="1" sID="gen29642"/>calumniam dilexit. <l eID="gen29642" level="1"/>

** Hosea 12:8

Et dixit Ephraim : Verumtamen dives effectus sum ; <l eID="gen29643" level="1"/> <l level="1" sID="gen29644"/>inveni idolum mihi : <l eID="gen29644" level="1"/> <l level="1" sID="gen29645"/>omnes labores mei non invenient mihi iniquitatem quam peccavi. <l eID="gen29645" level="1"/>

** Hosea 12:9

Et ego Dominus Deus tuus ex terra Ægypti : <l eID="gen29646" level="1"/> <l level="1" sID="gen29647"/>adhuc sedere te faciam in tabernaculis, sicut in diebus festivitatis. <l eID="gen29647" level="1"/>

** Hosea 12:10

Et locutus sum super prophetas, <l eID="gen29648" level="1"/> <l level="1" sID="gen29649"/>et ego visionem multiplicavi, <l eID="gen29649" level="1"/> <l level="1" sID="gen29650"/>et in manu prophetarum assimilatus sum. <l eID="gen29650" level="1"/>

** Hosea 12:11

Si Galaad idolum, ergo frustra erant in Galgal bobus immolantes ; <l eID="gen29651" level="1"/> <l level="1" sID="gen29652"/>nam et altaria eorum quasi acervi super sulcos agri. <l eID="gen29652" level="1"/>

** Hosea 12:12

Fugit Jacob in regionem Syriæ, <l eID="gen29653" level="1"/> <l level="1" sID="gen29654"/>et servivit Israël in uxorem, <l eID="gen29654" level="1"/> <l level="1" sID="gen29655"/>et in uxorem servavit. <l eID="gen29655" level="1"/>

** Hosea 12:13

In propheta autem eduxit Dominus Israël de Ægypto, <l eID="gen29656" level="1"/> <l level="1" sID="gen29657"/>et in propheta servatus est. <l eID="gen29657" level="1"/>

** Hosea 12:14

Ad iracundiam me provocavit Ephraim in amaritudinibus suis : <l eID="gen29658" level="1"/> <l level="1" sID="gen29659"/>et sanguis ejus super eum veniet, <l eID="gen29659" level="1"/> <l level="1" sID="gen29660"/>et opprobrium ejus restituet ei Dominus suus.  <chapter eID="Hos.12"/>

* Hosea 13

** Hosea 13:1

Loquente Ephraim, horror invasit Israël ; <l eID="gen29661" level="1"/> <l level="1" sID="gen29662"/>et deliquit in Baal, et mortuus est. <l eID="gen29662" level="1"/>

** Hosea 13:2

Et nunc addiderunt ad peccandum ; <l eID="gen29663" level="1"/> <l level="1" sID="gen29664"/>feceruntque sibi conflatile de argento suo <l eID="gen29664" level="1"/> <l level="1" sID="gen29665"/>quasi similitudinem idolorum : <l eID="gen29665" level="1"/> <l level="1" sID="gen29666"/>factura artificum totum est : <l eID="gen29666" level="1"/> <l level="1" sID="gen29667"/>his ipsi dicunt : Immolate homines, vitulos adorantes. <l eID="gen29667" level="1"/>

** Hosea 13:3

Idcirco erunt quasi nubes matutina, <l eID="gen29668" level="1"/> <l level="1" sID="gen29669"/>et sicut ros matutinus præteriens ; <l eID="gen29669" level="1"/> <l level="1" sID="gen29670"/>sicut pulvis turbine raptus ex area, <l eID="gen29670" level="1"/> <l level="1" sID="gen29671"/>et sicut fumus de fumario. <l eID="gen29671" level="1"/>

** Hosea 13:4

Ego autem Dominus Deus tuus, ex terra Ægypti ; <l eID="gen29672" level="1"/> <l level="1" sID="gen29673"/>et Deum absque me nescies, <l eID="gen29673" level="1"/> <l level="1" sID="gen29674"/>et salvator non est præter me. <l eID="gen29674" level="1"/>

** Hosea 13:5

Ego cognovi te in deserto, <l eID="gen29675" level="1"/> <l level="1" sID="gen29676"/>in terra solitudinis. <l eID="gen29676" level="1"/>

** Hosea 13:6

Juxta pascua sua adimpleti sunt et saturati sunt ; <l eID="gen29677" level="1"/> <l level="1" sID="gen29678"/>et levaverunt cor suum, et obliti sunt mei. <l eID="gen29678" level="1"/>

** Hosea 13:7

Et ego ero eis quasi leæna, <l eID="gen29679" level="1"/> <l level="1" sID="gen29680"/>sicut pardus in via Assyriorum. <l eID="gen29680" level="1"/>

** Hosea 13:8

Occurram eis quasi ursa raptis catulis, <l eID="gen29681" level="1"/> <l level="1" sID="gen29682"/>et dirumpam interiora jecoris eorum, <l eID="gen29682" level="1"/> <l level="1" sID="gen29683"/>et consumam eos ibi quasi leo : <l eID="gen29683" level="1"/> <l level="1" sID="gen29684"/>bestia agri scindet eos. <l eID="gen29684" level="1"/>

** Hosea 13:9

Perditio tua, Israël : tantummodo in me auxilium tuum. <l eID="gen29685" level="1"/>

** Hosea 13:10

Ubi est rex tuus ? <l eID="gen29686" level="1"/> <l level="1" sID="gen29687"/>maxime nunc salvet te in omnibus urbibus tuis ; <l eID="gen29687" level="1"/> <l level="1" sID="gen29688"/>et judices tui, de quibus dixisti : <l eID="gen29688" level="1"/> <l level="1" sID="gen29689"/>Da mihi regem et principes. <l eID="gen29689" level="1"/>

** Hosea 13:11

Dabo tibi regem in furore meo, <l eID="gen29690" level="1"/> <l level="1" sID="gen29691"/>et auferam in indignatione mea. <l eID="gen29691" level="1"/>

** Hosea 13:12

Colligata est iniquitas Ephraim ; <l eID="gen29692" level="1"/> <l level="1" sID="gen29693"/>absconditum peccatum ejus. <l eID="gen29693" level="1"/>

** Hosea 13:13

Dolores parturientis venient ei : <l eID="gen29694" level="1"/> <l level="1" sID="gen29695"/>ipse filius non sapiens : <l eID="gen29695" level="1"/> <l level="1" sID="gen29696"/>nunc enim non stabit in contritione filiorum. <l eID="gen29696" level="1"/>

** Hosea 13:14

De manu mortis liberabo eos ; <l eID="gen29697" level="1"/> <l level="1" sID="gen29698"/>de morte redimam eos. <l eID="gen29698" level="1"/> <l level="1" sID="gen29699"/>Ero mors tua, o mors ! <l eID="gen29699" level="1"/> <l level="1" sID="gen29700"/>morsus tuus ero, inferne ! <l eID="gen29700" level="1"/> <l level="1" sID="gen29701"/>consolatio abscondita est ab oculis meis. <l eID="gen29701" level="1"/>

** Hosea 13:15

Quia ipse inter fratres dividet : <l eID="gen29702" level="1"/> <l level="1" sID="gen29703"/>adducet urentem ventum Dominus de deserto ascendentem, <l eID="gen29703" level="1"/> <l level="1" sID="gen29704"/>et siccabit venas ejus, <l eID="gen29704" level="1"/> <l level="1" sID="gen29705"/>et desolabit fontem ejus : <l eID="gen29705" level="1"/> <l level="1" sID="gen29706"/>et ipse diripiet thesaurum omnis vasis desiderabilis.  <chapter eID="Hos.13"/>

* Hosea 14

** Hosea 14:1

Pereat Samaria, quoniam ad amaritudinem concitavit Deum suum ! <l eID="gen29707" level="1"/> <l level="1" sID="gen29708"/>in gladio pereant, <l eID="gen29708" level="1"/> <l level="1" sID="gen29709"/>parvuli eorum elidantur, <l eID="gen29709" level="1"/> <l level="1" sID="gen29710"/>et fœtæ ejus discindantur ! <l eID="gen29710" level="1"/>

** Hosea 14:2

Convertere, Israël, ad Dominum Deum tuum, <l eID="gen29711" level="1"/> <l level="1" sID="gen29712"/>quoniam corruisti in iniquitate tua. <l eID="gen29712" level="1"/>

** Hosea 14:3

Tollite vobiscum verba, <l eID="gen29713" level="1"/> <l level="1" sID="gen29714"/>et convertimini ad Dominum ; et dicite ei : <l eID="gen29714" level="1"/> <l level="1" sID="gen29715"/>Omnem aufer iniquitatem, accipe bonum, <l eID="gen29715" level="1"/> <l level="1" sID="gen29716"/>et reddemus vitulos labiorum nostrorum. <l eID="gen29716" level="1"/>

** Hosea 14:4

Assur non salvabit nos : <l eID="gen29717" level="1"/> <l level="1" sID="gen29718"/>super equum non ascendemus, <l eID="gen29718" level="1"/> <l level="1" sID="gen29719"/>nec dicemus ultra, Dii nostri opera manuum nostrarum : <l eID="gen29719" level="1"/> <l level="1" sID="gen29720"/>quia ejus, qui in te est, misereberis pupilli. <l eID="gen29720" level="1"/>

** Hosea 14:5

Sanabo contritiones eorum ; <l eID="gen29721" level="1"/> <l level="1" sID="gen29722"/>diligam eos spontanee : <l eID="gen29722" level="1"/> <l level="1" sID="gen29723"/>quia aversus est furor meus ab eis. <l eID="gen29723" level="1"/>

** Hosea 14:6

Ero quasi ros ; <l eID="gen29724" level="1"/> <l level="1" sID="gen29725"/>Israël germinabit sicut lilium, <l eID="gen29725" level="1"/> <l level="1" sID="gen29726"/>et erumpet radix ejus ut Libani. <l eID="gen29726" level="1"/>

** Hosea 14:7

Ibunt rami ejus, <l eID="gen29727" level="1"/> <l level="1" sID="gen29728"/>et erit quasi oliva gloria ejus, <l eID="gen29728" level="1"/> <l level="1" sID="gen29729"/>et odor ejus ut Libani. <l eID="gen29729" level="1"/>

** Hosea 14:8

Convertentur sedentes in umbra ejus ; <l eID="gen29730" level="1"/> <l level="1" sID="gen29731"/>vivent tritico, et germinabunt quasi vinea ; <l eID="gen29731" level="1"/> <l level="1" sID="gen29732"/>memoriale ejus sicut vinum Libani. <l eID="gen29732" level="1"/>

** Hosea 14:9

Ephraim, quid mihi ultra idola ? <l eID="gen29733" level="1"/> <l level="1" sID="gen29734"/>Ego exaudiam, et dirigam eum ego ut abietem virentem ; <l eID="gen29734" level="1"/> <l level="1" sID="gen29735"/>ex me fructus tuus inventus est. <l eID="gen29735" level="1"/>

** Hosea 14:10

Quis sapiens, et intelliget ista ? intelligens, et sciet hæc ? <l eID="gen29736" level="1"/> <l level="1" sID="gen29737"/>quia rectæ viæ Domini, <l eID="gen29737" level="1"/> <l level="1" sID="gen29738"/>et justi ambulabunt in eis ; <l eID="gen29738" level="1"/> <l level="1" sID="gen29739"/>prævaricatores vero corruent in eis. <l eID="gen29739" level="1"/> <lg eID="gen29224"/> <chapter eID="Hos.14"/> <div eID="gen29142" osisID="Hos" type="book"/>

