* Job 1

** Job 1:1

Vir erat in terra Hus, nomine Job : et erat vir ille simplex, et rectus, ac timens Deum, et recedens a malo.

** Job 1:2

Natique sunt ei septem filii, et tres filiæ.

** Job 1:3

Et fuit possessio ejus septem millia ovium, et tria millia camelorum, quingenta quoque juga boum, et quingentæ asinæ, ac familia multa nimis : eratque vir ille magnus inter omnes orientales.

** Job 1:4

Et ibant filii ejus, et faciebant convivium per domos, unusquisque in die suo. Et mittentes vocabant tres sorores suas, ut comederent et biberent cum eis.

** Job 1:5

Cumque in orbem transissent dies convivii, mittebat ad eos Job, et sanctificabat illos : consurgensque diluculo, offerebat holocausta pro singulis. Dicebat enim : Ne forte peccaverint filii mei, et benedixerint Deo in cordibus suis. Sic faciebat Job cunctis diebus.  <div eID="gen2423" type="x-p"/>

** Job 1:6

Quadam autem die, cum venissent filii Dei ut assisterent coram Domino, affuit inter eos etiam Satan.

** Job 1:7

Cui dixit Dominus : Unde venis ? Qui respondens, ait : Circuivi terram, et perambulavi eam.

** Job 1:8

Dixitque Dominus ad eum : Numquid considerasti servum meum Job, quod non sit ei similis in terra, homo simplex et rectus, ac timens Deum, et recedens a malo ?

** Job 1:9

Cui respondens Satan, ait : Numquid Job frustra timet Deum ?

** Job 1:10

nonne tu vallasti eum, ac domum ejus, universamque substantiam per circuitum ; operibus manuum ejus benedixisti, et possessio ejus crevit in terra ?

** Job 1:11

sed extende paululum manum tuam et tange cuncta quæ possidet, nisi in faciem benedixerit tibi.

** Job 1:12

Dixit ergo Dominus ad Satan : Ecce universa quæ habet in manu tua sunt : tantum in eum ne extendas manum tuam. Egressusque est Satan a facie Domini.

** Job 1:13

Cum autem quadam die filii et filiæ ejus comederent et biberent vinum in domo fratris sui primogeniti,

** Job 1:14

nuntius venit ad Job, qui diceret : Boves arabant, et asinæ pascebantur juxta eos :

** Job 1:15

et irruerunt Sabæi, tuleruntque omnia, et pueros percusserunt gladio : et evasi ego solus, ut nuntiarem tibi.

** Job 1:16

Cumque adhuc ille loqueretur, venit alter, et dixit : Ignis Dei cecidit e cælo, et tactas oves puerosque consumpsit : et effugi ego solus, ut nuntiarem tibi.

** Job 1:17

Sed et illo adhuc loquente, venit alius, et dixit : Chaldæi fecerunt tres turmas, et invaserunt camelos, et tulerunt eos, necnon et pueros percusserunt gladio : et ego fugi solus, ut nuntiarem tibi.

** Job 1:18

Adhuc loquebatur ille, et ecce alius intravit, et dixit : Filiis tuis et filiabus vescentibus et bibentibus vinum in domo fratris sui primogeniti,

** Job 1:19

repente ventus vehemens irruit a regione deserti, et concussit quatuor angulos domus : quæ corruens oppressit liberos tuos, et mortui sunt : et effugi ego solus, ut nuntiarem tibi.

** Job 1:20

Tunc surrexit Job, et scidit vestimenta sua : et tonso capite corruens in terram, adoravit,

** Job 1:21

et dixit : Nudus egressus sum de utero matris meæ, et nudus revertar illuc. Dominus dedit, Dominus abstulit ; sicut Domino placuit, ita factum est. Sit nomen Domini benedictum.

** Job 1:22

In omnibus his non peccavit Job labiis suis, neque stultum quid contra Deum locutus est.  <chapter eID="Job.1"/> <div eID="gen2424" type="x-p"/>

* Job 2

** Job 2:1

Factum est autem, cum quadam die venissent filii Dei, et starent coram Domino, venisset quoque Satan inter eos, et staret in conspectu ejus,

** Job 2:2

ut diceret Dominus ad Satan : Unde venis ? Qui respondens ait : Circuivi terram, et perambulavi eam.

** Job 2:3

Et dixit Dominus ad Satan : Numquid considerasti servum meum Job, quod non sit ei similis in terra, vir simplex et rectus, ac timens Deum, et recedens a malo, et adhuc retinens innocentiam ? tu autem commovisti me adversus eum, ut affligerem eum frustra.

** Job 2:4

Cui respondens Satan, ait : Pellem pro pelle, et cuncta quæ habet homo dabit pro anima sua ;

** Job 2:5

alioquin mitte manum tuam, et tange os ejus et carnem, et tunc videbis quod in faciem benedicat tibi.

** Job 2:6

Dixit ergo Dominus ad Satan : Ecce in manu tua est : verumtamen animam illius serva.

** Job 2:7

Egressus igitur Satan a facie Domini, percussit Job ulcere pessimo, a planta pedis usque ad verticem ejus ;

** Job 2:8

qui testa saniem radebat, sedens in sterquilinio.

** Job 2:9

Dixit autem illi uxor sua : Adhuc tu permanes in simplicitate tua ? Benedic Deo, et morere.

** Job 2:10

Qui ait ad illam : Quasi una de stultis mulieribus locuta es : si bona suscepimus de manu Dei, mala quare non suscipiamus ? In omnibus his non peccavit Job labiis suis.  <div eID="gen2425" type="x-p"/>

** Job 2:11

Igitur audientes tres amici Job omne malum quod accidisset ei, venerunt singuli de loco suo, Eliphaz Themanites, et Baldad Suhites, et Sophar Naamathites. Condixerant enim ut pariter venientes visitarent eum, et consolarentur.

** Job 2:12

Cumque elevassent procul oculos suos, non cognoverunt eum, et exclamantes ploraverunt, scissisque vestibus sparserunt pulverem super caput suum in cælum.

** Job 2:13

Et sederunt cum eo in terra septem diebus et septem noctibus : et nemo loquebatur ei verbum : videbant enim dolorem esse vehementem.  <chapter eID="Job.2"/> <div eID="gen2426" type="x-p"/>

* Job 3

** Job 3:1

Post hæc aperuit Job os suum, et maledixit diei suo,

** Job 3:2

et locutus est :  <div eID="gen2427" type="x-p"/>

** Job 3:3

Pereat dies in qua natus sum, <l eID="gen2429" level="1"/> <l level="1" sID="gen2430"/>et nox in qua dictum est : Conceptus est homo. <l eID="gen2430" level="1"/>

** Job 3:4

Dies ille vertatur in tenebras : <l eID="gen2431" level="1"/> <l level="1" sID="gen2432"/>non requirat eum Deus desuper, <l eID="gen2432" level="1"/> <l level="1" sID="gen2433"/>et non illustretur lumine. <l eID="gen2433" level="1"/>

** Job 3:5

Obscurent eum tenebræ et umbra mortis ; <l eID="gen2434" level="1"/> <l level="1" sID="gen2435"/>occupet eum caligo, <l eID="gen2435" level="1"/> <l level="1" sID="gen2436"/>et involvatur amaritudine. <l eID="gen2436" level="1"/>

** Job 3:6

Noctem illam tenebrosus turbo possideat ; <l eID="gen2437" level="1"/> <l level="1" sID="gen2438"/>non computetur in diebus anni, <l eID="gen2438" level="1"/> <l level="1" sID="gen2439"/>nec numeretur in mensibus. <l eID="gen2439" level="1"/>

** Job 3:7

Sit nox illa solitaria, <l eID="gen2440" level="1"/> <l level="1" sID="gen2441"/>nec laude digna. <l eID="gen2441" level="1"/>

** Job 3:8

Maledicant ei qui maledicunt diei, <l eID="gen2442" level="1"/> <l level="1" sID="gen2443"/>qui parati sunt suscitare Leviathan. <l eID="gen2443" level="1"/>

** Job 3:9

Obtenebrentur stellæ caligine ejus ; <l eID="gen2444" level="1"/> <l level="1" sID="gen2445"/>expectet lucem, et non videat, <l eID="gen2445" level="1"/> <l level="1" sID="gen2446"/>nec ortum surgentis auroræ. <l eID="gen2446" level="1"/>

** Job 3:10

Quia non conclusit ostia ventris qui portavit me, <l eID="gen2447" level="1"/> <l level="1" sID="gen2448"/>nec abstulit mala ab oculis meis. <l eID="gen2448" level="1"/>

** Job 3:11

Quare non in vulva mortuus sum ? <l eID="gen2449" level="1"/> <l level="1" sID="gen2450"/>egressus ex utero non statim perii ? <l eID="gen2450" level="1"/>

** Job 3:12

Quare exceptus genibus ? <l eID="gen2451" level="1"/> <l level="1" sID="gen2452"/>cur lactatus uberibus ? <l eID="gen2452" level="1"/>

** Job 3:13

Nunc enim dormiens silerem, <l eID="gen2453" level="1"/> <l level="1" sID="gen2454"/>et somno meo requiescerem <l eID="gen2454" level="1"/>

** Job 3:14

cum regibus et consulibus terræ, <l eID="gen2455" level="1"/> <l level="1" sID="gen2456"/>qui ædificant sibi solitudines ; <l eID="gen2456" level="1"/>

** Job 3:15

aut cum principibus qui possident aurum, <l eID="gen2457" level="1"/> <l level="1" sID="gen2458"/>et replent domos suas argento ; <l eID="gen2458" level="1"/>

** Job 3:16

aut sicut abortivum absconditum non subsisterem, <l eID="gen2459" level="1"/> <l level="1" sID="gen2460"/>vel qui concepti non viderunt lucem. <l eID="gen2460" level="1"/>

** Job 3:17

Ibi impii cessaverunt a tumultu, <l eID="gen2461" level="1"/> <l level="1" sID="gen2462"/>et ibi requieverunt fessi robore. <l eID="gen2462" level="1"/>

** Job 3:18

Et quondam vincti pariter sine molestia, <l eID="gen2463" level="1"/> <l level="1" sID="gen2464"/>non audierunt vocem exactoris. <l eID="gen2464" level="1"/>

** Job 3:19

Parvus et magnus ibi sunt, <l eID="gen2465" level="1"/> <l level="1" sID="gen2466"/>et servus liber a domino suo. <l eID="gen2466" level="1"/>

** Job 3:20

Quare misero data est lux, <l eID="gen2467" level="1"/> <l level="1" sID="gen2468"/>et vita his qui in amaritudine animæ sunt : <l eID="gen2468" level="1"/>

** Job 3:21

qui expectant mortem, et non venit, <l eID="gen2469" level="1"/> <l level="1" sID="gen2470"/>quasi effodientes thesaurum ; <l eID="gen2470" level="1"/>

** Job 3:22

gaudentque vehementer <l eID="gen2471" level="1"/> <l level="1" sID="gen2472"/>cum invenerint sepulchrum ? <l eID="gen2472" level="1"/>

** Job 3:23

viro cujus abscondita est via <l eID="gen2473" level="1"/> <l level="1" sID="gen2474"/>et circumdedit eum Deus tenebris ? <l eID="gen2474" level="1"/>

** Job 3:24

Antequam comedam, suspiro ; <l eID="gen2475" level="1"/> <l level="1" sID="gen2476"/>et tamquam inundantes aquæ, sic rugitus meus : <l eID="gen2476" level="1"/>

** Job 3:25

quia timor quem timebam evenit mihi, <l eID="gen2477" level="1"/> <l level="1" sID="gen2478"/>et quod verebar accidit. <l eID="gen2478" level="1"/>

** Job 3:26

Nonne dissimulavi ? nonne silui ? nonne quievi ? <l eID="gen2479" level="1"/> <l level="1" sID="gen2480"/>et venit super me indignatio. <l eID="gen2480" level="1"/><lg eID="gen2428"/> <chapter eID="Job.3"/>

* Job 4

** Job 4:1

Respondens autem Eliphaz Themanites, dixit :  <div eID="gen2481" type="x-p"/>

** Job 4:2

Si cœperimus loqui tibi, forsitan moleste accipies ; <l eID="gen2483" level="1"/> <l level="1" sID="gen2484"/>sed conceptum sermonem tenere quis poterit ? <l eID="gen2484" level="1"/>

** Job 4:3

Ecce docuisti multos, <l eID="gen2485" level="1"/> <l level="1" sID="gen2486"/>et manus lassas roborasti ; <l eID="gen2486" level="1"/>

** Job 4:4

vacillantes confirmaverunt sermones tui, <l eID="gen2487" level="1"/> <l level="1" sID="gen2488"/>et genua trementia confortasti. <l eID="gen2488" level="1"/>

** Job 4:5

Nunc autem venit super te plaga, et defecisti ; <l eID="gen2489" level="1"/> <l level="1" sID="gen2490"/>tetigit te, et conturbatus es. <l eID="gen2490" level="1"/>

** Job 4:6

Ubi est timor tuus, fortitudo tua, <l eID="gen2491" level="1"/> <l level="1" sID="gen2492"/>patientia tua, et perfectio viarum tuarum ? <l eID="gen2492" level="1"/>

** Job 4:7

Recordare, obsecro te, quis umquam innocens periit ? <l eID="gen2493" level="1"/> <l level="1" sID="gen2494"/>aut quando recti deleti sunt ? <l eID="gen2494" level="1"/>

** Job 4:8

Quin potius vidi eos qui operantur iniquitatem, <l eID="gen2495" level="1"/> <l level="1" sID="gen2496"/>et seminant dolores, et metunt eos, <l eID="gen2496" level="1"/>

** Job 4:9

flante Deo perisse, <l eID="gen2497" level="1"/> <l level="1" sID="gen2498"/>et spiritu iræ ejus esse consumptos. <l eID="gen2498" level="1"/>

** Job 4:10

Rugitus leonis, et vox leænæ, <l eID="gen2499" level="1"/> <l level="1" sID="gen2500"/>et dentes catulorum leonum contriti sunt. <l eID="gen2500" level="1"/>

** Job 4:11

Tigris periit, eo quod non haberet prædam, <l eID="gen2501" level="1"/> <l level="1" sID="gen2502"/>et catuli leonis dissipati sunt. <l eID="gen2502" level="1"/>

** Job 4:12

Porro ad me dictum est verbum absconditum, <l eID="gen2503" level="1"/> <l level="1" sID="gen2504"/>et quasi furtive suscepit auris mea venas susurri ejus. <l eID="gen2504" level="1"/>

** Job 4:13

In horrore visionis nocturnæ, <l eID="gen2505" level="1"/> <l level="1" sID="gen2506"/>quando solet sopor occupare homines, <l eID="gen2506" level="1"/>

** Job 4:14

pavor tenuit me, et tremor, <l eID="gen2507" level="1"/> <l level="1" sID="gen2508"/>et omnia ossa mea perterrita sunt ; <l eID="gen2508" level="1"/>

** Job 4:15

et cum spiritus, me præsente, transiret, <l eID="gen2509" level="1"/> <l level="1" sID="gen2510"/>inhorruerunt pili carnis meæ. <l eID="gen2510" level="1"/>

** Job 4:16

Stetit quidam, cujus non agnoscebam vultum, <l eID="gen2511" level="1"/> <l level="1" sID="gen2512"/>imago coram oculis meis, <l eID="gen2512" level="1"/> <l level="1" sID="gen2513"/>et vocem quasi auræ lenis audivi. <l eID="gen2513" level="1"/>

** Job 4:17

Numquid homo, Dei comparatione, justificabitur ? <l eID="gen2514" level="1"/> <l level="1" sID="gen2515"/>aut factore suo purior erit vir ? <l eID="gen2515" level="1"/>

** Job 4:18

Ecce qui serviunt ei, non sunt stabiles, <l eID="gen2516" level="1"/> <l level="1" sID="gen2517"/>et in angelis suis reperit pravitatem ; <l eID="gen2517" level="1"/>

** Job 4:19

quanto magis hi qui habitant domos luteas, <l eID="gen2518" level="1"/> <l level="1" sID="gen2519"/>qui terrenum habent fundamentum, <l eID="gen2519" level="1"/> <l level="1" sID="gen2520"/>consumentur velut a tinea ? <l eID="gen2520" level="1"/>

** Job 4:20

De mane usque ad vesperam succidentur ; <l eID="gen2521" level="1"/> <l level="1" sID="gen2522"/>et quia nullus intelligit, in æternum peribunt. <l eID="gen2522" level="1"/>

** Job 4:21

Qui autem reliqui fuerint, auferentur ex eis ; <l eID="gen2523" level="1"/> <l level="1" sID="gen2524"/>morientur, et non in sapientia.  <chapter eID="Job.4"/>

* Job 5

** Job 5:1

Voca ergo, si est qui tibi respondeat, <l eID="gen2525" level="1"/> <l level="1" sID="gen2526"/>et ad aliquem sanctorum convertere. <l eID="gen2526" level="1"/>

** Job 5:2

Vere stultum interficit iracundia, <l eID="gen2527" level="1"/> <l level="1" sID="gen2528"/>et parvulum occidit invidia. <l eID="gen2528" level="1"/>

** Job 5:3

Ego vidi stultum firma radice, <l eID="gen2529" level="1"/> <l level="1" sID="gen2530"/>et maledixi pulchritudini ejus statim. <l eID="gen2530" level="1"/>

** Job 5:4

Longe fient filii ejus a salute, <l eID="gen2531" level="1"/> <l level="1" sID="gen2532"/>et conterentur in porta, <l eID="gen2532" level="1"/> <l level="1" sID="gen2533"/>et non erit qui eruat. <l eID="gen2533" level="1"/>

** Job 5:5

Cujus messem famelicus comedet, <l eID="gen2534" level="1"/> <l level="1" sID="gen2535"/>et ipsum rapiet armatus, <l eID="gen2535" level="1"/> <l level="1" sID="gen2536"/>et bibent sitientes divitias ejus. <l eID="gen2536" level="1"/>

** Job 5:6

Nihil in terra sine causa fit, <l eID="gen2537" level="1"/> <l level="1" sID="gen2538"/>et de humo non oritur dolor. <l eID="gen2538" level="1"/>

** Job 5:7

Homo nascitur ad laborem, <l eID="gen2539" level="1"/> <l level="1" sID="gen2540"/>et avis ad volatum. <l eID="gen2540" level="1"/>

** Job 5:8

Quam ob rem ego deprecabor Dominum, <l eID="gen2541" level="1"/> <l level="1" sID="gen2542"/>et ad Deum ponam eloquium meum : <l eID="gen2542" level="1"/>

** Job 5:9

qui facit magna et inscrutabilia, <l eID="gen2543" level="1"/> <l level="1" sID="gen2544"/>et mirabilia absque numero ; <l eID="gen2544" level="1"/>

** Job 5:10

qui dat pluviam super faciem terræ, <l eID="gen2545" level="1"/> <l level="1" sID="gen2546"/>et irrigat aquis universa ; <l eID="gen2546" level="1"/>

** Job 5:11

qui ponit humiles in sublime, <l eID="gen2547" level="1"/> <l level="1" sID="gen2548"/>et mœrentes erigit sospitate ; <l eID="gen2548" level="1"/>

** Job 5:12

qui dissipat cogitationes malignorum, <l eID="gen2549" level="1"/> <l level="1" sID="gen2550"/>ne possint implere manus eorum quod cœperant ; <l eID="gen2550" level="1"/>

** Job 5:13

qui apprehendit sapientes in astutia eorum, <l eID="gen2551" level="1"/> <l level="1" sID="gen2552"/>et consilium pravorum dissipat. <l eID="gen2552" level="1"/>

** Job 5:14

Per diem incurrent tenebras, <l eID="gen2553" level="1"/> <l level="1" sID="gen2554"/>et quasi in nocte, sic palpabunt in meridie. <l eID="gen2554" level="1"/>

** Job 5:15

Porro salvum faciet egenum a gladio oris eorum, <l eID="gen2555" level="1"/> <l level="1" sID="gen2556"/>et de manu violenti pauperem. <l eID="gen2556" level="1"/>

** Job 5:16

Et erit egeno spes ; <l eID="gen2557" level="1"/> <l level="1" sID="gen2558"/>iniquitas autem contrahet os suum. <l eID="gen2558" level="1"/>

** Job 5:17

Beatus homo qui corripitur a Deo : <l eID="gen2559" level="1"/> <l level="1" sID="gen2560"/>increpationem ergo Domini ne reprobes : <l eID="gen2560" level="1"/>

** Job 5:18

quia ipse vulnerat, et medetur ; <l eID="gen2561" level="1"/> <l level="1" sID="gen2562"/>percutit, et manus ejus sanabunt. <l eID="gen2562" level="1"/>

** Job 5:19

In sex tribulationibus liberabit te, <l eID="gen2563" level="1"/> <l level="1" sID="gen2564"/>et in septima non tanget te malum. <l eID="gen2564" level="1"/>

** Job 5:20

In fame eruet te de morte, <l eID="gen2565" level="1"/> <l level="1" sID="gen2566"/>et in bello de manu gladii. <l eID="gen2566" level="1"/>

** Job 5:21

A flagello linguæ absconderis, <l eID="gen2567" level="1"/> <l level="1" sID="gen2568"/>et non timebis calamitatem cum venerit. <l eID="gen2568" level="1"/>

** Job 5:22

In vastitate et fame ridebis, <l eID="gen2569" level="1"/> <l level="1" sID="gen2570"/>et bestias terræ non formidabis. <l eID="gen2570" level="1"/>

** Job 5:23

Sed cum lapidibus regionum pactum tuum, <l eID="gen2571" level="1"/> <l level="1" sID="gen2572"/>et bestiæ terræ pacificæ erunt tibi. <l eID="gen2572" level="1"/>

** Job 5:24

Et scies quod pacem habeat tabernaculum tuum ; <l eID="gen2573" level="1"/> <l level="1" sID="gen2574"/>et visitans speciem tuam, non peccabis. <l eID="gen2574" level="1"/>

** Job 5:25

Scies quoque quoniam multiplex erit semen tuum, <l eID="gen2575" level="1"/> <l level="1" sID="gen2576"/>et progenies tua quasi herba terræ. <l eID="gen2576" level="1"/>

** Job 5:26

Ingredieris in abundantia sepulchrum, <l eID="gen2577" level="1"/> <l level="1" sID="gen2578"/>sicut infertur acervus tritici in tempore suo. <l eID="gen2578" level="1"/>

** Job 5:27

Ecce hoc, ut investigavimus, ita est : <l eID="gen2579" level="1"/> <l level="1" sID="gen2580"/>quod auditum, mente pertracta. <l eID="gen2580" level="1"/><lg eID="gen2482"/> <chapter eID="Job.5"/>

* Job 6

** Job 6:1

Respondens autem Job, dixit :  <div eID="gen2581" type="x-p"/>

** Job 6:2

Utinam appenderentur peccata mea quibus iram merui, <l eID="gen2583" level="1"/> <l level="1" sID="gen2584"/>et calamitas quam patior, in statera ! <l eID="gen2584" level="1"/>

** Job 6:3

Quasi arena maris hæc gravior appareret ; <l eID="gen2585" level="1"/> <l level="1" sID="gen2586"/>unde et verba mea dolore sunt plena : <l eID="gen2586" level="1"/>

** Job 6:4

quia sagittæ Domini in me sunt, <l eID="gen2587" level="1"/> <l level="1" sID="gen2588"/>quarum indignatio ebibit spiritum meum ; <l eID="gen2588" level="1"/> <l level="1" sID="gen2589"/>et terrores Domini militant contra me. <l eID="gen2589" level="1"/>

** Job 6:5

Numquid rugiet onager cum habuerit herbam ? <l eID="gen2590" level="1"/> <l level="1" sID="gen2591"/>aut mugiet bos cum ante præsepe plenum steterit ? <l eID="gen2591" level="1"/>

** Job 6:6

aut poterit comedi insulsum, quod non est sale conditum ? <l eID="gen2592" level="1"/> <l level="1" sID="gen2593"/>aut potest aliquis gustare quod gustatum affert mortem ? <l eID="gen2593" level="1"/>

** Job 6:7

Quæ prius nolebat tangere anima mea, <l eID="gen2594" level="1"/> <l level="1" sID="gen2595"/>nunc, præ angustia, cibi mei sunt. <l eID="gen2595" level="1"/>

** Job 6:8

Quis det ut veniat petitio mea, <l eID="gen2596" level="1"/> <l level="1" sID="gen2597"/>et quod expecto tribuat mihi Deus ? <l eID="gen2597" level="1"/>

** Job 6:9

et qui cœpit, ipse me conterat ; <l eID="gen2598" level="1"/> <l level="1" sID="gen2599"/>solvat manum suam, et succidat me ? <l eID="gen2599" level="1"/>

** Job 6:10

Et hæc mihi sit consolatio, ut affligens me dolore, non parcat, <l eID="gen2600" level="1"/> <l level="1" sID="gen2601"/>nec contradicam sermonibus Sancti. <l eID="gen2601" level="1"/>

** Job 6:11

Quæ est enim fortitudo mea, ut sustineam ? <l eID="gen2602" level="1"/> <l level="1" sID="gen2603"/>aut quis finis meus, ut patienter agam ? <l eID="gen2603" level="1"/>

** Job 6:12

Nec fortitudo lapidum fortitudo mea, <l eID="gen2604" level="1"/> <l level="1" sID="gen2605"/>nec caro mea ænea est. <l eID="gen2605" level="1"/>

** Job 6:13

Ecce non est auxilium mihi in me, <l eID="gen2606" level="1"/> <l level="1" sID="gen2607"/>et necessarii quoque mei recesserunt a me. <l eID="gen2607" level="1"/>

** Job 6:14

Qui tollit ab amico suo misericordiam, <l eID="gen2608" level="1"/> <l level="1" sID="gen2609"/>timorem Domini derelinquit. <l eID="gen2609" level="1"/>

** Job 6:15

Fratres mei præterierunt me, <l eID="gen2610" level="1"/> <l level="1" sID="gen2611"/>sicut torrens qui raptim transit in convallibus. <l eID="gen2611" level="1"/>

** Job 6:16

Qui timent pruinam, <l eID="gen2612" level="1"/> <l level="1" sID="gen2613"/>irruet super eos nix. <l eID="gen2613" level="1"/>

** Job 6:17

Tempore quo fuerint dissipati, peribunt ; <l eID="gen2614" level="1"/> <l level="1" sID="gen2615"/>et ut incaluerit, solventur de loco suo. <l eID="gen2615" level="1"/>

** Job 6:18

Involutæ sunt semitæ gressuum eorum ; <l eID="gen2616" level="1"/> <l level="1" sID="gen2617"/>ambulabunt in vacuum, et peribunt. <l eID="gen2617" level="1"/>

** Job 6:19

Considerate semitas Thema, itinera Saba, <l eID="gen2618" level="1"/> <l level="1" sID="gen2619"/>et expectate paulisper. <l eID="gen2619" level="1"/>

** Job 6:20

Confusi sunt, quia speravi : <l eID="gen2620" level="1"/> <l level="1" sID="gen2621"/>venerunt quoque usque ad me, et pudore cooperti sunt. <l eID="gen2621" level="1"/>

** Job 6:21

Nunc venistis ; <l eID="gen2622" level="1"/> <l level="1" sID="gen2623"/>et modo videntes plagam meam, timetis. <l eID="gen2623" level="1"/>

** Job 6:22

Numquid dixi : Afferte mihi, <l eID="gen2624" level="1"/> <l level="1" sID="gen2625"/>et de substantia vestra donate mihi ? <l eID="gen2625" level="1"/>

** Job 6:23

vel : Liberate me de manu hostis, <l eID="gen2626" level="1"/> <l level="1" sID="gen2627"/>et de manu robustorum eruite me ? <l eID="gen2627" level="1"/>

** Job 6:24

Docete me, et ego tacebo : <l eID="gen2628" level="1"/> <l level="1" sID="gen2629"/>et si quid forte ignoravi, instruite me. <l eID="gen2629" level="1"/>

** Job 6:25

Quare detraxistis sermonibus veritatis, <l eID="gen2630" level="1"/> <l level="1" sID="gen2631"/>cum e vobis nullus sit qui possit arguere me ? <l eID="gen2631" level="1"/>

** Job 6:26

Ad increpandum tantum eloquia concinnatis, <l eID="gen2632" level="1"/> <l level="1" sID="gen2633"/>et in ventum verba profertis. <l eID="gen2633" level="1"/>

** Job 6:27

Super pupillum irruitis, <l eID="gen2634" level="1"/> <l level="1" sID="gen2635"/>et subvertere nitimini amicum vestrum. <l eID="gen2635" level="1"/>

** Job 6:28

Verumtamen quod cœpistis explete : <l eID="gen2636" level="1"/> <l level="1" sID="gen2637"/>præbete aurem, et videte an mentiar. <l eID="gen2637" level="1"/>

** Job 6:29

Respondete, obsecro, absque contentione ; <l eID="gen2638" level="1"/> <l level="1" sID="gen2639"/>et loquentes id quod justum est, judicate. <l eID="gen2639" level="1"/>

** Job 6:30

Et non invenietis in lingua mea iniquitatem, <l eID="gen2640" level="1"/> <l level="1" sID="gen2641"/>nec in faucibus meis stultitia personabit.  <chapter eID="Job.6"/>

* Job 7

** Job 7:1

Militia est vita hominis super terram, <l eID="gen2642" level="1"/> <l level="1" sID="gen2643"/>et sicut dies mercenarii dies ejus. <l eID="gen2643" level="1"/>

** Job 7:2

Sicut servus desiderat umbram, <l eID="gen2644" level="1"/> <l level="1" sID="gen2645"/>et sicut mercenarius præstolatur finem operis sui, <l eID="gen2645" level="1"/>

** Job 7:3

sic et ego habui menses vacuos, <l eID="gen2646" level="1"/> <l level="1" sID="gen2647"/>et noctes laboriosas enumeravi mihi. <l eID="gen2647" level="1"/>

** Job 7:4

Si dormiero, dicam : Quando consurgam ? <l eID="gen2648" level="1"/> <l level="1" sID="gen2649"/>et rursum expectabo vesperam, <l eID="gen2649" level="1"/> <l level="1" sID="gen2650"/>et replebor doloribus usque ad tenebras. <l eID="gen2650" level="1"/>

** Job 7:5

Induta est caro mea putredine, <l eID="gen2651" level="1"/> <l level="1" sID="gen2652"/>et sordibus pulveris cutis mea aruit et contracta est. <l eID="gen2652" level="1"/>

** Job 7:6

Dies mei velocius transierunt quam a texente tela succiditur, <l eID="gen2653" level="1"/> <l level="1" sID="gen2654"/>et consumpti sunt absque ulla spe. <l eID="gen2654" level="1"/>

** Job 7:7

Memento quia ventus est vita mea, <l eID="gen2655" level="1"/> <l level="1" sID="gen2656"/>et non revertetur oculus meus ut videat bona. <l eID="gen2656" level="1"/>

** Job 7:8

Nec aspiciet me visus hominis ; <l eID="gen2657" level="1"/> <l level="1" sID="gen2658"/>oculi tui in me, et non subsistam. <l eID="gen2658" level="1"/>

** Job 7:9

Sicut consumitur nubes, et pertransit, <l eID="gen2659" level="1"/> <l level="1" sID="gen2660"/>sic qui descenderit ad inferos, non ascendet. <l eID="gen2660" level="1"/>

** Job 7:10

Nec revertetur ultra in domum suam, <l eID="gen2661" level="1"/> <l level="1" sID="gen2662"/>neque cognoscet eum amplius locus ejus. <l eID="gen2662" level="1"/>

** Job 7:11

Quapropter et ego non parcam ori meo : <l eID="gen2663" level="1"/> <l level="1" sID="gen2664"/>loquar in tribulatione spiritus mei ; <l eID="gen2664" level="1"/> <l level="1" sID="gen2665"/>confabulabor cum amaritudine animæ meæ. <l eID="gen2665" level="1"/>

** Job 7:12

Numquid mare ego sum, aut cetus, <l eID="gen2666" level="1"/> <l level="1" sID="gen2667"/>quia circumdedisti me carcere ? <l eID="gen2667" level="1"/>

** Job 7:13

Si dixero : Consolabitur me lectulus meus, <l eID="gen2668" level="1"/> <l level="1" sID="gen2669"/>et relevabor loquens mecum in strato meo : <l eID="gen2669" level="1"/>

** Job 7:14

terrebis me per somnia, <l eID="gen2670" level="1"/> <l level="1" sID="gen2671"/>et per visiones horrore concuties. <l eID="gen2671" level="1"/>

** Job 7:15

Quam ob rem elegit suspendium anima mea, <l eID="gen2672" level="1"/> <l level="1" sID="gen2673"/>et mortem ossa mea. <l eID="gen2673" level="1"/>

** Job 7:16

Desperavi : nequaquam ultra jam vivam : <l eID="gen2674" level="1"/> <l level="1" sID="gen2675"/>parce mihi, nihil enim sunt dies mei. <l eID="gen2675" level="1"/>

** Job 7:17

Quid est homo, quia magnificas eum ? <l eID="gen2676" level="1"/> <l level="1" sID="gen2677"/>aut quid apponis erga eum cor tuum ? <l eID="gen2677" level="1"/>

** Job 7:18

Visitas eum diluculo, <l eID="gen2678" level="1"/> <l level="1" sID="gen2679"/>et subito probas illum. <l eID="gen2679" level="1"/>

** Job 7:19

Usquequo non parcis mihi, <l eID="gen2680" level="1"/> <l level="1" sID="gen2681"/>nec dimittis me ut glutiam salivam meam ? <l eID="gen2681" level="1"/>

** Job 7:20

Peccavi ; quid faciam tibi, o custos hominum ? <l eID="gen2682" level="1"/> <l level="1" sID="gen2683"/>quare posuisti me contrarium tibi, <l eID="gen2683" level="1"/> <l level="1" sID="gen2684"/>et factus sum mihimetipsi gravis ? <l eID="gen2684" level="1"/>

** Job 7:21

Cur non tollis peccatum meum, <l eID="gen2685" level="1"/> <l level="1" sID="gen2686"/>et quare non aufers iniquitatem meam ? <l eID="gen2686" level="1"/> <l level="1" sID="gen2687"/>ecce nunc in pulvere dormiam, <l eID="gen2687" level="1"/> <l level="1" sID="gen2688"/>et si mane me quæsieris, non subsistam. <l eID="gen2688" level="1"/><lg eID="gen2582"/> <chapter eID="Job.7"/>

* Job 8

** Job 8:1

Respondens autem Baldad Suhites, dixit :  <div eID="gen2689" type="x-p"/>

** Job 8:2

Usquequo loqueris talia, <l eID="gen2691" level="1"/> <l level="1" sID="gen2692"/>et spiritus multiplex sermones oris tui ? <l eID="gen2692" level="1"/>

** Job 8:3

Numquid Deus supplantat judicium ? <l eID="gen2693" level="1"/> <l level="1" sID="gen2694"/>aut Omnipotens subvertit quod justum est ? <l eID="gen2694" level="1"/>

** Job 8:4

Etiam si filii tui peccaverunt ei, <l eID="gen2695" level="1"/> <l level="1" sID="gen2696"/>et dimisit eos in manu iniquitatis suæ : <l eID="gen2696" level="1"/>

** Job 8:5

tu tamen si diluculo consurrexeris ad Deum, <l eID="gen2697" level="1"/> <l level="1" sID="gen2698"/>et Omnipotentem fueris deprecatus ; <l eID="gen2698" level="1"/>

** Job 8:6

si mundus et rectus incesseris : <l eID="gen2699" level="1"/> <l level="1" sID="gen2700"/>statim evigilabit ad te, <l eID="gen2700" level="1"/> <l level="1" sID="gen2701"/>et pacatum reddet habitaculum justitiæ tuæ, <l eID="gen2701" level="1"/>

** Job 8:7

in tantum ut si priora tua fuerint parva, <l eID="gen2702" level="1"/> <l level="1" sID="gen2703"/>et novissima tua multiplicentur nimis. <l eID="gen2703" level="1"/>

** Job 8:8

Interroga enim generationem pristinam, <l eID="gen2704" level="1"/> <l level="1" sID="gen2705"/>et diligenter investiga patrum memoriam <l eID="gen2705" level="1"/>

** Job 8:9

(hesterni quippe sumus, et ignoramus, <l eID="gen2706" level="1"/> <l level="1" sID="gen2707"/>quoniam sicut umbra dies nostri sunt super terram), <l eID="gen2707" level="1"/>

** Job 8:10

et ipsi docebunt te, loquentur tibi, <l eID="gen2708" level="1"/> <l level="1" sID="gen2709"/>et de corde suo proferent eloquia. <l eID="gen2709" level="1"/>

** Job 8:11

Numquid vivere potest scirpus absque humore ? <l eID="gen2710" level="1"/> <l level="1" sID="gen2711"/>aut crescere carectum sine aqua ? <l eID="gen2711" level="1"/>

** Job 8:12

Cum adhuc sit in flore, nec carpatur manu, <l eID="gen2712" level="1"/> <l level="1" sID="gen2713"/>ante omnes herbas arescit. <l eID="gen2713" level="1"/>

** Job 8:13

Sic viæ omnium qui obliviscuntur Deum, <l eID="gen2714" level="1"/> <l level="1" sID="gen2715"/>et spes hypocritæ peribit. <l eID="gen2715" level="1"/>

** Job 8:14

Non ei placebit vecordia sua, <l eID="gen2716" level="1"/> <l level="1" sID="gen2717"/>et sicut tela aranearum fiducia ejus. <l eID="gen2717" level="1"/>

** Job 8:15

Innitetur super domum suam, et non stabit ; <l eID="gen2718" level="1"/> <l level="1" sID="gen2719"/>fulciet eam, et non consurget. <l eID="gen2719" level="1"/>

** Job 8:16

Humectus videtur antequam veniat sol, <l eID="gen2720" level="1"/> <l level="1" sID="gen2721"/>et in ortu suo germen ejus egredietur. <l eID="gen2721" level="1"/>

** Job 8:17

Super acervum petrarum radices ejus densabuntur, <l eID="gen2722" level="1"/> <l level="1" sID="gen2723"/>et inter lapides commorabitur. <l eID="gen2723" level="1"/>

** Job 8:18

Si absorbuerit eum de loco suo, <l eID="gen2724" level="1"/> <l level="1" sID="gen2725"/>negabit eum, et dicet : Non novi te. <l eID="gen2725" level="1"/>

** Job 8:19

Hæc est enim lætitia viæ ejus, <l eID="gen2726" level="1"/> <l level="1" sID="gen2727"/>ut rursum de terra alii germinentur. <l eID="gen2727" level="1"/>

** Job 8:20

Deus non projiciet simplicem, <l eID="gen2728" level="1"/> <l level="1" sID="gen2729"/>nec porriget manum malignis, <l eID="gen2729" level="1"/>

** Job 8:21

donec impleatur risu os tuum, <l eID="gen2730" level="1"/> <l level="1" sID="gen2731"/>et labia tua jubilo. <l eID="gen2731" level="1"/>

** Job 8:22

Qui oderunt te induentur confusione, <l eID="gen2732" level="1"/> <l level="1" sID="gen2733"/>et tabernaculum impiorum non subsistet. <l eID="gen2733" level="1"/><lg eID="gen2690"/> <chapter eID="Job.8"/>

* Job 9

** Job 9:1

Et respondens Job, ait :  <div eID="gen2734" type="x-p"/>

** Job 9:2

Vere scio quod ita sit, <l eID="gen2736" level="1"/> <l level="1" sID="gen2737"/>et quod non justificetur homo compositus Deo. <l eID="gen2737" level="1"/>

** Job 9:3

Si voluerit contendere cum eo, <l eID="gen2738" level="1"/> <l level="1" sID="gen2739"/>non poterit ei respondere unum pro mille. <l eID="gen2739" level="1"/>

** Job 9:4

Sapiens corde est, et fortis robore : <l eID="gen2740" level="1"/> <l level="1" sID="gen2741"/>quis restitit ei, et pacem habuit ? <l eID="gen2741" level="1"/>

** Job 9:5

Qui transtulit montes, et nescierunt <l eID="gen2742" level="1"/> <l level="1" sID="gen2743"/>hi quos subvertit in furore suo. <l eID="gen2743" level="1"/>

** Job 9:6

Qui commovet terram de loco suo, <l eID="gen2744" level="1"/> <l level="1" sID="gen2745"/>et columnæ ejus concutiuntur. <l eID="gen2745" level="1"/>

** Job 9:7

Qui præcipit soli, et non oritur, <l eID="gen2746" level="1"/> <l level="1" sID="gen2747"/>et stellas claudit quasi sub signaculo. <l eID="gen2747" level="1"/>

** Job 9:8

Qui extendit cælos solus, <l eID="gen2748" level="1"/> <l level="1" sID="gen2749"/>et graditur super fluctus maris. <l eID="gen2749" level="1"/>

** Job 9:9

Qui facit Arcturum et Oriona, <l eID="gen2750" level="1"/> <l level="1" sID="gen2751"/>et Hyadas et interiora austri. <l eID="gen2751" level="1"/>

** Job 9:10

Qui facit magna, et incomprehensibilia, <l eID="gen2752" level="1"/> <l level="1" sID="gen2753"/>et mirabilia, quorum non est numerus. <l eID="gen2753" level="1"/>

** Job 9:11

Si venerit ad me, non videbo eum ; <l eID="gen2754" level="1"/> <l level="1" sID="gen2755"/>si abierit, non intelligam. <l eID="gen2755" level="1"/>

** Job 9:12

Si repente interroget, quis respondebit ei ? <l eID="gen2756" level="1"/> <l level="1" sID="gen2757"/>vel quis dicere potest : Cur ita facis ? <l eID="gen2757" level="1"/>

** Job 9:13

Deus, cujus iræ nemo resistere potest, <l eID="gen2758" level="1"/> <l level="1" sID="gen2759"/>et sub quo curvantur qui portant orbem. <l eID="gen2759" level="1"/>

** Job 9:14

Quantus ergo sum ego, ut respondeam ei, <l eID="gen2760" level="1"/> <l level="1" sID="gen2761"/>et loquar verbis meis cum eo ? <l eID="gen2761" level="1"/>

** Job 9:15

qui etiam si habuero quippiam justum, non respondebo : <l eID="gen2762" level="1"/> <l level="1" sID="gen2763"/>sed meum judicem deprecabor. <l eID="gen2763" level="1"/>

** Job 9:16

Et cum invocantem exaudierit me, <l eID="gen2764" level="1"/> <l level="1" sID="gen2765"/>non credo quod audierit vocem meam. <l eID="gen2765" level="1"/>

** Job 9:17

In turbine enim conteret me, <l eID="gen2766" level="1"/> <l level="1" sID="gen2767"/>et multiplicabit vulnera mea, etiam sine causa. <l eID="gen2767" level="1"/>

** Job 9:18

Non concedit requiescere spiritum meum, <l eID="gen2768" level="1"/> <l level="1" sID="gen2769"/>et implet me amaritudinibus. <l eID="gen2769" level="1"/>

** Job 9:19

Si fortitudo quæritur, robustissimus est ; <l eID="gen2770" level="1"/> <l level="1" sID="gen2771"/>si æquitas judicii, nemo audet pro me testimonium dicere. <l eID="gen2771" level="1"/>

** Job 9:20

Si justificare me voluero, os meum condemnabit me ; <l eID="gen2772" level="1"/> <l level="1" sID="gen2773"/>si innocentem ostendero, pravum me comprobabit. <l eID="gen2773" level="1"/>

** Job 9:21

Etiam si simplex fuero, hoc ipsum ignorabit anima mea, <l eID="gen2774" level="1"/> <l level="1" sID="gen2775"/>et tædebit me vitæ meæ. <l eID="gen2775" level="1"/>

** Job 9:22

Unum est quod locutus sum : <l eID="gen2776" level="1"/> <l level="1" sID="gen2777"/>et innocentem et impium ipse consumit. <l eID="gen2777" level="1"/>

** Job 9:23

Si flagellat, occidat semel, <l eID="gen2778" level="1"/> <l level="1" sID="gen2779"/>et non de pœnis innocentum rideat. <l eID="gen2779" level="1"/>

** Job 9:24

Terra data est in manus impii ; <l eID="gen2780" level="1"/> <l level="1" sID="gen2781"/>vultum judicum ejus operit. <l eID="gen2781" level="1"/> <l level="1" sID="gen2782"/>Quod si non ille est, quis ergo est ? <l eID="gen2782" level="1"/>

** Job 9:25

Dies mei velociores fuerunt cursore ; <l eID="gen2783" level="1"/> <l level="1" sID="gen2784"/>fugerunt, et non viderunt bonum. <l eID="gen2784" level="1"/>

** Job 9:26

Pertransierunt quasi naves poma portantes ; <l eID="gen2785" level="1"/> <l level="1" sID="gen2786"/>sicut aquila volans ad escam. <l eID="gen2786" level="1"/>

** Job 9:27

Cum dixero : Nequaquam ita loquar : <l eID="gen2787" level="1"/> <l level="1" sID="gen2788"/>commuto faciem meam, et dolore torqueor. <l eID="gen2788" level="1"/>

** Job 9:28

Verebar omnia opera mea, <l eID="gen2789" level="1"/> <l level="1" sID="gen2790"/>sciens quod non parceres delinquenti. <l eID="gen2790" level="1"/>

** Job 9:29

Si autem et sic impius sum, <l eID="gen2791" level="1"/> <l level="1" sID="gen2792"/>quare frustra laboravi ? <l eID="gen2792" level="1"/>

** Job 9:30

Si lotus fuero quasi aquis nivis, <l eID="gen2793" level="1"/> <l level="1" sID="gen2794"/>et fulserint velut mundissimæ manus meæ, <l eID="gen2794" level="1"/>

** Job 9:31

tamen sordibus intinges me, <l eID="gen2795" level="1"/> <l level="1" sID="gen2796"/>et abominabuntur me vestimenta mea. <l eID="gen2796" level="1"/>

** Job 9:32

Neque enim viro qui similis mei est, respondebo ; <l eID="gen2797" level="1"/> <l level="1" sID="gen2798"/>nec qui mecum in judicio ex æquo possit audiri. <l eID="gen2798" level="1"/>

** Job 9:33

Non est qui utrumque valeat arguere, <l eID="gen2799" level="1"/> <l level="1" sID="gen2800"/>et ponere manum suam in ambobus. <l eID="gen2800" level="1"/>

** Job 9:34

Auferat a me virgam suam, <l eID="gen2801" level="1"/> <l level="1" sID="gen2802"/>et pavor ejus non me terreat. <l eID="gen2802" level="1"/>

** Job 9:35

Loquar, et non timebo eum ; <l eID="gen2803" level="1"/> <l level="1" sID="gen2804"/>neque enim possum metuens respondere.  <chapter eID="Job.9"/>

* Job 10

** Job 10:1

Tædet animam meam vitæ meæ ; <l eID="gen2805" level="1"/> <l level="1" sID="gen2806"/>dimittam adversum me eloquium meum : <l eID="gen2806" level="1"/> <l level="1" sID="gen2807"/>loquar in amaritudine animæ meæ. <l eID="gen2807" level="1"/>

** Job 10:2

Dicam Deo : Noli me condemnare ; <l eID="gen2808" level="1"/> <l level="1" sID="gen2809"/>indica mihi cur me ita judices. <l eID="gen2809" level="1"/>

** Job 10:3

Numquid bonum tibi videtur, si calumnieris me, <l eID="gen2810" level="1"/> <l level="1" sID="gen2811"/>et opprimas me opus manuum tuarum, <l eID="gen2811" level="1"/> <l level="1" sID="gen2812"/>et consilium impiorum adjuves ? <l eID="gen2812" level="1"/>

** Job 10:4

Numquid oculi carnei tibi sunt ? <l eID="gen2813" level="1"/> <l level="1" sID="gen2814"/>aut sicut videt homo, et tu videbis ? <l eID="gen2814" level="1"/>

** Job 10:5

Numquid sicut dies hominis dies tui, <l eID="gen2815" level="1"/> <l level="1" sID="gen2816"/>et anni tui sicut humana sunt tempora, <l eID="gen2816" level="1"/>

** Job 10:6

ut quæras iniquitatem meam, <l eID="gen2817" level="1"/> <l level="1" sID="gen2818"/>et peccatum meum scruteris, <l eID="gen2818" level="1"/>

** Job 10:7

et scias quia nihil impium fecerim, <l eID="gen2819" level="1"/> <l level="1" sID="gen2820"/>cum sit nemo qui de manu tua possit eruere ? <l eID="gen2820" level="1"/>

** Job 10:8

Manus tuæ fecerunt me, <l eID="gen2821" level="1"/> <l level="1" sID="gen2822"/>et plasmaverunt me totum in circuitu : <l eID="gen2822" level="1"/> <l level="1" sID="gen2823"/>et sic repente præcipitas me ? <l eID="gen2823" level="1"/>

** Job 10:9

Memento, quæso, quod sicut lutum feceris me, <l eID="gen2824" level="1"/> <l level="1" sID="gen2825"/>et in pulverem reduces me. <l eID="gen2825" level="1"/>

** Job 10:10

Nonne sicut lac mulsisti me, <l eID="gen2826" level="1"/> <l level="1" sID="gen2827"/>et sicut caseum me coagulasti ? <l eID="gen2827" level="1"/>

** Job 10:11

Pelle et carnibus vestisti me ; <l eID="gen2828" level="1"/> <l level="1" sID="gen2829"/>ossibus et nervis compegisti me. <l eID="gen2829" level="1"/>

** Job 10:12

Vitam et misericordiam tribuisti mihi, <l eID="gen2830" level="1"/> <l level="1" sID="gen2831"/>et visitatio tua custodivit spiritum meum. <l eID="gen2831" level="1"/>

** Job 10:13

Licet hæc celes in corde tuo, <l eID="gen2832" level="1"/> <l level="1" sID="gen2833"/>tamen scio quia universorum memineris. <l eID="gen2833" level="1"/>

** Job 10:14

Si peccavi, et ad horam pepercisti mihi, <l eID="gen2834" level="1"/> <l level="1" sID="gen2835"/>cur ab iniquitate mea mundum me esse non pateris ? <l eID="gen2835" level="1"/>

** Job 10:15

Et si impius fuero, væ mihi est ; <l eID="gen2836" level="1"/> <l level="1" sID="gen2837"/>et si justus, non levabo caput, <l eID="gen2837" level="1"/> <l level="1" sID="gen2838"/>saturatus afflictione et miseria. <l eID="gen2838" level="1"/>

** Job 10:16

Et propter superbiam quasi leænam capies me, <l eID="gen2839" level="1"/> <l level="1" sID="gen2840"/>reversusque mirabiliter me crucias. <l eID="gen2840" level="1"/>

** Job 10:17

Instauras testes tuos contra me, <l eID="gen2841" level="1"/> <l level="1" sID="gen2842"/>et multiplicas iram tuam adversum me, <l eID="gen2842" level="1"/> <l level="1" sID="gen2843"/>et pœnæ militant in me. <l eID="gen2843" level="1"/>

** Job 10:18

Quare de vulva eduxisti me ? <l eID="gen2844" level="1"/> <l level="1" sID="gen2845"/>qui utinam consumptus essem, ne oculus me videret. <l eID="gen2845" level="1"/>

** Job 10:19

Fuissem quasi non essem, <l eID="gen2846" level="1"/> <l level="1" sID="gen2847"/>de utero translatus ad tumulum. <l eID="gen2847" level="1"/>

** Job 10:20

Numquid non paucitas dierum meorum finietur brevi ? <l eID="gen2848" level="1"/> <l level="1" sID="gen2849"/>dimitte ergo me, ut plangam paululum dolorem meum, <l eID="gen2849" level="1"/>

** Job 10:21

antequam vadam, et non revertar, <l eID="gen2850" level="1"/> <l level="1" sID="gen2851"/>ad terram tenebrosam, et opertam mortis caligine : <l eID="gen2851" level="1"/>

** Job 10:22

terram miseriæ et tenebrarum, <l eID="gen2852" level="1"/> <l level="1" sID="gen2853"/>ubi umbra mortis et nullus ordo, <l eID="gen2853" level="1"/> <l level="1" sID="gen2854"/>sed sempiternus horror inhabitat. <l eID="gen2854" level="1"/><lg eID="gen2735"/> <chapter eID="Job.10"/>

* Job 11

** Job 11:1

Respondens autem Sophar Naamathites, dixit :  <div eID="gen2855" type="x-p"/>

** Job 11:2

Numquid qui multa loquitur, non et audiet ? <l eID="gen2857" level="1"/> <l level="1" sID="gen2858"/>aut vir verbosus justificabitur ? <l eID="gen2858" level="1"/>

** Job 11:3

Tibi soli tacebunt homines ? <l eID="gen2859" level="1"/> <l level="1" sID="gen2860"/>et cum ceteros irriseris, a nullo confutaberis ? <l eID="gen2860" level="1"/>

** Job 11:4

Dixisti enim : Purus est sermo meus, <l eID="gen2861" level="1"/> <l level="1" sID="gen2862"/>et mundus sum in conspectu tuo. <l eID="gen2862" level="1"/>

** Job 11:5

Atque utinam Deus loqueretur tecum, <l eID="gen2863" level="1"/> <l level="1" sID="gen2864"/>et aperiret labia sua tibi, <l eID="gen2864" level="1"/>

** Job 11:6

ut ostenderet tibi secreta sapientiæ, <l eID="gen2865" level="1"/> <l level="1" sID="gen2866"/>et quod multiplex esset lex ejus : <l eID="gen2866" level="1"/> <l level="1" sID="gen2867"/>et intelligeres quod multo minora exigaris ab eo <l eID="gen2867" level="1"/> <l level="1" sID="gen2868"/>quam meretur iniquitas tua ! <l eID="gen2868" level="1"/>

** Job 11:7

Forsitan vestigia Dei comprehendes, <l eID="gen2869" level="1"/> <l level="1" sID="gen2870"/>et usque ad perfectum Omnipotentem reperies ? <l eID="gen2870" level="1"/>

** Job 11:8

Excelsior cælo est, et quid facies ? <l eID="gen2871" level="1"/> <l level="1" sID="gen2872"/>profundior inferno, et unde cognosces ? <l eID="gen2872" level="1"/>

** Job 11:9

Longior terra mensura ejus, <l eID="gen2873" level="1"/> <l level="1" sID="gen2874"/>et latior mari. <l eID="gen2874" level="1"/>

** Job 11:10

Si subverterit omnia, vel in unum coarctaverit, <l eID="gen2875" level="1"/> <l level="1" sID="gen2876"/>quis contradicet ei ? <l eID="gen2876" level="1"/>

** Job 11:11

Ipse enim novit hominum vanitatem ; <l eID="gen2877" level="1"/> <l level="1" sID="gen2878"/>et videns iniquitatem, nonne considerat ? <l eID="gen2878" level="1"/>

** Job 11:12

Vir vanus in superbiam erigitur, <l eID="gen2879" level="1"/> <l level="1" sID="gen2880"/>et tamquam pullum onagri se liberum natum putat. <l eID="gen2880" level="1"/>

** Job 11:13

Tu autem firmasti cor tuum, <l eID="gen2881" level="1"/> <l level="1" sID="gen2882"/>et expandisti ad eum manus tuas. <l eID="gen2882" level="1"/>

** Job 11:14

Si iniquitatem quæ est in manu tua abstuleris a te, <l eID="gen2883" level="1"/> <l level="1" sID="gen2884"/>et non manserit in tabernaculo tuo injustitia, <l eID="gen2884" level="1"/>

** Job 11:15

tunc levare poteris faciem tuam absque macula ; <l eID="gen2885" level="1"/> <l level="1" sID="gen2886"/>et eris stabilis, et non timebis. <l eID="gen2886" level="1"/>

** Job 11:16

Miseriæ quoque oblivisceris, <l eID="gen2887" level="1"/> <l level="1" sID="gen2888"/>et quasi aquarum quæ præterierunt recordaberis. <l eID="gen2888" level="1"/>

** Job 11:17

Et quasi meridianus fulgor consurget tibi ad vesperam ; <l eID="gen2889" level="1"/> <l level="1" sID="gen2890"/>et cum te consumptum putaveris, orieris ut lucifer. <l eID="gen2890" level="1"/>

** Job 11:18

Et habebis fiduciam, proposita tibi spe : <l eID="gen2891" level="1"/> <l level="1" sID="gen2892"/>et defossus securus dormies. <l eID="gen2892" level="1"/>

** Job 11:19

Requiesces, et non erit qui te exterreat ; <l eID="gen2893" level="1"/> <l level="1" sID="gen2894"/>et deprecabuntur faciem tuam plurimi. <l eID="gen2894" level="1"/>

** Job 11:20

Oculi autem impiorum deficient, <l eID="gen2895" level="1"/> <l level="1" sID="gen2896"/>et effugium peribit ab eis : <l eID="gen2896" level="1"/> <l level="1" sID="gen2897"/>et spes illorum abominatio animæ. <l eID="gen2897" level="1"/><lg eID="gen2856"/> <chapter eID="Job.11"/>

* Job 12

** Job 12:1

Respondens autem Job, dixit :  <div eID="gen2898" type="x-p"/>

** Job 12:2

Ergo vos estis soli homines, <l eID="gen2900" level="1"/> <l level="1" sID="gen2901"/>et vobiscum morietur sapientia ? <l eID="gen2901" level="1"/>

** Job 12:3

Et mihi est cor sicut et vobis, nec inferior vestri sum ; <l eID="gen2902" level="1"/> <l level="1" sID="gen2903"/>quis enim hæc quæ nostis ignorat ? <l eID="gen2903" level="1"/>

** Job 12:4

Qui deridetur ab amico suo, sicut ego, <l eID="gen2904" level="1"/> <l level="1" sID="gen2905"/>invocabit Deum, et exaudiet eum : <l eID="gen2905" level="1"/> <l level="1" sID="gen2906"/>deridetur enim justi simplicitas. <l eID="gen2906" level="1"/>

** Job 12:5

Lampas contempta apud cogitationes divitum <l eID="gen2907" level="1"/> <l level="1" sID="gen2908"/>parata ad tempus statutum. <l eID="gen2908" level="1"/>

** Job 12:6

Abundant tabernacula prædonum, <l eID="gen2909" level="1"/> <l level="1" sID="gen2910"/>et audacter provocant Deum, <l eID="gen2910" level="1"/> <l level="1" sID="gen2911"/>cum ipse dederit omnia in manus eorum. <l eID="gen2911" level="1"/>

** Job 12:7

Nimirum interroga jumenta, et docebunt te ; <l eID="gen2912" level="1"/> <l level="1" sID="gen2913"/>et volatilia cæli, et indicabunt tibi. <l eID="gen2913" level="1"/>

** Job 12:8

Loquere terræ, et respondebit tibi, <l eID="gen2914" level="1"/> <l level="1" sID="gen2915"/>et narrabunt pisces maris. <l eID="gen2915" level="1"/>

** Job 12:9

Quis ignorat quod omnia hæc manus Domini fecerit ? <l eID="gen2916" level="1"/>

** Job 12:10

In cujus manu anima omnis viventis, <l eID="gen2917" level="1"/> <l level="1" sID="gen2918"/>et spiritus universæ carnis hominis. <l eID="gen2918" level="1"/>

** Job 12:11

Nonne auris verba dijudicat ? <l eID="gen2919" level="1"/> <l level="1" sID="gen2920"/>et fauces comedentis, saporem ? <l eID="gen2920" level="1"/>

** Job 12:12

In antiquis est sapientia, <l eID="gen2921" level="1"/> <l level="1" sID="gen2922"/>et in multo tempore prudentia. <l eID="gen2922" level="1"/>

** Job 12:13

Apud ipsum est sapientia et fortitudo ; <l eID="gen2923" level="1"/> <l level="1" sID="gen2924"/>ipse habet consilium et intelligentiam. <l eID="gen2924" level="1"/>

** Job 12:14

Si destruxerit, nemo est qui ædificet ; <l eID="gen2925" level="1"/> <l level="1" sID="gen2926"/>si incluserit hominem, nullus est qui aperiat. <l eID="gen2926" level="1"/>

** Job 12:15

Si continuerit aquas, omnia siccabuntur ; <l eID="gen2927" level="1"/> <l level="1" sID="gen2928"/>et si emiserit eas, subvertent terram. <l eID="gen2928" level="1"/>

** Job 12:16

Apud ipsum est fortitudo et sapientia ; <l eID="gen2929" level="1"/> <l level="1" sID="gen2930"/>ipse novit et decipientem, et eum qui decipitur. <l eID="gen2930" level="1"/>

** Job 12:17

Adducit consiliarios in stultum finem, <l eID="gen2931" level="1"/> <l level="1" sID="gen2932"/>et judices in stuporem. <l eID="gen2932" level="1"/>

** Job 12:18

Balteum regum dissolvit, <l eID="gen2933" level="1"/> <l level="1" sID="gen2934"/>et præcingit fune renes eorum. <l eID="gen2934" level="1"/>

** Job 12:19

Ducit sacerdotes inglorios, <l eID="gen2935" level="1"/> <l level="1" sID="gen2936"/>et optimates supplantat : <l eID="gen2936" level="1"/>

** Job 12:20

commutans labium veracium, <l eID="gen2937" level="1"/> <l level="1" sID="gen2938"/>et doctrinam senum auferens. <l eID="gen2938" level="1"/>

** Job 12:21

Effundit despectionem super principes, <l eID="gen2939" level="1"/> <l level="1" sID="gen2940"/>eos qui oppressi fuerant relevans. <l eID="gen2940" level="1"/>

** Job 12:22

Qui revelat profunda de tenebris, <l eID="gen2941" level="1"/> <l level="1" sID="gen2942"/>et producit in lucem umbram mortis. <l eID="gen2942" level="1"/>

** Job 12:23

Qui multiplicat gentes, et perdit eas, <l eID="gen2943" level="1"/> <l level="1" sID="gen2944"/>et subversas in integrum restituit. <l eID="gen2944" level="1"/>

** Job 12:24

Qui immutat cor principum populi terræ, <l eID="gen2945" level="1"/> <l level="1" sID="gen2946"/>et decipit eos ut frustra incedant per invium : <l eID="gen2946" level="1"/>

** Job 12:25

palpabunt quasi in tenebris, et non in luce, <l eID="gen2947" level="1"/> <l level="1" sID="gen2948"/>et errare eos faciet quasi ebrios.  <chapter eID="Job.12"/>

* Job 13

** Job 13:1

Ecce omnia hæc vidit oculus meus, <l eID="gen2949" level="1"/> <l level="1" sID="gen2950"/>et audivit auris mea, et intellexi singula. <l eID="gen2950" level="1"/>

** Job 13:2

Secundum scientiam vestram et ego novi : <l eID="gen2951" level="1"/> <l level="1" sID="gen2952"/>nec inferior vestri sum. <l eID="gen2952" level="1"/>

** Job 13:3

Sed tamen ad Omnipotentem loquar, <l eID="gen2953" level="1"/> <l level="1" sID="gen2954"/>et disputare cum Deo cupio : <l eID="gen2954" level="1"/>

** Job 13:4

prius vos ostendens fabricatores mendacii, <l eID="gen2955" level="1"/> <l level="1" sID="gen2956"/>et cultores perversorum dogmatum. <l eID="gen2956" level="1"/>

** Job 13:5

Atque utinam taceretis, <l eID="gen2957" level="1"/> <l level="1" sID="gen2958"/>ut putaremini esse sapientes. <l eID="gen2958" level="1"/>

** Job 13:6

Audite ergo correptionem meam, <l eID="gen2959" level="1"/> <l level="1" sID="gen2960"/>et judicium labiorum meorum attendite. <l eID="gen2960" level="1"/>

** Job 13:7

Numquid Deus indiget vestro mendacio, <l eID="gen2961" level="1"/> <l level="1" sID="gen2962"/>ut pro illo loquamini dolos ? <l eID="gen2962" level="1"/>

** Job 13:8

numquid faciem ejus accipitis, <l eID="gen2963" level="1"/> <l level="1" sID="gen2964"/>et pro Deo judicare nitimini ? <l eID="gen2964" level="1"/>

** Job 13:9

aut placebit ei quem celare nihil potest ? <l eID="gen2965" level="1"/> <l level="1" sID="gen2966"/>aut decipietur, ut homo, vestris fraudulentiis ? <l eID="gen2966" level="1"/>

** Job 13:10

Ipse vos arguet, <l eID="gen2967" level="1"/> <l level="1" sID="gen2968"/>quoniam in abscondito faciem ejus accipitis. <l eID="gen2968" level="1"/>

** Job 13:11

Statim ut se commoverit, turbabit vos, <l eID="gen2969" level="1"/> <l level="1" sID="gen2970"/>et terror ejus irruet super vos. <l eID="gen2970" level="1"/>

** Job 13:12

Memoria vestra comparabitur cineri, <l eID="gen2971" level="1"/> <l level="1" sID="gen2972"/>et redigentur in lutum cervices vestræ. <l eID="gen2972" level="1"/>

** Job 13:13

Tacete paulisper, ut loquar <l eID="gen2973" level="1"/> <l level="1" sID="gen2974"/>quodcumque mihi mens suggesserit. <l eID="gen2974" level="1"/>

** Job 13:14

Quare lacero carnes meas dentibus meis, <l eID="gen2975" level="1"/> <l level="1" sID="gen2976"/>et animam meam porto in manibus meis ? <l eID="gen2976" level="1"/>

** Job 13:15

Etiam si occiderit me, in ipso sperabo : <l eID="gen2977" level="1"/> <l level="1" sID="gen2978"/>verumtamen vias meas in conspectu ejus arguam. <l eID="gen2978" level="1"/>

** Job 13:16

Et ipse erit salvator meus : <l eID="gen2979" level="1"/> <l level="1" sID="gen2980"/>non enim veniet in conspectu ejus omnis hypocrita. <l eID="gen2980" level="1"/>

** Job 13:17

Audite sermonem meum, <l eID="gen2981" level="1"/> <l level="1" sID="gen2982"/>et ænigmata percipite auribus vestris. <l eID="gen2982" level="1"/>

** Job 13:18

Si fuero judicatus, <l eID="gen2983" level="1"/> <l level="1" sID="gen2984"/>scio quod justus inveniar. <l eID="gen2984" level="1"/>

** Job 13:19

Quis est qui judicetur mecum ? <l eID="gen2985" level="1"/> <l level="1" sID="gen2986"/>veniat : quare tacens consumor ? <l eID="gen2986" level="1"/>

** Job 13:20

Duo tantum ne facias mihi, <l eID="gen2987" level="1"/> <l level="1" sID="gen2988"/>et tunc a facie tua non abscondar : <l eID="gen2988" level="1"/>

** Job 13:21

manum tuam longe fac a me, <l eID="gen2989" level="1"/> <l level="1" sID="gen2990"/>et formido tua non me terreat. <l eID="gen2990" level="1"/>

** Job 13:22

Voca me, et ego respondebo tibi : <l eID="gen2991" level="1"/> <l level="1" sID="gen2992"/>aut certe loquar, et tu responde mihi. <l eID="gen2992" level="1"/>

** Job 13:23

Quantas habeo iniquitates et peccata ? <l eID="gen2993" level="1"/> <l level="1" sID="gen2994"/>scelera mea et delicta ostende mihi. <l eID="gen2994" level="1"/>

** Job 13:24

Cur faciem tuam abscondis, <l eID="gen2995" level="1"/> <l level="1" sID="gen2996"/>et arbitraris me inimicum tuum ? <l eID="gen2996" level="1"/>

** Job 13:25

Contra folium, quod vento rapitur, ostendis potentiam tuam, <l eID="gen2997" level="1"/> <l level="1" sID="gen2998"/>et stipulam siccam persequeris : <l eID="gen2998" level="1"/>

** Job 13:26

scribis enim contra me amaritudines, <l eID="gen2999" level="1"/> <l level="1" sID="gen3000"/>et consumere me vis peccatis adolescentiæ meæ. <l eID="gen3000" level="1"/>

** Job 13:27

Posuisti in nervo pedem meum, <l eID="gen3001" level="1"/> <l level="1" sID="gen3002"/>et observasti omnes semitas meas, <l eID="gen3002" level="1"/> <l level="1" sID="gen3003"/>et vestigia pedum meorum considerasti : <l eID="gen3003" level="1"/>

** Job 13:28

qui quasi putredo consumendus sum, <l eID="gen3004" level="1"/> <l level="1" sID="gen3005"/>et quasi vestimentum quod comeditur a tinea.  <chapter eID="Job.13"/>

* Job 14

** Job 14:1

Homo natus de muliere, brevi vivens tempore, <l eID="gen3006" level="1"/> <l level="1" sID="gen3007"/>repletur multis miseriis. <l eID="gen3007" level="1"/>

** Job 14:2

Qui quasi flos egreditur et conteritur, <l eID="gen3008" level="1"/> <l level="1" sID="gen3009"/>et fugit velut umbra, et numquam in eodem statu permanet. <l eID="gen3009" level="1"/>

** Job 14:3

Et dignum ducis super hujuscemodi aperire oculos tuos, <l eID="gen3010" level="1"/> <l level="1" sID="gen3011"/>et adducere eum tecum in judicium ? <l eID="gen3011" level="1"/>

** Job 14:4

Quis potest facere mundum de immundo conceptum semine ? <l eID="gen3012" level="1"/> <l level="1" sID="gen3013"/>nonne tu qui solus es ? <l eID="gen3013" level="1"/>

** Job 14:5

Breves dies hominis sunt : <l eID="gen3014" level="1"/> <l level="1" sID="gen3015"/>numerus mensium ejus apud te est : <l eID="gen3015" level="1"/> <l level="1" sID="gen3016"/>constituisti terminos ejus, qui præteriri non poterunt. <l eID="gen3016" level="1"/>

** Job 14:6

Recede paululum ab eo, ut quiescat, <l eID="gen3017" level="1"/> <l level="1" sID="gen3018"/>donec optata veniat, sicut mercenarii, dies ejus. <l eID="gen3018" level="1"/>

** Job 14:7

Lignum habet spem : <l eID="gen3019" level="1"/> <l level="1" sID="gen3020"/>si præcisum fuerit, rursum virescit, <l eID="gen3020" level="1"/> <l level="1" sID="gen3021"/>et rami ejus pullulant. <l eID="gen3021" level="1"/>

** Job 14:8

Si senuerit in terra radix ejus, <l eID="gen3022" level="1"/> <l level="1" sID="gen3023"/>et in pulvere emortuus fuerit truncus illius, <l eID="gen3023" level="1"/>

** Job 14:9

ad odorem aquæ germinabit, <l eID="gen3024" level="1"/> <l level="1" sID="gen3025"/>et faciet comam, quasi cum primum plantatum est. <l eID="gen3025" level="1"/>

** Job 14:10

Homo vero cum mortuus fuerit, et nudatus, <l eID="gen3026" level="1"/> <l level="1" sID="gen3027"/>atque consumptus, ubi, quæso, est ? <l eID="gen3027" level="1"/>

** Job 14:11

Quomodo si recedant aquæ de mari, <l eID="gen3028" level="1"/> <l level="1" sID="gen3029"/>et fluvius vacuefactus arescat : <l eID="gen3029" level="1"/>

** Job 14:12

sic homo, cum dormierit, non resurget : <l eID="gen3030" level="1"/> <l level="1" sID="gen3031"/>donec atteratur cælum, non evigilabit, <l eID="gen3031" level="1"/> <l level="1" sID="gen3032"/>nec consurget de somno suo. <l eID="gen3032" level="1"/>

** Job 14:13

Quis mihi hoc tribuat, ut in inferno protegas me, <l eID="gen3033" level="1"/> <l level="1" sID="gen3034"/>et abscondas me donec pertranseat furor tuus, <l eID="gen3034" level="1"/> <l level="1" sID="gen3035"/>et constituas mihi tempus in quo recorderis mei ? <l eID="gen3035" level="1"/>

** Job 14:14

Putasne mortuus homo rursum vivat ? <l eID="gen3036" level="1"/> <l level="1" sID="gen3037"/>cunctis diebus quibus nunc milito, expecto <l eID="gen3037" level="1"/> <l level="1" sID="gen3038"/>donec veniat immutatio mea. <l eID="gen3038" level="1"/>

** Job 14:15

Vocabis me, et ego respondebo tibi : <l eID="gen3039" level="1"/> <l level="1" sID="gen3040"/>operi manuum tuarum porriges dexteram. <l eID="gen3040" level="1"/>

** Job 14:16

Tu quidem gressus meos dinumerasti : <l eID="gen3041" level="1"/> <l level="1" sID="gen3042"/>sed parce peccatis meis. <l eID="gen3042" level="1"/>

** Job 14:17

Signasti quasi in sacculo delicta mea, <l eID="gen3043" level="1"/> <l level="1" sID="gen3044"/>sed curasti iniquitatem meam. <l eID="gen3044" level="1"/>

** Job 14:18

Mons cadens defluit, <l eID="gen3045" level="1"/> <l level="1" sID="gen3046"/>et saxum transfertur de loco suo : <l eID="gen3046" level="1"/>

** Job 14:19

lapides excavant aquæ, <l eID="gen3047" level="1"/> <l level="1" sID="gen3048"/>et alluvione paulatim terra consumitur : <l eID="gen3048" level="1"/> <l level="1" sID="gen3049"/>et hominem ergo similiter perdes. <l eID="gen3049" level="1"/>

** Job 14:20

Roborasti eum paululum, ut in perpetuum transiret : <l eID="gen3050" level="1"/> <l level="1" sID="gen3051"/>immutabis faciem ejus, et emittes eum. <l eID="gen3051" level="1"/>

** Job 14:21

Sive nobiles fuerint filii ejus, <l eID="gen3052" level="1"/> <l level="1" sID="gen3053"/>sive ignobiles, non intelliget. <l eID="gen3053" level="1"/>

** Job 14:22

Attamen caro ejus, dum vivet, dolebit, <l eID="gen3054" level="1"/> <l level="1" sID="gen3055"/>et anima illius super semetipso lugebit. <l eID="gen3055" level="1"/><lg eID="gen2899"/> <chapter eID="Job.14"/>

* Job 15

** Job 15:1

Respondens autem Eliphaz Themanites, dixit :  <div eID="gen3056" type="x-p"/>

** Job 15:2

Numquid sapiens respondebit quasi in ventum loquens, <l eID="gen3058" level="1"/> <l level="1" sID="gen3059"/>et implebit ardore stomachum suum ? <l eID="gen3059" level="1"/>

** Job 15:3

Arguis verbis eum qui non est æqualis tibi, <l eID="gen3060" level="1"/> <l level="1" sID="gen3061"/>et loqueris quod tibi non expedit. <l eID="gen3061" level="1"/>

** Job 15:4

Quantum in te est, evacuasti timorem, <l eID="gen3062" level="1"/> <l level="1" sID="gen3063"/>et tulisti preces coram Deo. <l eID="gen3063" level="1"/>

** Job 15:5

Docuit enim iniquitas tua os tuum, <l eID="gen3064" level="1"/> <l level="1" sID="gen3065"/>et imitaris linguam blasphemantium. <l eID="gen3065" level="1"/>

** Job 15:6

Condemnabit te os tuum, et non ego : <l eID="gen3066" level="1"/> <l level="1" sID="gen3067"/>et labia tua respondebunt tibi. <l eID="gen3067" level="1"/>

** Job 15:7

Numquid primus homo tu natus es, <l eID="gen3068" level="1"/> <l level="1" sID="gen3069"/>et ante colles formatus ? <l eID="gen3069" level="1"/>

** Job 15:8

numquid consilium Dei audisti, <l eID="gen3070" level="1"/> <l level="1" sID="gen3071"/>et inferior te erit ejus sapientia ? <l eID="gen3071" level="1"/>

** Job 15:9

Quid nosti quod ignoremus ? <l eID="gen3072" level="1"/> <l level="1" sID="gen3073"/>quid intelligis quod nesciamus ? <l eID="gen3073" level="1"/>

** Job 15:10

Et senes et antiqui sunt in nobis, <l eID="gen3074" level="1"/> <l level="1" sID="gen3075"/>multo vetustiores quam patres tui. <l eID="gen3075" level="1"/>

** Job 15:11

Numquid grande est ut consoletur te Deus ? <l eID="gen3076" level="1"/> <l level="1" sID="gen3077"/>sed verba tua prava hoc prohibent. <l eID="gen3077" level="1"/>

** Job 15:12

Quid te elevat cor tuum, <l eID="gen3078" level="1"/> <l level="1" sID="gen3079"/>et quasi magna cogitans attonitos habes oculos ? <l eID="gen3079" level="1"/>

** Job 15:13

Quid tumet contra Deum spiritus tuus, <l eID="gen3080" level="1"/> <l level="1" sID="gen3081"/>ut proferas de ore tuo hujuscemodi sermones ? <l eID="gen3081" level="1"/>

** Job 15:14

Quid est homo ut immaculatus sit, <l eID="gen3082" level="1"/> <l level="1" sID="gen3083"/>et ut justus appareat natus de muliere ? <l eID="gen3083" level="1"/>

** Job 15:15

Ecce inter sanctos ejus nemo immutabilis, <l eID="gen3084" level="1"/> <l level="1" sID="gen3085"/>et cæli non sunt mundi in conspectu ejus. <l eID="gen3085" level="1"/>

** Job 15:16

Quanto magis abominabilis et inutilis homo, <l eID="gen3086" level="1"/> <l level="1" sID="gen3087"/>qui bibit quasi aquam iniquitatem ? <l eID="gen3087" level="1"/>

** Job 15:17

Ostendam tibi : audi me : <l eID="gen3088" level="1"/> <l level="1" sID="gen3089"/>quod vidi, narrabo tibi. <l eID="gen3089" level="1"/>

** Job 15:18

Sapientes confitentur, <l eID="gen3090" level="1"/> <l level="1" sID="gen3091"/>et non abscondunt patres suos : <l eID="gen3091" level="1"/>

** Job 15:19

quibus solis data est terra, <l eID="gen3092" level="1"/> <l level="1" sID="gen3093"/>et non transivit alienus per eos. <l eID="gen3093" level="1"/>

** Job 15:20

Cunctis diebus suis impius superbit, <l eID="gen3094" level="1"/> <l level="1" sID="gen3095"/>et numerus annorum incertus est tyrannidis ejus. <l eID="gen3095" level="1"/>

** Job 15:21

Sonitus terroris semper in auribus illius : <l eID="gen3096" level="1"/> <l level="1" sID="gen3097"/>et cum pax sit, ille semper insidias suspicatur. <l eID="gen3097" level="1"/>

** Job 15:22

Non credit quod reverti possit de tenebris ad lucem, <l eID="gen3098" level="1"/> <l level="1" sID="gen3099"/>circumspectans undique gladium. <l eID="gen3099" level="1"/>

** Job 15:23

Cum se moverit ad quærendum panem, <l eID="gen3100" level="1"/> <l level="1" sID="gen3101"/>novit quod paratus sit in manu ejus tenebrarum dies. <l eID="gen3101" level="1"/>

** Job 15:24

Terrebit eum tribulatio, <l eID="gen3102" level="1"/> <l level="1" sID="gen3103"/>et angustia vallabit eum, <l eID="gen3103" level="1"/> <l level="1" sID="gen3104"/>sicut regem qui præparatur ad prælium. <l eID="gen3104" level="1"/>

** Job 15:25

Tetendit enim adversus Deum manum suam, <l eID="gen3105" level="1"/> <l level="1" sID="gen3106"/>et contra Omnipotentem roboratus est. <l eID="gen3106" level="1"/>

** Job 15:26

Cucurrit adversus eum erecto collo, <l eID="gen3107" level="1"/> <l level="1" sID="gen3108"/>et pingui cervice armatus est. <l eID="gen3108" level="1"/>

** Job 15:27

Operuit faciem ejus crassitudo, <l eID="gen3109" level="1"/> <l level="1" sID="gen3110"/>et de lateribus ejus arvina dependet. <l eID="gen3110" level="1"/>

** Job 15:28

Habitavit in civitatibus desolatis, <l eID="gen3111" level="1"/> <l level="1" sID="gen3112"/>et in domibus desertis, quæ in tumulos sunt redactæ. <l eID="gen3112" level="1"/>

** Job 15:29

Non ditabitur, nec perseverabit substantia ejus, <l eID="gen3113" level="1"/> <l level="1" sID="gen3114"/>nec mittet in terra radicem suam. <l eID="gen3114" level="1"/>

** Job 15:30

Non recedet de tenebris : <l eID="gen3115" level="1"/> <l level="1" sID="gen3116"/>ramos ejus arefaciet flamma, <l eID="gen3116" level="1"/> <l level="1" sID="gen3117"/>et auferetur spiritu oris sui. <l eID="gen3117" level="1"/>

** Job 15:31

Non credet, frustra errore deceptus, <l eID="gen3118" level="1"/> <l level="1" sID="gen3119"/>quod aliquo pretio redimendus sit. <l eID="gen3119" level="1"/>

** Job 15:32

Antequam dies ejus impleantur peribit, <l eID="gen3120" level="1"/> <l level="1" sID="gen3121"/>et manus ejus arescent. <l eID="gen3121" level="1"/>

** Job 15:33

Lædetur quasi vinea in primo flore botrus ejus, <l eID="gen3122" level="1"/> <l level="1" sID="gen3123"/>et quasi oliva projiciens florem suum. <l eID="gen3123" level="1"/>

** Job 15:34

Congregatio enim hypocritæ sterilis, <l eID="gen3124" level="1"/> <l level="1" sID="gen3125"/>et ignis devorabit tabernacula eorum qui munera libenter accipiunt. <l eID="gen3125" level="1"/>

** Job 15:35

Concepit dolorem, et peperit iniquitatem, <l eID="gen3126" level="1"/> <l level="1" sID="gen3127"/>et uterus ejus præparat dolos. <l eID="gen3127" level="1"/><lg eID="gen3057"/> <chapter eID="Job.15"/>

* Job 16

** Job 16:1

Respondens autem Job, dixit :  <div eID="gen3128" type="x-p"/>

** Job 16:2

Audivi frequenter talia : <l eID="gen3130" level="1"/> <l level="1" sID="gen3131"/>consolatores onerosi omnes vos estis. <l eID="gen3131" level="1"/>

** Job 16:3

Numquid habebunt finem verba ventosa ? <l eID="gen3132" level="1"/> <l level="1" sID="gen3133"/>aut aliquid tibi molestum est, si loquaris ? <l eID="gen3133" level="1"/>

** Job 16:4

Poteram et ego similia vestri loqui, <l eID="gen3134" level="1"/> <l level="1" sID="gen3135"/>atque utinam esset anima vestra pro anima mea : <l eID="gen3135" level="1"/>

** Job 16:5

consolarer et ego vos sermonibus, <l eID="gen3136" level="1"/> <l level="1" sID="gen3137"/>et moverem caput meum super vos ; <l eID="gen3137" level="1"/>

** Job 16:6

roborarem vos ore meo, <l eID="gen3138" level="1"/> <l level="1" sID="gen3139"/>et moverem labia mea, quasi parcens vobis. <l eID="gen3139" level="1"/>

** Job 16:7

Sed quid agam ? Si locutus fuero, non quiescet dolor meus, <l eID="gen3140" level="1"/> <l level="1" sID="gen3141"/>et si tacuero, non recedet a me. <l eID="gen3141" level="1"/>

** Job 16:8

Nunc autem oppressit me dolor meus, <l eID="gen3142" level="1"/> <l level="1" sID="gen3143"/>et in nihilum redacti sunt omnes artus mei. <l eID="gen3143" level="1"/>

** Job 16:9

Rugæ meæ testimonium dicunt contra me, <l eID="gen3144" level="1"/> <l level="1" sID="gen3145"/>et suscitatur falsiloquus adversus faciem meam, contradicens mihi. <l eID="gen3145" level="1"/>

** Job 16:10

Collegit furorem suum in me, <l eID="gen3146" level="1"/> <l level="1" sID="gen3147"/>et comminans mihi, infremuit contra me dentibus suis : <l eID="gen3147" level="1"/> <l level="1" sID="gen3148"/>hostis meus terribilibus oculis me intuitus est. <l eID="gen3148" level="1"/>

** Job 16:11

Aperuerunt super me ora sua, <l eID="gen3149" level="1"/> <l level="1" sID="gen3150"/>et exprobrantes percusserunt maxillam meam : <l eID="gen3150" level="1"/> <l level="1" sID="gen3151"/>satiati sunt pœnis meis. <l eID="gen3151" level="1"/>

** Job 16:12

Conclusit me Deus apud iniquum, <l eID="gen3152" level="1"/> <l level="1" sID="gen3153"/>et manibus impiorum me tradidit. <l eID="gen3153" level="1"/>

** Job 16:13

Ego ille quondam opulentus, repente contritus sum : <l eID="gen3154" level="1"/> <l level="1" sID="gen3155"/>tenuit cervicem meam, confregit me, <l eID="gen3155" level="1"/> <l level="1" sID="gen3156"/>et posuit me sibi quasi in signum. <l eID="gen3156" level="1"/>

** Job 16:14

Circumdedit me lanceis suis ; <l eID="gen3157" level="1"/> <l level="1" sID="gen3158"/>convulneravit lumbos meos : <l eID="gen3158" level="1"/> <l level="1" sID="gen3159"/>non pepercit, et effudit in terra viscera mea. <l eID="gen3159" level="1"/>

** Job 16:15

Concidit me vulnere super vulnus : <l eID="gen3160" level="1"/> <l level="1" sID="gen3161"/>irruit in me quasi gigas. <l eID="gen3161" level="1"/>

** Job 16:16

Saccum consui super cutem meam, <l eID="gen3162" level="1"/> <l level="1" sID="gen3163"/>et operui cinere carnem meam. <l eID="gen3163" level="1"/>

** Job 16:17

Facies mea intumuit a fletu, <l eID="gen3164" level="1"/> <l level="1" sID="gen3165"/>et palpebræ meæ caligaverunt. <l eID="gen3165" level="1"/>

** Job 16:18

Hæc passus sum absque iniquitate manus meæ, <l eID="gen3166" level="1"/> <l level="1" sID="gen3167"/>cum haberem mundas ad Deum preces. <l eID="gen3167" level="1"/>

** Job 16:19

Terra, ne operias sanguinem meum, <l eID="gen3168" level="1"/> <l level="1" sID="gen3169"/>neque inveniat in te locum latendi clamor meus : <l eID="gen3169" level="1"/>

** Job 16:20

ecce enim in cælo testis meus, <l eID="gen3170" level="1"/> <l level="1" sID="gen3171"/>et conscius meus in excelsis. <l eID="gen3171" level="1"/>

** Job 16:21

Verbosi amici mei : <l eID="gen3172" level="1"/> <l level="1" sID="gen3173"/>ad Deum stillat oculus meus : <l eID="gen3173" level="1"/>

** Job 16:22

atque utinam sic judicaretur vir cum Deo, <l eID="gen3174" level="1"/> <l level="1" sID="gen3175"/>quomodo judicatur filius hominis cum collega suo. <l eID="gen3175" level="1"/>

** Job 16:23

Ecce enim breves anni transeunt, <l eID="gen3176" level="1"/> <l level="1" sID="gen3177"/>et semitam per quam non revertar ambulo.  <chapter eID="Job.16"/>

* Job 17

** Job 17:1

Spiritus meus attenuabitur ; <l eID="gen3178" level="1"/> <l level="1" sID="gen3179"/>dies mei breviabuntur : <l eID="gen3179" level="1"/> <l level="1" sID="gen3180"/>et solum mihi superest sepulchrum. <l eID="gen3180" level="1"/>

** Job 17:2

Non peccavi, <l eID="gen3181" level="1"/> <l level="1" sID="gen3182"/>et in amaritudinibus moratur oculus meus. <l eID="gen3182" level="1"/>

** Job 17:3

Libera me, Domine, et pone me juxta te, <l eID="gen3183" level="1"/> <l level="1" sID="gen3184"/>et cujusvis manus pugnet contra me. <l eID="gen3184" level="1"/>

** Job 17:4

Cor eorum longe fecisti a disciplina : <l eID="gen3185" level="1"/> <l level="1" sID="gen3186"/>propterea non exaltabuntur. <l eID="gen3186" level="1"/>

** Job 17:5

Prædam pollicetur sociis, <l eID="gen3187" level="1"/> <l level="1" sID="gen3188"/>et oculi filiorum ejus deficient. <l eID="gen3188" level="1"/>

** Job 17:6

Posuit me quasi in proverbium vulgi, <l eID="gen3189" level="1"/> <l level="1" sID="gen3190"/>et exemplum sum coram eis. <l eID="gen3190" level="1"/>

** Job 17:7

Caligavit ab indignatione oculus meus, <l eID="gen3191" level="1"/> <l level="1" sID="gen3192"/>et membra mea quasi in nihilum redacta sunt. <l eID="gen3192" level="1"/>

** Job 17:8

Stupebunt justi super hoc, <l eID="gen3193" level="1"/> <l level="1" sID="gen3194"/>et innocens contra hypocritam suscitabitur. <l eID="gen3194" level="1"/>

** Job 17:9

Et tenebit justus viam suam, <l eID="gen3195" level="1"/> <l level="1" sID="gen3196"/>et mundis manibus addet fortitudinem. <l eID="gen3196" level="1"/>

** Job 17:10

Igitur omnes vos convertimini, et venite, <l eID="gen3197" level="1"/> <l level="1" sID="gen3198"/>et non inveniam in vobis ullum sapientem. <l eID="gen3198" level="1"/>

** Job 17:11

Dies mei transierunt ; <l eID="gen3199" level="1"/> <l level="1" sID="gen3200"/>cogitationes meæ dissipatæ sunt, <l eID="gen3200" level="1"/> <l level="1" sID="gen3201"/>torquentes cor meum. <l eID="gen3201" level="1"/>

** Job 17:12

Noctem verterunt in diem, <l eID="gen3202" level="1"/> <l level="1" sID="gen3203"/>et rursum post tenebras spero lucem. <l eID="gen3203" level="1"/>

** Job 17:13

Si sustinuero, infernus domus mea est, <l eID="gen3204" level="1"/> <l level="1" sID="gen3205"/>et in tenebris stravi lectulum meum. <l eID="gen3205" level="1"/>

** Job 17:14

Putredini dixi : Pater meus es ; <l eID="gen3206" level="1"/> <l level="1" sID="gen3207"/>Mater mea, et soror mea, vermibus. <l eID="gen3207" level="1"/>

** Job 17:15

Ubi est ergo nunc præstolatio mea ? <l eID="gen3208" level="1"/> <l level="1" sID="gen3209"/>et patientiam meam quis considerat ? <l eID="gen3209" level="1"/>

** Job 17:16

In profundissimum infernum descendent omnia mea : <l eID="gen3210" level="1"/> <l level="1" sID="gen3211"/>putasne saltem ibi erit requies mihi ? <l eID="gen3211" level="1"/><lg eID="gen3129"/> <chapter eID="Job.17"/>

* Job 18

** Job 18:1

Respondens autem Baldad Suhites, dixit :  <div eID="gen3212" type="x-p"/>

** Job 18:2

Usque ad quem finem verba jactabitis ? <l eID="gen3214" level="1"/> <l level="1" sID="gen3215"/>intelligite prius, et sic loquamur. <l eID="gen3215" level="1"/>

** Job 18:3

Quare reputati sumus ut jumenta, <l eID="gen3216" level="1"/> <l level="1" sID="gen3217"/>et sorduimus coram vobis ? <l eID="gen3217" level="1"/>

** Job 18:4

Qui perdis animam tuam in furore tuo, <l eID="gen3218" level="1"/> <l level="1" sID="gen3219"/>numquid propter te derelinquetur terra, <l eID="gen3219" level="1"/> <l level="1" sID="gen3220"/>et transferentur rupes de loco suo ? <l eID="gen3220" level="1"/>

** Job 18:5

Nonne lux impii extinguetur, <l eID="gen3221" level="1"/> <l level="1" sID="gen3222"/>nec splendebit flamma ignis ejus ? <l eID="gen3222" level="1"/>

** Job 18:6

Lux obtenebrescet in tabernaculo illius, <l eID="gen3223" level="1"/> <l level="1" sID="gen3224"/>et lucerna quæ super eum est extinguetur. <l eID="gen3224" level="1"/>

** Job 18:7

Arctabuntur gressus virtutis ejus, <l eID="gen3225" level="1"/> <l level="1" sID="gen3226"/>et præcipitabit eum consilium suum. <l eID="gen3226" level="1"/>

** Job 18:8

Immisit enim in rete pedes suos, <l eID="gen3227" level="1"/> <l level="1" sID="gen3228"/>et in maculis ejus ambulat. <l eID="gen3228" level="1"/>

** Job 18:9

Tenebitur planta illius laqueo, <l eID="gen3229" level="1"/> <l level="1" sID="gen3230"/>et exardescet contra eum sitis. <l eID="gen3230" level="1"/>

** Job 18:10

Abscondita est in terra pedica ejus, <l eID="gen3231" level="1"/> <l level="1" sID="gen3232"/>et decipula illius super semitam. <l eID="gen3232" level="1"/>

** Job 18:11

Undique terrebunt eum formidines, <l eID="gen3233" level="1"/> <l level="1" sID="gen3234"/>et involvent pedes ejus. <l eID="gen3234" level="1"/>

** Job 18:12

Attenuetur fame robur ejus, <l eID="gen3235" level="1"/> <l level="1" sID="gen3236"/>et inedia invadat costas illius. <l eID="gen3236" level="1"/>

** Job 18:13

Devoret pulchritudinem cutis ejus ; <l eID="gen3237" level="1"/> <l level="1" sID="gen3238"/>consumat brachia illius primogenita mors. <l eID="gen3238" level="1"/>

** Job 18:14

Avellatur de tabernaculo suo fiducia ejus, <l eID="gen3239" level="1"/> <l level="1" sID="gen3240"/>et calcet super eum, quasi rex, interitus. <l eID="gen3240" level="1"/>

** Job 18:15

Habitent in tabernaculo illius socii ejus qui non est ; <l eID="gen3241" level="1"/> <l level="1" sID="gen3242"/>aspergatur in tabernaculo ejus sulphur. <l eID="gen3242" level="1"/>

** Job 18:16

Deorsum radices ejus siccentur : <l eID="gen3243" level="1"/> <l level="1" sID="gen3244"/>sursum autem atteratur messis ejus. <l eID="gen3244" level="1"/>

** Job 18:17

Memoria illius pereat de terra, <l eID="gen3245" level="1"/> <l level="1" sID="gen3246"/>et non celebretur nomen ejus in plateis. <l eID="gen3246" level="1"/>

** Job 18:18

Expellet eum de luce in tenebras, <l eID="gen3247" level="1"/> <l level="1" sID="gen3248"/>et de orbe transferet eum. <l eID="gen3248" level="1"/>

** Job 18:19

Non erit semen ejus, neque progenies in populo suo, <l eID="gen3249" level="1"/> <l level="1" sID="gen3250"/>nec ullæ reliquiæ in regionibus ejus. <l eID="gen3250" level="1"/>

** Job 18:20

In die ejus stupebunt novissimi, <l eID="gen3251" level="1"/> <l level="1" sID="gen3252"/>et primos invadet horror. <l eID="gen3252" level="1"/>

** Job 18:21

Hæc sunt ergo tabernacula iniqui, <l eID="gen3253" level="1"/> <l level="1" sID="gen3254"/>et iste locus ejus qui ignorat Deum. <l eID="gen3254" level="1"/><lg eID="gen3213"/> <chapter eID="Job.18"/>

* Job 19

** Job 19:1

Respondens autem Job, dixit :  <div eID="gen3255" type="x-p"/>

** Job 19:2

Usquequo affligitis animam meam, <l eID="gen3257" level="1"/> <l level="1" sID="gen3258"/>et atteritis me sermonibus ? <l eID="gen3258" level="1"/>

** Job 19:3

En decies confunditis me, <l eID="gen3259" level="1"/> <l level="1" sID="gen3260"/>et non erubescitis opprimentes me. <l eID="gen3260" level="1"/>

** Job 19:4

Nempe etsi ignoravi, <l eID="gen3261" level="1"/> <l level="1" sID="gen3262"/>mecum erit ignorantia mea. <l eID="gen3262" level="1"/>

** Job 19:5

At vos contra me erigimini, <l eID="gen3263" level="1"/> <l level="1" sID="gen3264"/>et arguitis me opprobriis meis. <l eID="gen3264" level="1"/>

** Job 19:6

Saltem nunc intelligite quia Deus non æquo judicio afflixerit me, <l eID="gen3265" level="1"/> <l level="1" sID="gen3266"/>et flagellis suis me cinxerit. <l eID="gen3266" level="1"/>

** Job 19:7

Ecce clamabo, vim patiens, et nemo audiet ; <l eID="gen3267" level="1"/> <l level="1" sID="gen3268"/>vociferabor, et non est qui judicet. <l eID="gen3268" level="1"/>

** Job 19:8

Semitam meam circumsepsit, et transire non possum : <l eID="gen3269" level="1"/> <l level="1" sID="gen3270"/>et in calle meo tenebras posuit. <l eID="gen3270" level="1"/>

** Job 19:9

Spoliavit me gloria mea, <l eID="gen3271" level="1"/> <l level="1" sID="gen3272"/>et abstulit coronam de capite meo. <l eID="gen3272" level="1"/>

** Job 19:10

Destruxit me undique, et pereo : <l eID="gen3273" level="1"/> <l level="1" sID="gen3274"/>et quasi evulsæ arbori abstulit spem meam. <l eID="gen3274" level="1"/>

** Job 19:11

Iratus est contra me furor ejus, <l eID="gen3275" level="1"/> <l level="1" sID="gen3276"/>et sic me habuit quasi hostem suum. <l eID="gen3276" level="1"/>

** Job 19:12

Simul venerunt latrones ejus, <l eID="gen3277" level="1"/> <l level="1" sID="gen3278"/>et fecerunt sibi viam per me, <l eID="gen3278" level="1"/> <l level="1" sID="gen3279"/>et obsederunt in gyro tabernaculum meum. <l eID="gen3279" level="1"/>

** Job 19:13

Fratres meos longe fecit a me, <l eID="gen3280" level="1"/> <l level="1" sID="gen3281"/>et noti mei quasi alieni recesserunt a me. <l eID="gen3281" level="1"/>

** Job 19:14

Dereliquerunt me propinqui mei, <l eID="gen3282" level="1"/> <l level="1" sID="gen3283"/>et qui me noverant obliti sunt mei. <l eID="gen3283" level="1"/>

** Job 19:15

Inquilini domus meæ et ancillæ meæ sicut alienum habuerunt me, <l eID="gen3284" level="1"/> <l level="1" sID="gen3285"/>et quasi peregrinus fui in oculis eorum. <l eID="gen3285" level="1"/>

** Job 19:16

Servum meum vocavi, et non respondit : <l eID="gen3286" level="1"/> <l level="1" sID="gen3287"/>ore proprio deprecabar illum. <l eID="gen3287" level="1"/>

** Job 19:17

Halitum meum exhorruit uxor mea, <l eID="gen3288" level="1"/> <l level="1" sID="gen3289"/>et orabam filios uteri mei. <l eID="gen3289" level="1"/>

** Job 19:18

Stulti quoque despiciebant me : <l eID="gen3290" level="1"/> <l level="1" sID="gen3291"/>et cum ab eis recessissem, detrahebant mihi. <l eID="gen3291" level="1"/>

** Job 19:19

Abominati sunt me quondam consiliarii mei, <l eID="gen3292" level="1"/> <l level="1" sID="gen3293"/>et quem maxime diligebam, aversatus est me. <l eID="gen3293" level="1"/>

** Job 19:20

Pelli meæ, consumptis carnibus, adhæsit os meum, <l eID="gen3294" level="1"/> <l level="1" sID="gen3295"/>et derelicta sunt tantummodo labia circa dentes meos. <l eID="gen3295" level="1"/>

** Job 19:21

Miseremini mei, miseremini mei saltem vos, amici mei, <l eID="gen3296" level="1"/> <l level="1" sID="gen3297"/>quia manus Domini tetigit me. <l eID="gen3297" level="1"/>

** Job 19:22

Quare persequimini me sicut Deus, <l eID="gen3298" level="1"/> <l level="1" sID="gen3299"/>et carnibus meis saturamini ? <l eID="gen3299" level="1"/>

** Job 19:23

Quis mihi tribuat ut scribantur sermones mei ? <l eID="gen3300" level="1"/> <l level="1" sID="gen3301"/>quis mihi det ut exarentur in libro <l eID="gen3301" level="1"/>

** Job 19:24

stylo ferreo et plumbi lamina, <l eID="gen3302" level="1"/> <l level="1" sID="gen3303"/>vel celte sculpantur in silice ? <l eID="gen3303" level="1"/>

** Job 19:25

Scio enim quod redemptor meus vivit, <l eID="gen3304" level="1"/> <l level="1" sID="gen3305"/>et in novissimo die de terra surrecturus sum : <l eID="gen3305" level="1"/>

** Job 19:26

et rursum circumdabor pelle mea, <l eID="gen3306" level="1"/> <l level="1" sID="gen3307"/>et in carne mea videbo Deum meum : <l eID="gen3307" level="1"/>

** Job 19:27

quem visurus sum ego ipse, <l eID="gen3308" level="1"/> <l level="1" sID="gen3309"/>et oculi mei conspecturi sunt, et non alius : <l eID="gen3309" level="1"/> <l level="1" sID="gen3310"/>reposita est hæc spes mea in sinu meo. <l eID="gen3310" level="1"/>

** Job 19:28

Quare ergo nunc dicitis : Persequamur eum, <l eID="gen3311" level="1"/> <l level="1" sID="gen3312"/>et radicem verbi inveniamus contra eum ? <l eID="gen3312" level="1"/>

** Job 19:29

Fugite ergo a facie gladii, <l eID="gen3313" level="1"/> <l level="1" sID="gen3314"/>quoniam ultor iniquitatum gladius est : <l eID="gen3314" level="1"/> <l level="1" sID="gen3315"/>et scitote esse judicium. <l eID="gen3315" level="1"/><lg eID="gen3256"/> <chapter eID="Job.19"/>

* Job 20

** Job 20:1

Respondens autem Sophar Naamathites, dixit :  <div eID="gen3316" type="x-p"/>

** Job 20:2

Idcirco cogitationes meæ variæ succedunt sibi, <l eID="gen3318" level="1"/> <l level="1" sID="gen3319"/>et mens in diversa rapitur. <l eID="gen3319" level="1"/>

** Job 20:3

Doctrinam qua me arguis audiam, <l eID="gen3320" level="1"/> <l level="1" sID="gen3321"/>et spiritus intelligentiæ meæ respondebit mihi. <l eID="gen3321" level="1"/>

** Job 20:4

Hoc scio a principio, <l eID="gen3322" level="1"/> <l level="1" sID="gen3323"/>ex quo positus est homo super terram, <l eID="gen3323" level="1"/>

** Job 20:5

quod laus impiorum brevis sit, <l eID="gen3324" level="1"/> <l level="1" sID="gen3325"/>et gaudium hypocritæ ad instar puncti. <l eID="gen3325" level="1"/>

** Job 20:6

Si ascenderit usque ad cælum superbia ejus, <l eID="gen3326" level="1"/> <l level="1" sID="gen3327"/>et caput ejus nubes tetigerit, <l eID="gen3327" level="1"/>

** Job 20:7

quasi sterquilinium in fine perdetur, <l eID="gen3328" level="1"/> <l level="1" sID="gen3329"/>et qui eum viderant, dicent : Ubi est ? <l eID="gen3329" level="1"/>

** Job 20:8

Velut somnium avolans non invenietur : <l eID="gen3330" level="1"/> <l level="1" sID="gen3331"/>transiet sicut visio nocturna. <l eID="gen3331" level="1"/>

** Job 20:9

Oculus qui eum viderat non videbit, <l eID="gen3332" level="1"/> <l level="1" sID="gen3333"/>neque ultra intuebitur eum locus suus. <l eID="gen3333" level="1"/>

** Job 20:10

Filii ejus atterentur egestate, <l eID="gen3334" level="1"/> <l level="1" sID="gen3335"/>et manus illius reddent ei dolorem suum. <l eID="gen3335" level="1"/>

** Job 20:11

Ossa ejus implebuntur vitiis adolescentiæ ejus, <l eID="gen3336" level="1"/> <l level="1" sID="gen3337"/>et cum eo in pulvere dormient. <l eID="gen3337" level="1"/>

** Job 20:12

Cum enim dulce fuerit in ore ejus malum, <l eID="gen3338" level="1"/> <l level="1" sID="gen3339"/>abscondet illud sub lingua sua. <l eID="gen3339" level="1"/>

** Job 20:13

Parcet illi, et non derelinquet illud, <l eID="gen3340" level="1"/> <l level="1" sID="gen3341"/>et celabit in gutture suo. <l eID="gen3341" level="1"/>

** Job 20:14

Panis ejus in utero illius <l eID="gen3342" level="1"/> <l level="1" sID="gen3343"/>vertetur in fel aspidum intrinsecus. <l eID="gen3343" level="1"/>

** Job 20:15

Divitias quas devoravit evomet, <l eID="gen3344" level="1"/> <l level="1" sID="gen3345"/>et de ventre illius extrahet eas Deus. <l eID="gen3345" level="1"/>

** Job 20:16

Caput aspidum suget, <l eID="gen3346" level="1"/> <l level="1" sID="gen3347"/>et occidet eum lingua viperæ. <l eID="gen3347" level="1"/>

** Job 20:17

(Non videat rivulos fluminis, <l eID="gen3348" level="1"/> <l level="1" sID="gen3349"/>torrentes mellis et butyri.) <l eID="gen3349" level="1"/>

** Job 20:18

Luet quæ fecit omnia, nec tamen consumetur : <l eID="gen3350" level="1"/> <l level="1" sID="gen3351"/>juxta multitudinem adinventionum suarum, sic et sustinebit. <l eID="gen3351" level="1"/>

** Job 20:19

Quoniam confringens nudavit pauperes : <l eID="gen3352" level="1"/> <l level="1" sID="gen3353"/>domum rapuit, et non ædificavit eam. <l eID="gen3353" level="1"/>

** Job 20:20

Nec est satiatus venter ejus : <l eID="gen3354" level="1"/> <l level="1" sID="gen3355"/>et cum habuerit quæ concupierat, possidere non poterit. <l eID="gen3355" level="1"/>

** Job 20:21

Non remansit de cibo ejus, <l eID="gen3356" level="1"/> <l level="1" sID="gen3357"/>et propterea nihil permanebit de bonis ejus. <l eID="gen3357" level="1"/>

** Job 20:22

Cum satiatus fuerit, arctabitur : <l eID="gen3358" level="1"/> <l level="1" sID="gen3359"/>æstuabit, et omnis dolor irruet super eum. <l eID="gen3359" level="1"/>

** Job 20:23

Utinam impleatur venter ejus, <l eID="gen3360" level="1"/> <l level="1" sID="gen3361"/>ut emittat in eum iram furoris sui, <l eID="gen3361" level="1"/> <l level="1" sID="gen3362"/>et pluat super illum bellum suum. <l eID="gen3362" level="1"/>

** Job 20:24

Fugiet arma ferrea, <l eID="gen3363" level="1"/> <l level="1" sID="gen3364"/>et irruet in arcum æreum. <l eID="gen3364" level="1"/>

** Job 20:25

Eductus, et egrediens de vagina sua, <l eID="gen3365" level="1"/> <l level="1" sID="gen3366"/>et fulgurans in amaritudine sua : <l eID="gen3366" level="1"/> <l level="1" sID="gen3367"/>vadent et venient super eum horribiles. <l eID="gen3367" level="1"/>

** Job 20:26

Omnes tenebræ absconditæ sunt in occultis ejus ; <l eID="gen3368" level="1"/> <l level="1" sID="gen3369"/>devorabit eum ignis qui non succenditur : <l eID="gen3369" level="1"/> <l level="1" sID="gen3370"/>affligetur relictus in tabernaculo suo. <l eID="gen3370" level="1"/>

** Job 20:27

Revelabunt cæli iniquitatem ejus, <l eID="gen3371" level="1"/> <l level="1" sID="gen3372"/>et terra consurget adversus eum. <l eID="gen3372" level="1"/>

** Job 20:28

Apertum erit germen domus illius : <l eID="gen3373" level="1"/> <l level="1" sID="gen3374"/>detrahetur in die furoris Dei. <l eID="gen3374" level="1"/>

** Job 20:29

Hæc est pars hominis impii a Deo, <l eID="gen3375" level="1"/> <l level="1" sID="gen3376"/>et hæreditas verborum ejus a Domino. <l eID="gen3376" level="1"/><lg eID="gen3317"/> <chapter eID="Job.20"/>

* Job 21

** Job 21:1

Respondens autem Job, dixit :  <div eID="gen3377" type="x-p"/>

** Job 21:2

Audite, quæso, sermones meos, <l eID="gen3379" level="1"/> <l level="1" sID="gen3380"/>et agite pœnitentiam. <l eID="gen3380" level="1"/>

** Job 21:3

Sustinete me, et ego loquar : <l eID="gen3381" level="1"/> <l level="1" sID="gen3382"/>et post mea, si videbitur, verba, ridete. <l eID="gen3382" level="1"/>

** Job 21:4

Numquid contra hominem disputatio mea est, <l eID="gen3383" level="1"/> <l level="1" sID="gen3384"/>ut merito non debeam contristari ? <l eID="gen3384" level="1"/>

** Job 21:5

Attendite me et obstupescite, <l eID="gen3385" level="1"/> <l level="1" sID="gen3386"/>et superponite digitum ori vestro. <l eID="gen3386" level="1"/>

** Job 21:6

Et ego, quando recordatus fuero, pertimesco, <l eID="gen3387" level="1"/> <l level="1" sID="gen3388"/>et concutit carnem meam tremor. <l eID="gen3388" level="1"/>

** Job 21:7

Quare ergo impii vivunt, <l eID="gen3389" level="1"/> <l level="1" sID="gen3390"/>sublevati sunt, confortatique divitiis ? <l eID="gen3390" level="1"/>

** Job 21:8

Semen eorum permanet coram eis : <l eID="gen3391" level="1"/> <l level="1" sID="gen3392"/>propinquorum turba et nepotum in conspectu eorum. <l eID="gen3392" level="1"/>

** Job 21:9

Domus eorum securæ sunt et pacatæ, <l eID="gen3393" level="1"/> <l level="1" sID="gen3394"/>et non est virga Dei super illos. <l eID="gen3394" level="1"/>

** Job 21:10

Bos eorum concepit, et non abortivit : <l eID="gen3395" level="1"/> <l level="1" sID="gen3396"/>vacca peperit, et non est privata fœtu suo. <l eID="gen3396" level="1"/>

** Job 21:11

Egrediuntur quasi greges parvuli eorum, <l eID="gen3397" level="1"/> <l level="1" sID="gen3398"/>et infantes eorum exultant lusibus. <l eID="gen3398" level="1"/>

** Job 21:12

Tenent tympanum et citharam, <l eID="gen3399" level="1"/> <l level="1" sID="gen3400"/>et gaudent ad sonitum organi. <l eID="gen3400" level="1"/>

** Job 21:13

Ducunt in bonis dies suos, <l eID="gen3401" level="1"/> <l level="1" sID="gen3402"/>et in puncto ad inferna descendunt. <l eID="gen3402" level="1"/>

** Job 21:14

Qui dixerunt Deo : Recede a nobis, <l eID="gen3403" level="1"/> <l level="1" sID="gen3404"/>et scientiam viarum tuarum nolumus. <l eID="gen3404" level="1"/>

** Job 21:15

Quis est Omnipotens, ut serviamus ei ? <l eID="gen3405" level="1"/> <l level="1" sID="gen3406"/>et quid nobis prodest si oraverimus illum ? <l eID="gen3406" level="1"/>

** Job 21:16

Verumtamen quia non sunt in manu eorum bona sua, <l eID="gen3407" level="1"/> <l level="1" sID="gen3408"/>consilium impiorum longe sit a me. <l eID="gen3408" level="1"/>

** Job 21:17

Quoties lucerna impiorum extinguetur, <l eID="gen3409" level="1"/> <l level="1" sID="gen3410"/>et superveniet eis inundatio, <l eID="gen3410" level="1"/> <l level="1" sID="gen3411"/>et dolores dividet furoris sui ? <l eID="gen3411" level="1"/>

** Job 21:18

Erunt sicut paleæ ante faciem venti, <l eID="gen3412" level="1"/> <l level="1" sID="gen3413"/>et sicut favilla quam turbo dispergit. <l eID="gen3413" level="1"/>

** Job 21:19

Deus servabit filiis illius dolorem patris, <l eID="gen3414" level="1"/> <l level="1" sID="gen3415"/>et cum reddiderit, tunc sciet. <l eID="gen3415" level="1"/>

** Job 21:20

Videbunt oculi ejus interfectionem suam, <l eID="gen3416" level="1"/> <l level="1" sID="gen3417"/>et de furore Omnipotentis bibet. <l eID="gen3417" level="1"/>

** Job 21:21

Quid enim ad eum pertinet de domo sua post se, <l eID="gen3418" level="1"/> <l level="1" sID="gen3419"/>et si numerus mensium ejus dimidietur ? <l eID="gen3419" level="1"/>

** Job 21:22

Numquid Deus docebit quispiam scientiam, <l eID="gen3420" level="1"/> <l level="1" sID="gen3421"/>qui excelsos judicat ? <l eID="gen3421" level="1"/>

** Job 21:23

Iste moritur robustus et sanus, <l eID="gen3422" level="1"/> <l level="1" sID="gen3423"/>dives et felix : <l eID="gen3423" level="1"/>

** Job 21:24

viscera ejus plena sunt adipe, <l eID="gen3424" level="1"/> <l level="1" sID="gen3425"/>et medullis ossa illius irrigantur : <l eID="gen3425" level="1"/>

** Job 21:25

alius vero moritur in amaritudine animæ <l eID="gen3426" level="1"/> <l level="1" sID="gen3427"/>absque ullis opibus : <l eID="gen3427" level="1"/>

** Job 21:26

et tamen simul in pulvere dormient, <l eID="gen3428" level="1"/> <l level="1" sID="gen3429"/>et vermes operient eos. <l eID="gen3429" level="1"/>

** Job 21:27

Certe novi cogitationes vestras, <l eID="gen3430" level="1"/> <l level="1" sID="gen3431"/>et sententias contra me iniquas. <l eID="gen3431" level="1"/>

** Job 21:28

Dicitis enim : Ubi est domus principis ? <l eID="gen3432" level="1"/> <l level="1" sID="gen3433"/>et ubi tabernacula impiorum ? <l eID="gen3433" level="1"/>

** Job 21:29

Interrogate quemlibet de viatoribus, <l eID="gen3434" level="1"/> <l level="1" sID="gen3435"/>et hæc eadem illum intelligere cognoscetis : <l eID="gen3435" level="1"/>

** Job 21:30

quia in diem perditionis servatur malus, <l eID="gen3436" level="1"/> <l level="1" sID="gen3437"/>et ad diem furoris ducetur. <l eID="gen3437" level="1"/>

** Job 21:31

Quis arguet coram eo viam ejus ? <l eID="gen3438" level="1"/> <l level="1" sID="gen3439"/>et quæ fecit, quis reddet illi ? <l eID="gen3439" level="1"/>

** Job 21:32

Ipse ad sepulchra ducetur, <l eID="gen3440" level="1"/> <l level="1" sID="gen3441"/>et in congerie mortuorum vigilabit. <l eID="gen3441" level="1"/>

** Job 21:33

Dulcis fuit glareis Cocyti, <l eID="gen3442" level="1"/> <l level="1" sID="gen3443"/>et post se omnem hominem trahet, <l eID="gen3443" level="1"/> <l level="1" sID="gen3444"/>et ante se innumerabiles. <l eID="gen3444" level="1"/>

** Job 21:34

Quomodo igitur consolamini me frustra, <l eID="gen3445" level="1"/> <l level="1" sID="gen3446"/>cum responsio vestra repugnare ostensa sit veritati ? <l eID="gen3446" level="1"/><lg eID="gen3378"/> <chapter eID="Job.21"/>

* Job 22

** Job 22:1

Respondens autem Eliphaz Themanites, dixit :  <div eID="gen3447" type="x-p"/>

** Job 22:2

Numquid Deo potest comparari homo, <l eID="gen3449" level="1"/> <l level="1" sID="gen3450"/>etiam cum perfectæ fuerit scientiæ ? <l eID="gen3450" level="1"/>

** Job 22:3

Quid prodest Deo, si justus fueris ? <l eID="gen3451" level="1"/> <l level="1" sID="gen3452"/>aut quid ei confers, si immaculata fuerit via tua ? <l eID="gen3452" level="1"/>

** Job 22:4

Numquid timens arguet te, <l eID="gen3453" level="1"/> <l level="1" sID="gen3454"/>et veniet tecum in judicium, <l eID="gen3454" level="1"/>

** Job 22:5

et non propter malitiam tuam plurimam, <l eID="gen3455" level="1"/> <l level="1" sID="gen3456"/>et infinitas iniquitates tuas ? <l eID="gen3456" level="1"/>

** Job 22:6

Abstulisti enim pignus fratrum tuorum sine causa, <l eID="gen3457" level="1"/> <l level="1" sID="gen3458"/>et nudos spoliasti vestibus. <l eID="gen3458" level="1"/>

** Job 22:7

Aquam lasso non dedisti, <l eID="gen3459" level="1"/> <l level="1" sID="gen3460"/>et esurienti subtraxisti panem. <l eID="gen3460" level="1"/>

** Job 22:8

In fortitudine brachii tui possidebas terram, <l eID="gen3461" level="1"/> <l level="1" sID="gen3462"/>et potentissimus obtinebas eam. <l eID="gen3462" level="1"/>

** Job 22:9

Viduas dimisisti vacuas, <l eID="gen3463" level="1"/> <l level="1" sID="gen3464"/>et lacertos pupillorum comminuisti. <l eID="gen3464" level="1"/>

** Job 22:10

Propterea circumdatus es laqueis, <l eID="gen3465" level="1"/> <l level="1" sID="gen3466"/>et conturbat te formido subita. <l eID="gen3466" level="1"/>

** Job 22:11

Et putabas te tenebras non visurum, <l eID="gen3467" level="1"/> <l level="1" sID="gen3468"/>et impetu aquarum inundantium non oppressum iri ? <l eID="gen3468" level="1"/>

** Job 22:12

an non cogitas quod Deus excelsior cælo sit, <l eID="gen3469" level="1"/> <l level="1" sID="gen3470"/>et super stellarum verticem sublimetur ? <l eID="gen3470" level="1"/>

** Job 22:13

Et dicis : Quid enim novit Deus ? <l eID="gen3471" level="1"/> <l level="1" sID="gen3472"/>et quasi per caliginem judicat. <l eID="gen3472" level="1"/>

** Job 22:14

Nubes latibulum ejus, nec nostra considerat, <l eID="gen3473" level="1"/> <l level="1" sID="gen3474"/>et circa cardines cæli perambulat. <l eID="gen3474" level="1"/>

** Job 22:15

Numquid semitam sæculorum custodire cupis, <l eID="gen3475" level="1"/> <l level="1" sID="gen3476"/>quam calcaverunt viri iniqui, <l eID="gen3476" level="1"/>

** Job 22:16

qui sublati sunt ante tempus suum, <l eID="gen3477" level="1"/> <l level="1" sID="gen3478"/>et fluvius subvertit fundamentum eorum ? <l eID="gen3478" level="1"/>

** Job 22:17

Qui dicebant Deo : Recede a nobis : <l eID="gen3479" level="1"/> <l level="1" sID="gen3480"/>et quasi nihil posset facere Omnipotens, æstimabant eum, <l eID="gen3480" level="1"/>

** Job 22:18

cum ille implesset domos eorum bonis : <l eID="gen3481" level="1"/> <l level="1" sID="gen3482"/>quorum sententia procul sit a me. <l eID="gen3482" level="1"/>

** Job 22:19

Videbunt justi, et lætabuntur, <l eID="gen3483" level="1"/> <l level="1" sID="gen3484"/>et innocens subsannabit eos : <l eID="gen3484" level="1"/>

** Job 22:20

nonne succisa est erectio eorum ? <l eID="gen3485" level="1"/> <l level="1" sID="gen3486"/>et reliquias eorum devoravit ignis ? <l eID="gen3486" level="1"/>

** Job 22:21

Acquiesce igitur ei, et habeto pacem, <l eID="gen3487" level="1"/> <l level="1" sID="gen3488"/>et per hæc habebis fructus optimos. <l eID="gen3488" level="1"/>

** Job 22:22

Suscipe ex ore illius legem, <l eID="gen3489" level="1"/> <l level="1" sID="gen3490"/>et pone sermones ejus in corde tuo. <l eID="gen3490" level="1"/>

** Job 22:23

Si reversus fueris ad Omnipotentem, ædificaberis, <l eID="gen3491" level="1"/> <l level="1" sID="gen3492"/>et longe facies iniquitatem a tabernaculo tuo. <l eID="gen3492" level="1"/>

** Job 22:24

Dabit pro terra silicem, <l eID="gen3493" level="1"/> <l level="1" sID="gen3494"/>et pro silice torrentes aureos. <l eID="gen3494" level="1"/>

** Job 22:25

Eritque Omnipotens contra hostes tuos, <l eID="gen3495" level="1"/> <l level="1" sID="gen3496"/>et argentum coacervabitur tibi. <l eID="gen3496" level="1"/>

** Job 22:26

Tunc super Omnipotentem deliciis afflues, <l eID="gen3497" level="1"/> <l level="1" sID="gen3498"/>et elevabis ad Deum faciem tuam. <l eID="gen3498" level="1"/>

** Job 22:27

Rogabis eum, et exaudiet te, <l eID="gen3499" level="1"/> <l level="1" sID="gen3500"/>et vota tua reddes. <l eID="gen3500" level="1"/>

** Job 22:28

Decernes rem, et veniet tibi, <l eID="gen3501" level="1"/> <l level="1" sID="gen3502"/>et in viis tuis splendebit lumen. <l eID="gen3502" level="1"/>

** Job 22:29

Qui enim humiliatus fuerit, erit in gloria, <l eID="gen3503" level="1"/> <l level="1" sID="gen3504"/>et qui inclinaverit oculos, ipse salvabitur. <l eID="gen3504" level="1"/>

** Job 22:30

Salvabitur innocens : <l eID="gen3505" level="1"/> <l level="1" sID="gen3506"/>salvabitur autem in munditia manuum suarum. <l eID="gen3506" level="1"/><lg eID="gen3448"/> <chapter eID="Job.22"/>

* Job 23

** Job 23:1

Respondens autem Job, ait :  <div eID="gen3507" type="x-p"/>

** Job 23:2

Nunc quoque in amaritudine est sermo meus, <l eID="gen3509" level="1"/> <l level="1" sID="gen3510"/>et manus plagæ meæ aggravata est super gemitum meum. <l eID="gen3510" level="1"/>

** Job 23:3

Quis mihi tribuat ut cognoscam et inveniam illum, <l eID="gen3511" level="1"/> <l level="1" sID="gen3512"/>et veniam usque ad solium ejus ? <l eID="gen3512" level="1"/>

** Job 23:4

Ponam coram eo judicium, <l eID="gen3513" level="1"/> <l level="1" sID="gen3514"/>et os meum replebo increpationibus : <l eID="gen3514" level="1"/>

** Job 23:5

ut sciam verba quæ mihi respondeat, <l eID="gen3515" level="1"/> <l level="1" sID="gen3516"/>et intelligam quid loquatur mihi. <l eID="gen3516" level="1"/>

** Job 23:6

Nolo multa fortitudine contendat mecum, <l eID="gen3517" level="1"/> <l level="1" sID="gen3518"/>nec magnitudinis suæ mole me premat. <l eID="gen3518" level="1"/>

** Job 23:7

Proponat æquitatem contra me, <l eID="gen3519" level="1"/> <l level="1" sID="gen3520"/>et perveniat ad victoriam judicium meum. <l eID="gen3520" level="1"/>

** Job 23:8

Si ad orientem iero, non apparet ; <l eID="gen3521" level="1"/> <l level="1" sID="gen3522"/>si ad occidentem, non intelligam eum. <l eID="gen3522" level="1"/>

** Job 23:9

Si ad sinistram, quid agam ? non apprehendam eum ; <l eID="gen3523" level="1"/> <l level="1" sID="gen3524"/>si me vertam ad dexteram, non videbo illum. <l eID="gen3524" level="1"/>

** Job 23:10

Ipse vero scit viam meam, <l eID="gen3525" level="1"/> <l level="1" sID="gen3526"/>et probavit me quasi aurum quod per ignem transit. <l eID="gen3526" level="1"/>

** Job 23:11

Vestigia ejus secutus est pes meus : <l eID="gen3527" level="1"/> <l level="1" sID="gen3528"/>viam ejus custodivi, et non declinavi ex ea. <l eID="gen3528" level="1"/>

** Job 23:12

A mandatis labiorum ejus non recessi, <l eID="gen3529" level="1"/> <l level="1" sID="gen3530"/>et in sinu meo abscondi verba oris ejus. <l eID="gen3530" level="1"/>

** Job 23:13

Ipse enim solus est, et nemo avertere potest cogitationem ejus : <l eID="gen3531" level="1"/> <l level="1" sID="gen3532"/>et anima ejus quodcumque voluit, hoc fecit. <l eID="gen3532" level="1"/>

** Job 23:14

Cum expleverit in me voluntatem suam, <l eID="gen3533" level="1"/> <l level="1" sID="gen3534"/>et alia multa similia præsto sunt ei. <l eID="gen3534" level="1"/>

** Job 23:15

Et idcirco a facie ejus turbatus sum, <l eID="gen3535" level="1"/> <l level="1" sID="gen3536"/>et considerans eum, timore sollicitor. <l eID="gen3536" level="1"/>

** Job 23:16

Deus mollivit cor meum, <l eID="gen3537" level="1"/> <l level="1" sID="gen3538"/>et Omnipotens conturbavit me. <l eID="gen3538" level="1"/>

** Job 23:17

Non enim perii propter imminentes tenebras, <l eID="gen3539" level="1"/> <l level="1" sID="gen3540"/>nec faciem meam operuit caligo.  <chapter eID="Job.23"/>

* Job 24

** Job 24:1

Ab Omnipotente non sunt abscondita tempora : <l eID="gen3541" level="1"/> <l level="1" sID="gen3542"/>qui autem noverunt eum, <l eID="gen3542" level="1"/> <l level="1" sID="gen3543"/>ignorant dies illius. <l eID="gen3543" level="1"/>

** Job 24:2

Alii terminos transtulerunt ; <l eID="gen3544" level="1"/> <l level="1" sID="gen3545"/>diripuerunt greges, et paverunt eos. <l eID="gen3545" level="1"/>

** Job 24:3

Asinum pupillorum abegerunt, <l eID="gen3546" level="1"/> <l level="1" sID="gen3547"/>et abstulerunt pro pignore bovem viduæ. <l eID="gen3547" level="1"/>

** Job 24:4

Subverterunt pauperum viam, <l eID="gen3548" level="1"/> <l level="1" sID="gen3549"/>et oppresserunt pariter mansuetos terræ. <l eID="gen3549" level="1"/>

** Job 24:5

Alii quasi onagri in deserto egrediuntur ad opus suum : <l eID="gen3550" level="1"/> <l level="1" sID="gen3551"/>vigilantes ad prædam, præparant panem liberis. <l eID="gen3551" level="1"/>

** Job 24:6

Agrum non suum demetunt, <l eID="gen3552" level="1"/> <l level="1" sID="gen3553"/>et vineam ejus, quem vi oppresserint, vindemiant. <l eID="gen3553" level="1"/>

** Job 24:7

Nudos dimittunt homines, indumenta tollentes, <l eID="gen3554" level="1"/> <l level="1" sID="gen3555"/>quibus non est operimentum in frigore : <l eID="gen3555" level="1"/>

** Job 24:8

quos imbres montium rigant, <l eID="gen3556" level="1"/> <l level="1" sID="gen3557"/>et non habentes velamen, amplexantur lapides. <l eID="gen3557" level="1"/>

** Job 24:9

Vim fecerunt deprædantes pupillos, <l eID="gen3558" level="1"/> <l level="1" sID="gen3559"/>et vulgum pauperem spoliaverunt. <l eID="gen3559" level="1"/>

** Job 24:10

Nudis et incedentibus absque vestitu, <l eID="gen3560" level="1"/> <l level="1" sID="gen3561"/>et esurientibus tulerunt spicas. <l eID="gen3561" level="1"/>

** Job 24:11

Inter acervos eorum meridiati sunt, <l eID="gen3562" level="1"/> <l level="1" sID="gen3563"/>qui calcatis torcularibus sitiunt. <l eID="gen3563" level="1"/>

** Job 24:12

De civitatibus fecerunt viros gemere, <l eID="gen3564" level="1"/> <l level="1" sID="gen3565"/>et anima vulneratorum clamavit : <l eID="gen3565" level="1"/> <l level="1" sID="gen3566"/>et Deus inultum abire non patitur. <l eID="gen3566" level="1"/>

** Job 24:13

Ipsi fuerunt rebelles lumini : <l eID="gen3567" level="1"/> <l level="1" sID="gen3568"/>nescierunt vias ejus, <l eID="gen3568" level="1"/> <l level="1" sID="gen3569"/>nec reversi sunt per semitas ejus. <l eID="gen3569" level="1"/>

** Job 24:14

Mane primo consurgit homicida ; <l eID="gen3570" level="1"/> <l level="1" sID="gen3571"/>interficit egenum et pauperem : <l eID="gen3571" level="1"/> <l level="1" sID="gen3572"/>per noctem vero erit quasi fur. <l eID="gen3572" level="1"/>

** Job 24:15

Oculus adulteri observat caliginem, <l eID="gen3573" level="1"/> <l level="1" sID="gen3574"/>dicens : Non me videbit oculus : <l eID="gen3574" level="1"/> <l level="1" sID="gen3575"/>et operiet vultum suum. <l eID="gen3575" level="1"/>

** Job 24:16

Perfodit in tenebris domos, <l eID="gen3576" level="1"/> <l level="1" sID="gen3577"/>sicut in die condixerant sibi, <l eID="gen3577" level="1"/> <l level="1" sID="gen3578"/>et ignoraverunt lucem. <l eID="gen3578" level="1"/>

** Job 24:17

Si subito apparuerit aurora, arbitrantur umbram mortis : <l eID="gen3579" level="1"/> <l level="1" sID="gen3580"/>et sic in tenebris quasi in luce ambulant. <l eID="gen3580" level="1"/>

** Job 24:18

Levis est super faciem aquæ : <l eID="gen3581" level="1"/> <l level="1" sID="gen3582"/>maledicta sit pars ejus in terra, <l eID="gen3582" level="1"/> <l level="1" sID="gen3583"/>nec ambulet per viam vinearum. <l eID="gen3583" level="1"/>

** Job 24:19

Ad nimium calorem transeat ab aquis nivium, <l eID="gen3584" level="1"/> <l level="1" sID="gen3585"/>et usque ad inferos peccatum illius. <l eID="gen3585" level="1"/>

** Job 24:20

Obliviscatur ejus misericordia ; dulcedo illius vermes : <l eID="gen3586" level="1"/> <l level="1" sID="gen3587"/>non sit in recordatione, <l eID="gen3587" level="1"/> <l level="1" sID="gen3588"/>sed conteratur quasi lignum infructuosum. <l eID="gen3588" level="1"/>

** Job 24:21

Pavit enim sterilem quæ non parit, <l eID="gen3589" level="1"/> <l level="1" sID="gen3590"/>et viduæ bene non fecit. <l eID="gen3590" level="1"/>

** Job 24:22

Detraxit fortes in fortitudine sua, <l eID="gen3591" level="1"/> <l level="1" sID="gen3592"/>et cum steterit, non credet vitæ suæ. <l eID="gen3592" level="1"/>

** Job 24:23

Dedit ei Deus locum pœnitentiæ, <l eID="gen3593" level="1"/> <l level="1" sID="gen3594"/>et ille abutitur eo in superbiam : <l eID="gen3594" level="1"/> <l level="1" sID="gen3595"/>oculi autem ejus sunt in viis illius. <l eID="gen3595" level="1"/>

** Job 24:24

Elevati sunt ad modicum, et non subsistent : <l eID="gen3596" level="1"/> <l level="1" sID="gen3597"/>et humiliabuntur sicut omnia, et auferentur, <l eID="gen3597" level="1"/> <l level="1" sID="gen3598"/>et sicut summitates spicarum conterentur. <l eID="gen3598" level="1"/>

** Job 24:25

Quod si non est ita, quis me potest arguere esse mentitum, <l eID="gen3599" level="1"/> <l level="1" sID="gen3600"/>et ponere ante Deum verba mea ? <l eID="gen3600" level="1"/><lg eID="gen3508"/> <chapter eID="Job.24"/>

* Job 25

** Job 25:1

Respondens autem Baldad Suhites, dixit :  <div eID="gen3601" type="x-p"/>

** Job 25:2

Potestas et terror apud eum est, <l eID="gen3603" level="1"/> <l level="1" sID="gen3604"/>qui facit concordiam in sublimibus suis. <l eID="gen3604" level="1"/>

** Job 25:3

Numquid est numerus militum ejus ? <l eID="gen3605" level="1"/> <l level="1" sID="gen3606"/>et super quem non surget lumen illius ? <l eID="gen3606" level="1"/>

** Job 25:4

Numquid justificari potest homo comparatus Deo ? <l eID="gen3607" level="1"/> <l level="1" sID="gen3608"/>aut apparere mundus natus de muliere ? <l eID="gen3608" level="1"/>

** Job 25:5

Ecce luna etiam non splendet, <l eID="gen3609" level="1"/> <l level="1" sID="gen3610"/>et stellæ non sunt mundæ in conspectu ejus : <l eID="gen3610" level="1"/>

** Job 25:6

quanto magis homo putredo, <l eID="gen3611" level="1"/> <l level="1" sID="gen3612"/>et filius hominis vermis ? <l eID="gen3612" level="1"/><lg eID="gen3602"/> <chapter eID="Job.25"/>

* Job 26

** Job 26:1

Respondens autem Job dixit :  <div eID="gen3613" type="x-p"/>

** Job 26:2

Cujus adjutor es ? numquid imbecillis ? <l eID="gen3615" level="1"/> <l level="1" sID="gen3616"/>et sustentas brachium ejus qui non est fortis ? <l eID="gen3616" level="1"/>

** Job 26:3

Cui dedisti consilium ? <l eID="gen3617" level="1"/> <l level="1" sID="gen3618"/>forsitan illi qui non habet sapientiam : <l eID="gen3618" level="1"/> <l level="1" sID="gen3619"/>et prudentiam tuam ostendisti plurimam. <l eID="gen3619" level="1"/>

** Job 26:4

Quem docere voluisti ? <l eID="gen3620" level="1"/> <l level="1" sID="gen3621"/>nonne eum qui fecit spiramentum ? <l eID="gen3621" level="1"/>

** Job 26:5

Ecce gigantes gemunt sub aquis, <l eID="gen3622" level="1"/> <l level="1" sID="gen3623"/>et qui habitant cum eis. <l eID="gen3623" level="1"/>

** Job 26:6

Nudus est infernus coram illo, <l eID="gen3624" level="1"/> <l level="1" sID="gen3625"/>et nullum est operimentum perditioni. <l eID="gen3625" level="1"/>

** Job 26:7

Qui extendit aquilonem super vacuum, <l eID="gen3626" level="1"/> <l level="1" sID="gen3627"/>et appendit terram super nihilum. <l eID="gen3627" level="1"/>

** Job 26:8

Qui ligat aquas in nubibus suis, <l eID="gen3628" level="1"/> <l level="1" sID="gen3629"/>ut non erumpant pariter deorsum. <l eID="gen3629" level="1"/>

** Job 26:9

Qui tenet vultum solii sui, <l eID="gen3630" level="1"/> <l level="1" sID="gen3631"/>et expandit super illud nebulam suam. <l eID="gen3631" level="1"/>

** Job 26:10

Terminum circumdedit aquis, <l eID="gen3632" level="1"/> <l level="1" sID="gen3633"/>usque dum finiantur lux et tenebræ. <l eID="gen3633" level="1"/>

** Job 26:11

Columnæ cæli contremiscunt, <l eID="gen3634" level="1"/> <l level="1" sID="gen3635"/>et pavent ad nutum ejus. <l eID="gen3635" level="1"/>

** Job 26:12

In fortitudine illius repente maria congregata sunt, <l eID="gen3636" level="1"/> <l level="1" sID="gen3637"/>et prudentia ejus percussit superbum. <l eID="gen3637" level="1"/>

** Job 26:13

Spiritus ejus ornavit cælos, <l eID="gen3638" level="1"/> <l level="1" sID="gen3639"/>et obstetricante manu ejus, eductus est coluber tortuosus. <l eID="gen3639" level="1"/>

** Job 26:14

Ecce hæc ex parte dicta sunt viarum ejus : <l eID="gen3640" level="1"/> <l level="1" sID="gen3641"/>et cum vix parvam stillam sermonis ejus audierimus, <l eID="gen3641" level="1"/> <l level="1" sID="gen3642"/>quis poterit tonitruum magnitudinis illius intueri ? <l eID="gen3642" level="1"/><lg eID="gen3614"/> <chapter eID="Job.26"/>

* Job 27

** Job 27:1

Addidit quoque Job, assumens parabolam suam, et dixit :  <div eID="gen3643" type="x-p"/>

** Job 27:2

Vivit Deus, qui abstulit judicium meum, <l eID="gen3645" level="1"/> <l level="1" sID="gen3646"/>et Omnipotens, qui ad amaritudinem adduxit animam meam. <l eID="gen3646" level="1"/>

** Job 27:3

Quia donec superest halitus in me, <l eID="gen3647" level="1"/> <l level="1" sID="gen3648"/>et spiritus Dei in naribus meis, <l eID="gen3648" level="1"/>

** Job 27:4

non loquentur labia mea iniquitatem, <l eID="gen3649" level="1"/> <l level="1" sID="gen3650"/>nec lingua mea meditabitur mendacium. <l eID="gen3650" level="1"/>

** Job 27:5

Absit a me ut justos vos esse judicem : <l eID="gen3651" level="1"/> <l level="1" sID="gen3652"/>donec deficiam, non recedam ab innocentia mea. <l eID="gen3652" level="1"/>

** Job 27:6

Justificationem meam, quam cœpi tenere, non deseram : <l eID="gen3653" level="1"/> <l level="1" sID="gen3654"/>neque enim reprehendit me cor meum in omni vita mea. <l eID="gen3654" level="1"/>

** Job 27:7

Sit ut impius, inimicus meus, <l eID="gen3655" level="1"/> <l level="1" sID="gen3656"/>et adversarius meus quasi iniquus. <l eID="gen3656" level="1"/>

** Job 27:8

Quæ est enim spes hypocritæ, si avare rapiat, <l eID="gen3657" level="1"/> <l level="1" sID="gen3658"/>et non liberet Deus animam ejus ? <l eID="gen3658" level="1"/>

** Job 27:9

Numquid Deus audiet clamorem ejus, <l eID="gen3659" level="1"/> <l level="1" sID="gen3660"/>cum venerit super eum angustia ? <l eID="gen3660" level="1"/>

** Job 27:10

aut poterit in Omnipotente delectari, <l eID="gen3661" level="1"/> <l level="1" sID="gen3662"/>et invocare Deum omni tempore ? <l eID="gen3662" level="1"/>

** Job 27:11

Docebo vos per manum Dei quæ Omnipotens habeat, <l eID="gen3663" level="1"/> <l level="1" sID="gen3664"/>nec abscondam. <l eID="gen3664" level="1"/>

** Job 27:12

Ecce vos omnes nostis : <l eID="gen3665" level="1"/> <l level="1" sID="gen3666"/>et quid sine causa vana loquimini ? <l eID="gen3666" level="1"/>

** Job 27:13

Hæc est pars hominis impii apud Deum, <l eID="gen3667" level="1"/> <l level="1" sID="gen3668"/>et hæreditas violentorum, quam ob Omnipotente suscipient. <l eID="gen3668" level="1"/>

** Job 27:14

Si multiplicati fuerint filii ejus, in gladio erunt, <l eID="gen3669" level="1"/> <l level="1" sID="gen3670"/>et nepotes ejus non saturabuntur pane : <l eID="gen3670" level="1"/>

** Job 27:15

qui reliqui fuerint ex eo sepelientur in interitu, <l eID="gen3671" level="1"/> <l level="1" sID="gen3672"/>et viduæ illius non plorabunt. <l eID="gen3672" level="1"/>

** Job 27:16

Si comportaverit quasi terram argentum, <l eID="gen3673" level="1"/> <l level="1" sID="gen3674"/>et sicut lutum præparaverit vestimenta : <l eID="gen3674" level="1"/>

** Job 27:17

præparabit quidem, sed justus vestietur illis, <l eID="gen3675" level="1"/> <l level="1" sID="gen3676"/>et argentum innocens dividet. <l eID="gen3676" level="1"/>

** Job 27:18

Ædificavit sicut tinea domum suam, <l eID="gen3677" level="1"/> <l level="1" sID="gen3678"/>et sicut custos fecit umbraculum. <l eID="gen3678" level="1"/>

** Job 27:19

Dives, cum dormierit, nihil secum auferet : <l eID="gen3679" level="1"/> <l level="1" sID="gen3680"/>aperiet oculos suos, et nihil inveniet. <l eID="gen3680" level="1"/>

** Job 27:20

Apprehendet eum quasi aqua inopia : <l eID="gen3681" level="1"/> <l level="1" sID="gen3682"/>nocte opprimet eum tempestas. <l eID="gen3682" level="1"/>

** Job 27:21

Tollet eum ventus urens, et auferet, <l eID="gen3683" level="1"/> <l level="1" sID="gen3684"/>et velut turbo rapiet eum de loco suo. <l eID="gen3684" level="1"/>

** Job 27:22

Et mittet super eum, et non parcet : <l eID="gen3685" level="1"/> <l level="1" sID="gen3686"/>de manu ejus fugiens fugiet. <l eID="gen3686" level="1"/>

** Job 27:23

Stringet super eum manus suas, <l eID="gen3687" level="1"/> <l level="1" sID="gen3688"/>et sibilabit super illum, intuens locum ejus.  <chapter eID="Job.27"/>

* Job 28

** Job 28:1

Habet argentum venarum suarum principia, <l eID="gen3689" level="1"/> <l level="1" sID="gen3690"/>et auro locus est in quo conflatur. <l eID="gen3690" level="1"/>

** Job 28:2

Ferrum de terra tollitur, <l eID="gen3691" level="1"/> <l level="1" sID="gen3692"/>et lapis solutus calore in æs vertitur. <l eID="gen3692" level="1"/>

** Job 28:3

Tempus posuit tenebris, <l eID="gen3693" level="1"/> <l level="1" sID="gen3694"/>et universorum finem ipse considerat : <l eID="gen3694" level="1"/> <l level="1" sID="gen3695"/>lapidem quoque caliginis et umbram mortis. <l eID="gen3695" level="1"/>

** Job 28:4

Dividit torrens a populo peregrinante <l eID="gen3696" level="1"/> <l level="1" sID="gen3697"/>eos quos oblitus est pes egentis hominis, et invios. <l eID="gen3697" level="1"/>

** Job 28:5

Terra de qua oriebatur panis, <l eID="gen3698" level="1"/> <l level="1" sID="gen3699"/>in loco suo igni subversa est. <l eID="gen3699" level="1"/>

** Job 28:6

Locus sapphiri lapides ejus, <l eID="gen3700" level="1"/> <l level="1" sID="gen3701"/>et glebæ illius aurum. <l eID="gen3701" level="1"/>

** Job 28:7

Semitam ignoravit avis, <l eID="gen3702" level="1"/> <l level="1" sID="gen3703"/>nec intuitus est eam oculus vulturis. <l eID="gen3703" level="1"/>

** Job 28:8

Non calcaverunt eam filii institorum, <l eID="gen3704" level="1"/> <l level="1" sID="gen3705"/>nec pertransivit per eam leæna. <l eID="gen3705" level="1"/>

** Job 28:9

Ad silicem extendit manum suam : <l eID="gen3706" level="1"/> <l level="1" sID="gen3707"/>subvertit a radicibus montes. <l eID="gen3707" level="1"/>

** Job 28:10

In petris rivos excidit, <l eID="gen3708" level="1"/> <l level="1" sID="gen3709"/>et omne pretiosum vidit oculus ejus. <l eID="gen3709" level="1"/>

** Job 28:11

Profunda quoque fluviorum scrutatus est, <l eID="gen3710" level="1"/> <l level="1" sID="gen3711"/>et abscondita in lucem produxit. <l eID="gen3711" level="1"/>

** Job 28:12

Sapientia vero ubi invenitur ? <l eID="gen3712" level="1"/> <l level="1" sID="gen3713"/>et quis est locus intelligentiæ ? <l eID="gen3713" level="1"/>

** Job 28:13

Nescit homo pretium ejus, <l eID="gen3714" level="1"/> <l level="1" sID="gen3715"/>nec invenitur in terra suaviter viventium. <l eID="gen3715" level="1"/>

** Job 28:14

Abyssus dicit : Non est in me, <l eID="gen3716" level="1"/> <l level="1" sID="gen3717"/>et mare loquitur : Non est mecum. <l eID="gen3717" level="1"/>

** Job 28:15

Non dabitur aurum obrizum pro ea, <l eID="gen3718" level="1"/> <l level="1" sID="gen3719"/>nec appendetur argentum in commutatione ejus. <l eID="gen3719" level="1"/>

** Job 28:16

Non conferetur tinctis Indiæ coloribus, <l eID="gen3720" level="1"/> <l level="1" sID="gen3721"/>nec lapidi sardonycho pretiosissimo vel sapphiro. <l eID="gen3721" level="1"/>

** Job 28:17

Non adæquabitur ei aurum vel vitrum, <l eID="gen3722" level="1"/> <l level="1" sID="gen3723"/>nec commutabuntur pro ea vasa auri. <l eID="gen3723" level="1"/>

** Job 28:18

Excelsa et eminentia non memorabuntur comparatione ejus : <l eID="gen3724" level="1"/> <l level="1" sID="gen3725"/>trahitur autem sapientia de occultis. <l eID="gen3725" level="1"/>

** Job 28:19

Non adæquabitur ei topazius de Æthiopia, <l eID="gen3726" level="1"/> <l level="1" sID="gen3727"/>nec tincturæ mundissimæ componetur. <l eID="gen3727" level="1"/>

** Job 28:20

Unde ergo sapientia venit ? <l eID="gen3728" level="1"/> <l level="1" sID="gen3729"/>et quis est locus intelligentiæ ? <l eID="gen3729" level="1"/>

** Job 28:21

Abscondita est ab oculis omnium viventium : <l eID="gen3730" level="1"/> <l level="1" sID="gen3731"/>volucres quoque cæli latet. <l eID="gen3731" level="1"/>

** Job 28:22

Perditio et mors dixerunt : <l eID="gen3732" level="1"/> <l level="1" sID="gen3733"/>Auribus nostris audivimus famam ejus. <l eID="gen3733" level="1"/>

** Job 28:23

Deus intelligit viam ejus, <l eID="gen3734" level="1"/> <l level="1" sID="gen3735"/>et ipse novit locum illius. <l eID="gen3735" level="1"/>

** Job 28:24

Ipse enim fines mundi intuetur, <l eID="gen3736" level="1"/> <l level="1" sID="gen3737"/>et omnia quæ sub cælo sunt respicit. <l eID="gen3737" level="1"/>

** Job 28:25

Qui fecit ventis pondus, <l eID="gen3738" level="1"/> <l level="1" sID="gen3739"/>et aquas appendit in mensura. <l eID="gen3739" level="1"/>

** Job 28:26

Quando ponebat pluviis legem, <l eID="gen3740" level="1"/> <l level="1" sID="gen3741"/>et viam procellis sonantibus : <l eID="gen3741" level="1"/>

** Job 28:27

tunc vidit illam et enarravit, <l eID="gen3742" level="1"/> <l level="1" sID="gen3743"/>et præparavit, et investigavit. <l eID="gen3743" level="1"/>

** Job 28:28

Et dixit homini : Ecce timor Domini, ipsa est sapientia ; <l eID="gen3744" level="1"/> <l level="1" sID="gen3745"/>et recedere a malo, intelligentia. <l eID="gen3745" level="1"/><lg eID="gen3644"/> <chapter eID="Job.28"/>

* Job 29

** Job 29:1

Addidit quoque Job, assumens parabolam suam, et dixit :  <div eID="gen3746" type="x-p"/>

** Job 29:2

Quis mihi tribuat ut sim juxta menses pristinos, <l eID="gen3748" level="1"/> <l level="1" sID="gen3749"/>secundum dies quibus Deus custodiebat me ? <l eID="gen3749" level="1"/>

** Job 29:3

Quando splendebat lucerna ejus super caput meum, <l eID="gen3750" level="1"/> <l level="1" sID="gen3751"/>et ad lumen ejus ambulabam in tenebris : <l eID="gen3751" level="1"/>

** Job 29:4

sicut fui in diebus adolescentiæ meæ, <l eID="gen3752" level="1"/> <l level="1" sID="gen3753"/>quando secreto Deus erat in tabernaculo meo : <l eID="gen3753" level="1"/>

** Job 29:5

quando erat Omnipotens mecum, <l eID="gen3754" level="1"/> <l level="1" sID="gen3755"/>et in circuitu meo pueri mei : <l eID="gen3755" level="1"/>

** Job 29:6

quando lavabam pedes meos butyro, <l eID="gen3756" level="1"/> <l level="1" sID="gen3757"/>et petra fundebat mihi rivos olei : <l eID="gen3757" level="1"/>

** Job 29:7

quando procedebam ad portam civitatis, <l eID="gen3758" level="1"/> <l level="1" sID="gen3759"/>et in platea parabant cathedram mihi. <l eID="gen3759" level="1"/>

** Job 29:8

Videbant me juvenes, et abscondebantur : <l eID="gen3760" level="1"/> <l level="1" sID="gen3761"/>et senes assurgentes stabant. <l eID="gen3761" level="1"/>

** Job 29:9

Principes cessabant loqui, <l eID="gen3762" level="1"/> <l level="1" sID="gen3763"/>et digitum superponebant ori suo. <l eID="gen3763" level="1"/>

** Job 29:10

Vocem suam cohibebant duces, <l eID="gen3764" level="1"/> <l level="1" sID="gen3765"/>et lingua eorum gutturi suo adhærebat. <l eID="gen3765" level="1"/>

** Job 29:11

Auris audiens beatificabat me, <l eID="gen3766" level="1"/> <l level="1" sID="gen3767"/>et oculus videns testimonium reddebat mihi : <l eID="gen3767" level="1"/>

** Job 29:12

eo quod liberassem pauperem vociferantem, <l eID="gen3768" level="1"/> <l level="1" sID="gen3769"/>et pupillum cui non esset adjutor. <l eID="gen3769" level="1"/>

** Job 29:13

Benedictio perituri super me veniebat, <l eID="gen3770" level="1"/> <l level="1" sID="gen3771"/>et cor viduæ consolatus sum. <l eID="gen3771" level="1"/>

** Job 29:14

Justitia indutus sum, <l eID="gen3772" level="1"/> <l level="1" sID="gen3773"/>et vestivi me, sicut vestimento et diademate, judicio meo. <l eID="gen3773" level="1"/>

** Job 29:15

Oculus fui cæco, et pes claudo. <l eID="gen3774" level="1"/>

** Job 29:16

Pater eram pauperum, <l eID="gen3775" level="1"/> <l level="1" sID="gen3776"/>et causam quam nesciebam diligentissime investigabam. <l eID="gen3776" level="1"/>

** Job 29:17

Conterebam molas iniqui, <l eID="gen3777" level="1"/> <l level="1" sID="gen3778"/>et de dentibus illius auferebam prædam. <l eID="gen3778" level="1"/>

** Job 29:18

Dicebamque : In nidulo meo moriar, <l eID="gen3779" level="1"/> <l level="1" sID="gen3780"/>et sicut palma multiplicabo dies. <l eID="gen3780" level="1"/>

** Job 29:19

Radix mea aperta est secus aquas, <l eID="gen3781" level="1"/> <l level="1" sID="gen3782"/>et ros morabitur in messione mea. <l eID="gen3782" level="1"/>

** Job 29:20

Gloria mea semper innovabitur, <l eID="gen3783" level="1"/> <l level="1" sID="gen3784"/>et arcus meus in manu mea instaurabitur. <l eID="gen3784" level="1"/>

** Job 29:21

Qui me audiebant, expectabant sententiam, <l eID="gen3785" level="1"/> <l level="1" sID="gen3786"/>et intenti tacebant ad consilium meum. <l eID="gen3786" level="1"/>

** Job 29:22

Verbis meis addere nihil audebant, <l eID="gen3787" level="1"/> <l level="1" sID="gen3788"/>et super illos stillabat eloquium meum. <l eID="gen3788" level="1"/>

** Job 29:23

Expectabant me sicut pluviam, <l eID="gen3789" level="1"/> <l level="1" sID="gen3790"/>et os suum aperiebant quasi ad imbrem serotinum. <l eID="gen3790" level="1"/>

** Job 29:24

Siquando ridebam ad eos, non credebant : <l eID="gen3791" level="1"/> <l level="1" sID="gen3792"/>et lux vultus mei non cadebat in terram. <l eID="gen3792" level="1"/>

** Job 29:25

Si voluissem ire ad eos, sedebam primus : <l eID="gen3793" level="1"/> <l level="1" sID="gen3794"/>cumque sederem quasi rex, circumstante exercitu, <l eID="gen3794" level="1"/> <l level="1" sID="gen3795"/>eram tamen mœrentium consolator.  <chapter eID="Job.29"/>

* Job 30

** Job 30:1

Nunc autem derident me juniores tempore, <l eID="gen3796" level="1"/> <l level="1" sID="gen3797"/>quorum non dignabar patres ponere cum canibus gregis mei : <l eID="gen3797" level="1"/>

** Job 30:2

quorum virtus manuum mihi erat pro nihilo, <l eID="gen3798" level="1"/> <l level="1" sID="gen3799"/>et vita ipsa putabantur indigni : <l eID="gen3799" level="1"/>

** Job 30:3

egestate et fame steriles, qui rodebant in solitudine, <l eID="gen3800" level="1"/> <l level="1" sID="gen3801"/>squallentes calamitate et miseria. <l eID="gen3801" level="1"/>

** Job 30:4

Et mandebant herbas, et arborum cortices, <l eID="gen3802" level="1"/> <l level="1" sID="gen3803"/>et radix juniperorum erat cibus eorum : <l eID="gen3803" level="1"/>

** Job 30:5

qui de convallibus ista rapientes, <l eID="gen3804" level="1"/> <l level="1" sID="gen3805"/>cum singula reperissent, ad ea cum clamore currebant. <l eID="gen3805" level="1"/>

** Job 30:6

In desertis habitabant torrentium, <l eID="gen3806" level="1"/> <l level="1" sID="gen3807"/>et in cavernis terræ, vel super glaream : <l eID="gen3807" level="1"/>

** Job 30:7

qui inter hujuscemodi lætabantur, <l eID="gen3808" level="1"/> <l level="1" sID="gen3809"/>et esse sub sentibus delicias computabant : <l eID="gen3809" level="1"/>

** Job 30:8

filii stultorum et ignobilium, <l eID="gen3810" level="1"/> <l level="1" sID="gen3811"/>et in terra penitus non parentes. <l eID="gen3811" level="1"/>

** Job 30:9

Nunc in eorum canticum versus sum, <l eID="gen3812" level="1"/> <l level="1" sID="gen3813"/>et factus sum eis in proverbium. <l eID="gen3813" level="1"/>

** Job 30:10

Abominantur me, et longe fugiunt a me, <l eID="gen3814" level="1"/> <l level="1" sID="gen3815"/>et faciem meam conspuere non verentur. <l eID="gen3815" level="1"/>

** Job 30:11

Pharetram enim suam aperuit, et afflixit me, <l eID="gen3816" level="1"/> <l level="1" sID="gen3817"/>et frenum posuit in os meum. <l eID="gen3817" level="1"/>

** Job 30:12

Ad dexteram orientis calamitates meæ illico surrexerunt : <l eID="gen3818" level="1"/> <l level="1" sID="gen3819"/>pedes meos subverterunt, <l eID="gen3819" level="1"/> <l level="1" sID="gen3820"/>et oppresserunt quasi fluctibus semitis suis. <l eID="gen3820" level="1"/>

** Job 30:13

Dissipaverunt itinera mea ; <l eID="gen3821" level="1"/> <l level="1" sID="gen3822"/>insidiati sunt mihi, et prævaluerunt : <l eID="gen3822" level="1"/> <l level="1" sID="gen3823"/>et non fuit qui ferret auxilium. <l eID="gen3823" level="1"/>

** Job 30:14

Quasi rupto muro, et aperta janua, irruerunt super me, <l eID="gen3824" level="1"/> <l level="1" sID="gen3825"/>et ad meas miserias devoluti sunt. <l eID="gen3825" level="1"/>

** Job 30:15

Redactus sum in nihilum : <l eID="gen3826" level="1"/> <l level="1" sID="gen3827"/>abstulisti quasi ventus desiderium meum, <l eID="gen3827" level="1"/> <l level="1" sID="gen3828"/>et velut nubes pertransiit salus mea. <l eID="gen3828" level="1"/>

** Job 30:16

Nunc autem in memetipso marcescit anima mea, <l eID="gen3829" level="1"/> <l level="1" sID="gen3830"/>et possident me dies afflictionis. <l eID="gen3830" level="1"/>

** Job 30:17

Nocte os meum perforatur doloribus, <l eID="gen3831" level="1"/> <l level="1" sID="gen3832"/>et qui me comedunt, non dormiunt. <l eID="gen3832" level="1"/>

** Job 30:18

In multitudine eorum consumitur vestimentum meum, <l eID="gen3833" level="1"/> <l level="1" sID="gen3834"/>et quasi capitio tunicæ succinxerunt me. <l eID="gen3834" level="1"/>

** Job 30:19

Comparatus sum luto, <l eID="gen3835" level="1"/> <l level="1" sID="gen3836"/>et assimilatus sum favillæ et cineri. <l eID="gen3836" level="1"/>

** Job 30:20

Clamo ad te, et non exaudis me : <l eID="gen3837" level="1"/> <l level="1" sID="gen3838"/>sto, et non respicis me. <l eID="gen3838" level="1"/>

** Job 30:21

Mutatus es mihi in crudelem, <l eID="gen3839" level="1"/> <l level="1" sID="gen3840"/>et in duritia manus tuæ adversaris mihi. <l eID="gen3840" level="1"/>

** Job 30:22

Elevasti me, et quasi super ventum ponens ; <l eID="gen3841" level="1"/> <l level="1" sID="gen3842"/>elisisti me valide. <l eID="gen3842" level="1"/>

** Job 30:23

Scio quia morti trades me, <l eID="gen3843" level="1"/> <l level="1" sID="gen3844"/>ubi constituta est domus omni viventi. <l eID="gen3844" level="1"/>

** Job 30:24

Verumtamen non ad consumptionem eorum emittis manum tuam : <l eID="gen3845" level="1"/> <l level="1" sID="gen3846"/>et si corruerint, ipse salvabis. <l eID="gen3846" level="1"/>

** Job 30:25

Flebam quondam super eo qui afflictus erat, <l eID="gen3847" level="1"/> <l level="1" sID="gen3848"/>et compatiebatur anima mea pauperi. <l eID="gen3848" level="1"/>

** Job 30:26

Expectabam bona, et venerunt mihi mala : <l eID="gen3849" level="1"/> <l level="1" sID="gen3850"/>præstolabar lucem, et eruperunt tenebræ. <l eID="gen3850" level="1"/>

** Job 30:27

Interiora mea efferbuerunt absque ulla requie : <l eID="gen3851" level="1"/> <l level="1" sID="gen3852"/>prævenerunt me dies afflictionis. <l eID="gen3852" level="1"/>

** Job 30:28

Mœrens incedebam sine furore ; <l eID="gen3853" level="1"/> <l level="1" sID="gen3854"/>consurgens, in turba clamabam. <l eID="gen3854" level="1"/>

** Job 30:29

Frater fui draconum, <l eID="gen3855" level="1"/> <l level="1" sID="gen3856"/>et socius struthionum. <l eID="gen3856" level="1"/>

** Job 30:30

Cutis mea denigrata est super me, <l eID="gen3857" level="1"/> <l level="1" sID="gen3858"/>et ossa mea aruerunt præ caumate. <l eID="gen3858" level="1"/>

** Job 30:31

Versa est in luctum cithara mea, <l eID="gen3859" level="1"/> <l level="1" sID="gen3860"/>et organum meum in vocem flentium.  <chapter eID="Job.30"/>

* Job 31

** Job 31:1

Pepigi fœdus cum oculis meis, <l eID="gen3861" level="1"/> <l level="1" sID="gen3862"/>ut ne cogitarem quidem de virgine. <l eID="gen3862" level="1"/>

** Job 31:2

Quam enim partem haberet in me Deus desuper, <l eID="gen3863" level="1"/> <l level="1" sID="gen3864"/>et hæreditatem Omnipotens de excelsis ? <l eID="gen3864" level="1"/>

** Job 31:3

Numquid non perditio est iniquo, <l eID="gen3865" level="1"/> <l level="1" sID="gen3866"/>et alienatio operantibus injustitiam ? <l eID="gen3866" level="1"/>

** Job 31:4

Nonne ipse considerat vias meas, <l eID="gen3867" level="1"/> <l level="1" sID="gen3868"/>et cunctos gressus meos dinumerat ? <l eID="gen3868" level="1"/>

** Job 31:5

Si ambulavi in vanitate, <l eID="gen3869" level="1"/> <l level="1" sID="gen3870"/>et festinavit in dolo pes meus, <l eID="gen3870" level="1"/>

** Job 31:6

appendat me in statera justa, <l eID="gen3871" level="1"/> <l level="1" sID="gen3872"/>et sciat Deus simplicitatem meam. <l eID="gen3872" level="1"/>

** Job 31:7

Si declinavit gressus meus de via, <l eID="gen3873" level="1"/> <l level="1" sID="gen3874"/>et si secutum est oculos meos cor meum, <l eID="gen3874" level="1"/> <l level="1" sID="gen3875"/>et si manibus meis adhæsit macula, <l eID="gen3875" level="1"/>

** Job 31:8

seram, et alius comedat, <l eID="gen3876" level="1"/> <l level="1" sID="gen3877"/>et progenies mea eradicetur. <l eID="gen3877" level="1"/>

** Job 31:9

Si deceptum est cor meum super muliere, <l eID="gen3878" level="1"/> <l level="1" sID="gen3879"/>et si ad ostium amici mei insidiatus sum, <l eID="gen3879" level="1"/>

** Job 31:10

scortum alterius sit uxor mea, <l eID="gen3880" level="1"/> <l level="1" sID="gen3881"/>et super illam incurventur alii. <l eID="gen3881" level="1"/>

** Job 31:11

Hoc enim nefas est, <l eID="gen3882" level="1"/> <l level="1" sID="gen3883"/>et iniquitas maxima. <l eID="gen3883" level="1"/>

** Job 31:12

Ignis est usque ad perditionem devorans, <l eID="gen3884" level="1"/> <l level="1" sID="gen3885"/>et omnia eradicans genimina. <l eID="gen3885" level="1"/>

** Job 31:13

Si contempsi subire judicium cum servo meo et ancilla mea, <l eID="gen3886" level="1"/> <l level="1" sID="gen3887"/>cum disceptarent adversum me : <l eID="gen3887" level="1"/>

** Job 31:14

quid enim faciam cum surrexerit ad judicandum Deus ? <l eID="gen3888" level="1"/> <l level="1" sID="gen3889"/>et cum quæsierit, quid respondebo illi ? <l eID="gen3889" level="1"/>

** Job 31:15

Numquid non in utero fecit me, qui et illum operatus est, <l eID="gen3890" level="1"/> <l level="1" sID="gen3891"/>et formavit me in vulva unus ? <l eID="gen3891" level="1"/>

** Job 31:16

Si negavi quod volebant pauperibus, <l eID="gen3892" level="1"/> <l level="1" sID="gen3893"/>et oculos viduæ expectare feci ; <l eID="gen3893" level="1"/>

** Job 31:17

si comedi buccellam meam solus, <l eID="gen3894" level="1"/> <l level="1" sID="gen3895"/>et non comedit pupillus ex ea <l eID="gen3895" level="1"/>

** Job 31:18

(quia ab infantia mea crevit mecum miseratio, <l eID="gen3896" level="1"/> <l level="1" sID="gen3897"/>et de utero matris meæ egressa est mecum) ; <l eID="gen3897" level="1"/>

** Job 31:19

si despexi pereuntem, eo quod non habuerit indumentum, <l eID="gen3898" level="1"/> <l level="1" sID="gen3899"/>et absque operimento pauperem ; <l eID="gen3899" level="1"/>

** Job 31:20

si non benedixerunt mihi latera ejus, <l eID="gen3900" level="1"/> <l level="1" sID="gen3901"/>et de velleribus ovium mearum calefactus est ; <l eID="gen3901" level="1"/>

** Job 31:21

si levavi super pupillum manum meam, <l eID="gen3902" level="1"/> <l level="1" sID="gen3903"/>etiam cum viderem me in porta superiorem : <l eID="gen3903" level="1"/>

** Job 31:22

humerus meus a junctura sua cadat, <l eID="gen3904" level="1"/> <l level="1" sID="gen3905"/>et brachium meum cum suis ossibus confringatur. <l eID="gen3905" level="1"/>

** Job 31:23

Semper enim quasi tumentes super me fluctus timui Deum, <l eID="gen3906" level="1"/> <l level="1" sID="gen3907"/>et pondus ejus ferre non potui. <l eID="gen3907" level="1"/>

** Job 31:24

Si putavi aurum robur meum, <l eID="gen3908" level="1"/> <l level="1" sID="gen3909"/>et obrizo dixi : Fiducia mea ; <l eID="gen3909" level="1"/>

** Job 31:25

si lætatus sum super multis divitiis meis, <l eID="gen3910" level="1"/> <l level="1" sID="gen3911"/>et quia plurima reperit manus mea ; <l eID="gen3911" level="1"/>

** Job 31:26

si vidi solem cum fulgeret, <l eID="gen3912" level="1"/> <l level="1" sID="gen3913"/>et lunam incedentem clare, <l eID="gen3913" level="1"/>

** Job 31:27

et lætatum est in abscondito cor meum, <l eID="gen3914" level="1"/> <l level="1" sID="gen3915"/>et osculatus sum manum meam ore meo : <l eID="gen3915" level="1"/>

** Job 31:28

quæ est iniquitas maxima, <l eID="gen3916" level="1"/> <l level="1" sID="gen3917"/>et negatio contra Deum altissimum. <l eID="gen3917" level="1"/>

** Job 31:29

Si gavisus sum ad ruinam ejus qui me oderat, <l eID="gen3918" level="1"/> <l level="1" sID="gen3919"/>et exsultavi quod invenisset eum malum : <l eID="gen3919" level="1"/>

** Job 31:30

non enim dedi ad peccandum guttur meum, <l eID="gen3920" level="1"/> <l level="1" sID="gen3921"/>ut expeterem maledicens animam ejus. <l eID="gen3921" level="1"/>

** Job 31:31

Si non dixerunt viri tabernaculi mei : <l eID="gen3922" level="1"/> <l level="1" sID="gen3923"/>Quis det de carnibus ejus, ut saturemur ? <l eID="gen3923" level="1"/>

** Job 31:32

foris non mansit peregrinus : <l eID="gen3924" level="1"/> <l level="1" sID="gen3925"/>ostium meum viatori patuit. <l eID="gen3925" level="1"/>

** Job 31:33

Si abscondi quasi homo peccatum meum, <l eID="gen3926" level="1"/> <l level="1" sID="gen3927"/>et celavi in sinu meo iniquitatem meam ; <l eID="gen3927" level="1"/>

** Job 31:34

si expavi ad multitudinem nimiam, <l eID="gen3928" level="1"/> <l level="1" sID="gen3929"/>et despectio propinquorum terruit me : <l eID="gen3929" level="1"/> <l level="1" sID="gen3930"/>et non magis tacui, nec egressus sum ostium. <l eID="gen3930" level="1"/>

** Job 31:35

Quis mihi tribuat auditorem, <l eID="gen3931" level="1"/> <l level="1" sID="gen3932"/>ut desiderium meum audiat Omnipotens, <l eID="gen3932" level="1"/> <l level="1" sID="gen3933"/>et librum scribat ipse qui judicat, <l eID="gen3933" level="1"/>

** Job 31:36

ut in humero meo portem illum, <l eID="gen3934" level="1"/> <l level="1" sID="gen3935"/>et circumdem illum quasi coronam mihi ? <l eID="gen3935" level="1"/>

** Job 31:37

Per singulos gradus meos pronuntiabo illum, <l eID="gen3936" level="1"/> <l level="1" sID="gen3937"/>et quasi principi offeram eum. <l eID="gen3937" level="1"/>

** Job 31:38

Si adversum me terra mea clamat, <l eID="gen3938" level="1"/> <l level="1" sID="gen3939"/>et cum ipsa sulci ejus deflent : <l eID="gen3939" level="1"/>

** Job 31:39

si fructus ejus comedi absque pecunia, <l eID="gen3940" level="1"/> <l level="1" sID="gen3941"/>et animam agricolarum ejus afflixi : <l eID="gen3941" level="1"/>

** Job 31:40

pro frumento oriatur mihi tribulus, <l eID="gen3942" level="1"/> <l level="1" sID="gen3943"/>et pro hordeo spina. Finita sunt verba Job. <l eID="gen3943" level="1"/><lg eID="gen3747"/> <chapter eID="Job.31"/>

* Job 32

** Job 32:1

Omiserunt autem tres viri isti respondere Job, eo quod justus sibi videretur.

** Job 32:2

Et iratus indignatusque est Eliu filius Barachel Buzites, de cognatione Ram : iratus est autem adversum Job, eo quod justum se esse diceret coram Deo.

** Job 32:3

Porro adversum amicos ejus indignatus est, eo quod non invenissent responsionem rationabilem, sed tantummodo condemnassent Job.

** Job 32:4

Igitur Eliu expectavit Job loquentem, eo quod seniores essent qui loquebantur.

** Job 32:5

Cum autem vidisset quod tres respondere non potuissent, iratus est vehementer.

** Job 32:6

Respondensque Eliu filius Barachel Buzites, dixit : <div eID="gen3944" type="x-p"/> <lg sID="gen3945"/> <l level="1" sID="gen3946"/>Junior sum tempore, vos autem antiquiores : <l eID="gen3946" level="1"/> <l level="1" sID="gen3947"/>idcirco, demisso capite, <l eID="gen3947" level="1"/> <l level="1" sID="gen3948"/>veritus sum vobis indicare meam sententiam. <l eID="gen3948" level="1"/>

** Job 32:7

Sperabam enim quod ætas prolixior loqueretur, <l eID="gen3949" level="1"/> <l level="1" sID="gen3950"/>et annorum multitudo doceret sapientiam. <l eID="gen3950" level="1"/>

** Job 32:8

Sed, ut video, spiritus est in hominibus, <l eID="gen3951" level="1"/> <l level="1" sID="gen3952"/>et inspiratio Omnipotentis dat intelligentiam. <l eID="gen3952" level="1"/>

** Job 32:9

Non sunt longævi sapientes, <l eID="gen3953" level="1"/> <l level="1" sID="gen3954"/>nec senes intelligunt judicium. <l eID="gen3954" level="1"/>

** Job 32:10

Ideo dicam : Audite me : <l eID="gen3955" level="1"/> <l level="1" sID="gen3956"/>ostendam vobis etiam ego meam sapientiam. <l eID="gen3956" level="1"/>

** Job 32:11

Expectavi enim sermones vestros ; <l eID="gen3957" level="1"/> <l level="1" sID="gen3958"/>audivi prudentiam vestram, <l eID="gen3958" level="1"/> <l level="1" sID="gen3959"/>donec disceptaremini sermonibus ; <l eID="gen3959" level="1"/>

** Job 32:12

et donec putabam vos aliquid dicere, considerabam : <l eID="gen3960" level="1"/> <l level="1" sID="gen3961"/>sed, ut video, non est qui possit arguere Job, <l eID="gen3961" level="1"/> <l level="1" sID="gen3962"/>et respondere ex vobis sermonibus ejus. <l eID="gen3962" level="1"/>

** Job 32:13

Ne forte dicatis : Invenimus sapientiam : <l eID="gen3963" level="1"/> <l level="1" sID="gen3964"/>Deus projecit eum, non homo. <l eID="gen3964" level="1"/>

** Job 32:14

Nihil locutus est mihi : <l eID="gen3965" level="1"/> <l level="1" sID="gen3966"/>et ego non secundum sermones vestros respondebo illi. <l eID="gen3966" level="1"/>

** Job 32:15

Extimuerunt, nec responderunt ultra, <l eID="gen3967" level="1"/> <l level="1" sID="gen3968"/>abstuleruntque a se eloquia. <l eID="gen3968" level="1"/>

** Job 32:16

Quoniam igitur expectavi, et non sunt locuti : <l eID="gen3969" level="1"/> <l level="1" sID="gen3970"/>steterunt, nec ultra responderunt : <l eID="gen3970" level="1"/>

** Job 32:17

respondebo et ego partem meam, <l eID="gen3971" level="1"/> <l level="1" sID="gen3972"/>et ostendam scientiam meam. <l eID="gen3972" level="1"/>

** Job 32:18

Plenus sum enim sermonibus, <l eID="gen3973" level="1"/> <l level="1" sID="gen3974"/>et coarctat me spiritus uteri mei. <l eID="gen3974" level="1"/>

** Job 32:19

En venter meus quasi mustum absque spiraculo, <l eID="gen3975" level="1"/> <l level="1" sID="gen3976"/>quod lagunculas novas disrumpit. <l eID="gen3976" level="1"/>

** Job 32:20

Loquar, et respirabo paululum : <l eID="gen3977" level="1"/> <l level="1" sID="gen3978"/>aperiam labia mea, et respondebo. <l eID="gen3978" level="1"/>

** Job 32:21

Non accipiam personam viri, <l eID="gen3979" level="1"/> <l level="1" sID="gen3980"/>et Deum homini non æquabo. <l eID="gen3980" level="1"/>

** Job 32:22

Nescio enim quamdiu subsistam, <l eID="gen3981" level="1"/> <l level="1" sID="gen3982"/>et si post modicum tollat me factor meus.  <chapter eID="Job.32"/>

* Job 33

** Job 33:1

Audi igitur, Job, eloquia mea, <l eID="gen3983" level="1"/> <l level="1" sID="gen3984"/>et omnes sermones meos ausculta. <l eID="gen3984" level="1"/>

** Job 33:2

Ecce aperui os meum : <l eID="gen3985" level="1"/> <l level="1" sID="gen3986"/>loquatur lingua mea in faucibus meis. <l eID="gen3986" level="1"/>

** Job 33:3

Simplici corde meo sermones mei, <l eID="gen3987" level="1"/> <l level="1" sID="gen3988"/>et sententiam puram labia mea loquentur. <l eID="gen3988" level="1"/>

** Job 33:4

Spiritus Dei fecit me, <l eID="gen3989" level="1"/> <l level="1" sID="gen3990"/>et spiraculum Omnipotentis vivificavit me. <l eID="gen3990" level="1"/>

** Job 33:5

Si potes, responde mihi, <l eID="gen3991" level="1"/> <l level="1" sID="gen3992"/>et adversus faciem meam consiste. <l eID="gen3992" level="1"/>

** Job 33:6

Ecce, et me sicut et te fecit Deus, <l eID="gen3993" level="1"/> <l level="1" sID="gen3994"/>et de eodem luto ego quoque formatus sum. <l eID="gen3994" level="1"/>

** Job 33:7

Verumtamen miraculum meum non te terreat, <l eID="gen3995" level="1"/> <l level="1" sID="gen3996"/>et eloquentia mea non sit tibi gravis. <l eID="gen3996" level="1"/>

** Job 33:8

Dixisti ergo in auribus meis, <l eID="gen3997" level="1"/> <l level="1" sID="gen3998"/>et vocem verborum tuorum audivi : <l eID="gen3998" level="1"/>

** Job 33:9

Mundus sum ego, et absque delicto : <l eID="gen3999" level="1"/> <l level="1" sID="gen4000"/>immaculatus, et non est iniquitas in me. <l eID="gen4000" level="1"/>

** Job 33:10

Quia querelas in me reperit, <l eID="gen4001" level="1"/> <l level="1" sID="gen4002"/>ideo arbitratus est me inimicum sibi. <l eID="gen4002" level="1"/>

** Job 33:11

Posuit in nervo pedes meos ; <l eID="gen4003" level="1"/> <l level="1" sID="gen4004"/>custodivit omnes semitas meas. <l eID="gen4004" level="1"/>

** Job 33:12

Hoc est ergo in quo non es justificatus : <l eID="gen4005" level="1"/> <l level="1" sID="gen4006"/>respondebo tibi, quia major sit Deus homine. <l eID="gen4006" level="1"/>

** Job 33:13

Adversus eum contendis, <l eID="gen4007" level="1"/> <l level="1" sID="gen4008"/>quod non ad omnia verba responderit tibi ? <l eID="gen4008" level="1"/>

** Job 33:14

Semel loquitur Deus, <l eID="gen4009" level="1"/> <l level="1" sID="gen4010"/>et secundo idipsum non repetit. <l eID="gen4010" level="1"/>

** Job 33:15

Per somnium, in visione nocturna, <l eID="gen4011" level="1"/> <l level="1" sID="gen4012"/>quando irruit sopor super homines, <l eID="gen4012" level="1"/> <l level="1" sID="gen4013"/>et dormiunt in lectulo, <l eID="gen4013" level="1"/>

** Job 33:16

tunc aperit aures virorum, <l eID="gen4014" level="1"/> <l level="1" sID="gen4015"/>et erudiens eos instruit disciplina, <l eID="gen4015" level="1"/>

** Job 33:17

ut avertat hominem ab his quæ facit, <l eID="gen4016" level="1"/> <l level="1" sID="gen4017"/>et liberet eum de superbia, <l eID="gen4017" level="1"/>

** Job 33:18

eruens animam ejus a corruptione, <l eID="gen4018" level="1"/> <l level="1" sID="gen4019"/>et vitam illius ut non transeat in gladium. <l eID="gen4019" level="1"/>

** Job 33:19

Increpat quoque per dolorem in lectulo, <l eID="gen4020" level="1"/> <l level="1" sID="gen4021"/>et omnia ossa ejus marcescere facit. <l eID="gen4021" level="1"/>

** Job 33:20

Abominabilis ei fit in vita sua panis, <l eID="gen4022" level="1"/> <l level="1" sID="gen4023"/>et animæ illius cibus ante desiderabilis. <l eID="gen4023" level="1"/>

** Job 33:21

Tabescet caro ejus, <l eID="gen4024" level="1"/> <l level="1" sID="gen4025"/>et ossa, quæ tecta fuerant, nudabuntur. <l eID="gen4025" level="1"/>

** Job 33:22

Appropinquavit corruptioni anima ejus, <l eID="gen4026" level="1"/> <l level="1" sID="gen4027"/>et vita illius mortiferis. <l eID="gen4027" level="1"/>

** Job 33:23

Si fuerit pro eo angelus loquens, <l eID="gen4028" level="1"/> <l level="1" sID="gen4029"/>unus de millibus, ut annuntiet hominis æquitatem, <l eID="gen4029" level="1"/>

** Job 33:24

miserebitur ejus, et dicet : <l eID="gen4030" level="1"/> <l level="1" sID="gen4031"/>Libera eum, ut non descendat in corruptionem : <l eID="gen4031" level="1"/> <l level="1" sID="gen4032"/>inveni in quo ei propitier. <l eID="gen4032" level="1"/>

** Job 33:25

Consumpta est caro ejus a suppliciis : <l eID="gen4033" level="1"/> <l level="1" sID="gen4034"/>revertatur ad dies adolescentiæ suæ. <l eID="gen4034" level="1"/>

** Job 33:26

Deprecabitur Deum, et placabilis ei erit : <l eID="gen4035" level="1"/> <l level="1" sID="gen4036"/>et videbit faciem ejus in jubilo, <l eID="gen4036" level="1"/> <l level="1" sID="gen4037"/>et reddet homini justitiam suam. <l eID="gen4037" level="1"/>

** Job 33:27

Respiciet homines, et dicet : Peccavi, <l eID="gen4038" level="1"/> <l level="1" sID="gen4039"/>et vere deliqui, et ut eram dignus, non recepi. <l eID="gen4039" level="1"/>

** Job 33:28

Liberavit animam suam, ne pergeret in interitum, <l eID="gen4040" level="1"/> <l level="1" sID="gen4041"/>sed vivens lucem videret. <l eID="gen4041" level="1"/>

** Job 33:29

Ecce hæc omnia operatur Deus <l eID="gen4042" level="1"/> <l level="1" sID="gen4043"/>tribus vicibus per singulos, <l eID="gen4043" level="1"/>

** Job 33:30

ut revocet animas eorum a corruptione, <l eID="gen4044" level="1"/> <l level="1" sID="gen4045"/>et illuminet luce viventium. <l eID="gen4045" level="1"/>

** Job 33:31

Attende, Job, et audi me : <l eID="gen4046" level="1"/> <l level="1" sID="gen4047"/>et tace, dum ego loquor. <l eID="gen4047" level="1"/>

** Job 33:32

Si autem habes quod loquaris, responde mihi : <l eID="gen4048" level="1"/> <l level="1" sID="gen4049"/>loquere, volo enim te apparere justum. <l eID="gen4049" level="1"/>

** Job 33:33

Quod si non habes, audi me : <l eID="gen4050" level="1"/> <l level="1" sID="gen4051"/>tace, et docebo te sapientiam. <l eID="gen4051" level="1"/><lg eID="gen3945"/> <chapter eID="Job.33"/>

* Job 34

** Job 34:1

Pronuntians itaque Eliu, etiam hæc locutus est :  <div eID="gen4052" type="x-p"/>

** Job 34:2

Audite, sapientes, verba mea : <l eID="gen4054" level="1"/> <l level="1" sID="gen4055"/>et eruditi, auscultate me. <l eID="gen4055" level="1"/>

** Job 34:3

Auris enim verba probat, <l eID="gen4056" level="1"/> <l level="1" sID="gen4057"/>et guttur escas gustu dijudicat. <l eID="gen4057" level="1"/>

** Job 34:4

Judicium eligamus nobis, <l eID="gen4058" level="1"/> <l level="1" sID="gen4059"/>et inter nos videamus quid sit melius. <l eID="gen4059" level="1"/>

** Job 34:5

Quia dixit Job : Justus sum, <l eID="gen4060" level="1"/> <l level="1" sID="gen4061"/>et Deus subvertit judicium meum. <l eID="gen4061" level="1"/>

** Job 34:6

In judicando enim me mendacium est : <l eID="gen4062" level="1"/> <l level="1" sID="gen4063"/>violenta sagitta mea absque ullo peccato. <l eID="gen4063" level="1"/>

** Job 34:7

Quis est vir ut est Job, <l eID="gen4064" level="1"/> <l level="1" sID="gen4065"/>qui bibit subsannationem quasi aquam : <l eID="gen4065" level="1"/>

** Job 34:8

qui graditur cum operantibus iniquitatem, <l eID="gen4066" level="1"/> <l level="1" sID="gen4067"/>et ambulat cum viris impiis ? <l eID="gen4067" level="1"/>

** Job 34:9

Dixit enim : Non placebit vir Deo, <l eID="gen4068" level="1"/> <l level="1" sID="gen4069"/>etiam si cucurrerit cum eo. <l eID="gen4069" level="1"/>

** Job 34:10

Ideo, viri cordati, audite me : <l eID="gen4070" level="1"/> <l level="1" sID="gen4071"/>absit a Deo impietas, <l eID="gen4071" level="1"/> <l level="1" sID="gen4072"/>et ab Omnipotente iniquitas. <l eID="gen4072" level="1"/>

** Job 34:11

Opus enim hominis reddet ei, <l eID="gen4073" level="1"/> <l level="1" sID="gen4074"/>et juxta vias singulorum restituet eis. <l eID="gen4074" level="1"/>

** Job 34:12

Vere enim Deus non condemnabit frustra, <l eID="gen4075" level="1"/> <l level="1" sID="gen4076"/>nec Omnipotens subvertet judicium. <l eID="gen4076" level="1"/>

** Job 34:13

Quem constituit alium super terram ? <l eID="gen4077" level="1"/> <l level="1" sID="gen4078"/>aut quem posuit super orbem quem fabricatus est ? <l eID="gen4078" level="1"/>

** Job 34:14

Si direxerit ad eum cor suum, <l eID="gen4079" level="1"/> <l level="1" sID="gen4080"/>spiritum illius et flatum ad se trahet. <l eID="gen4080" level="1"/>

** Job 34:15

Deficiet omnis caro simul, <l eID="gen4081" level="1"/> <l level="1" sID="gen4082"/>et homo in cinerem revertetur. <l eID="gen4082" level="1"/>

** Job 34:16

Si habes ergo intellectum, audi quod dicitur, <l eID="gen4083" level="1"/> <l level="1" sID="gen4084"/>et ausculta vocem eloquii mei : <l eID="gen4084" level="1"/>

** Job 34:17

numquid qui non amat judicium sanari potest ? <l eID="gen4085" level="1"/> <l level="1" sID="gen4086"/>et quomodo tu eum qui justus est in tantum condemnas ? <l eID="gen4086" level="1"/>

** Job 34:18

Qui dicit regi : Apostata ; <l eID="gen4087" level="1"/> <l level="1" sID="gen4088"/>qui vocat duces impios ; <l eID="gen4088" level="1"/>

** Job 34:19

qui non accipit personas principum, <l eID="gen4089" level="1"/> <l level="1" sID="gen4090"/>nec cognovit tyrannum cum disceptaret contra pauperem : <l eID="gen4090" level="1"/> <l level="1" sID="gen4091"/>opus enim manuum ejus sunt universi. <l eID="gen4091" level="1"/>

** Job 34:20

Subito morientur, et in media nocte turbabuntur populi : <l eID="gen4092" level="1"/> <l level="1" sID="gen4093"/>et pertransibunt, et auferent violentum absque manu. <l eID="gen4093" level="1"/>

** Job 34:21

Oculi enim ejus super vias hominum, <l eID="gen4094" level="1"/> <l level="1" sID="gen4095"/>et omnes gressus eorum considerat. <l eID="gen4095" level="1"/>

** Job 34:22

Non sunt tenebræ, et non est umbra mortis, <l eID="gen4096" level="1"/> <l level="1" sID="gen4097"/>ut abscondantur ibi qui operantur iniquitatem, <l eID="gen4097" level="1"/>

** Job 34:23

neque enim ultra in hominis potestate est, <l eID="gen4098" level="1"/> <l level="1" sID="gen4099"/>ut veniat ad Deum in judicium. <l eID="gen4099" level="1"/>

** Job 34:24

Conteret multos, et innumerabiles, <l eID="gen4100" level="1"/> <l level="1" sID="gen4101"/>et stare faciet alios pro eis. <l eID="gen4101" level="1"/>

** Job 34:25

Novit enim opera eorum, <l eID="gen4102" level="1"/> <l level="1" sID="gen4103"/>et idcirco inducet noctem, et conterentur. <l eID="gen4103" level="1"/>

** Job 34:26

Quasi impios percussit eos <l eID="gen4104" level="1"/> <l level="1" sID="gen4105"/>in loco videntium : <l eID="gen4105" level="1"/>

** Job 34:27

qui quasi de industria recesserunt ab eo, <l eID="gen4106" level="1"/> <l level="1" sID="gen4107"/>et omnes vias ejus intelligere noluerunt : <l eID="gen4107" level="1"/>

** Job 34:28

ut pervenire facerent ad eum clamorem egeni, <l eID="gen4108" level="1"/> <l level="1" sID="gen4109"/>et audiret vocem pauperum. <l eID="gen4109" level="1"/>

** Job 34:29

Ipso enim concedente pacem, quis est qui condemnet ? <l eID="gen4110" level="1"/> <l level="1" sID="gen4111"/>ex quo absconderit vultum, quis est qui contempletur eum, <l eID="gen4111" level="1"/> <l level="1" sID="gen4112"/>et super gentes, et super omnes homines ? <l eID="gen4112" level="1"/>

** Job 34:30

Qui regnare facit hominem hypocritam <l eID="gen4113" level="1"/> <l level="1" sID="gen4114"/>propter peccata populi. <l eID="gen4114" level="1"/>

** Job 34:31

Quia ergo ego locutus sum ad Deum, <l eID="gen4115" level="1"/> <l level="1" sID="gen4116"/>te quoque non prohibebo. <l eID="gen4116" level="1"/>

** Job 34:32

Si erravi, tu doce me ; <l eID="gen4117" level="1"/> <l level="1" sID="gen4118"/>si iniquitatem locutus sum, ultra non addam. <l eID="gen4118" level="1"/>

** Job 34:33

Numquid a te Deus expetit eam, quia displicuit tibi ? <l eID="gen4119" level="1"/> <l level="1" sID="gen4120"/>tu enim cœpisti loqui, et non ego : <l eID="gen4120" level="1"/> <l level="1" sID="gen4121"/>quod si quid nosti melius, loquere. <l eID="gen4121" level="1"/>

** Job 34:34

Viri intelligentes loquantur mihi, <l eID="gen4122" level="1"/> <l level="1" sID="gen4123"/>et vir sapiens audiat me. <l eID="gen4123" level="1"/>

** Job 34:35

Job autem stulte locutus est, <l eID="gen4124" level="1"/> <l level="1" sID="gen4125"/>et verba illius non sonant disciplinam. <l eID="gen4125" level="1"/>

** Job 34:36

Pater mi, probetur Job usque ad finem : <l eID="gen4126" level="1"/> <l level="1" sID="gen4127"/>ne desinas ab homine iniquitatis : <l eID="gen4127" level="1"/>

** Job 34:37

quia addit super peccata sua blasphemiam, <l eID="gen4128" level="1"/> <l level="1" sID="gen4129"/>inter nos interim constringatur : <l eID="gen4129" level="1"/> <l level="1" sID="gen4130"/>et tunc ad judicium provocet sermonibus suis Deum. <l eID="gen4130" level="1"/><lg eID="gen4053"/> <chapter eID="Job.34"/>

* Job 35

** Job 35:1

Igitur Eliu hæc rursum locutus est :  <div eID="gen4131" type="x-p"/>

** Job 35:2

Numquid æqua tibi videtur tua cogitatio, <l eID="gen4133" level="1"/> <l level="1" sID="gen4134"/>ut diceres : Justior sum Deo ? <l eID="gen4134" level="1"/>

** Job 35:3

Dixisti enim : Non tibi placet quod rectum est : <l eID="gen4135" level="1"/> <l level="1" sID="gen4136"/>vel quid tibi proderit, si ego peccavero ? <l eID="gen4136" level="1"/>

** Job 35:4

Itaque ego respondebo sermonibus tuis, <l eID="gen4137" level="1"/> <l level="1" sID="gen4138"/>et amicis tuis tecum. <l eID="gen4138" level="1"/>

** Job 35:5

Suspice cælum, et intuere : <l eID="gen4139" level="1"/> <l level="1" sID="gen4140"/>et contemplare æthera quod altior te sit. <l eID="gen4140" level="1"/>

** Job 35:6

Si peccaveris, quid ei nocebis ? <l eID="gen4141" level="1"/> <l level="1" sID="gen4142"/>et si multiplicatæ fuerint iniquitates tuæ, quid facies contra eum ? <l eID="gen4142" level="1"/>

** Job 35:7

Porro si juste egeris, quid donabis ei ? <l eID="gen4143" level="1"/> <l level="1" sID="gen4144"/>aut quid de manu tua accipiet ? <l eID="gen4144" level="1"/>

** Job 35:8

Homini qui similis tui est, nocebit impietas tua : <l eID="gen4145" level="1"/> <l level="1" sID="gen4146"/>et filium hominis adjuvabit justitia tua. <l eID="gen4146" level="1"/>

** Job 35:9

Propter multitudinem calumniatorum clamabunt, <l eID="gen4147" level="1"/> <l level="1" sID="gen4148"/>et ejulabunt propter vim brachii tyrannorum. <l eID="gen4148" level="1"/>

** Job 35:10

Et non dixit : Ubi est Deus qui fecit me, <l eID="gen4149" level="1"/> <l level="1" sID="gen4150"/>qui dedit carmina in nocte ; <l eID="gen4150" level="1"/>

** Job 35:11

qui docet nos super jumenta terræ, <l eID="gen4151" level="1"/> <l level="1" sID="gen4152"/>et super volucres cæli erudit nos ? <l eID="gen4152" level="1"/>

** Job 35:12

Ibi clamabunt, et non exaudiet, <l eID="gen4153" level="1"/> <l level="1" sID="gen4154"/>propter superbiam malorum. <l eID="gen4154" level="1"/>

** Job 35:13

Non ergo frustra audiet Deus, <l eID="gen4155" level="1"/> <l level="1" sID="gen4156"/>et Omnipotens causas singulorum intuebitur. <l eID="gen4156" level="1"/>

** Job 35:14

Etiam cum dixeris : Non considerat : <l eID="gen4157" level="1"/> <l level="1" sID="gen4158"/>judicare coram illo, et expecta eum. <l eID="gen4158" level="1"/>

** Job 35:15

Nunc enim non infert furorem suum, <l eID="gen4159" level="1"/> <l level="1" sID="gen4160"/>nec ulciscitur scelus valde. <l eID="gen4160" level="1"/>

** Job 35:16

Ergo Job frustra aperit os suum, <l eID="gen4161" level="1"/> <l level="1" sID="gen4162"/>et absque scientia verba multiplicat. <l eID="gen4162" level="1"/><lg eID="gen4132"/> <chapter eID="Job.35"/>

* Job 36

** Job 36:1

Addens quoque Eliu, hæc locutus est :  <div eID="gen4163" type="x-p"/>

** Job 36:2

Sustine me paululum, et indicabo tibi : <l eID="gen4165" level="1"/> <l level="1" sID="gen4166"/>adhuc enim habeo quod pro Deo loquar. <l eID="gen4166" level="1"/>

** Job 36:3

Repetam scientiam meam a principio, <l eID="gen4167" level="1"/> <l level="1" sID="gen4168"/>et operatorem meum probabo justum. <l eID="gen4168" level="1"/>

** Job 36:4

Vere enim absque mendacio sermones mei, <l eID="gen4169" level="1"/> <l level="1" sID="gen4170"/>et perfecta scientia probabitur tibi. <l eID="gen4170" level="1"/>

** Job 36:5

Deus potentes non abjicit, <l eID="gen4171" level="1"/> <l level="1" sID="gen4172"/>cum et ipse sit potens : <l eID="gen4172" level="1"/>

** Job 36:6

sed non salvat impios, <l eID="gen4173" level="1"/> <l level="1" sID="gen4174"/>et judicium pauperibus tribuit. <l eID="gen4174" level="1"/>

** Job 36:7

Non auferet a justo oculos suos : <l eID="gen4175" level="1"/> <l level="1" sID="gen4176"/>et reges in solio collocat in perpetuum, <l eID="gen4176" level="1"/> <l level="1" sID="gen4177"/>et illi eriguntur. <l eID="gen4177" level="1"/>

** Job 36:8

Et si fuerint in catenis, <l eID="gen4178" level="1"/> <l level="1" sID="gen4179"/>et vinciantur funibus paupertatis, <l eID="gen4179" level="1"/>

** Job 36:9

indicabit eis opera eorum, <l eID="gen4180" level="1"/> <l level="1" sID="gen4181"/>et scelera eorum, quia violenti fuerunt. <l eID="gen4181" level="1"/>

** Job 36:10

Revelabit quoque aurem eorum, ut corripiat : <l eID="gen4182" level="1"/> <l level="1" sID="gen4183"/>et loquetur, ut revertantur ab iniquitate. <l eID="gen4183" level="1"/>

** Job 36:11

Si audierint et observaverint, complebunt dies suos in bono, <l eID="gen4184" level="1"/> <l level="1" sID="gen4185"/>et annos suos in gloria : <l eID="gen4185" level="1"/>

** Job 36:12

si autem non audierint, <l eID="gen4186" level="1"/> <l level="1" sID="gen4187"/>transibunt per gladium, <l eID="gen4187" level="1"/> <l level="1" sID="gen4188"/>et consumentur in stultitia. <l eID="gen4188" level="1"/>

** Job 36:13

Simulatores et callidi provocant iram Dei, <l eID="gen4189" level="1"/> <l level="1" sID="gen4190"/>neque clamabunt cum vincti fuerint. <l eID="gen4190" level="1"/>

** Job 36:14

Morietur in tempestate anima eorum, <l eID="gen4191" level="1"/> <l level="1" sID="gen4192"/>et vita eorum inter effeminatos. <l eID="gen4192" level="1"/>

** Job 36:15

Eripiet de angustia sua pauperem, <l eID="gen4193" level="1"/> <l level="1" sID="gen4194"/>et revelabit in tribulatione aurem ejus. <l eID="gen4194" level="1"/>

** Job 36:16

Igitur salvabit te de ore angusto latissime, <l eID="gen4195" level="1"/> <l level="1" sID="gen4196"/>et non habente fundamentum subter se : <l eID="gen4196" level="1"/> <l level="1" sID="gen4197"/>requies autem mensæ tuæ erit plena pinguedine. <l eID="gen4197" level="1"/>

** Job 36:17

Causa tua quasi impii judicata est : <l eID="gen4198" level="1"/> <l level="1" sID="gen4199"/>causam judiciumque recipies. <l eID="gen4199" level="1"/>

** Job 36:18

Non te ergo superet ira ut aliquem opprimas : <l eID="gen4200" level="1"/> <l level="1" sID="gen4201"/>nec multitudo donorum inclinet te. <l eID="gen4201" level="1"/>

** Job 36:19

Depone magnitudinem tuam absque tribulatione, <l eID="gen4202" level="1"/> <l level="1" sID="gen4203"/>et omnes robustos fortitudine. <l eID="gen4203" level="1"/>

** Job 36:20

Ne protrahas noctem, <l eID="gen4204" level="1"/> <l level="1" sID="gen4205"/>ut ascendant populi pro eis. <l eID="gen4205" level="1"/>

** Job 36:21

Cave ne declines ad iniquitatem : <l eID="gen4206" level="1"/> <l level="1" sID="gen4207"/>hanc enim cœpisti sequi post miseriam. <l eID="gen4207" level="1"/>

** Job 36:22

Ecce Deus excelsus in fortitudine sua, <l eID="gen4208" level="1"/> <l level="1" sID="gen4209"/>et nullus ei similis in legislatoribus. <l eID="gen4209" level="1"/>

** Job 36:23

Quis poterit scrutari vias ejus ? <l eID="gen4210" level="1"/> <l level="1" sID="gen4211"/>aut quis potest ei dicere : Operatus es iniquitatem ? <l eID="gen4211" level="1"/>

** Job 36:24

Memento quod ignores opus ejus, <l eID="gen4212" level="1"/> <l level="1" sID="gen4213"/>de quo cecinerunt viri. <l eID="gen4213" level="1"/>

** Job 36:25

Omnes homines vident eum : <l eID="gen4214" level="1"/> <l level="1" sID="gen4215"/>unusquisque intuetur procul. <l eID="gen4215" level="1"/>

** Job 36:26

Ecce Deus magnus vincens scientiam nostram : <l eID="gen4216" level="1"/> <l level="1" sID="gen4217"/>numerus annorum ejus inæstimabilis. <l eID="gen4217" level="1"/>

** Job 36:27

Qui aufert stillas pluviæ, <l eID="gen4218" level="1"/> <l level="1" sID="gen4219"/>et effundit imbres ad instar gurgitum, <l eID="gen4219" level="1"/>

** Job 36:28

qui de nubibus fluunt <l eID="gen4220" level="1"/> <l level="1" sID="gen4221"/>quæ prætexunt cuncta desuper. <l eID="gen4221" level="1"/>

** Job 36:29

Si voluerit extendere nubes quasi tentorium suum, <l eID="gen4222" level="1"/>

** Job 36:30

et fulgurare lumine suo desuper, <l eID="gen4223" level="1"/> <l level="1" sID="gen4224"/>cardines quoque maris operiet. <l eID="gen4224" level="1"/>

** Job 36:31

Per hæc enim judicat populos, <l eID="gen4225" level="1"/> <l level="1" sID="gen4226"/>et dat escas multis mortalibus. <l eID="gen4226" level="1"/>

** Job 36:32

In manibus abscondit lucem, <l eID="gen4227" level="1"/> <l level="1" sID="gen4228"/>et præcepit ei ut rursus adveniat. <l eID="gen4228" level="1"/>

** Job 36:33

Annuntiat de ea amico suo, quod possessio ejus sit, <l eID="gen4229" level="1"/> <l level="1" sID="gen4230"/>et ad eam possit ascendere.  <chapter eID="Job.36"/>

* Job 37

** Job 37:1

Super hoc expavit cor meum, <l eID="gen4231" level="1"/> <l level="1" sID="gen4232"/>et emotum est de loco suo. <l eID="gen4232" level="1"/>

** Job 37:2

Audite auditionem in terrore vocis ejus, <l eID="gen4233" level="1"/> <l level="1" sID="gen4234"/>et sonum de ore illius procedentem. <l eID="gen4234" level="1"/>

** Job 37:3

Subter omnes cælos ipse considerat, <l eID="gen4235" level="1"/> <l level="1" sID="gen4236"/>et lumen illius super terminos terræ. <l eID="gen4236" level="1"/>

** Job 37:4

Post eum rugiet sonitus ; <l eID="gen4237" level="1"/> <l level="1" sID="gen4238"/>tonabit voce magnitudinis suæ : <l eID="gen4238" level="1"/> <l level="1" sID="gen4239"/>et non investigabitur, cum audita fuerit vox ejus. <l eID="gen4239" level="1"/>

** Job 37:5

Tonabit Deus in voce sua mirabiliter, <l eID="gen4240" level="1"/> <l level="1" sID="gen4241"/>qui facit magna et inscrutabilia ; <l eID="gen4241" level="1"/>

** Job 37:6

qui præcipit nivi ut descendat in terram, <l eID="gen4242" level="1"/> <l level="1" sID="gen4243"/>et hiemis pluviis, et imbri fortitudinis suæ ; <l eID="gen4243" level="1"/>

** Job 37:7

qui in manu omnium hominum signat, <l eID="gen4244" level="1"/> <l level="1" sID="gen4245"/>ut noverint singuli opera sua. <l eID="gen4245" level="1"/>

** Job 37:8

Ingredietur bestia latibulum, <l eID="gen4246" level="1"/> <l level="1" sID="gen4247"/>et in antro suo morabitur. <l eID="gen4247" level="1"/>

** Job 37:9

Ab interioribus egredietur tempestas, <l eID="gen4248" level="1"/> <l level="1" sID="gen4249"/>et ab Arcturo frigus. <l eID="gen4249" level="1"/>

** Job 37:10

Flante Deo, concrescit gelu, <l eID="gen4250" level="1"/> <l level="1" sID="gen4251"/>et rursum latissimæ funduntur aquæ. <l eID="gen4251" level="1"/>

** Job 37:11

Frumentum desiderat nubes, <l eID="gen4252" level="1"/> <l level="1" sID="gen4253"/>et nubes spargunt lumen suum. <l eID="gen4253" level="1"/>

** Job 37:12

Quæ lustrant per circuitum, <l eID="gen4254" level="1"/> <l level="1" sID="gen4255"/>quocumque eas voluntas gubernantis duxerit, <l eID="gen4255" level="1"/> <l level="1" sID="gen4256"/>ad omne quod præceperit illis super faciem orbis terrarum : <l eID="gen4256" level="1"/>

** Job 37:13

sive in una tribu, sive in terra sua, <l eID="gen4257" level="1"/> <l level="1" sID="gen4258"/>sive in quocumque loco misericordiæ suæ <l eID="gen4258" level="1"/> <l level="1" sID="gen4259"/>eas jusserit inveniri. <l eID="gen4259" level="1"/>

** Job 37:14

Ausculta hæc, Job : <l eID="gen4260" level="1"/> <l level="1" sID="gen4261"/>sta, et considera mirabilia Dei. <l eID="gen4261" level="1"/>

** Job 37:15

Numquid scis quando præceperit Deus pluviis, <l eID="gen4262" level="1"/> <l level="1" sID="gen4263"/>ut ostenderent lucem nubium ejus ? <l eID="gen4263" level="1"/>

** Job 37:16

Numquid nosti semitas nubium magnas, <l eID="gen4264" level="1"/> <l level="1" sID="gen4265"/>et perfectas scientias ? <l eID="gen4265" level="1"/>

** Job 37:17

Nonne vestimenta tua calida sunt, <l eID="gen4266" level="1"/> <l level="1" sID="gen4267"/>cum perflata fuerit terra austro ? <l eID="gen4267" level="1"/>

** Job 37:18

Tu forsitan cum eo fabricatus es cælos, <l eID="gen4268" level="1"/> <l level="1" sID="gen4269"/>qui solidissimi quasi ære fusi sunt. <l eID="gen4269" level="1"/>

** Job 37:19

Ostende nobis quid dicamus illi : <l eID="gen4270" level="1"/> <l level="1" sID="gen4271"/>nos quippe involvimur tenebris. <l eID="gen4271" level="1"/>

** Job 37:20

Quis narrabit ei quæ loquor ? <l eID="gen4272" level="1"/> <l level="1" sID="gen4273"/>etiam si locutus fuerit homo, devorabitur. <l eID="gen4273" level="1"/>

** Job 37:21

At nunc non vident lucem : <l eID="gen4274" level="1"/> <l level="1" sID="gen4275"/>subito aër cogetur in nubes, <l eID="gen4275" level="1"/> <l level="1" sID="gen4276"/>et ventus transiens fugabit eas. <l eID="gen4276" level="1"/>

** Job 37:22

Ab aquilone aurum venit, <l eID="gen4277" level="1"/> <l level="1" sID="gen4278"/>et ad Deum formidolosa laudatio. <l eID="gen4278" level="1"/>

** Job 37:23

Digne eum invenire non possumus : <l eID="gen4279" level="1"/> <l level="1" sID="gen4280"/>magnus fortitudine, et judicio, et justitia : <l eID="gen4280" level="1"/> <l level="1" sID="gen4281"/>et enarrari non potest. <l eID="gen4281" level="1"/>

** Job 37:24

Ideo timebunt eum viri, <l eID="gen4282" level="1"/> <l level="1" sID="gen4283"/>et non audebunt contemplari omnes qui sibi videntur esse sapientes. <l eID="gen4283" level="1"/><lg eID="gen4164"/> <chapter eID="Job.37"/>

* Job 38

** Job 38:1

Respondens autem Dominus Job de turbine, dixit :  <div eID="gen4284" type="x-p"/>

** Job 38:2

Quis est iste involvens sententias <l eID="gen4286" level="1"/> <l level="1" sID="gen4287"/>sermonibus imperitis ? <l eID="gen4287" level="1"/>

** Job 38:3

Accinge sicut vir lumbos tuos : <l eID="gen4288" level="1"/> <l level="1" sID="gen4289"/>interrogabo te, et responde mihi. <l eID="gen4289" level="1"/>

** Job 38:4

Ubi eras quando ponebam fundamenta terræ ? <l eID="gen4290" level="1"/> <l level="1" sID="gen4291"/>indica mihi, si habes intelligentiam. <l eID="gen4291" level="1"/>

** Job 38:5

Quis posuit mensuras ejus, si nosti ? <l eID="gen4292" level="1"/> <l level="1" sID="gen4293"/>vel quis tetendit super eam lineam ? <l eID="gen4293" level="1"/>

** Job 38:6

Super quo bases illius solidatæ sunt ? <l eID="gen4294" level="1"/> <l level="1" sID="gen4295"/>aut quis demisit lapidem angularem ejus, <l eID="gen4295" level="1"/>

** Job 38:7

cum me laudarent simul astra matutina, <l eID="gen4296" level="1"/> <l level="1" sID="gen4297"/>et jubilarent omnes filii Dei ? <l eID="gen4297" level="1"/>

** Job 38:8

Quis conclusit ostiis mare, <l eID="gen4298" level="1"/> <l level="1" sID="gen4299"/>quando erumpebat quasi de vulva procedens ; <l eID="gen4299" level="1"/>

** Job 38:9

cum ponerem nubem vestimentum ejus, <l eID="gen4300" level="1"/> <l level="1" sID="gen4301"/>et caligine illud quasi pannis infantiæ obvolverem ? <l eID="gen4301" level="1"/>

** Job 38:10

Circumdedi illud terminis meis, <l eID="gen4302" level="1"/> <l level="1" sID="gen4303"/>et posui vectem et ostia, <l eID="gen4303" level="1"/>

** Job 38:11

et dixi : Usque huc venies, et non procedes amplius, <l eID="gen4304" level="1"/> <l level="1" sID="gen4305"/>et hic confringes tumentes fluctus tuos. <l eID="gen4305" level="1"/>

** Job 38:12

Numquid post ortum tuum præcepisti diluculo, <l eID="gen4306" level="1"/> <l level="1" sID="gen4307"/>et ostendisti auroræ locum suum ? <l eID="gen4307" level="1"/>

** Job 38:13

Et tenuisti concutiens extrema terræ, <l eID="gen4308" level="1"/> <l level="1" sID="gen4309"/>et excussisti impios ex ea ? <l eID="gen4309" level="1"/>

** Job 38:14

Restituetur ut lutum signaculum, <l eID="gen4310" level="1"/> <l level="1" sID="gen4311"/>et stabit sicut vestimentum : <l eID="gen4311" level="1"/>

** Job 38:15

auferetur ab impiis lux sua, <l eID="gen4312" level="1"/> <l level="1" sID="gen4313"/>et brachium excelsum confringetur. <l eID="gen4313" level="1"/>

** Job 38:16

Numquid ingressus es profunda maris, <l eID="gen4314" level="1"/> <l level="1" sID="gen4315"/>et in novissimis abyssi deambulasti ? <l eID="gen4315" level="1"/>

** Job 38:17

Numquid apertæ sunt tibi portæ mortis, <l eID="gen4316" level="1"/> <l level="1" sID="gen4317"/>et ostia tenebrosa vidisti ? <l eID="gen4317" level="1"/>

** Job 38:18

Numquid considerasti latitudinem terræ ? <l eID="gen4318" level="1"/> <l level="1" sID="gen4319"/>indica mihi, si nosti, omnia : <l eID="gen4319" level="1"/>

** Job 38:19

in qua via lux habitet, <l eID="gen4320" level="1"/> <l level="1" sID="gen4321"/>et tenebrarum quis locus sit : <l eID="gen4321" level="1"/>

** Job 38:20

ut ducas unumquodque ad terminos suos, <l eID="gen4322" level="1"/> <l level="1" sID="gen4323"/>et intelligas semitas domus ejus. <l eID="gen4323" level="1"/>

** Job 38:21

Sciebas tunc quod nasciturus esses, <l eID="gen4324" level="1"/> <l level="1" sID="gen4325"/>et numerum dierum tuorum noveras ? <l eID="gen4325" level="1"/>

** Job 38:22

Numquid ingressus es thesauros nivis, <l eID="gen4326" level="1"/> <l level="1" sID="gen4327"/>aut thesauros grandinis aspexisti, <l eID="gen4327" level="1"/>

** Job 38:23

quæ præparavi in tempus hostis, <l eID="gen4328" level="1"/> <l level="1" sID="gen4329"/>in diem pugnæ et belli ? <l eID="gen4329" level="1"/>

** Job 38:24

Per quam viam spargitur lux, <l eID="gen4330" level="1"/> <l level="1" sID="gen4331"/>dividitur æstus super terram ? <l eID="gen4331" level="1"/>

** Job 38:25

Quis dedit vehementissimo imbri cursum, <l eID="gen4332" level="1"/> <l level="1" sID="gen4333"/>et viam sonantis tonitrui, <l eID="gen4333" level="1"/>

** Job 38:26

ut plueret super terram absque homine in deserto, <l eID="gen4334" level="1"/> <l level="1" sID="gen4335"/>ubi nullus mortalium commoratur ; <l eID="gen4335" level="1"/>

** Job 38:27

ut impleret inviam et desolatam, <l eID="gen4336" level="1"/> <l level="1" sID="gen4337"/>et produceret herbas virentes ? <l eID="gen4337" level="1"/>

** Job 38:28

Quis est pluviæ pater ? <l eID="gen4338" level="1"/> <l level="1" sID="gen4339"/>vel quis genuit stillas roris ? <l eID="gen4339" level="1"/>

** Job 38:29

De cujus utero egressa est glacies ? <l eID="gen4340" level="1"/> <l level="1" sID="gen4341"/>et gelu de cælo quis genuit ? <l eID="gen4341" level="1"/>

** Job 38:30

In similitudinem lapidis aquæ durantur, <l eID="gen4342" level="1"/> <l level="1" sID="gen4343"/>et superficies abyssi constringitur. <l eID="gen4343" level="1"/>

** Job 38:31

Numquid conjungere valebis micantes stellas Pleiadas, <l eID="gen4344" level="1"/> <l level="1" sID="gen4345"/>aut gyrum Arcturi poteris dissipare ? <l eID="gen4345" level="1"/>

** Job 38:32

Numquid producis luciferum in tempore suo, <l eID="gen4346" level="1"/> <l level="1" sID="gen4347"/>et vesperum super filios terræ consurgere facis ? <l eID="gen4347" level="1"/>

** Job 38:33

Numquid nosti ordinem cæli, <l eID="gen4348" level="1"/> <l level="1" sID="gen4349"/>et pones rationem ejus in terra ? <l eID="gen4349" level="1"/>

** Job 38:34

Numquid elevabis in nebula vocem tuam, <l eID="gen4350" level="1"/> <l level="1" sID="gen4351"/>et impetus aquarum operiet te ? <l eID="gen4351" level="1"/>

** Job 38:35

Numquid mittes fulgura, et ibunt, <l eID="gen4352" level="1"/> <l level="1" sID="gen4353"/>et revertentia dicent tibi : Adsumus ? <l eID="gen4353" level="1"/>

** Job 38:36

Quis posuit in visceribus hominis sapientiam ? <l eID="gen4354" level="1"/> <l level="1" sID="gen4355"/>vel quis dedit gallo intelligentiam ? <l eID="gen4355" level="1"/>

** Job 38:37

Quis enarrabit cælorum rationem ? <l eID="gen4356" level="1"/> <l level="1" sID="gen4357"/>et concentum cæli quis dormire faciet ? <l eID="gen4357" level="1"/>

** Job 38:38

Quando fundebatur pulvis in terra, <l eID="gen4358" level="1"/> <l level="1" sID="gen4359"/>et glebæ compingebantur ? <l eID="gen4359" level="1"/>

** Job 38:39

Numquid capies leænæ prædam, <l eID="gen4360" level="1"/> <l level="1" sID="gen4361"/>et animam catulorum ejus implebis, <l eID="gen4361" level="1"/>

** Job 38:40

quando cubant in antris, <l eID="gen4362" level="1"/> <l level="1" sID="gen4363"/>et in specubus insidiantur ? <l eID="gen4363" level="1"/>

** Job 38:41

Quis præparat corvo escam suam, <l eID="gen4364" level="1"/> <l level="1" sID="gen4365"/>quando pulli ejus clamant ad Deum, <l eID="gen4365" level="1"/> <l level="1" sID="gen4366"/>vagantes, eo quod non habeant cibos ?  <chapter eID="Job.38"/>

* Job 39

** Job 39:1

Numquid nosti tempus partus ibicum in petris, <l eID="gen4367" level="1"/> <l level="1" sID="gen4368"/>vel parturientes cervas observasti ? <l eID="gen4368" level="1"/>

** Job 39:2

Dinumerasti menses conceptus earum, <l eID="gen4369" level="1"/> <l level="1" sID="gen4370"/>et scisti tempus partus earum ? <l eID="gen4370" level="1"/>

** Job 39:3

Incurvantur ad fœtum, et pariunt, <l eID="gen4371" level="1"/> <l level="1" sID="gen4372"/>et rugitus emittunt. <l eID="gen4372" level="1"/>

** Job 39:4

Separantur filii earum, et pergunt ad pastum : <l eID="gen4373" level="1"/> <l level="1" sID="gen4374"/>egrediuntur, et non revertuntur ad eas. <l eID="gen4374" level="1"/>

** Job 39:5

Quis dimisit onagrum liberum, <l eID="gen4375" level="1"/> <l level="1" sID="gen4376"/>et vincula ejus quis solvit ? <l eID="gen4376" level="1"/>

** Job 39:6

cui dedi in solitudine domum, <l eID="gen4377" level="1"/> <l level="1" sID="gen4378"/>et tabernacula ejus in terra salsuginis. <l eID="gen4378" level="1"/>

** Job 39:7

Contemnit multitudinem civitatis : <l eID="gen4379" level="1"/> <l level="1" sID="gen4380"/>clamorem exactoris non audit. <l eID="gen4380" level="1"/>

** Job 39:8

Circumspicit montes pascuæ suæ, <l eID="gen4381" level="1"/> <l level="1" sID="gen4382"/>et virentia quæque perquirit. <l eID="gen4382" level="1"/>

** Job 39:9

Numquid volet rhinoceros servire tibi, <l eID="gen4383" level="1"/> <l level="1" sID="gen4384"/>aut morabitur ad præsepe tuum ? <l eID="gen4384" level="1"/>

** Job 39:10

Numquid alligabis rhinocerota ad arandum loro tuo, <l eID="gen4385" level="1"/> <l level="1" sID="gen4386"/>aut confringet glebas vallium post te ? <l eID="gen4386" level="1"/>

** Job 39:11

Numquid fiduciam habebis in magna fortitudine ejus, <l eID="gen4387" level="1"/> <l level="1" sID="gen4388"/>et derelinques ei labores tuos ? <l eID="gen4388" level="1"/>

** Job 39:12

Numquid credes illi quod sementem reddat tibi, <l eID="gen4389" level="1"/> <l level="1" sID="gen4390"/>et aream tuam congreget ? <l eID="gen4390" level="1"/>

** Job 39:13

Penna struthionis similis est <l eID="gen4391" level="1"/> <l level="1" sID="gen4392"/>pennis herodii et accipitris. <l eID="gen4392" level="1"/>

** Job 39:14

Quando derelinquit ova sua in terra, <l eID="gen4393" level="1"/> <l level="1" sID="gen4394"/>tu forsitan in pulvere calefacies ea ? <l eID="gen4394" level="1"/>

** Job 39:15

Obliviscitur quod pes conculcet ea, <l eID="gen4395" level="1"/> <l level="1" sID="gen4396"/>aut bestia agri conterat. <l eID="gen4396" level="1"/>

** Job 39:16

Duratur ad filios suos, quasi non sint sui : <l eID="gen4397" level="1"/> <l level="1" sID="gen4398"/>frustra laboravit, nullo timore cogente. <l eID="gen4398" level="1"/>

** Job 39:17

Privavit enim eam Deus sapientia, <l eID="gen4399" level="1"/> <l level="1" sID="gen4400"/>nec dedit illi intelligentiam. <l eID="gen4400" level="1"/>

** Job 39:18

Cum tempus fuerit, in altum alas erigit : <l eID="gen4401" level="1"/> <l level="1" sID="gen4402"/>deridet equum et ascensorem ejus. <l eID="gen4402" level="1"/>

** Job 39:19

Numquid præbebis equo fortitudinem, <l eID="gen4403" level="1"/> <l level="1" sID="gen4404"/>aut circumdabis collo ejus hinnitum ? <l eID="gen4404" level="1"/>

** Job 39:20

Numquid suscitabis eum quasi locustas ? <l eID="gen4405" level="1"/> <l level="1" sID="gen4406"/>gloria narium ejus terror. <l eID="gen4406" level="1"/>

** Job 39:21

Terram ungula fodit ; exultat audacter : <l eID="gen4407" level="1"/> <l level="1" sID="gen4408"/>in occursum pergit armatis. <l eID="gen4408" level="1"/>

** Job 39:22

Contemnit pavorem, <l eID="gen4409" level="1"/> <l level="1" sID="gen4410"/>nec cedit gladio. <l eID="gen4410" level="1"/>

** Job 39:23

Super ipsum sonabit pharetra ; <l eID="gen4411" level="1"/> <l level="1" sID="gen4412"/>vibrabit hasta et clypeus : <l eID="gen4412" level="1"/>

** Job 39:24

fervens et fremens sorbet terram, <l eID="gen4413" level="1"/> <l level="1" sID="gen4414"/>nec reputat tubæ sonare clangorem. <l eID="gen4414" level="1"/>

** Job 39:25

Ubi audierit buccinam, dicit : Vah ! <l eID="gen4415" level="1"/> <l level="1" sID="gen4416"/>procul odoratur bellum : <l eID="gen4416" level="1"/> <l level="1" sID="gen4417"/>exhortationem ducum, et ululatum exercitus. <l eID="gen4417" level="1"/>

** Job 39:26

Numquid per sapientiam tuam plumescit accipiter, <l eID="gen4418" level="1"/> <l level="1" sID="gen4419"/>expandens alas suas ad austrum ? <l eID="gen4419" level="1"/>

** Job 39:27

Numquid ad præceptum tuum elevabitur aquila, <l eID="gen4420" level="1"/> <l level="1" sID="gen4421"/>et in arduis ponet nidum suum ? <l eID="gen4421" level="1"/>

** Job 39:28

In petris manet, <l eID="gen4422" level="1"/> <l level="1" sID="gen4423"/>et in præruptis silicibus commoratur, <l eID="gen4423" level="1"/> <l level="1" sID="gen4424"/>atque inaccessis rupibus. <l eID="gen4424" level="1"/>

** Job 39:29

Inde contemplatur escam, <l eID="gen4425" level="1"/> <l level="1" sID="gen4426"/>et de longe oculi ejus prospiciunt. <l eID="gen4426" level="1"/>

** Job 39:30

Pulli ejus lambent sanguinem : <l eID="gen4427" level="1"/> <l level="1" sID="gen4428"/>et ubicumque cadaver fuerit, statim adest.

** Job 39:31

Et adjecit Dominus, et locutus est ad Job : <l eID="gen4428" level="1"/>

** Job 39:32

Numquid qui contendit cum Deo, tam facile conquiescit ? <l eID="gen4429" level="1"/> <l level="1" sID="gen4430"/>utique qui arguit Deum, debet respondere ei.

** Job 39:33

Respondens autem Job Domino, dixit : <l eID="gen4430" level="1"/>

** Job 39:34

Qui leviter locutus sum, respondere quid possum ? <l eID="gen4431" level="1"/> <l level="1" sID="gen4432"/>manum meam ponam super os meum. <l eID="gen4432" level="1"/>

** Job 39:35

Unum locutus sum, quod utinam non dixissem : <l eID="gen4433" level="1"/> <l level="1" sID="gen4434"/>et alterum, quibus ultra non addam. <l eID="gen4434" level="1"/><lg eID="gen4285"/> <chapter eID="Job.39"/>

* Job 40

** Job 40:1

Respondens autem Dominus Job de turbine, dixit :  <div eID="gen4435" type="x-p"/>

** Job 40:2

Accinge sicut vir lumbos tuos : <l eID="gen4437" level="1"/> <l level="1" sID="gen4438"/>interrogabo te, et indica mihi. <l eID="gen4438" level="1"/>

** Job 40:3

Numquid irritum facies judicium meum, <l eID="gen4439" level="1"/> <l level="1" sID="gen4440"/>et condemnabis me, ut tu justificeris ? <l eID="gen4440" level="1"/>

** Job 40:4

Et si habes brachium sicut Deus ? <l eID="gen4441" level="1"/> <l level="1" sID="gen4442"/>et si voce simili tonas ? <l eID="gen4442" level="1"/>

** Job 40:5

Circumda tibi decorem, et in sublime erigere, <l eID="gen4443" level="1"/> <l level="1" sID="gen4444"/>et esto gloriosus, et speciosis induere vestibus. <l eID="gen4444" level="1"/>

** Job 40:6

Disperge superbos in furore tuo, <l eID="gen4445" level="1"/> <l level="1" sID="gen4446"/>et respiciens omnem arrogantem humilia. <l eID="gen4446" level="1"/>

** Job 40:7

Respice cunctos superbos, et confunde eos, <l eID="gen4447" level="1"/> <l level="1" sID="gen4448"/>et contere impios in loco suo. <l eID="gen4448" level="1"/>

** Job 40:8

Absconde eos in pulvere simul, <l eID="gen4449" level="1"/> <l level="1" sID="gen4450"/>et facies eorum demerge in foveam. <l eID="gen4450" level="1"/>

** Job 40:9

Et ego confitebor <l eID="gen4451" level="1"/> <l level="1" sID="gen4452"/>quod salvare te possit dextera tua. <l eID="gen4452" level="1"/>

** Job 40:10

Ecce behemoth quem feci tecum, <l eID="gen4453" level="1"/> <l level="1" sID="gen4454"/>fœnum quasi bos comedet. <l eID="gen4454" level="1"/>

** Job 40:11

Fortitudo ejus in lumbis ejus, <l eID="gen4455" level="1"/> <l level="1" sID="gen4456"/>et virtus illius in umbilico ventris ejus. <l eID="gen4456" level="1"/>

** Job 40:12

Stringit caudam suam quasi cedrum ; <l eID="gen4457" level="1"/> <l level="1" sID="gen4458"/>nervi testiculorum ejus perplexi sunt. <l eID="gen4458" level="1"/>

** Job 40:13

Ossa ejus velut fistulæ æris ; <l eID="gen4459" level="1"/> <l level="1" sID="gen4460"/>cartilago illius quasi laminæ ferreæ. <l eID="gen4460" level="1"/>

** Job 40:14

Ipse est principium viarum Dei : <l eID="gen4461" level="1"/> <l level="1" sID="gen4462"/>qui fecit eum applicabit gladium ejus. <l eID="gen4462" level="1"/>

** Job 40:15

Huic montes herbas ferunt : <l eID="gen4463" level="1"/> <l level="1" sID="gen4464"/>omnes bestiæ agri ludent ibi. <l eID="gen4464" level="1"/>

** Job 40:16

Sub umbra dormit in secreto calami, <l eID="gen4465" level="1"/> <l level="1" sID="gen4466"/>et in locis humentibus. <l eID="gen4466" level="1"/>

** Job 40:17

Protegunt umbræ umbram ejus : <l eID="gen4467" level="1"/> <l level="1" sID="gen4468"/>circumdabunt eum salices torrentis. <l eID="gen4468" level="1"/>

** Job 40:18

Ecce absorbebit fluvium, et non mirabitur, <l eID="gen4469" level="1"/> <l level="1" sID="gen4470"/>et habet fiduciam quod influat Jordanis in os ejus. <l eID="gen4470" level="1"/>

** Job 40:19

In oculis ejus quasi hamo capiet eum, <l eID="gen4471" level="1"/> <l level="1" sID="gen4472"/>et in sudibus perforabit nares ejus. <l eID="gen4472" level="1"/>

** Job 40:20

An extrahere poteris Leviathan hamo, <l eID="gen4473" level="1"/> <l level="1" sID="gen4474"/>et fune ligabis linguam ejus ? <l eID="gen4474" level="1"/>

** Job 40:21

Numquid pones circulum in naribus ejus, <l eID="gen4475" level="1"/> <l level="1" sID="gen4476"/>aut armilla perforabis maxillam ejus ? <l eID="gen4476" level="1"/>

** Job 40:22

Numquid multiplicabit ad te preces, <l eID="gen4477" level="1"/> <l level="1" sID="gen4478"/>aut loquetur tibi mollia ? <l eID="gen4478" level="1"/>

** Job 40:23

Numquid feriet tecum pactum, <l eID="gen4479" level="1"/> <l level="1" sID="gen4480"/>et accipies eum servum sempiternum ? <l eID="gen4480" level="1"/>

** Job 40:24

Numquid illudes ei quasi avi, <l eID="gen4481" level="1"/> <l level="1" sID="gen4482"/>aut ligabis eum ancillis tuis ? <l eID="gen4482" level="1"/>

** Job 40:25

Concident eum amici ? <l eID="gen4483" level="1"/> <l level="1" sID="gen4484"/>divident illum negotiatores ? <l eID="gen4484" level="1"/>

** Job 40:26

Numquid implebis sagenas pelle ejus, <l eID="gen4485" level="1"/> <l level="1" sID="gen4486"/>et gurgustium piscium capite illius ? <l eID="gen4486" level="1"/>

** Job 40:27

Pone super eum manum tuam : <l eID="gen4487" level="1"/> <l level="1" sID="gen4488"/>memento belli, nec ultra addas loqui. <l eID="gen4488" level="1"/>

** Job 40:28

Ecce spes ejus frustrabitur eum, <l eID="gen4489" level="1"/> <l level="1" sID="gen4490"/>et videntibus cunctis præcipitabitur.  <chapter eID="Job.40"/>

* Job 41

** Job 41:1

Non quasi crudelis suscitabo eum : <l eID="gen4491" level="1"/> <l level="1" sID="gen4492"/>quis enim resistere potest vultui meo ? <l eID="gen4492" level="1"/>

** Job 41:2

Quis ante dedit mihi, ut reddam ei ? <l eID="gen4493" level="1"/> <l level="1" sID="gen4494"/>omnia quæ sub cælo sunt, mea sunt. <l eID="gen4494" level="1"/>

** Job 41:3

Non parcam ei, et verbis potentibus, <l eID="gen4495" level="1"/> <l level="1" sID="gen4496"/>et ad deprecandum compositis. <l eID="gen4496" level="1"/>

** Job 41:4

Quis revelabit faciem indumenti ejus ? <l eID="gen4497" level="1"/> <l level="1" sID="gen4498"/>et in medium oris ejus quis intrabit ? <l eID="gen4498" level="1"/>

** Job 41:5

Portas vultus ejus quis aperiet ? <l eID="gen4499" level="1"/> <l level="1" sID="gen4500"/>per gyrum dentium ejus formido. <l eID="gen4500" level="1"/>

** Job 41:6

Corpus illius quasi scuta fusilia, <l eID="gen4501" level="1"/> <l level="1" sID="gen4502"/>compactum squamis se prementibus. <l eID="gen4502" level="1"/>

** Job 41:7

Una uni conjungitur, <l eID="gen4503" level="1"/> <l level="1" sID="gen4504"/>et ne spiraculum quidem incedit per eas. <l eID="gen4504" level="1"/>

** Job 41:8

Una alteri adhærebit, <l eID="gen4505" level="1"/> <l level="1" sID="gen4506"/>et tenentes se nequaquam separabuntur. <l eID="gen4506" level="1"/>

** Job 41:9

Sternutatio ejus splendor ignis, <l eID="gen4507" level="1"/> <l level="1" sID="gen4508"/>et oculi ejus ut palpebræ diluculi. <l eID="gen4508" level="1"/>

** Job 41:10

De ore ejus lampades procedunt, <l eID="gen4509" level="1"/> <l level="1" sID="gen4510"/>sicut tædæ ignis accensæ. <l eID="gen4510" level="1"/>

** Job 41:11

De naribus ejus procedit fumus, <l eID="gen4511" level="1"/> <l level="1" sID="gen4512"/>sicut ollæ succensæ atque ferventis. <l eID="gen4512" level="1"/>

** Job 41:12

Halitus ejus prunas ardere facit, <l eID="gen4513" level="1"/> <l level="1" sID="gen4514"/>et flamma de ore ejus egreditur. <l eID="gen4514" level="1"/>

** Job 41:13

In collo ejus morabitur fortitudo, <l eID="gen4515" level="1"/> <l level="1" sID="gen4516"/>et faciem ejus præcedit egestas. <l eID="gen4516" level="1"/>

** Job 41:14

Membra carnium ejus cohærentia sibi : <l eID="gen4517" level="1"/> <l level="1" sID="gen4518"/>mittet contra eum fulmina, et ad locum alium non ferentur. <l eID="gen4518" level="1"/>

** Job 41:15

Cor ejus indurabitur tamquam lapis, <l eID="gen4519" level="1"/> <l level="1" sID="gen4520"/>et stringetur quasi malleatoris incus. <l eID="gen4520" level="1"/>

** Job 41:16

Cum sublatus fuerit, timebunt angeli, <l eID="gen4521" level="1"/> <l level="1" sID="gen4522"/>et territi purgabuntur. <l eID="gen4522" level="1"/>

** Job 41:17

Cum apprehenderit eum gladius, subsistere non poterit, <l eID="gen4523" level="1"/> <l level="1" sID="gen4524"/>neque hasta, neque thorax : <l eID="gen4524" level="1"/>

** Job 41:18

reputabit enim quasi paleas ferrum, <l eID="gen4525" level="1"/> <l level="1" sID="gen4526"/>et quasi lignum putridum æs. <l eID="gen4526" level="1"/>

** Job 41:19

Non fugabit eum vir sagittarius : <l eID="gen4527" level="1"/> <l level="1" sID="gen4528"/>in stipulam versi sunt ei lapides fundæ. <l eID="gen4528" level="1"/>

** Job 41:20

Quasi stipulam æstimabit malleum, <l eID="gen4529" level="1"/> <l level="1" sID="gen4530"/>et deridebit vibrantem hastam. <l eID="gen4530" level="1"/>

** Job 41:21

Sub ipso erunt radii solis, <l eID="gen4531" level="1"/> <l level="1" sID="gen4532"/>et sternet sibi aurum quasi lutum. <l eID="gen4532" level="1"/>

** Job 41:22

Fervescere faciet quasi ollam profundum mare, <l eID="gen4533" level="1"/> <l level="1" sID="gen4534"/>et ponet quasi cum unguenta bulliunt. <l eID="gen4534" level="1"/>

** Job 41:23

Post eum lucebit semita : <l eID="gen4535" level="1"/> <l level="1" sID="gen4536"/>æstimabit abyssum quasi senescentem. <l eID="gen4536" level="1"/>

** Job 41:24

Non est super terram potestas quæ comparetur ei, <l eID="gen4537" level="1"/> <l level="1" sID="gen4538"/>qui factus est ut nullum timeret. <l eID="gen4538" level="1"/>

** Job 41:25

Omne sublime videt : <l eID="gen4539" level="1"/> <l level="1" sID="gen4540"/>ipse est rex super universos filios superbiæ. <l eID="gen4540" level="1"/><lg eID="gen4436"/> <chapter eID="Job.41"/>

* Job 42

** Job 42:1

Respondens autem Job Domino, dixit :  <div eID="gen4541" type="x-p"/>

** Job 42:2

Scio quia omnia potes, <l eID="gen4543" level="1"/> <l level="1" sID="gen4544"/>et nulla te latet cogitatio. <l eID="gen4544" level="1"/>

** Job 42:3

Quis est iste qui celat consilium absque scientia ? <l eID="gen4545" level="1"/> <l level="1" sID="gen4546"/>ideo insipienter locutus sum, <l eID="gen4546" level="1"/> <l level="1" sID="gen4547"/>et quæ ultra modum excederent scientiam meam. <l eID="gen4547" level="1"/>

** Job 42:4

Audi, et ego loquar : <l eID="gen4548" level="1"/> <l level="1" sID="gen4549"/>interrogabo te, et responde mihi. <l eID="gen4549" level="1"/>

** Job 42:5

Auditu auris audivi te : <l eID="gen4550" level="1"/> <l level="1" sID="gen4551"/>nunc autem oculus meus videt te. <l eID="gen4551" level="1"/>

** Job 42:6

Idcirco ipse me reprehendo, <l eID="gen4552" level="1"/> <l level="1" sID="gen4553"/>et ago pœnitentiam in favilla et cinere. <l eID="gen4553" level="1"/> <lg eID="gen4542"/>

** Job 42:7

Postquam autem locutus est Dominus verba hæc ad Job, dixit ad Eliphaz Themanitem : Iratus est furor meus in te, et in duos amicos tuos, quoniam non estis locuti coram me rectum, sicut servus meus Job.

** Job 42:8

Sumite ergo vobis septem tauros et septem arietes, et ite ad servum meum Job, et offerte holocaustum pro vobis : Job autem servus meus orabit pro vobis. Faciem ejus suscipiam, ut non vobis imputetur stultitia : neque enim locuti estis ad me recta, sicut servus meus Job.

** Job 42:9

Abierunt ergo Eliphaz Themanites, et Baldad Suhites, et Sophar Naamathites, et fecerunt sicut locutus fuerat Dominus ad eos : et suscepit Dominus faciem Job.

** Job 42:10

Dominus quoque conversus est ad pœnitentiam Job, cum oraret ille pro amicis suis : et addidit Dominus omnia quæcumque fuerant Job, duplicia.

** Job 42:11

Venerunt autem ad eum omnes fratres sui, et universæ sorores suæ, et cuncti qui noverant eum prius, et comederunt cum eo panem in domo ejus : et moverunt super eum caput, et consolati sunt eum super omni malo quod intulerat Dominus super eum : et dederunt ei unusquisque ovem unam, et inaurem auream unam.

** Job 42:12

Dominus autem benedixit novissimis Job magis quam principio ejus : et facta sunt ei quatuordecim millia ovium, et sex millia camelorum, et mille juga boum, et mille asinæ.

** Job 42:13

Et fuerunt ei septem filii, et tres filiæ.

** Job 42:14

Et vocavit nomen unius Diem, et nomen secundæ Cassiam, et nomen tertiæ Cornustibii.

** Job 42:15

Non sunt autem inventæ mulieres speciosæ sicut filiæ Job in universa terra : deditque eis pater suus hæreditatem inter fratres earum.

** Job 42:16

Vixit autem Job post hæc centum quadraginta annis, et vidit filios suos, et filios filiorum suorum usque ad quartam generationem : et mortuus est senex, et plenus dierum.  <div eID="gen4554" type="x-p"/> <chapter eID="Job.42"/> <div eID="gen2422" osisID="Job" type="book"/>

