* Joel 1

** Joel 1:1

Verbum Domini, quod factum est ad Joël, filium Phatuel.  <div eID="gen29741" type="x-p"/>

** Joel 1:2

Audite hoc, senes, <l eID="gen29743" level="1"/> <l level="1" sID="gen29744"/>et auribus percipite, omnes habitatores terræ : <l eID="gen29744" level="1"/> <l level="1" sID="gen29745"/>si factum est istud in diebus vestris, <l eID="gen29745" level="1"/> <l level="1" sID="gen29746"/>aut in diebus patrum vestrorum ? <l eID="gen29746" level="1"/>

** Joel 1:3

Super hoc filiis vestris narrate, <l eID="gen29747" level="1"/> <l level="1" sID="gen29748"/>et filii vestri filiis suis, <l eID="gen29748" level="1"/> <l level="1" sID="gen29749"/>et filii eorum generationi alteræ. <l eID="gen29749" level="1"/>

** Joel 1:4

Residuum erucæ comedit locusta, <l eID="gen29750" level="1"/> <l level="1" sID="gen29751"/>et residuum locustæ comedit bruchus, <l eID="gen29751" level="1"/> <l level="1" sID="gen29752"/>et residuum bruchi comedit rubigo. <l eID="gen29752" level="1"/>

** Joel 1:5

Expergiscimini, ebrii, <l eID="gen29753" level="1"/> <l level="1" sID="gen29754"/>et flete et ululate, omnes qui bibitis vinum in dulcedine, <l eID="gen29754" level="1"/> <l level="1" sID="gen29755"/>quoniam periit ab ore vestro. <l eID="gen29755" level="1"/>

** Joel 1:6

Gens enim ascendit super terram meam, <l eID="gen29756" level="1"/> <l level="1" sID="gen29757"/>fortis et innumerabilis : <l eID="gen29757" level="1"/> <l level="1" sID="gen29758"/>dentes ejus ut dentes leonis, <l eID="gen29758" level="1"/> <l level="1" sID="gen29759"/>et molares ejus ut catuli leonis. <l eID="gen29759" level="1"/>

** Joel 1:7

Posuit vineam meam in desertum, <l eID="gen29760" level="1"/> <l level="1" sID="gen29761"/>et ficum meam decorticavit ; <l eID="gen29761" level="1"/> <l level="1" sID="gen29762"/>nudans spoliavit eam, et projecit : <l eID="gen29762" level="1"/> <l level="1" sID="gen29763"/>albi facti sunt rami ejus. <l eID="gen29763" level="1"/>

** Joel 1:8

Plange quasi virgo accincta sacco super virum pubertatis suæ. <l eID="gen29764" level="1"/>

** Joel 1:9

Periit sacrificium et libatio de domo Domini ; <l eID="gen29765" level="1"/> <l level="1" sID="gen29766"/>luxerunt sacerdotes, ministri Domini. <l eID="gen29766" level="1"/>

** Joel 1:10

Depopulata est regio, <l eID="gen29767" level="1"/> <l level="1" sID="gen29768"/>luxit humus, <l eID="gen29768" level="1"/> <l level="1" sID="gen29769"/>quoniam devastatum est triticum, <l eID="gen29769" level="1"/> <l level="1" sID="gen29770"/>confusum est vinum, <l eID="gen29770" level="1"/> <l level="1" sID="gen29771"/>elanguit oleum. <l eID="gen29771" level="1"/>

** Joel 1:11

Confusi sunt agricolæ, <l eID="gen29772" level="1"/> <l level="1" sID="gen29773"/>ululaverunt vinitores <l eID="gen29773" level="1"/> <l level="1" sID="gen29774"/>super frumento et hordeo, <l eID="gen29774" level="1"/> <l level="1" sID="gen29775"/>quia periit messis agri. <l eID="gen29775" level="1"/>

** Joel 1:12

Vinea confusa est, <l eID="gen29776" level="1"/> <l level="1" sID="gen29777"/>et ficus elanguit ; <l eID="gen29777" level="1"/> <l level="1" sID="gen29778"/>malogranatum, et palma, et malum, <l eID="gen29778" level="1"/> <l level="1" sID="gen29779"/>et omnia ligna agri aruerunt, <l eID="gen29779" level="1"/> <l level="1" sID="gen29780"/>quia confusum est gaudium a filiis hominum. <l eID="gen29780" level="1"/>

** Joel 1:13

Accingite vos, et plangite, sacerdotes : <l eID="gen29781" level="1"/> <l level="1" sID="gen29782"/>ululate, ministri altaris ; <l eID="gen29782" level="1"/> <l level="1" sID="gen29783"/>ingredimini, cubate in sacco, ministri Dei mei, <l eID="gen29783" level="1"/> <l level="1" sID="gen29784"/>quoniam interiit de domo Dei vestri sacrificium et libatio. <l eID="gen29784" level="1"/>

** Joel 1:14

Sanctificate jejunium, vocate cœtum, <l eID="gen29785" level="1"/> <l level="1" sID="gen29786"/>congregate senes, omnes habitatores terræ <l eID="gen29786" level="1"/> <l level="1" sID="gen29787"/>in domum Dei vestri, <l eID="gen29787" level="1"/> <l level="1" sID="gen29788"/>et clamate ad Dominum : <l eID="gen29788" level="1"/>

** Joel 1:15

A, a, a, diei ! <l eID="gen29789" level="1"/> <l level="1" sID="gen29790"/>quia prope est dies Domini, <l eID="gen29790" level="1"/> <l level="1" sID="gen29791"/>et quasi vastitas a potente veniet. <l eID="gen29791" level="1"/>

** Joel 1:16

Numquid non coram oculis vestris alimenta perierunt <l eID="gen29792" level="1"/> <l level="1" sID="gen29793"/>de domo Dei nostri, lætitia et exsultatio ? <l eID="gen29793" level="1"/>

** Joel 1:17

Computruerunt jumenta in stercore suo, <l eID="gen29794" level="1"/> <l level="1" sID="gen29795"/>demolita sunt horrea, <l eID="gen29795" level="1"/> <l level="1" sID="gen29796"/>dissipatæ sunt apothecæ, <l eID="gen29796" level="1"/> <l level="1" sID="gen29797"/>quoniam confusum est triticum. <l eID="gen29797" level="1"/>

** Joel 1:18

Quid ingemuit animal, <l eID="gen29798" level="1"/> <l level="1" sID="gen29799"/>mugierunt greges armenti ? <l eID="gen29799" level="1"/> <l level="1" sID="gen29800"/>quia non est pascua eis ; <l eID="gen29800" level="1"/> <l level="1" sID="gen29801"/>sed et greges pecorum disperierunt. <l eID="gen29801" level="1"/>

** Joel 1:19

Ad te, Domine, clamabo, <l eID="gen29802" level="1"/> <l level="1" sID="gen29803"/>quia ignis comedit speciosa deserti, <l eID="gen29803" level="1"/> <l level="1" sID="gen29804"/>et flamma succendit omnia ligna regionis. <l eID="gen29804" level="1"/>

** Joel 1:20

Sed et bestiæ agri, quasi area sitiens imbrem, suspexerunt ad te, <l eID="gen29805" level="1"/> <l level="1" sID="gen29806"/>quoniam exsiccati sunt fontes aquarum, <l eID="gen29806" level="1"/> <l level="1" sID="gen29807"/>et ignis devoravit speciosa deserti.  <chapter eID="Joel.1"/>

* Joel 2

** Joel 2:1

Canite tuba in Sion, <l eID="gen29808" level="1"/> <l level="1" sID="gen29809"/>ululate in monte sancto meo, <l eID="gen29809" level="1"/> <l level="1" sID="gen29810"/>conturbentur omnes habitatores terræ : <l eID="gen29810" level="1"/> <l level="1" sID="gen29811"/>quia venit dies Domini, quia prope est. <l eID="gen29811" level="1"/>

** Joel 2:2

Dies tenebrarum et caliginis, <l eID="gen29812" level="1"/> <l level="1" sID="gen29813"/>dies nubis et turbinis ; <l eID="gen29813" level="1"/> <l level="1" sID="gen29814"/>quasi mane expansum super montes <l eID="gen29814" level="1"/> <l level="1" sID="gen29815"/>populus multus et fortis : <l eID="gen29815" level="1"/> <l level="1" sID="gen29816"/>similis ei non fuit a principio, <l eID="gen29816" level="1"/> <l level="1" sID="gen29817"/>et post eum non erit <l eID="gen29817" level="1"/> <l level="1" sID="gen29818"/>usque in annos generationis et generationis. <l eID="gen29818" level="1"/>

** Joel 2:3

Ante faciem ejus ignis vorans, <l eID="gen29819" level="1"/> <l level="1" sID="gen29820"/>et post eum exurens flamma. <l eID="gen29820" level="1"/> <l level="1" sID="gen29821"/>Quasi hortus voluptatis terra coram eo, <l eID="gen29821" level="1"/> <l level="1" sID="gen29822"/>et post eum solitudo deserti, <l eID="gen29822" level="1"/> <l level="1" sID="gen29823"/>neque est qui effugiat eum. <l eID="gen29823" level="1"/>

** Joel 2:4

Quasi aspectus equorum, aspectus eorum ; <l eID="gen29824" level="1"/> <l level="1" sID="gen29825"/>et quasi equites, sic current. <l eID="gen29825" level="1"/>

** Joel 2:5

Sicut sonitus quadrigarum super capita montium exilient, <l eID="gen29826" level="1"/> <l level="1" sID="gen29827"/>sicut sonitus flammæ ignis devorantis stipulam, <l eID="gen29827" level="1"/> <l level="1" sID="gen29828"/>velut populus fortis præparatus ad prælium. <l eID="gen29828" level="1"/>

** Joel 2:6

A facie ejus cruciabuntur populi ; <l eID="gen29829" level="1"/> <l level="1" sID="gen29830"/>omnes vultus redigentur in ollam. <l eID="gen29830" level="1"/>

** Joel 2:7

Sicut fortes current ; <l eID="gen29831" level="1"/> <l level="1" sID="gen29832"/>quasi viri bellatores ascendent murum : <l eID="gen29832" level="1"/> <l level="1" sID="gen29833"/>viri in viis suis gradientur, <l eID="gen29833" level="1"/> <l level="1" sID="gen29834"/>et non declinabunt a semitis suis. <l eID="gen29834" level="1"/>

** Joel 2:8

Unusquisque fratrem suum non coarctabit, <l eID="gen29835" level="1"/> <l level="1" sID="gen29836"/>singuli in calle suo ambulabunt ; <l eID="gen29836" level="1"/> <l level="1" sID="gen29837"/>sed et per fenestras cadent, et non demolientur. <l eID="gen29837" level="1"/>

** Joel 2:9

Urbem ingredientur, in muro current, <l eID="gen29838" level="1"/> <l level="1" sID="gen29839"/>domos conscendent, per fenestras intrabunt quasi fur. <l eID="gen29839" level="1"/>

** Joel 2:10

A facie ejus contremuit terra, <l eID="gen29840" level="1"/> <l level="1" sID="gen29841"/>moti sunt cæli, <l eID="gen29841" level="1"/> <l level="1" sID="gen29842"/>sol et luna obtenebrati sunt, <l eID="gen29842" level="1"/> <l level="1" sID="gen29843"/>et stellæ retraxerunt splendorem suum. <l eID="gen29843" level="1"/>

** Joel 2:11

Et Dominus dedit vocem suam ante faciem exercitus sui, <l eID="gen29844" level="1"/> <l level="1" sID="gen29845"/>quia multa sunt nimis castra ejus, <l eID="gen29845" level="1"/> <l level="1" sID="gen29846"/>quia fortia et facientia verbum ejus : <l eID="gen29846" level="1"/> <l level="1" sID="gen29847"/>magnus enim dies Domini, et terribilis valde, <l eID="gen29847" level="1"/> <l level="1" sID="gen29848"/>et quis sustinebit eum ? <l eID="gen29848" level="1"/>

** Joel 2:12

Nunc ergo, dicit Dominus, <l eID="gen29849" level="1"/> <l level="1" sID="gen29850"/>convertimini ad me in toto corde vestro, <l eID="gen29850" level="1"/> <l level="1" sID="gen29851"/>in jejunio, et in fletu, et in planctu. <l eID="gen29851" level="1"/>

** Joel 2:13

Et scindite corda vestra, et non vestimenta vestra ; <l eID="gen29852" level="1"/> <l level="1" sID="gen29853"/>et convertimini ad Dominum Deum vestrum, <l eID="gen29853" level="1"/> <l level="1" sID="gen29854"/>quia benignus et misericors est, <l eID="gen29854" level="1"/> <l level="1" sID="gen29855"/>patiens et multæ misericordiæ, <l eID="gen29855" level="1"/> <l level="1" sID="gen29856"/>et præstabilis super malitia. <l eID="gen29856" level="1"/>

** Joel 2:14

Quis scit si convertatur, et ignoscat, <l eID="gen29857" level="1"/> <l level="1" sID="gen29858"/>et relinquat post se benedictionem, sacrificium et libamen Domino Deo vestro ? <l eID="gen29858" level="1"/>

** Joel 2:15

Canite tuba in Sion, <l eID="gen29859" level="1"/> <l level="1" sID="gen29860"/>sanctificate jejunium, vocate cœtum : <l eID="gen29860" level="1"/>

** Joel 2:16

congregate populum, sanctificate ecclesiam, <l eID="gen29861" level="1"/> <l level="1" sID="gen29862"/>coadunate senes, congregate parvulos, et sugentes ubera ; <l eID="gen29862" level="1"/> <l level="1" sID="gen29863"/>egrediatur sponsus de cubili suo, <l eID="gen29863" level="1"/> <l level="1" sID="gen29864"/>et sponsa de thalamo suo. <l eID="gen29864" level="1"/>

** Joel 2:17

Inter vestibulum et altare plorabunt sacerdotes, ministri Domini, <l eID="gen29865" level="1"/> <l level="1" sID="gen29866"/>et dicent : Parce, Domine, parce populo tuo ; <l eID="gen29866" level="1"/> <l level="1" sID="gen29867"/>et ne des hæreditatem tuam in opprobrium, <l eID="gen29867" level="1"/> <l level="1" sID="gen29868"/>ut dominentur eis nationes. <l eID="gen29868" level="1"/> <l level="1" sID="gen29869"/>Quare dicunt in populis : Ubi est Deus eorum ? <l eID="gen29869" level="1"/>

** Joel 2:18

Zelatus est Dominus terram suam, <l eID="gen29870" level="1"/> <l level="1" sID="gen29871"/>et pepercit populo suo. <l eID="gen29871" level="1"/>

** Joel 2:19

Et respondit Dominus, et dixit populo suo : <l eID="gen29872" level="1"/> <l level="1" sID="gen29873"/>Ecce ego mittam vobis frumentum, et vinum, et oleum, <l eID="gen29873" level="1"/> <l level="1" sID="gen29874"/>et replebimini eis ; <l eID="gen29874" level="1"/> <l level="1" sID="gen29875"/>et non dabo vos ultra opprobrium in gentibus. <l eID="gen29875" level="1"/>

** Joel 2:20

Et eum qui ab aquilone est procul faciam a vobis, <l eID="gen29876" level="1"/> <l level="1" sID="gen29877"/>et expellam eum in terram inviam et desertam : <l eID="gen29877" level="1"/> <l level="1" sID="gen29878"/>faciem ejus contra mare orientale, <l eID="gen29878" level="1"/> <l level="1" sID="gen29879"/>et extremum ejus ad mare novissimum : <l eID="gen29879" level="1"/> <l level="1" sID="gen29880"/>et ascendet fœtor ejus, <l eID="gen29880" level="1"/> <l level="1" sID="gen29881"/>et ascendet putredo ejus, <l eID="gen29881" level="1"/> <l level="1" sID="gen29882"/>quia superbe egit. <l eID="gen29882" level="1"/>

** Joel 2:21

Noli timere, terra : <l eID="gen29883" level="1"/> <l level="1" sID="gen29884"/>exsulta, et lætare, <l eID="gen29884" level="1"/> <l level="1" sID="gen29885"/>quoniam magnificavit Dominus ut faceret. <l eID="gen29885" level="1"/>

** Joel 2:22

Nolite timere, animalia regionis, <l eID="gen29886" level="1"/> <l level="1" sID="gen29887"/>quia germinaverunt speciosa deserti ; <l eID="gen29887" level="1"/> <l level="1" sID="gen29888"/>quia lignum attulit fructum suum, <l eID="gen29888" level="1"/> <l level="1" sID="gen29889"/>ficus et vinea dederunt virtutem suam. <l eID="gen29889" level="1"/>

** Joel 2:23

Et, filii Sion, exsultate, <l eID="gen29890" level="1"/> <l level="1" sID="gen29891"/>et lætamini in Domino Deo vestro, <l eID="gen29891" level="1"/> <l level="1" sID="gen29892"/>quia dedit vobis doctorem justitiæ, <l eID="gen29892" level="1"/> <l level="1" sID="gen29893"/>et descendere faciet ad vos imbrem matutinum et serotinum, <l eID="gen29893" level="1"/> <l level="1" sID="gen29894"/>sicut in principio. <l eID="gen29894" level="1"/>

** Joel 2:24

Et implebuntur areæ frumento, <l eID="gen29895" level="1"/> <l level="1" sID="gen29896"/>et redundabunt torcularia vino et oleo. <l eID="gen29896" level="1"/>

** Joel 2:25

Et reddam vobis annos, quos comedit locusta, <l eID="gen29897" level="1"/> <l level="1" sID="gen29898"/>bruchus, et rubigo, et eruca : <l eID="gen29898" level="1"/> <l level="1" sID="gen29899"/>fortitudo mea magna quam misi in vos. <l eID="gen29899" level="1"/>

** Joel 2:26

Et comedetis vescentes, et saturabimini ; <l eID="gen29900" level="1"/> <l level="1" sID="gen29901"/>et laudabitis nomen Domini Dei vestri, <l eID="gen29901" level="1"/> <l level="1" sID="gen29902"/>qui fecit mirabilia vobiscum ; <l eID="gen29902" level="1"/> <l level="1" sID="gen29903"/>et non confundetur populus meus in sempiternum. <l eID="gen29903" level="1"/>

** Joel 2:27

Et scietis quia in medio Israël ego sum, <l eID="gen29904" level="1"/> <l level="1" sID="gen29905"/>et ego Dominus Deus vester, et non est amplius ; <l eID="gen29905" level="1"/> <l level="1" sID="gen29906"/>et non confundetur populus meus in æternum. <l eID="gen29906" level="1"/>

** Joel 2:28

Et erit post hæc : <l eID="gen29907" level="1"/> <l level="1" sID="gen29908"/>effundam spiritum meum super omnem carnem, <l eID="gen29908" level="1"/> <l level="1" sID="gen29909"/>et prophetabunt filii vestri et filiæ vestræ : <l eID="gen29909" level="1"/> <l level="1" sID="gen29910"/>senes vestri somnia somniabunt, <l eID="gen29910" level="1"/> <l level="1" sID="gen29911"/>et juvenes vestri visiones videbunt. <l eID="gen29911" level="1"/>

** Joel 2:29

Sed et super servos meos et ancillas <l eID="gen29912" level="1"/> <l level="1" sID="gen29913"/>in diebus illis effundam spiritum meum. <l eID="gen29913" level="1"/>

** Joel 2:30

Et dabo prodigia in cælo et in terra, <l eID="gen29914" level="1"/> <l level="1" sID="gen29915"/>sanguinem, et ignem, et vaporem fumi. <l eID="gen29915" level="1"/>

** Joel 2:31

Sol convertetur in tenebras, <l eID="gen29916" level="1"/> <l level="1" sID="gen29917"/>et luna in sanguinem, <l eID="gen29917" level="1"/> <l level="1" sID="gen29918"/>antequam veniat dies Domini magnus et horribilis. <l eID="gen29918" level="1"/>

** Joel 2:32

Et erit : omnis qui invocaverit nomen Domini, salvus erit : <l eID="gen29919" level="1"/> <l level="1" sID="gen29920"/>quia in monte Sion et in Jerusalem <l eID="gen29920" level="1"/> <l level="1" sID="gen29921"/>erit salvatio, sicut dixit Dominus, <l eID="gen29921" level="1"/> <l level="1" sID="gen29922"/>et in residuis quos Dominus vocaverit.  <chapter eID="Joel.2"/>

* Joel 3

** Joel 3:1

Quia ecce in diebus illis, et in tempore illo, <l eID="gen29923" level="1"/> <l level="1" sID="gen29924"/>cum convertero captivitatem Juda et Jerusalem, <l eID="gen29924" level="1"/>

** Joel 3:2

congregabo omnes gentes, <l eID="gen29925" level="1"/> <l level="1" sID="gen29926"/>et deducam eas in vallem Josaphat ; <l eID="gen29926" level="1"/> <l level="1" sID="gen29927"/>et disceptabo cum eis ibi super populo meo, <l eID="gen29927" level="1"/> <l level="1" sID="gen29928"/>et hæreditate mea Israël, <l eID="gen29928" level="1"/> <l level="1" sID="gen29929"/>quos disperserunt in nationibus, <l eID="gen29929" level="1"/> <l level="1" sID="gen29930"/>et terram meam diviserunt. <l eID="gen29930" level="1"/>

** Joel 3:3

Et super populum meum miserunt sortem ; <l eID="gen29931" level="1"/> <l level="1" sID="gen29932"/>et posuerunt puerum in prostibulo, <l eID="gen29932" level="1"/> <l level="1" sID="gen29933"/>et puellam vendiderunt pro vino ut biberent. <l eID="gen29933" level="1"/>

** Joel 3:4

Verum quid mihi et vobis, Tyrus et Sidon, <l eID="gen29934" level="1"/> <l level="1" sID="gen29935"/>et omnis terminus Palæstinorum ? <l eID="gen29935" level="1"/> <l level="1" sID="gen29936"/>numquid ultionem vos reddetis mihi ? <l eID="gen29936" level="1"/> <l level="1" sID="gen29937"/>et si ulciscimini vos contra me, <l eID="gen29937" level="1"/> <l level="1" sID="gen29938"/>cito velociter reddam vicissitudinem vobis super caput vestrum. <l eID="gen29938" level="1"/>

** Joel 3:5

Argentum enim meum et aurum tulistis, <l eID="gen29939" level="1"/> <l level="1" sID="gen29940"/>et desiderabilia mea et pulcherrima intulistis in delubra vestra. <l eID="gen29940" level="1"/>

** Joel 3:6

Et filios Juda et filios Jerusalem vendidistis filiis Græcorum, <l eID="gen29941" level="1"/> <l level="1" sID="gen29942"/>ut longe faceretis eos de finibus suis. <l eID="gen29942" level="1"/>

** Joel 3:7

Ecce ego suscitabo eos de loco in quo vendidistis eos, <l eID="gen29943" level="1"/> <l level="1" sID="gen29944"/>et convertam retributionem vestram in caput vestrum. <l eID="gen29944" level="1"/>

** Joel 3:8

Et vendam filios vestros et filias vestras in manibus filiorum Juda, <l eID="gen29945" level="1"/> <l level="1" sID="gen29946"/>et venundabunt eos Sabæis, genti longinquæ, <l eID="gen29946" level="1"/> <l level="1" sID="gen29947"/>quia Dominus locutus est. <l eID="gen29947" level="1"/>

** Joel 3:9

Clamate hoc in gentibus, <l eID="gen29948" level="1"/> <l level="1" sID="gen29949"/>sanctificate bellum, <l eID="gen29949" level="1"/> <l level="1" sID="gen29950"/>suscitate robustos : <l eID="gen29950" level="1"/> <l level="1" sID="gen29951"/>accedant, ascendant omnes viri bellatores. <l eID="gen29951" level="1"/>

** Joel 3:10

Concidite aratra vestra in gladios, <l eID="gen29952" level="1"/> <l level="1" sID="gen29953"/>et ligones vestros in lanceas. <l eID="gen29953" level="1"/> <l level="1" sID="gen29954"/>Infirmus dicat : Quia fortis ego sum. <l eID="gen29954" level="1"/>

** Joel 3:11

Erumpite, et venite, omnes gentes de circuitu, <l eID="gen29955" level="1"/> <l level="1" sID="gen29956"/>et congregamini ; <l eID="gen29956" level="1"/> <l level="1" sID="gen29957"/>ibi occumbere faciet Dominus robustos tuos. <l eID="gen29957" level="1"/>

** Joel 3:12

Consurgant, et ascendant gentes in vallem Josaphat, <l eID="gen29958" level="1"/> <l level="1" sID="gen29959"/>quia ibi sedebo ut judicem omnes gentes in circuitu. <l eID="gen29959" level="1"/>

** Joel 3:13

Mittite falces, quoniam maturavit messis ; <l eID="gen29960" level="1"/> <l level="1" sID="gen29961"/>venite, et descendite, <l eID="gen29961" level="1"/> <l level="1" sID="gen29962"/>quia plenum est torcular, exuberant torcularia : <l eID="gen29962" level="1"/> <l level="1" sID="gen29963"/>quia multiplicata est malitia eorum. <l eID="gen29963" level="1"/>

** Joel 3:14

Populi, populi, in valle concisionis, <l eID="gen29964" level="1"/> <l level="1" sID="gen29965"/>quia juxta est dies Domini in valle concisionis. <l eID="gen29965" level="1"/>

** Joel 3:15

Sol et luna obtenebrati sunt, <l eID="gen29966" level="1"/> <l level="1" sID="gen29967"/>et stellæ retraxerunt splendorem suum. <l eID="gen29967" level="1"/>

** Joel 3:16

Et Dominus de Sion rugiet, <l eID="gen29968" level="1"/> <l level="1" sID="gen29969"/>et de Jerusalem dabit vocem suam, <l eID="gen29969" level="1"/> <l level="1" sID="gen29970"/>et movebuntur cæli et terra ; <l eID="gen29970" level="1"/> <l level="1" sID="gen29971"/>et Dominus spes populi sui, <l eID="gen29971" level="1"/> <l level="1" sID="gen29972"/>et fortitudo filiorum Israël. <l eID="gen29972" level="1"/>

** Joel 3:17

Et scietis quia ego Dominus Deus vester, <l eID="gen29973" level="1"/> <l level="1" sID="gen29974"/>habitans in Sion monte sancto meo ; <l eID="gen29974" level="1"/> <l level="1" sID="gen29975"/>et erit Jerusalem sancta, <l eID="gen29975" level="1"/> <l level="1" sID="gen29976"/>et alieni non transibunt per eam amplius. <l eID="gen29976" level="1"/>

** Joel 3:18

Et erit in die illa : stillabunt montes dulcedinem, <l eID="gen29977" level="1"/> <l level="1" sID="gen29978"/>et colles fluent lacte, <l eID="gen29978" level="1"/> <l level="1" sID="gen29979"/>et per omnes rivos Juda ibunt aquæ ; <l eID="gen29979" level="1"/> <l level="1" sID="gen29980"/>et fons de domo Domini egredietur, <l eID="gen29980" level="1"/> <l level="1" sID="gen29981"/>et irrigabit torrentem spinarum. <l eID="gen29981" level="1"/>

** Joel 3:19

Ægyptus in desolationem erit, <l eID="gen29982" level="1"/> <l level="1" sID="gen29983"/>et Idumæa in desertum perditionis, <l eID="gen29983" level="1"/> <l level="1" sID="gen29984"/>pro eo quod inique egerint in filios Juda, <l eID="gen29984" level="1"/> <l level="1" sID="gen29985"/>et effuderint sanguinem innocentem in terra sua. <l eID="gen29985" level="1"/>

** Joel 3:20

Et Judæa in æternum habitabitur, <l eID="gen29986" level="1"/> <l level="1" sID="gen29987"/>et Jerusalem in generationem et generationem. <l eID="gen29987" level="1"/>

** Joel 3:21

Et mundabo sanguinem eorum, quem non mundaveram ; <l eID="gen29988" level="1"/> <l level="1" sID="gen29989"/>et Dominus commorabitur in Sion. <l eID="gen29989" level="1"/> <lg eID="gen29742"/> <chapter eID="Joel.3"/> <div eID="gen29740" osisID="Joel" type="book"/>

