* Jonah 1

** Jonah 1:1

Et factum est verbum Domini ad Jonam, filium Amathi, dicens :

** Jonah 1:2

Surge, et vade in Niniven, civitatem grandem, et prædica in ea, quia ascendit malitia ejus coram me.

** Jonah 1:3

Et surrexit Jonas, ut fugeret in Tharsis a facie Domini, et descendit in Joppen : et invenit navem euntem in Tharsis, et dedit naulum ejus, et descendit in eam ut iret cum eis in Tharsis a facie Domini.

** Jonah 1:4

Dominus autem misit ventum magnum in mare : et facta est tempestas magna in mari, et navis periclitabatur conteri.

** Jonah 1:5

Et timuerunt nautæ, et clamaverunt viri ad deum suum, et miserunt vasa quæ erant in navi, in mare, ut alleviaretur ab eis ; et Jonas descendit ad interiora navis, et dormiebat sopore gravi.

** Jonah 1:6

Et accessit ad eum gubernator, et dixit ei : Quid tu sopore deprimeris ? surge, invoca Deum tuum, si forte recogitet Deus de nobis, et non pereamus.

** Jonah 1:7

Et dixit vir ad collegam suum : Venite et mittamus sortes, et sciamus quare hoc malum sit nobis. Et miserunt sortes, et cecidit sors super Jonam.

** Jonah 1:8

Et dixerunt ad eum : Indica nobis cujus causa malum istud sit nobis : quod est opus tuum ? quæ terra tua, et quo vadis ? vel ex quo populo es tu ?

** Jonah 1:9

Et dixit ad eos : Hebræus ego sum, et Dominum Deum cæli ego timeo, qui fecit mare et aridam.

** Jonah 1:10

Et timuerunt viri timore magno, et dixerunt ad eum : Quid hoc fecisti ? cognoverunt enim viri quod a facie Domini fugeret, quia indicaverat eis.

** Jonah 1:11

Et dixerunt ad eum : Quid faciemus tibi, et cessabit mare a nobis ? quia mare ibat, et intumescebat.

** Jonah 1:12

Et dixit ad eos : Tollite me, et mittite in mare, et cessabit mare a vobis : scio enim ego quoniam propter me tempestas hæc grandis venit super vos.

** Jonah 1:13

Et remigabant viri ut reverterentur ad aridam, et non valebant, quia mare ibat, et intumescebat super eos.

** Jonah 1:14

Et clamaverunt ad Dominum, et dixerunt : Quæsumus, Domine, ne pereamus in anima viri istius, et ne des super nos sanguinem innocentem : quia tu, Domine, sicut voluisti, fecisti.

** Jonah 1:15

Et tulerunt Jonam, et miserunt in mare : et stetit mare a fervore suo.

** Jonah 1:16

Et timuerunt viri timore magno Dominum : et immolaverunt hostias Domino, et voverunt vota.  <chapter eID="Jonah.1"/> <div eID="gen30547" type="x-p"/>

* Jonah 2

** Jonah 2:1

Et præparavit Dominus piscem grandem ut deglutiret Jonam : et erat Jonas in ventre piscis tribus diebus et tribus noctibus.

** Jonah 2:2

Et oravit Jonas ad Dominum Deum suum de ventre piscis,

** Jonah 2:3

et dixit : <div eID="gen30548" type="x-p"/> <lg sID="gen30549"/> <l level="1" sID="gen30550"/>Clamavi de tribulatione mea ad Dominum, <l eID="gen30550" level="1"/> <l level="1" sID="gen30551"/>et exaudivit me ; <l eID="gen30551" level="1"/> <l level="1" sID="gen30552"/>de ventre inferi clamavi, <l eID="gen30552" level="1"/> <l level="1" sID="gen30553"/>et exaudisti vocem meam. <l eID="gen30553" level="1"/>

** Jonah 2:4

Et projecisti me in profundum in corde maris, <l eID="gen30554" level="1"/> <l level="1" sID="gen30555"/>et flumen circumdedit me : <l eID="gen30555" level="1"/> <l level="1" sID="gen30556"/>omnes gurgites tui, et fluctus tui super me transierunt. <l eID="gen30556" level="1"/>

** Jonah 2:5

Et ego dixi : <l eID="gen30557" level="1"/> <l level="1" sID="gen30558"/>Abjectus sum a conspectu oculorum tuorum ; <l eID="gen30558" level="1"/> <l level="1" sID="gen30559"/>verumtamen rursus videbo templum sanctum tuum. <l eID="gen30559" level="1"/>

** Jonah 2:6

Circumdederunt me aquæ usque ad animam : <l eID="gen30560" level="1"/> <l level="1" sID="gen30561"/>abyssus vallavit me, <l eID="gen30561" level="1"/> <l level="1" sID="gen30562"/>pelagus operuit caput meum. <l eID="gen30562" level="1"/>

** Jonah 2:7

Ad extrema montium descendi ; <l eID="gen30563" level="1"/> <l level="1" sID="gen30564"/>terræ vectes concluserunt me in æternum : <l eID="gen30564" level="1"/> <l level="1" sID="gen30565"/>et sublevabis de corruptione vitam meam, Domine Deus meus. <l eID="gen30565" level="1"/>

** Jonah 2:8

Cum angustiaretur in me anima mea, <l eID="gen30566" level="1"/> <l level="1" sID="gen30567"/>Domini recordatus sum : <l eID="gen30567" level="1"/> <l level="1" sID="gen30568"/>ut veniat ad te oratio mea, <l eID="gen30568" level="1"/> <l level="1" sID="gen30569"/>ad templum sanctum tuum. <l eID="gen30569" level="1"/>

** Jonah 2:9

Qui custodiunt vanitates frustra, <l eID="gen30570" level="1"/> <l level="1" sID="gen30571"/>misericordiam suam derelinquunt. <l eID="gen30571" level="1"/>

** Jonah 2:10

Ego autem in voce laudis immolabo tibi : <l eID="gen30572" level="1"/> <l level="1" sID="gen30573"/>quæcumque vovi, reddam pro salute Domino.

** Jonah 2:11

Et dixit Dominus pisci, et evomuit Jonam in aridam. <l eID="gen30573" level="1"/><lg eID="gen30549"/> <chapter eID="Jonah.2"/>

* Jonah 3

** Jonah 3:1

Et factum est verbum Domini ad Jonam secundo, dicens :

** Jonah 3:2

Surge, et vade in Niniven, civitatem magnam, et prædica in ea prædicationem quam ego loquor ad te.

** Jonah 3:3

Et surrexit Jonas, et abiit in Niniven juxta verbum Domini : et Ninive erat civitas magna, itinere trium dierum.

** Jonah 3:4

Et cœpit Jonas introire in civitatem itinere diei unius : et clamavit, et dixit : Adhuc quadraginta dies, et Ninive subvertetur.

** Jonah 3:5

Et crediderunt viri Ninivitæ in Deum, et prædicaverunt jejunium, et vestiti sunt saccis, a majore usque ad minorem.

** Jonah 3:6

Et pervenit verbum ad regem Ninive : et surrexit de solio suo, et abjecit vestimentum suum a se, et indutus est sacco, et sedit in cinere.

** Jonah 3:7

Et clamavit, et dixit in Ninive ex ore regis et principum ejus, dicens : Homines, et jumenta, et boves, et pecora non gustent quidquam : nec pascantur, et aquam non bibant.

** Jonah 3:8

Et operiantur saccis homines et jumenta, et clament ad Dominum in fortitudine : et convertatur vir a via sua mala, et ab iniquitate quæ est in manibus eorum.

** Jonah 3:9

Quis scit si convertatur et ignoscat Deus, et revertatur a furore iræ suæ, et non peribimus ?

** Jonah 3:10

Et vidit Deus opera eorum, quia conversi sunt de via sua mala : et misertus est Deus super malitiam quam locutus fuerat ut faceret eis, et non fecit.  <chapter eID="Jonah.3"/> <div eID="gen30574" type="x-p"/>

* Jonah 4

** Jonah 4:1

Et afflictus est Jonas afflictione magna, et iratus est :

** Jonah 4:2

et oravit ad Dominum, et dixit : Obsecro, Domine, numquid non hoc est verbum meum cum adhuc essem in terra mea ? propter hoc præoccupavi ut fugerem in Tharsis : scio enim quia tu Deus clemens et misericors es, patiens et multæ miserationis, et ignoscens super malitia.

** Jonah 4:3

Et nunc, Domine, tolle, quæso, animam meam a me, quia melior est mihi mors quam vita.

** Jonah 4:4

Et dixit Dominus : Putasne bene irasceris tu ?

** Jonah 4:5

Et egressus est Jonas de civitate, et sedit contra orientem civitatis : et fecit sibimet umbraculum ibi, et sedebat subter illud in umbra, donec videret quid accideret civitati.

** Jonah 4:6

Et præparavit Dominus Deus hederam, et ascendit super caput Jonæ, ut esset umbra super caput ejus, et protegeret eum (laboraverat enim) : et lætatus est Jonas super hedera lætitia magna.

** Jonah 4:7

Et paravit Deus vermen ascensu diluculi in crastinum : et percussit hederam, et exaruit.

** Jonah 4:8

Et cum ortus fuisset sol, præcepit Dominus vento calido et urenti : et percussit sol super caput Jonæ, et æstuabat : et petivit animæ suæ ut moreretur, et dixit : Melius est mihi mori quam vivere.

** Jonah 4:9

Et dixit Dominus ad Jonam : Putasne bene irasceris tu super hedera ? Et dixit : Bene irascor ego usque ad mortem.

** Jonah 4:10

Et dixit Dominus : Tu doles super hederam in qua non laborasti, neque fecisti ut cresceret ; quæ sub una nocte nata est, et sub una nocte periit :

** Jonah 4:11

et ego non parcam Ninive, civitati magnæ, in qua sunt plus quam centum viginti millia hominum qui nesciunt quid sit inter dexteram et sinistram suam, et jumenta multa ?  <div eID="gen30575" type="x-p"/> <chapter eID="Jonah.4"/> <div eID="gen30546" osisID="Jonah" type="book"/>

