* Micah 1

** Micah 1:1

Verbum Domini, quod factum est ad Michæam Morasthiten, in diebus Joathan, Achaz, et Ezechiæ, regum Juda, quod vidit super Samariam et Jerusalem.  <div eID="gen30577" type="x-p"/>

** Micah 1:2

Audite, populi omnes, <l eID="gen30579" level="1"/> <l level="1" sID="gen30580"/>et attendat terra, et plenitudo ejus : <l eID="gen30580" level="1"/> <l level="1" sID="gen30581"/>et sit Dominus Deus vobis in testem, <l eID="gen30581" level="1"/> <l level="1" sID="gen30582"/>Dominus de templo sancto suo. <l eID="gen30582" level="1"/>

** Micah 1:3

Quia ecce Dominus egredietur de loco suo, <l eID="gen30583" level="1"/> <l level="1" sID="gen30584"/>et descendet, et calcabit super excelsa terræ. <l eID="gen30584" level="1"/>

** Micah 1:4

Et consumentur montes subtus eum, <l eID="gen30585" level="1"/> <l level="1" sID="gen30586"/>et valles scindentur sicut cera a facie ignis, <l eID="gen30586" level="1"/> <l level="1" sID="gen30587"/>et sicut aquæ quæ decurrunt in præceps. <l eID="gen30587" level="1"/>

** Micah 1:5

In scelere Jacob omne istud, <l eID="gen30588" level="1"/> <l level="1" sID="gen30589"/>et in peccatis domus Israël. <l eID="gen30589" level="1"/> <l level="1" sID="gen30590"/>Quod scelus Jacob ? nonne Samaria ? <l eID="gen30590" level="1"/> <l level="1" sID="gen30591"/>et quæ excelsa Judæ ? nonne Jerusalem ? <l eID="gen30591" level="1"/>

** Micah 1:6

Et ponam Samariam quasi acervum lapidum in agro, <l eID="gen30592" level="1"/> <l level="1" sID="gen30593"/>cum plantatur vinea ; <l eID="gen30593" level="1"/> <l level="1" sID="gen30594"/>et detraham in vallem lapides ejus, <l eID="gen30594" level="1"/> <l level="1" sID="gen30595"/>et fundamenta ejus revelabo. <l eID="gen30595" level="1"/>

** Micah 1:7

Et omnia sculptilia ejus concidentur, <l eID="gen30596" level="1"/> <l level="1" sID="gen30597"/>et omnes mercedes ejus comburentur igne, <l eID="gen30597" level="1"/> <l level="1" sID="gen30598"/>et omnia idola ejus ponam in perditionem, <l eID="gen30598" level="1"/> <l level="1" sID="gen30599"/>quia de mercedibus meretricis congregata sunt, <l eID="gen30599" level="1"/> <l level="1" sID="gen30600"/>et usque ad mercedem meretricis revertentur. <l eID="gen30600" level="1"/>

** Micah 1:8

Super hoc plangam, et ululabo ; <l eID="gen30601" level="1"/> <l level="1" sID="gen30602"/>vadam spoliatus, et nudus ; <l eID="gen30602" level="1"/> <l level="1" sID="gen30603"/>faciam planctum velut draconum, <l eID="gen30603" level="1"/> <l level="1" sID="gen30604"/>et luctum quasi struthionum : <l eID="gen30604" level="1"/>

** Micah 1:9

quia desperata est plaga ejus, <l eID="gen30605" level="1"/> <l level="1" sID="gen30606"/>quia venit usque ad Judam ; <l eID="gen30606" level="1"/> <l level="1" sID="gen30607"/>tetigit portam populi mei usque ad Jerusalem. <l eID="gen30607" level="1"/>

** Micah 1:10

In Geth nolite annuntiare ; <l eID="gen30608" level="1"/> <l level="1" sID="gen30609"/>lacrimis ne ploretis ; <l eID="gen30609" level="1"/> <l level="1" sID="gen30610"/>in domo pulveris pulvere vos conspergite. <l eID="gen30610" level="1"/>

** Micah 1:11

Et transite vobis, habitatio pulchra, confusa ignominia : <l eID="gen30611" level="1"/> <l level="1" sID="gen30612"/>non est egressa quæ habitat in exitu : <l eID="gen30612" level="1"/> <l level="1" sID="gen30613"/>planctum domus vicina accipiet ex vobis, quæ stetit sibimet. <l eID="gen30613" level="1"/>

** Micah 1:12

Quia infirmata est in bonum, <l eID="gen30614" level="1"/> <l level="1" sID="gen30615"/>quæ habitat in amaritudinibus ; <l eID="gen30615" level="1"/> <l level="1" sID="gen30616"/>quia descendit malum a Domino in portam Jerusalem. <l eID="gen30616" level="1"/>

** Micah 1:13

Tumultus quadrigæ stuporis habitanti Lachis : <l eID="gen30617" level="1"/> <l level="1" sID="gen30618"/>principium peccati est filiæ Sion, <l eID="gen30618" level="1"/> <l level="1" sID="gen30619"/>quia in te inventa sunt scelera Israël. <l eID="gen30619" level="1"/>

** Micah 1:14

Propterea dabit emissarios super hæreditatem Geth, <l eID="gen30620" level="1"/> <l level="1" sID="gen30621"/>domus mendacii in deceptionem regibus Israël. <l eID="gen30621" level="1"/>

** Micah 1:15

Adhuc hæredem adducam tibi quæ habitas in Maresa ; <l eID="gen30622" level="1"/> <l level="1" sID="gen30623"/>usque ad Odollam veniet gloria Israël. <l eID="gen30623" level="1"/>

** Micah 1:16

Decalvare, et tondere super filios deliciarum tuarum ; <l eID="gen30624" level="1"/> <l level="1" sID="gen30625"/>dilata calvitium tuum sicut aquila, <l eID="gen30625" level="1"/> <l level="1" sID="gen30626"/>quoniam captivi ducti sunt ex te.  <chapter eID="Mic.1"/>

* Micah 2

** Micah 2:1

Væ qui cogitatis inutile, <l eID="gen30627" level="1"/> <l level="1" sID="gen30628"/>et operamini malum in cubilibus vestris ! <l eID="gen30628" level="1"/> <l level="1" sID="gen30629"/>In luce matutina faciunt illud, <l eID="gen30629" level="1"/> <l level="1" sID="gen30630"/>quoniam contra Deum est manus eorum. <l eID="gen30630" level="1"/>

** Micah 2:2

Et concupierunt agros, et violenter tulerunt : <l eID="gen30631" level="1"/> <l level="1" sID="gen30632"/>et rapuerunt domos, <l eID="gen30632" level="1"/> <l level="1" sID="gen30633"/>et calumniabantur virum, et domum ejus : <l eID="gen30633" level="1"/> <l level="1" sID="gen30634"/>virum, et hæreditatem ejus. <l eID="gen30634" level="1"/>

** Micah 2:3

Idcirco hæc dicit Dominus : <l eID="gen30635" level="1"/> <l level="1" sID="gen30636"/>Ecce ego cogito super familiam istam malum, <l eID="gen30636" level="1"/> <l level="1" sID="gen30637"/>unde non auferetis colla vestra, <l eID="gen30637" level="1"/> <l level="1" sID="gen30638"/>et non ambulabitis superbi : <l eID="gen30638" level="1"/> <l level="1" sID="gen30639"/>quoniam tempus pessimum est. <l eID="gen30639" level="1"/>

** Micah 2:4

In die illa sumetur super vos parabola, <l eID="gen30640" level="1"/> <l level="1" sID="gen30641"/>et cantabitur canticum cum suavitate, dicentium : <l eID="gen30641" level="1"/> <l level="1" sID="gen30642"/>Depopulatione vastati sumus ; <l eID="gen30642" level="1"/> <l level="1" sID="gen30643"/>pars populi mei commutata est : <l eID="gen30643" level="1"/> <l level="1" sID="gen30644"/>quomodo recedet a me, cum revertatur, <l eID="gen30644" level="1"/> <l level="1" sID="gen30645"/>qui regiones nostras dividat ? <l eID="gen30645" level="1"/>

** Micah 2:5

Propter hoc non erit tibi mittens funiculum sortis in cœtu Domini. <l eID="gen30646" level="1"/>

** Micah 2:6

Ne loquamini loquentes ; <l eID="gen30647" level="1"/> <l level="1" sID="gen30648"/>non stillabit super istos, non comprehendet confusio. <l eID="gen30648" level="1"/>

** Micah 2:7

Dicit domus Jacob : <l eID="gen30649" level="1"/> <l level="1" sID="gen30650"/>Numquid abbreviatus est spiritus Domini, <l eID="gen30650" level="1"/> <l level="1" sID="gen30651"/>aut tales sunt cogitationes ejus ? <l eID="gen30651" level="1"/> <l level="1" sID="gen30652"/>nonne verba mea bona sunt cum eo qui recte graditur ? <l eID="gen30652" level="1"/>

** Micah 2:8

et e contrario populus meus in adversarium consurrexit. <l eID="gen30653" level="1"/> <l level="1" sID="gen30654"/>Desuper tunica pallium sustulistis : <l eID="gen30654" level="1"/> <l level="1" sID="gen30655"/>et eos qui transibant simpliciter convertistis in bellum. <l eID="gen30655" level="1"/>

** Micah 2:9

Mulieres populi mei ejecistis de domo deliciarum suarum ; <l eID="gen30656" level="1"/> <l level="1" sID="gen30657"/>a parvulis earum tulistis laudem meam in perpetuum. <l eID="gen30657" level="1"/>

** Micah 2:10

Surgite, et ite, quia non habetis hic requiem : <l eID="gen30658" level="1"/> <l level="1" sID="gen30659"/>propter immunditiam ejus corrumpetur putredine pessima. <l eID="gen30659" level="1"/>

** Micah 2:11

Utinam non essem vir habens spiritum, <l eID="gen30660" level="1"/> <l level="1" sID="gen30661"/>et mendacium potius loquerer ! <l eID="gen30661" level="1"/> <l level="1" sID="gen30662"/>Stillabo tibi in vinum et in ebrietatem ; <l eID="gen30662" level="1"/> <l level="1" sID="gen30663"/>et erit super quem stillatur populus iste. <l eID="gen30663" level="1"/>

** Micah 2:12

Congregatione congregabo, Jacob, totum te ; <l eID="gen30664" level="1"/> <l level="1" sID="gen30665"/>in unum conducam reliquias Israël : <l eID="gen30665" level="1"/> <l level="1" sID="gen30666"/>pariter ponam illum quasi gregem in ovili, <l eID="gen30666" level="1"/> <l level="1" sID="gen30667"/>quasi pecus in medio caularum : <l eID="gen30667" level="1"/> <l level="1" sID="gen30668"/>tumultuabuntur a multitudine hominum. <l eID="gen30668" level="1"/>

** Micah 2:13

Ascendet enim pandens iter ante eos : <l eID="gen30669" level="1"/> <l level="1" sID="gen30670"/>divident, et transibunt portam, <l eID="gen30670" level="1"/> <l level="1" sID="gen30671"/>et ingredientur per eam : <l eID="gen30671" level="1"/> <l level="1" sID="gen30672"/>et transibit rex eorum coram eis, <l eID="gen30672" level="1"/> <l level="1" sID="gen30673"/>et Dominus in capite eorum.  <chapter eID="Mic.2"/>

* Micah 3

** Micah 3:1

Et dixi : Audite, princeps Jacob, <l eID="gen30674" level="1"/> <l level="1" sID="gen30675"/>et duces domus Israël : <l eID="gen30675" level="1"/> <l level="1" sID="gen30676"/>numquid non vestrum est scire judicium, <l eID="gen30676" level="1"/>

** Micah 3:2

qui odio habetis bonum, et diligitis malum ; <l eID="gen30677" level="1"/> <l level="1" sID="gen30678"/>qui violenter tollitis pelles eorum desuper eis, <l eID="gen30678" level="1"/> <l level="1" sID="gen30679"/>et carnem eorum desuper ossibus eorum ; <l eID="gen30679" level="1"/>

** Micah 3:3

qui comederunt carnem populi mei, <l eID="gen30680" level="1"/> <l level="1" sID="gen30681"/>et pellem eorum desuper excoriaverunt, <l eID="gen30681" level="1"/> <l level="1" sID="gen30682"/>et ossa eorum confregerunt, <l eID="gen30682" level="1"/> <l level="1" sID="gen30683"/>et conciderunt sicut in lebete, <l eID="gen30683" level="1"/> <l level="1" sID="gen30684"/>et quasi carnem in medio ollæ ? <l eID="gen30684" level="1"/>

** Micah 3:4

Tunc clamabunt ad Dominum, et non exaudiet eos, <l eID="gen30685" level="1"/> <l level="1" sID="gen30686"/>et abscondet faciem suam ab eis in tempore illo, <l eID="gen30686" level="1"/> <l level="1" sID="gen30687"/>sicut nequiter egerunt in adinventionibus suis. <l eID="gen30687" level="1"/>

** Micah 3:5

Hæc dicit Dominus super prophetas, <l eID="gen30688" level="1"/> <l level="1" sID="gen30689"/>qui seducunt populum meum : <l eID="gen30689" level="1"/> <l level="1" sID="gen30690"/>qui mordent dentibus suis, <l eID="gen30690" level="1"/> <l level="1" sID="gen30691"/>et prædicant pacem ; <l eID="gen30691" level="1"/> <l level="1" sID="gen30692"/>et si quis non dederit in ore eorum quippiam, <l eID="gen30692" level="1"/> <l level="1" sID="gen30693"/>sanctificant super eum prælium. <l eID="gen30693" level="1"/>

** Micah 3:6

Propterea nox vobis pro visione erit, <l eID="gen30694" level="1"/> <l level="1" sID="gen30695"/>et tenebræ vobis pro divinatione ; <l eID="gen30695" level="1"/> <l level="1" sID="gen30696"/>et occumbet sol super prophetas, <l eID="gen30696" level="1"/> <l level="1" sID="gen30697"/>et obtenebrabitur super eos dies. <l eID="gen30697" level="1"/>

** Micah 3:7

Et confundentur qui vident visiones, <l eID="gen30698" level="1"/> <l level="1" sID="gen30699"/>et confundentur divini ; <l eID="gen30699" level="1"/> <l level="1" sID="gen30700"/>et operient omnes vultos suos, <l eID="gen30700" level="1"/> <l level="1" sID="gen30701"/>quia non est responsum Dei. <l eID="gen30701" level="1"/>

** Micah 3:8

Verumtamen ego repletus sum fortitudine spiritus Domini, <l eID="gen30702" level="1"/> <l level="1" sID="gen30703"/>judicio, et virtute, <l eID="gen30703" level="1"/> <l level="1" sID="gen30704"/>ut annuntiem Jacob scelus suum, <l eID="gen30704" level="1"/> <l level="1" sID="gen30705"/>et Israël peccatum suum. <l eID="gen30705" level="1"/>

** Micah 3:9

Audite hoc, principes domus Jacob, <l eID="gen30706" level="1"/> <l level="1" sID="gen30707"/>et judices domus Israël, <l eID="gen30707" level="1"/> <l level="1" sID="gen30708"/>qui abominamini judicium, <l eID="gen30708" level="1"/> <l level="1" sID="gen30709"/>et omnia recta pervertitis : <l eID="gen30709" level="1"/>

** Micah 3:10

qui ædificatis Sion in sanguinibus, <l eID="gen30710" level="1"/> <l level="1" sID="gen30711"/>et Jerusalem in iniquitate. <l eID="gen30711" level="1"/>

** Micah 3:11

Principes ejus in muneribus judicabant, <l eID="gen30712" level="1"/> <l level="1" sID="gen30713"/>et sacerdotes ejus in mercede docebant, <l eID="gen30713" level="1"/> <l level="1" sID="gen30714"/>et prophetæ ejus in pecunia divinabant : <l eID="gen30714" level="1"/> <l level="1" sID="gen30715"/>et super Dominum requiescebant, dicentes : <l eID="gen30715" level="1"/> <l level="1" sID="gen30716"/>Numquid non Dominus in medio nostrum ? <l eID="gen30716" level="1"/> <l level="1" sID="gen30717"/>non venient super nos mala. <l eID="gen30717" level="1"/>

** Micah 3:12

Propter hoc, causa vestri, Sion quasi ager arabitur, <l eID="gen30718" level="1"/> <l level="1" sID="gen30719"/>et Jerusalem quasi acervus lapidum erit, <l eID="gen30719" level="1"/> <l level="1" sID="gen30720"/>et mons templi in excelsa silvarum.  <chapter eID="Mic.3"/>

* Micah 4

** Micah 4:1

Et erit : in novissimo dierum <l eID="gen30721" level="1"/> <l level="1" sID="gen30722"/>erit mons domus Domini præparatus in vertice montium, <l eID="gen30722" level="1"/> <l level="1" sID="gen30723"/>et sublimis super colles : <l eID="gen30723" level="1"/> <l level="1" sID="gen30724"/>et fluent ad eum populi, <l eID="gen30724" level="1"/>

** Micah 4:2

et properabunt gentes multæ, et dicent : <l eID="gen30725" level="1"/> <l level="1" sID="gen30726"/>Venite, ascendamus ad montem Domini, <l eID="gen30726" level="1"/> <l level="1" sID="gen30727"/>et ad domum Dei Jacob : <l eID="gen30727" level="1"/> <l level="1" sID="gen30728"/>et docebit nos de viis suis, <l eID="gen30728" level="1"/> <l level="1" sID="gen30729"/>et ibimus in semitis ejus, <l eID="gen30729" level="1"/> <l level="1" sID="gen30730"/>quia de Sion egredietur lex, <l eID="gen30730" level="1"/> <l level="1" sID="gen30731"/>et verbum Domini de Jerusalem. <l eID="gen30731" level="1"/>

** Micah 4:3

Et judicabit inter populos multos, <l eID="gen30732" level="1"/> <l level="1" sID="gen30733"/>et corripiet gentes fortes usque in longinquum : <l eID="gen30733" level="1"/> <l level="1" sID="gen30734"/>et concident gladios suos in vomeres, <l eID="gen30734" level="1"/> <l level="1" sID="gen30735"/>et hastas suas in ligones : <l eID="gen30735" level="1"/> <l level="1" sID="gen30736"/>non sumet gens adversus gentem gladium, <l eID="gen30736" level="1"/> <l level="1" sID="gen30737"/>et non discent ultra belligerare. <l eID="gen30737" level="1"/>

** Micah 4:4

Et sedebit vir subtus vitem suam et subtus ficum suam, <l eID="gen30738" level="1"/> <l level="1" sID="gen30739"/>et non erit qui deterreat, <l eID="gen30739" level="1"/> <l level="1" sID="gen30740"/>quia os Domini exercituum locutum est. <l eID="gen30740" level="1"/>

** Micah 4:5

Quia omnes populi ambulabunt <l eID="gen30741" level="1"/> <l level="1" sID="gen30742"/>unusquisque in nomine dei sui ; <l eID="gen30742" level="1"/> <l level="1" sID="gen30743"/>nos autem ambulabimus <l eID="gen30743" level="1"/> <l level="1" sID="gen30744"/>in nomine Domini Dei nostri, <l eID="gen30744" level="1"/> <l level="1" sID="gen30745"/>in æternum et ultra. <l eID="gen30745" level="1"/>

** Micah 4:6

In die illa, dicit Dominus, <l eID="gen30746" level="1"/> <l level="1" sID="gen30747"/>congregabo claudicantem, <l eID="gen30747" level="1"/> <l level="1" sID="gen30748"/>et eam quam ejeceram colligam, <l eID="gen30748" level="1"/> <l level="1" sID="gen30749"/>et quam afflixeram : <l eID="gen30749" level="1"/>

** Micah 4:7

et ponam claudicantem in reliquias, <l eID="gen30750" level="1"/> <l level="1" sID="gen30751"/>et eam quæ laboraverat, in gentem robustam : <l eID="gen30751" level="1"/> <l level="1" sID="gen30752"/>et regnabit Dominus super eos in monte Sion, <l eID="gen30752" level="1"/> <l level="1" sID="gen30753"/>ex hoc nunc et usque in æternum. <l eID="gen30753" level="1"/>

** Micah 4:8

Et tu, turris gregis nebulosa filiæ Sion, <l eID="gen30754" level="1"/> <l level="1" sID="gen30755"/>usque ad te veniet, <l eID="gen30755" level="1"/> <l level="1" sID="gen30756"/>et veniet potestas prima, <l eID="gen30756" level="1"/> <l level="1" sID="gen30757"/>regnum filiæ Jerusalem. <l eID="gen30757" level="1"/>

** Micah 4:9

Nunc quare mœrore contraheris ? <l eID="gen30758" level="1"/> <l level="1" sID="gen30759"/>numquid rex non est tibi, <l eID="gen30759" level="1"/> <l level="1" sID="gen30760"/>aut consiliarius tuus periit, <l eID="gen30760" level="1"/> <l level="1" sID="gen30761"/>quia comprehendit te dolor sicut parturientem ? <l eID="gen30761" level="1"/>

** Micah 4:10

Dole et satage, filia Sion, quasi parturiens, <l eID="gen30762" level="1"/> <l level="1" sID="gen30763"/>quia nunc egredieris de civitate, <l eID="gen30763" level="1"/> <l level="1" sID="gen30764"/>et habitabis in regione, <l eID="gen30764" level="1"/> <l level="1" sID="gen30765"/>et venies usque ad Babylonem : <l eID="gen30765" level="1"/> <l level="1" sID="gen30766"/>ibi liberaberis, <l eID="gen30766" level="1"/> <l level="1" sID="gen30767"/>ibi redimet te Dominus de manu inimicorum tuorum. <l eID="gen30767" level="1"/>

** Micah 4:11

Et nunc congregatæ sunt super te gentes multæ, quæ dicunt : <l eID="gen30768" level="1"/> <l level="1" sID="gen30769"/>Lapidetur, et aspiciat in Sion oculus noster. <l eID="gen30769" level="1"/>

** Micah 4:12

Ipsi autem non cognoverunt cogitationes Domini, <l eID="gen30770" level="1"/> <l level="1" sID="gen30771"/>et non intellexerunt consilium ejus, <l eID="gen30771" level="1"/> <l level="1" sID="gen30772"/>quia congregavit eos quasi fœnum areæ. <l eID="gen30772" level="1"/>

** Micah 4:13

Surge, et tritura, filia Sion, <l eID="gen30773" level="1"/> <l level="1" sID="gen30774"/>quia cornu tuum ponam ferreum, <l eID="gen30774" level="1"/> <l level="1" sID="gen30775"/>et ungulas tuas ponam æreas ; <l eID="gen30775" level="1"/> <l level="1" sID="gen30776"/>et comminues populos multos, <l eID="gen30776" level="1"/> <l level="1" sID="gen30777"/>et interficies Domino rapinas eorum, <l eID="gen30777" level="1"/> <l level="1" sID="gen30778"/>et fortitudinem eorum Domino universæ terræ.  <chapter eID="Mic.4"/>

* Micah 5

** Micah 5:1

Nunc vastaberis, filia latronis. <l eID="gen30779" level="1"/> <l level="1" sID="gen30780"/>Obsidionem posuerunt super nos : <l eID="gen30780" level="1"/> <l level="1" sID="gen30781"/>in virga percutient maxillam judicis Israël. <l eID="gen30781" level="1"/>

** Micah 5:2

Et tu, Bethlehem Ephrata, <l eID="gen30782" level="1"/> <l level="1" sID="gen30783"/>parvulus es in millibus Juda ; <l eID="gen30783" level="1"/> <l level="1" sID="gen30784"/>ex te mihi egredietur qui sit dominator in Israël, <l eID="gen30784" level="1"/> <l level="1" sID="gen30785"/>et egressus ejus ab initio, <l eID="gen30785" level="1"/> <l level="1" sID="gen30786"/>a diebus æternitatis. <l eID="gen30786" level="1"/>

** Micah 5:3

Propter hoc dabit eos usque ad tempus in quo parturiens pariet, <l eID="gen30787" level="1"/> <l level="1" sID="gen30788"/>et reliquiæ fratrum ejus convertentur ad filios Israël. <l eID="gen30788" level="1"/>

** Micah 5:4

Et stabit, et pascet in fortitudine Domini, <l eID="gen30789" level="1"/> <l level="1" sID="gen30790"/>in sublimitate nominis Domini Dei sui : <l eID="gen30790" level="1"/> <l level="1" sID="gen30791"/>et convertentur, <l eID="gen30791" level="1"/> <l level="1" sID="gen30792"/>quia nunc magnificabitur usque ad terminos terræ. <l eID="gen30792" level="1"/>

** Micah 5:5

Et erit iste pax : <l eID="gen30793" level="1"/> <l level="1" sID="gen30794"/>cum venerit Assyrius in terram nostram, <l eID="gen30794" level="1"/> <l level="1" sID="gen30795"/>et quando calcaverit domibus nostris, <l eID="gen30795" level="1"/> <l level="1" sID="gen30796"/>et suscitabimus super eum septem pastores <l eID="gen30796" level="1"/> <l level="1" sID="gen30797"/>et octo primates homines ; <l eID="gen30797" level="1"/>

** Micah 5:6

et pascent terram Assur in gladio, <l eID="gen30798" level="1"/> <l level="1" sID="gen30799"/>et terram Nemrod in lanceis ejus, <l eID="gen30799" level="1"/> <l level="1" sID="gen30800"/>et liberabit ab Assur cum venerit in terram nostram, <l eID="gen30800" level="1"/> <l level="1" sID="gen30801"/>et cum calcaverit in finibus nostris. <l eID="gen30801" level="1"/>

** Micah 5:7

Et erunt reliquiæ Jacob in medio populorum multorum <l eID="gen30802" level="1"/> <l level="1" sID="gen30803"/>quasi ros a Domino, <l eID="gen30803" level="1"/> <l level="1" sID="gen30804"/>et quasi stillæ super herbam, <l eID="gen30804" level="1"/> <l level="1" sID="gen30805"/>quæ non exspectat virum, <l eID="gen30805" level="1"/> <l level="1" sID="gen30806"/>et non præstolatur filios hominum. <l eID="gen30806" level="1"/>

** Micah 5:8

Et erunt reliquiæ Jacob in gentibus, <l eID="gen30807" level="1"/> <l level="1" sID="gen30808"/>in medio populorum multorum, <l eID="gen30808" level="1"/> <l level="1" sID="gen30809"/>quasi leo in jumentis silvarum, <l eID="gen30809" level="1"/> <l level="1" sID="gen30810"/>et quasi catulus leonis in gregibus pecorum, <l eID="gen30810" level="1"/> <l level="1" sID="gen30811"/>qui cum transierit, et conculcaverit, et ceperit, <l eID="gen30811" level="1"/> <l level="1" sID="gen30812"/>non est qui eruat. <l eID="gen30812" level="1"/>

** Micah 5:9

Exaltabitur manus tua super hostes tuos, <l eID="gen30813" level="1"/> <l level="1" sID="gen30814"/>et omnes inimici tui interibunt. <l eID="gen30814" level="1"/>

** Micah 5:10

Et erit in die illa, dicit Dominus : <l eID="gen30815" level="1"/> <l level="1" sID="gen30816"/>auferam equos tuos de medio tui, <l eID="gen30816" level="1"/> <l level="1" sID="gen30817"/>et disperdam quadrigas tuas. <l eID="gen30817" level="1"/>

** Micah 5:11

Et perdam civitates terræ tuæ, <l eID="gen30818" level="1"/> <l level="1" sID="gen30819"/>et destruam omnes munitiones tuas : <l eID="gen30819" level="1"/> <l level="1" sID="gen30820"/>et auferam maleficia de manu tua, <l eID="gen30820" level="1"/> <l level="1" sID="gen30821"/>et divinationes non erunt in te : <l eID="gen30821" level="1"/>

** Micah 5:12

et perire faciam sculptilia tua et statuas tuas de medio tui, <l eID="gen30822" level="1"/> <l level="1" sID="gen30823"/>et non adorabis ultra opera manuum tuarum : <l eID="gen30823" level="1"/>

** Micah 5:13

et evellam lucos tuos de medio tui, <l eID="gen30824" level="1"/> <l level="1" sID="gen30825"/>et conteram civitates tuas. <l eID="gen30825" level="1"/>

** Micah 5:14

Et faciam, in furore et in indignatione, ultionem <l eID="gen30826" level="1"/> <l level="1" sID="gen30827"/>in omnibus gentibus quæ non audierunt.  <chapter eID="Mic.5"/>

* Micah 6

** Micah 6:1

Audite quæ Dominus loquitur : <l eID="gen30828" level="1"/> <l level="1" sID="gen30829"/>Surge, contende judicio adversum montes, <l eID="gen30829" level="1"/> <l level="1" sID="gen30830"/>et audiant colles vocem tuam. <l eID="gen30830" level="1"/>

** Micah 6:2

Audiant montes judicium Domini, <l eID="gen30831" level="1"/> <l level="1" sID="gen30832"/>et fortia fundamenta terræ ; <l eID="gen30832" level="1"/> <l level="1" sID="gen30833"/>quia judicium Domini cum populo suo, <l eID="gen30833" level="1"/> <l level="1" sID="gen30834"/>et cum Israël dijudicabitur. <l eID="gen30834" level="1"/>

** Micah 6:3

Popule meus, quid feci tibi ? <l eID="gen30835" level="1"/> <l level="1" sID="gen30836"/>aut quid molestus fui tibi ? Responde mihi. <l eID="gen30836" level="1"/>

** Micah 6:4

Quia eduxi te de terra Ægypti, <l eID="gen30837" level="1"/> <l level="1" sID="gen30838"/>et de domo servientium liberavi te, <l eID="gen30838" level="1"/> <l level="1" sID="gen30839"/>et misi ante faciem tuam Moysen, et Aaron, et Mariam. <l eID="gen30839" level="1"/>

** Micah 6:5

Popule meus, memento, quæso, <l eID="gen30840" level="1"/> <l level="1" sID="gen30841"/>quid cogitaverit Balach, rex Moab, <l eID="gen30841" level="1"/> <l level="1" sID="gen30842"/>et quid responderit ei Balaam, filius Beor, <l eID="gen30842" level="1"/> <l level="1" sID="gen30843"/>de Setim usque ad Galgalam, <l eID="gen30843" level="1"/> <l level="1" sID="gen30844"/>ut cognosceres justitias Domini. <l eID="gen30844" level="1"/>

** Micah 6:6

Quid dignum offeram Domino ? <l eID="gen30845" level="1"/> <l level="1" sID="gen30846"/>curvabo genu Deo excelso ? <l eID="gen30846" level="1"/> <l level="1" sID="gen30847"/>Numquid offeram ei holocautomata et vitulos anniculos ? <l eID="gen30847" level="1"/>

** Micah 6:7

numquid placari potest Dominus in millibus arietum, <l eID="gen30848" level="1"/> <l level="1" sID="gen30849"/>aut in multis millibus hircorum pinguium ? <l eID="gen30849" level="1"/> <l level="1" sID="gen30850"/>numquid dabo primogenitum meum pro scelere meo, <l eID="gen30850" level="1"/> <l level="1" sID="gen30851"/>fructum ventris mei pro peccato animæ meæ ? <l eID="gen30851" level="1"/>

** Micah 6:8

Indicabo tibi, o homo, quid sit bonum, <l eID="gen30852" level="1"/> <l level="1" sID="gen30853"/>et quid Dominus requirat a te : <l eID="gen30853" level="1"/> <l level="1" sID="gen30854"/>utique facere judicium, <l eID="gen30854" level="1"/> <l level="1" sID="gen30855"/>et diligere misericordiam, <l eID="gen30855" level="1"/> <l level="1" sID="gen30856"/>et sollicitum ambulare cum Deo tuo. <l eID="gen30856" level="1"/>

** Micah 6:9

Vox Domini ad civitatem clamat, <l eID="gen30857" level="1"/> <l level="1" sID="gen30858"/>et salus erit timentibus nomen tuum : <l eID="gen30858" level="1"/> <l level="1" sID="gen30859"/>audite, tribus, et quis approbabit illud ? <l eID="gen30859" level="1"/>

** Micah 6:10

Adhuc ignis in domo impii thesauri iniquitatis, <l eID="gen30860" level="1"/> <l level="1" sID="gen30861"/>et mensura minor iræ plena. <l eID="gen30861" level="1"/>

** Micah 6:11

Numquid justificabo stateram impiam, <l eID="gen30862" level="1"/> <l level="1" sID="gen30863"/>et saccelli pondera dolosa ? <l eID="gen30863" level="1"/>

** Micah 6:12

In quibus divites ejus repleti sunt iniquitate, <l eID="gen30864" level="1"/> <l level="1" sID="gen30865"/>et habitantes in ea loquebantur mendacium, <l eID="gen30865" level="1"/> <l level="1" sID="gen30866"/>et lingua eorum fraudulenta in ore eorum. <l eID="gen30866" level="1"/>

** Micah 6:13

Et ego ergo cœpi percutere te perditione super peccatis tuis. <l eID="gen30867" level="1"/>

** Micah 6:14

Tu comedes, et non saturaberis, <l eID="gen30868" level="1"/> <l level="1" sID="gen30869"/>et humiliatio tua in medio tui : <l eID="gen30869" level="1"/> <l level="1" sID="gen30870"/>et apprehendes, et non salvabis, <l eID="gen30870" level="1"/> <l level="1" sID="gen30871"/>et quos salvaveris, in gladium dabo. <l eID="gen30871" level="1"/>

** Micah 6:15

Tu seminabis, et non metes : <l eID="gen30872" level="1"/> <l level="1" sID="gen30873"/>tu calcabis olivam, et non ungeris oleo ; <l eID="gen30873" level="1"/> <l level="1" sID="gen30874"/>et mustum, et non bibes vinum. <l eID="gen30874" level="1"/>

** Micah 6:16

Et custodisti præcepta Amri, <l eID="gen30875" level="1"/> <l level="1" sID="gen30876"/>et omne opus domus Achab, <l eID="gen30876" level="1"/> <l level="1" sID="gen30877"/>et ambulasti in voluntatibus eorum : <l eID="gen30877" level="1"/> <l level="1" sID="gen30878"/>ut darem te in perditionem, <l eID="gen30878" level="1"/> <l level="1" sID="gen30879"/>et habitantes in ea in sibilum, <l eID="gen30879" level="1"/> <l level="1" sID="gen30880"/>et opprobrium populi mei portabitis.  <chapter eID="Mic.6"/>

* Micah 7

** Micah 7:1

Væ mihi, quia factus sum sicut qui colligit in autumno racemos vindemiæ ! <l eID="gen30881" level="1"/> <l level="1" sID="gen30882"/>non est botrus ad comedendum, <l eID="gen30882" level="1"/> <l level="1" sID="gen30883"/>præcoquas ficus desideravit anima mea. <l eID="gen30883" level="1"/>

** Micah 7:2

Periit sanctus de terra, <l eID="gen30884" level="1"/> <l level="1" sID="gen30885"/>et rectus in hominibus non est : <l eID="gen30885" level="1"/> <l level="1" sID="gen30886"/>omnes in sanguine insidiantur ; <l eID="gen30886" level="1"/> <l level="1" sID="gen30887"/>vir fratrem suum ad mortem venatur. <l eID="gen30887" level="1"/>

** Micah 7:3

Malum manuum suarum dicunt bonum : <l eID="gen30888" level="1"/> <l level="1" sID="gen30889"/>princeps postulat, et judex in reddendo est ; <l eID="gen30889" level="1"/> <l level="1" sID="gen30890"/>et magnus locutus est desiderium animæ suæ, <l eID="gen30890" level="1"/> <l level="1" sID="gen30891"/>et conturbaverunt eam. <l eID="gen30891" level="1"/>

** Micah 7:4

Qui optimus in eis est, quasi paliurus, <l eID="gen30892" level="1"/> <l level="1" sID="gen30893"/>et qui rectus, quasi spina de sepe. <l eID="gen30893" level="1"/> <l level="1" sID="gen30894"/>Dies speculationis tuæ, visitatio tua venit : <l eID="gen30894" level="1"/> <l level="1" sID="gen30895"/>nunc erit vastitas eorum. <l eID="gen30895" level="1"/>

** Micah 7:5

Nolite credere amico, <l eID="gen30896" level="1"/> <l level="1" sID="gen30897"/>et nolite confidere in duce : <l eID="gen30897" level="1"/> <l level="1" sID="gen30898"/>ab ea quæ dormit in sinu tuo custodi claustra oris tui. <l eID="gen30898" level="1"/>

** Micah 7:6

Quia filius contumeliam facit patri, <l eID="gen30899" level="1"/> <l level="1" sID="gen30900"/>et filia consurgit adversus matrem suam : <l eID="gen30900" level="1"/> <l level="1" sID="gen30901"/>nurus adversus socrum suam, <l eID="gen30901" level="1"/> <l level="1" sID="gen30902"/>et inimici hominis domestici ejus. <l eID="gen30902" level="1"/>

** Micah 7:7

Ego autem ad Dominum aspiciam ; <l eID="gen30903" level="1"/> <l level="1" sID="gen30904"/>exspectabo Deum, salvatorem meum : <l eID="gen30904" level="1"/> <l level="1" sID="gen30905"/>audiet me Deus meus. <l eID="gen30905" level="1"/>

** Micah 7:8

Ne læteris, inimica mea, super me, quia cecidi : <l eID="gen30906" level="1"/> <l level="1" sID="gen30907"/>consurgam cum sedero in tenebris : <l eID="gen30907" level="1"/> <l level="1" sID="gen30908"/>Dominus lux mea est. <l eID="gen30908" level="1"/>

** Micah 7:9

Iram Domini portabo, <l eID="gen30909" level="1"/> <l level="1" sID="gen30910"/>quoniam peccavi ei, <l eID="gen30910" level="1"/> <l level="1" sID="gen30911"/>donec causam meam judicet, <l eID="gen30911" level="1"/> <l level="1" sID="gen30912"/>et faciat judicium meum. <l eID="gen30912" level="1"/> <l level="1" sID="gen30913"/>Educet me in lucem : <l eID="gen30913" level="1"/> <l level="1" sID="gen30914"/>videbo justitiam ejus. <l eID="gen30914" level="1"/>

** Micah 7:10

Et aspiciet inimica mea, <l eID="gen30915" level="1"/> <l level="1" sID="gen30916"/>et operietur confusione, <l eID="gen30916" level="1"/> <l level="1" sID="gen30917"/>quæ dicit ad me : Ubi est Dominus Deus tuus ? <l eID="gen30917" level="1"/> <l level="1" sID="gen30918"/>Oculi mei videbunt in eam : <l eID="gen30918" level="1"/> <l level="1" sID="gen30919"/>nunc erit in conculcationem ut lutum platearum. <l eID="gen30919" level="1"/>

** Micah 7:11

Dies, ut ædificentur maceriæ tuæ ; <l eID="gen30920" level="1"/> <l level="1" sID="gen30921"/>in die illa longe fiet lex. <l eID="gen30921" level="1"/>

** Micah 7:12

In die illa et usque ad te veniet de Assur, <l eID="gen30922" level="1"/> <l level="1" sID="gen30923"/>et usque ad civitates munitas, <l eID="gen30923" level="1"/> <l level="1" sID="gen30924"/>et a civitatibus munitis usque ad flumen, <l eID="gen30924" level="1"/> <l level="1" sID="gen30925"/>et ad mare de mari, <l eID="gen30925" level="1"/> <l level="1" sID="gen30926"/>et ad montem de monte. <l eID="gen30926" level="1"/>

** Micah 7:13

Et terra erit in desolationem propter habitatores suos, <l eID="gen30927" level="1"/> <l level="1" sID="gen30928"/>et propter fructum cogitationum eorum. <l eID="gen30928" level="1"/>

** Micah 7:14

Pasce populum tuum in virga tua, <l eID="gen30929" level="1"/> <l level="1" sID="gen30930"/>gregem hæreditatis tuæ, habitantes solos, in saltu, in medio Carmeli. <l eID="gen30930" level="1"/> <l level="1" sID="gen30931"/>Pascentur Basan et Galaad juxta dies antiquos. <l eID="gen30931" level="1"/>

** Micah 7:15

Secundum dies egressionis tuæ de terra Ægypti, <l eID="gen30932" level="1"/> <l level="1" sID="gen30933"/>ostendam ei mirabilia. <l eID="gen30933" level="1"/>

** Micah 7:16

Videbunt gentes, <l eID="gen30934" level="1"/> <l level="1" sID="gen30935"/>et confundentur super omni fortitudine sua. <l eID="gen30935" level="1"/> <l level="1" sID="gen30936"/>Ponent manum super os, <l eID="gen30936" level="1"/> <l level="1" sID="gen30937"/>aures eorum surdæ erunt. <l eID="gen30937" level="1"/>

** Micah 7:17

Lingent pulverem sicut serpentes ; <l eID="gen30938" level="1"/> <l level="1" sID="gen30939"/>velut reptilia terræ perturbabuntur in ædibus suis. <l eID="gen30939" level="1"/> <l level="1" sID="gen30940"/>Dominum Deum nostrum formidabunt, <l eID="gen30940" level="1"/> <l level="1" sID="gen30941"/>et timebunt te. <l eID="gen30941" level="1"/>

** Micah 7:18

Quis, Deus, similis tui, <l eID="gen30942" level="1"/> <l level="1" sID="gen30943"/>qui aufers iniquitatem, <l eID="gen30943" level="1"/> <l level="1" sID="gen30944"/>et transis peccatum reliquiarum hæreditatis tuæ ? <l eID="gen30944" level="1"/> <l level="1" sID="gen30945"/>Non immittet ultra furorem suum, <l eID="gen30945" level="1"/> <l level="1" sID="gen30946"/>quoniam volens misericordiam est. <l eID="gen30946" level="1"/>

** Micah 7:19

Revertetur, et miserebitur nostri ; <l eID="gen30947" level="1"/> <l level="1" sID="gen30948"/>deponet iniquitates nostras, <l eID="gen30948" level="1"/> <l level="1" sID="gen30949"/>et projiciet in profundum maris omnia peccata nostra. <l eID="gen30949" level="1"/>

** Micah 7:20

Dabis veritatem Jacob, <l eID="gen30950" level="1"/> <l level="1" sID="gen30951"/>misericordiam Abraham, <l eID="gen30951" level="1"/> <l level="1" sID="gen30952"/>quæ jurasti patribus nostris a diebus antiquis. <l eID="gen30952" level="1"/> <lg eID="gen30578"/> <chapter eID="Mic.7"/> <div eID="gen30576" osisID="Mic" type="book"/>

