* Nahum 1

** Nahum 1:1

Onus Ninive. Liber visionis Nahum Elcesæi.  <div eID="gen30954" type="x-p"/>

** Nahum 1:2

Deus æmulator, et ulciscens Dominus : <l eID="gen30956" level="1"/> <l level="1" sID="gen30957"/>ulciscens Dominus, et habens furorem : <l eID="gen30957" level="1"/> <l level="1" sID="gen30958"/>ulciscens Dominus in hostes suos, <l eID="gen30958" level="1"/> <l level="1" sID="gen30959"/>et irascens ipse inimicis suis. <l eID="gen30959" level="1"/>

** Nahum 1:3

Dominus patiens, et magnus fortitudine, <l eID="gen30960" level="1"/> <l level="1" sID="gen30961"/>et mundans non faciet innocentem. <l eID="gen30961" level="1"/> <l level="1" sID="gen30962"/>Dominus in tempestate et turbine viæ ejus, <l eID="gen30962" level="1"/> <l level="1" sID="gen30963"/>et nebulæ pulvis pedum ejus. <l eID="gen30963" level="1"/>

** Nahum 1:4

Increpans mare, et exsiccans illud, <l eID="gen30964" level="1"/> <l level="1" sID="gen30965"/>et omnia flumina ad desertum deducens. <l eID="gen30965" level="1"/> <l level="1" sID="gen30966"/>Infirmatus est Basan et Carmelus, <l eID="gen30966" level="1"/> <l level="1" sID="gen30967"/>et flos Libani elanguit. <l eID="gen30967" level="1"/>

** Nahum 1:5

Montes commoti sunt ab eo, <l eID="gen30968" level="1"/> <l level="1" sID="gen30969"/>et colles desolati sunt : <l eID="gen30969" level="1"/> <l level="1" sID="gen30970"/>et contremuit terra a facie ejus, <l eID="gen30970" level="1"/> <l level="1" sID="gen30971"/>et orbis, et omnes habitantes in eo. <l eID="gen30971" level="1"/>

** Nahum 1:6

Ante faciem indignationis ejus quis stabit ? <l eID="gen30972" level="1"/> <l level="1" sID="gen30973"/>et quis resistet in ira furoris ejus ? <l eID="gen30973" level="1"/> <l level="1" sID="gen30974"/>Indignatio ejus effusa est ut ignis, <l eID="gen30974" level="1"/> <l level="1" sID="gen30975"/>et petræ dissolutæ sunt ab eo. <l eID="gen30975" level="1"/>

** Nahum 1:7

Bonus Dominus, <l eID="gen30976" level="1"/> <l level="1" sID="gen30977"/>et confortans in die tribulationis, <l eID="gen30977" level="1"/> <l level="1" sID="gen30978"/>et sciens sperantes in se. <l eID="gen30978" level="1"/>

** Nahum 1:8

Et in diluvio prætereunte consummationem faciet loci ejus, <l eID="gen30979" level="1"/> <l level="1" sID="gen30980"/>et inimicos ejus persequentur tenebræ. <l eID="gen30980" level="1"/>

** Nahum 1:9

Quid cogitatis contra Dominum ? <l eID="gen30981" level="1"/> <l level="1" sID="gen30982"/>Consummationem ipse faciet : <l eID="gen30982" level="1"/> <l level="1" sID="gen30983"/>non consurget duplex tribulatio, <l eID="gen30983" level="1"/>

** Nahum 1:10

quia sicut spinæ se invicem complectuntur, <l eID="gen30984" level="1"/> <l level="1" sID="gen30985"/>sic convivium eorum pariter potantium ; <l eID="gen30985" level="1"/> <l level="1" sID="gen30986"/>consumentur quasi stipula ariditate plena. <l eID="gen30986" level="1"/>

** Nahum 1:11

Ex te exibit cogitans contra Dominum malitiam, <l eID="gen30987" level="1"/> <l level="1" sID="gen30988"/>mente pertractans prævaricationem. <l eID="gen30988" level="1"/>

** Nahum 1:12

Hæc dicit Dominus : <l eID="gen30989" level="1"/> <l level="1" sID="gen30990"/>Si perfecti fuerint, et ita plures, <l eID="gen30990" level="1"/> <l level="1" sID="gen30991"/>sic quoque attondentur, et pertransibit : <l eID="gen30991" level="1"/> <l level="1" sID="gen30992"/>afflixi te, et non affligam te ultra. <l eID="gen30992" level="1"/>

** Nahum 1:13

Et nunc conteram virgam ejus de dorso tuo, <l eID="gen30993" level="1"/> <l level="1" sID="gen30994"/>et vincula tua disrumpam. <l eID="gen30994" level="1"/>

** Nahum 1:14

Et præcipiet super te Dominus ; <l eID="gen30995" level="1"/> <l level="1" sID="gen30996"/>non seminabitur ex nomine tuo amplius : <l eID="gen30996" level="1"/> <l level="1" sID="gen30997"/>de domo Dei tui interficiam sculptile, et conflatile ; <l eID="gen30997" level="1"/> <l level="1" sID="gen30998"/>ponam sepulchrum tuum, quia inhonoratus es. <l eID="gen30998" level="1"/>

** Nahum 1:15

Ecce super montes pedes evangelizantis, <l eID="gen30999" level="1"/> <l level="1" sID="gen31000"/>et annuntiantis pacem. <l eID="gen31000" level="1"/> <l level="1" sID="gen31001"/>Celebra, Juda, festivitates tuas, <l eID="gen31001" level="1"/> <l level="1" sID="gen31002"/>et redde vota tua, <l eID="gen31002" level="1"/> <l level="1" sID="gen31003"/>quia non adjiciet ultra ut pertranseat in te Belial : <l eID="gen31003" level="1"/> <l level="1" sID="gen31004"/>universus interiit.  <chapter eID="Nah.1"/>

* Nahum 2

** Nahum 2:1

Ascendit qui dispergat coram te, <l eID="gen31005" level="1"/> <l level="1" sID="gen31006"/>qui custodiat obsidionem : <l eID="gen31006" level="1"/> <l level="1" sID="gen31007"/>contemplare viam, conforta lumbos, <l eID="gen31007" level="1"/> <l level="1" sID="gen31008"/>robora virtutem valde. <l eID="gen31008" level="1"/>

** Nahum 2:2

Quia reddidit Dominus superbiam Jacob, <l eID="gen31009" level="1"/> <l level="1" sID="gen31010"/>sicut superbiam Israël ; <l eID="gen31010" level="1"/> <l level="1" sID="gen31011"/>quia vastatores dissipaverunt eos, <l eID="gen31011" level="1"/> <l level="1" sID="gen31012"/>et propagines eorum corruperunt. <l eID="gen31012" level="1"/>

** Nahum 2:3

Clypeus fortium ejus ignitus, <l eID="gen31013" level="1"/> <l level="1" sID="gen31014"/>viri exercitus in coccineis ; <l eID="gen31014" level="1"/> <l level="1" sID="gen31015"/>igneæ habenæ currus in die præparationis ejus, <l eID="gen31015" level="1"/> <l level="1" sID="gen31016"/>et agitatores consopiti sunt. <l eID="gen31016" level="1"/>

** Nahum 2:4

In itineribus conturbati sunt ; <l eID="gen31017" level="1"/> <l level="1" sID="gen31018"/>quadrigæ collisæ sunt in plateis : <l eID="gen31018" level="1"/> <l level="1" sID="gen31019"/>aspectus eorum quasi lampades, <l eID="gen31019" level="1"/> <l level="1" sID="gen31020"/>quasi fulgura discurrentia. <l eID="gen31020" level="1"/>

** Nahum 2:5

Recordabitur fortium suorum ; <l eID="gen31021" level="1"/> <l level="1" sID="gen31022"/>ruent in itineribus suis : <l eID="gen31022" level="1"/> <l level="1" sID="gen31023"/>velociter ascendent muros ejus, <l eID="gen31023" level="1"/> <l level="1" sID="gen31024"/>et præparabitur umbraculum. <l eID="gen31024" level="1"/>

** Nahum 2:6

Portæ fluviorum apertæ sunt, <l eID="gen31025" level="1"/> <l level="1" sID="gen31026"/>et templum ad solum dirutum. <l eID="gen31026" level="1"/>

** Nahum 2:7

Et miles captivus abductus est, <l eID="gen31027" level="1"/> <l level="1" sID="gen31028"/>et ancillæ ejus minabantur gementes ut columbæ, <l eID="gen31028" level="1"/> <l level="1" sID="gen31029"/>murmurantes in cordibus suis. <l eID="gen31029" level="1"/>

** Nahum 2:8

Et Ninive quasi piscina aquarum aquæ ejus ; <l eID="gen31030" level="1"/> <l level="1" sID="gen31031"/>ipsi vero fugerunt. State, state ! <l eID="gen31031" level="1"/> <l level="1" sID="gen31032"/>et non est qui revertatur. <l eID="gen31032" level="1"/>

** Nahum 2:9

Diripite argentum, diripite aurum : <l eID="gen31033" level="1"/> <l level="1" sID="gen31034"/>et non est finis divitiarum ex omnibus vasis desiderabilibus. <l eID="gen31034" level="1"/>

** Nahum 2:10

Dissipata est, et scissa, et dilacerata ; <l eID="gen31035" level="1"/> <l level="1" sID="gen31036"/>et cor tabescens, et dissolutio geniculorum, <l eID="gen31036" level="1"/> <l level="1" sID="gen31037"/>et defectio in cunctis renibus, <l eID="gen31037" level="1"/> <l level="1" sID="gen31038"/>et facies omnium eorum sicut nigredo ollæ. <l eID="gen31038" level="1"/>

** Nahum 2:11

Ubi est habitaculum leonum, <l eID="gen31039" level="1"/> <l level="1" sID="gen31040"/>et pascua catulorum leonum, <l eID="gen31040" level="1"/> <l level="1" sID="gen31041"/>ad quam ivit leo ut ingrederetur illuc catulus leonis, <l eID="gen31041" level="1"/> <l level="1" sID="gen31042"/>et non est qui exterreat ? <l eID="gen31042" level="1"/>

** Nahum 2:12

Leo cepit sufficienter catulis suis, <l eID="gen31043" level="1"/> <l level="1" sID="gen31044"/>et necavit leænis suis, <l eID="gen31044" level="1"/> <l level="1" sID="gen31045"/>et implevit præda speluncas suas, <l eID="gen31045" level="1"/> <l level="1" sID="gen31046"/>et cubile suum rapina. <l eID="gen31046" level="1"/>

** Nahum 2:13

Ecce ego ad te, dicit Dominus exercituum, <l eID="gen31047" level="1"/> <l level="1" sID="gen31048"/>et succendam usque ad fumum quadrigas tuas, <l eID="gen31048" level="1"/> <l level="1" sID="gen31049"/>et leunculos tuos comedet gladius, <l eID="gen31049" level="1"/> <l level="1" sID="gen31050"/>et exterminabo de terra prædam tuam, <l eID="gen31050" level="1"/> <l level="1" sID="gen31051"/>et non audietur ultra vox nuntiorum tuorum.  <chapter eID="Nah.2"/>

* Nahum 3

** Nahum 3:1

Væ civitas sanguinum, <l eID="gen31052" level="1"/> <l level="1" sID="gen31053"/>universa mendacii dilaceratione plena ! <l eID="gen31053" level="1"/> <l level="1" sID="gen31054"/>non recedet a te rapina. <l eID="gen31054" level="1"/>

** Nahum 3:2

Vox flagelli, et vox impetus rotæ, et equi frementis, <l eID="gen31055" level="1"/> <l level="1" sID="gen31056"/>et quadrigæ ferventis, et equitis ascendentis, <l eID="gen31056" level="1"/>

** Nahum 3:3

et micantis gladii, et fulgurantis hastæ, <l eID="gen31057" level="1"/> <l level="1" sID="gen31058"/>et multitudinis interfectæ, et gravis ruinæ ; <l eID="gen31058" level="1"/> <l level="1" sID="gen31059"/>nec est finis cadaverum, <l eID="gen31059" level="1"/> <l level="1" sID="gen31060"/>et corruent in corporibus suis. <l eID="gen31060" level="1"/>

** Nahum 3:4

Propter multitudinem fornicationum meretricis <l eID="gen31061" level="1"/> <l level="1" sID="gen31062"/>speciosæ, et gratæ, et habentis maleficia, <l eID="gen31062" level="1"/> <l level="1" sID="gen31063"/>quæ vendidit gentes in fornicationibus suis, <l eID="gen31063" level="1"/> <l level="1" sID="gen31064"/>et familias in maleficiis suis. <l eID="gen31064" level="1"/>

** Nahum 3:5

Ecce ego ad te, dicit Dominus exercituum, <l eID="gen31065" level="1"/> <l level="1" sID="gen31066"/>et revelabo pudenda tua in facie tua ; <l eID="gen31066" level="1"/> <l level="1" sID="gen31067"/>et ostendam gentibus nuditatem tuam, <l eID="gen31067" level="1"/> <l level="1" sID="gen31068"/>et regnis ignominiam tuam. <l eID="gen31068" level="1"/>

** Nahum 3:6

Et projiciam super te abominationes, <l eID="gen31069" level="1"/> <l level="1" sID="gen31070"/>et contumeliis te afficiam, <l eID="gen31070" level="1"/> <l level="1" sID="gen31071"/>et ponam te in exemplum. <l eID="gen31071" level="1"/>

** Nahum 3:7

Et erit : omnis qui viderit te resiliet a te, <l eID="gen31072" level="1"/> <l level="1" sID="gen31073"/>et dicet : Vastata est Ninive. <l eID="gen31073" level="1"/> <l level="1" sID="gen31074"/>Quis commovebit super te caput ? <l eID="gen31074" level="1"/> <l level="1" sID="gen31075"/>unde quæram consolatorem tibi ? <l eID="gen31075" level="1"/>

** Nahum 3:8

Numquid melior es Alexandria populorum, <l eID="gen31076" level="1"/> <l level="1" sID="gen31077"/>quæ habitat in fluminibus ? <l eID="gen31077" level="1"/> <l level="1" sID="gen31078"/>aquæ in circuitu ejus ; <l eID="gen31078" level="1"/> <l level="1" sID="gen31079"/>cujus divitiæ, mare ; <l eID="gen31079" level="1"/> <l level="1" sID="gen31080"/>aquæ, muri ejus. <l eID="gen31080" level="1"/>

** Nahum 3:9

Æthiopia fortitudo ejus, et Ægyptus, et non est finis ; <l eID="gen31081" level="1"/> <l level="1" sID="gen31082"/>Africa et Libyes fuerunt in auxilio tuo. <l eID="gen31082" level="1"/>

** Nahum 3:10

Sed et ipsa in transmigrationem ducta est in captivitatem : <l eID="gen31083" level="1"/> <l level="1" sID="gen31084"/>parvuli ejus elisi sunt in capite omnium viarum, <l eID="gen31084" level="1"/> <l level="1" sID="gen31085"/>et super inclytos ejus miserunt sortem, <l eID="gen31085" level="1"/> <l level="1" sID="gen31086"/>et omnes optimates ejus confixi sunt in compedibus. <l eID="gen31086" level="1"/>

** Nahum 3:11

Et tu ergo inebriaberis, et eris despecta : <l eID="gen31087" level="1"/> <l level="1" sID="gen31088"/>et tu quæres auxilium ab inimico. <l eID="gen31088" level="1"/>

** Nahum 3:12

Omnes munitiones tuæ sicut ficus cum grossis suis : <l eID="gen31089" level="1"/> <l level="1" sID="gen31090"/>si concussæ fuerint, cadent in os comedentis. <l eID="gen31090" level="1"/>

** Nahum 3:13

Ecce populus tuus mulieres in medio tui : <l eID="gen31091" level="1"/> <l level="1" sID="gen31092"/>inimicis tuis adapertione pandentur portæ terræ tuæ, <l eID="gen31092" level="1"/> <l level="1" sID="gen31093"/>devorabit ignis vectes tuos. <l eID="gen31093" level="1"/>

** Nahum 3:14

Aquam propter obsidionem hauri tibi : <l eID="gen31094" level="1"/> <l level="1" sID="gen31095"/>exstrue munitiones tuas, <l eID="gen31095" level="1"/> <l level="1" sID="gen31096"/>intra in lutum, et calca, <l eID="gen31096" level="1"/> <l level="1" sID="gen31097"/>subigens tene laterem. <l eID="gen31097" level="1"/>

** Nahum 3:15

Ibi comedet te ignis, <l eID="gen31098" level="1"/> <l level="1" sID="gen31099"/>peribis gladio, devorabit te ut bruchus : <l eID="gen31099" level="1"/> <l level="1" sID="gen31100"/>congregare ut bruchus, <l eID="gen31100" level="1"/> <l level="1" sID="gen31101"/>multiplicare ut locusta. <l eID="gen31101" level="1"/>

** Nahum 3:16

Plures fecisti negotiationes tuas quam stellæ sint cæli ; <l eID="gen31102" level="1"/> <l level="1" sID="gen31103"/>bruchus expansus est, et avolavit. <l eID="gen31103" level="1"/>

** Nahum 3:17

Custodes tui quasi locustæ, <l eID="gen31104" level="1"/> <l level="1" sID="gen31105"/>et parvuli tui quasi locustæ locustarum, <l eID="gen31105" level="1"/> <l level="1" sID="gen31106"/>quæ considunt in sepibus in die frigoris : <l eID="gen31106" level="1"/> <l level="1" sID="gen31107"/>sol ortus est, et avolaverunt, <l eID="gen31107" level="1"/> <l level="1" sID="gen31108"/>et non est cognitus locus earum ubi fuerint. <l eID="gen31108" level="1"/>

** Nahum 3:18

Dormitaverunt pastores tui, rex Assur, <l eID="gen31109" level="1"/> <l level="1" sID="gen31110"/>sepelientur principes tui : <l eID="gen31110" level="1"/> <l level="1" sID="gen31111"/>latitavit populus tuus in montibus, <l eID="gen31111" level="1"/> <l level="1" sID="gen31112"/>et non est qui congreget. <l eID="gen31112" level="1"/>

** Nahum 3:19

Non est obscura contritio tua ; <l eID="gen31113" level="1"/> <l level="1" sID="gen31114"/>pessima est plaga tua. <l eID="gen31114" level="1"/> <l level="1" sID="gen31115"/>Omnes qui audierunt auditionem tuam compresserunt manum super te : <l eID="gen31115" level="1"/> <l level="1" sID="gen31116"/>quia super quem non transiit malitia tua semper ? <l eID="gen31116" level="1"/> <lg eID="gen30955"/> <chapter eID="Nah.3"/> <div eID="gen30953" osisID="Nah" type="book"/>

