* Obadiah 1

** Obadiah 1:1

Visio Abdiæ. <div eID="gen30462" type="x-p"/> <lg sID="gen30463"/> <l level="1" sID="gen30464"/>Hæc dicit Dominus Deus ad Edom : <l eID="gen30464" level="1"/> <l level="1" sID="gen30465"/>Auditum audivimus a Domino, <l eID="gen30465" level="1"/> <l level="1" sID="gen30466"/>et legatum ad gentes misit : <l eID="gen30466" level="1"/> <l level="1" sID="gen30467"/>surgite, et consurgamus adversus eum in prælium. <l eID="gen30467" level="1"/>

** Obadiah 1:2

Ecce parvulum dedi te in gentibus : <l eID="gen30468" level="1"/> <l level="1" sID="gen30469"/>contemptibilis tu es valde. <l eID="gen30469" level="1"/>

** Obadiah 1:3

Superbia cordis tui extulit te, <l eID="gen30470" level="1"/> <l level="1" sID="gen30471"/>habitantem in scissuris petrarum, <l eID="gen30471" level="1"/> <l level="1" sID="gen30472"/>exaltantem solium tuum ; <l eID="gen30472" level="1"/> <l level="1" sID="gen30473"/>qui dicis in corde tuo : <l eID="gen30473" level="1"/> <l level="1" sID="gen30474"/>Quis detrahet me in terram ? <l eID="gen30474" level="1"/>

** Obadiah 1:4

Si exaltatus fueris ut aquila, <l eID="gen30475" level="1"/> <l level="1" sID="gen30476"/>et si inter sidera posueris nidum tuum, <l eID="gen30476" level="1"/> <l level="1" sID="gen30477"/>inde detraham te, dicit Dominus. <l eID="gen30477" level="1"/>

** Obadiah 1:5

Si fures introissent ad te, <l eID="gen30478" level="1"/> <l level="1" sID="gen30479"/>si latrones per noctem, <l eID="gen30479" level="1"/> <l level="1" sID="gen30480"/>quomodo conticuisses ? <l eID="gen30480" level="1"/> <l level="1" sID="gen30481"/>nonne furati essent sufficientia sibi ? <l eID="gen30481" level="1"/> <l level="1" sID="gen30482"/>Si vindemiatores introissent ad te, <l eID="gen30482" level="1"/> <l level="1" sID="gen30483"/>numquid saltem racemum reliquissent tibi ? <l eID="gen30483" level="1"/>

** Obadiah 1:6

Quomodo scrutati sunt Esau ; <l eID="gen30484" level="1"/> <l level="1" sID="gen30485"/>investigaverunt abscondita ejus ? <l eID="gen30485" level="1"/>

** Obadiah 1:7

Usque ad terminum emiserunt te : <l eID="gen30486" level="1"/> <l level="1" sID="gen30487"/>omnes viri fœderis tui illuserunt tibi : <l eID="gen30487" level="1"/> <l level="1" sID="gen30488"/>invaluerunt adversum te viri pacis tuæ, <l eID="gen30488" level="1"/> <l level="1" sID="gen30489"/>qui comedunt tecum, ponent insidias subter te ; <l eID="gen30489" level="1"/> <l level="1" sID="gen30490"/>non est prudentia in eo. <l eID="gen30490" level="1"/>

** Obadiah 1:8

Numquid non in die illa, dicit Dominus, <l eID="gen30491" level="1"/> <l level="1" sID="gen30492"/>perdam sapientes de Idumæa, <l eID="gen30492" level="1"/> <l level="1" sID="gen30493"/>et prudentiam de monte Esau ? <l eID="gen30493" level="1"/>

** Obadiah 1:9

Et timebunt fortes tui a meridie, <l eID="gen30494" level="1"/> <l level="1" sID="gen30495"/>ut intereat vir de monte Esau. <l eID="gen30495" level="1"/>

** Obadiah 1:10

Propter interfectionem, <l eID="gen30496" level="1"/> <l level="1" sID="gen30497"/>et propter iniquitatem in fratrem tuum Jacob, <l eID="gen30497" level="1"/> <l level="1" sID="gen30498"/>operiet te confusio, et peribis in æternum. <l eID="gen30498" level="1"/>

** Obadiah 1:11

In die cum stares adversus eum, <l eID="gen30499" level="1"/> <l level="1" sID="gen30500"/>quando capiebant alieni exercitum ejus, <l eID="gen30500" level="1"/> <l level="1" sID="gen30501"/>et extranei ingrediebantur portas ejus, <l eID="gen30501" level="1"/> <l level="1" sID="gen30502"/>et super Jerusalem mittebant sortem, <l eID="gen30502" level="1"/> <l level="1" sID="gen30503"/>tu quoque eras quasi unus ex eis. <l eID="gen30503" level="1"/>

** Obadiah 1:12

Et non despicies in die fratris tui, <l eID="gen30504" level="1"/> <l level="1" sID="gen30505"/>in die peregrinationis ejus : <l eID="gen30505" level="1"/> <l level="1" sID="gen30506"/>et non lætaberis super filios Juda <l eID="gen30506" level="1"/> <l level="1" sID="gen30507"/>in die perditionis eorum : <l eID="gen30507" level="1"/> <l level="1" sID="gen30508"/>et non magnificabis os tuum <l eID="gen30508" level="1"/> <l level="1" sID="gen30509"/>in die angustiæ. <l eID="gen30509" level="1"/>

** Obadiah 1:13

Neque ingredieris portam populi mei <l eID="gen30510" level="1"/> <l level="1" sID="gen30511"/>in die ruinæ eorum ; <l eID="gen30511" level="1"/> <l level="1" sID="gen30512"/>neque despicies et tu in malis ejus <l eID="gen30512" level="1"/> <l level="1" sID="gen30513"/>in die vastitatis illius. <l eID="gen30513" level="1"/> <l level="1" sID="gen30514"/>Et non emitteris adversus exercitum ejus <l eID="gen30514" level="1"/> <l level="1" sID="gen30515"/>in die vastitatis illius, <l eID="gen30515" level="1"/>

** Obadiah 1:14

neque stabis in exitibus <l eID="gen30516" level="1"/> <l level="1" sID="gen30517"/>ut interficias eos qui fugerint, <l eID="gen30517" level="1"/> <l level="1" sID="gen30518"/>et non concludes reliquos ejus <l eID="gen30518" level="1"/> <l level="1" sID="gen30519"/>in die tribulationis. <l eID="gen30519" level="1"/>

** Obadiah 1:15

Quoniam juxta est dies Domini super omnes gentes : <l eID="gen30520" level="1"/> <l level="1" sID="gen30521"/>sicut fecisti, fiet tibi ; <l eID="gen30521" level="1"/> <l level="1" sID="gen30522"/>retributionem tuam convertet in caput tuum. <l eID="gen30522" level="1"/>

** Obadiah 1:16

Quomodo enim bibistis super montem sanctum meum, <l eID="gen30523" level="1"/> <l level="1" sID="gen30524"/>bibent omnes gentes jugiter : <l eID="gen30524" level="1"/> <l level="1" sID="gen30525"/>et bibent, et absorbebunt, <l eID="gen30525" level="1"/> <l level="1" sID="gen30526"/>et erunt quasi non sint. <l eID="gen30526" level="1"/> <lg eID="gen30463"/>

** Obadiah 1:17

Et in monte Sion erit salvatio, et erit sanctus ; <div eID="gen30527" type="x-p"/> <lg sID="gen30528"/> <l level="1" sID="gen30529"/>et possidebit domus Jacob eos qui se possederant. <l eID="gen30529" level="1"/>

** Obadiah 1:18

Et erit domus Jacob ignis, <l eID="gen30530" level="1"/> <l level="1" sID="gen30531"/>et domus Joseph flamma, <l eID="gen30531" level="1"/> <l level="1" sID="gen30532"/>et domus Esau stipula : <l eID="gen30532" level="1"/> <l level="1" sID="gen30533"/>et succendentur in eis, et devorabunt eos, <l eID="gen30533" level="1"/> <l level="1" sID="gen30534"/>et non erunt reliquiæ domus Esau, <l eID="gen30534" level="1"/> <l level="1" sID="gen30535"/>quia Dominus locutus est. <l eID="gen30535" level="1"/>

** Obadiah 1:19

Et hæreditabunt hi, qui ad austrum sunt, montem Esau, <l eID="gen30536" level="1"/> <l level="1" sID="gen30537"/>et qui in campestribus, Philisthiim : <l eID="gen30537" level="1"/> <l level="1" sID="gen30538"/>et possidebunt regionem Ephraim et regionem Samariæ, <l eID="gen30538" level="1"/> <l level="1" sID="gen30539"/>et Benjamin possidebit Galaad. <l eID="gen30539" level="1"/>

** Obadiah 1:20

Et transmigratio exercitus hujus filiorum Israël, <l eID="gen30540" level="1"/> <l level="1" sID="gen30541"/>omnia loca Chananæorum usque ad Sareptam : <l eID="gen30541" level="1"/> <l level="1" sID="gen30542"/>et transmigratio Jerusalem, quæ in Bosphoro est, <l eID="gen30542" level="1"/> <l level="1" sID="gen30543"/>possidebit civitates austri. <l eID="gen30543" level="1"/>

** Obadiah 1:21

Et ascendent salvatores in montem Sion judicare montem Esau, <l eID="gen30544" level="1"/> <l level="1" sID="gen30545"/>et erit Domino regnum. <l eID="gen30545" level="1"/> <lg eID="gen30528"/> <chapter eID="Obad.1"/> <div eID="gen30461" osisID="Obad" type="book"/>

