* Song of Solomon 1

** Song of Solomon 1:1

Osculetur me osculo oris sui ; <l eID="gen12915" level="1"/> <l level="1" sID="gen12916"/>quia meliora sunt ubera tua vino, <l eID="gen12916" level="1"/>

** Song of Solomon 1:2

fragrantia unguentis optimis. <l eID="gen12917" level="1"/> <l level="1" sID="gen12918"/>Oleum effusum nomen tuum ; <l eID="gen12918" level="1"/> <l level="1" sID="gen12919"/>ideo adolescentulæ dilexerunt te. <l eID="gen12919" level="1"/> <lg eID="gen12914"/>

** Song of Solomon 1:3

Trahe me, post te curremus <l eID="gen12921" level="1"/> <l level="1" sID="gen12922"/>in odorem unguentorum tuorum. <l eID="gen12922" level="1"/> <l level="1" sID="gen12923"/>Introduxit me rex in cellaria sua ; <l eID="gen12923" level="1"/> <l level="1" sID="gen12924"/>exsultabimus et lætabimur in te, <l eID="gen12924" level="1"/> <l level="1" sID="gen12925"/>memores uberum tuorum super vinum. <l eID="gen12925" level="1"/> <l level="1" sID="gen12926"/>Recti diligunt te. <l eID="gen12926" level="1"/> <lg eID="gen12920"/>

** Song of Solomon 1:4

Nigra sum, sed formosa, filiæ Jerusalem, <l eID="gen12928" level="1"/> <l level="1" sID="gen12929"/>sicut tabernacula Cedar, sicut pelles Salomonis. <l eID="gen12929" level="1"/>

** Song of Solomon 1:5

Nolite me considerare quod fusca sim, <l eID="gen12930" level="1"/> <l level="1" sID="gen12931"/>quia decoloravit me sol. <l eID="gen12931" level="1"/> <l level="1" sID="gen12932"/>Filii matris meæ pugnaverunt contra me ; <l eID="gen12932" level="1"/> <l level="1" sID="gen12933"/>posuerunt me custodem in vineis : <l eID="gen12933" level="1"/> <l level="1" sID="gen12934"/>vineam meam non custodivi. <l eID="gen12934" level="1"/>

** Song of Solomon 1:6

Indica mihi, quem diligit anima mea, ubi pascas, <l eID="gen12935" level="1"/> <l level="1" sID="gen12936"/>ubi cubes in meridie, <l eID="gen12936" level="1"/> <l level="1" sID="gen12937"/>ne vagari incipiam post greges sodalium tuorum. <l eID="gen12937" level="1"/> <lg eID="gen12927"/>

** Song of Solomon 1:7

Si ignoras te, o pulcherrima inter mulieres, <l eID="gen12939" level="1"/> <l level="1" sID="gen12940"/>egredere, et abi post vestigia gregum, <l eID="gen12940" level="1"/> <l level="1" sID="gen12941"/>et pasce hædos tuos juxta tabernacula pastorum. <l eID="gen12941" level="1"/>

** Song of Solomon 1:8

Equitatui meo in curribus Pharaonis <l eID="gen12942" level="1"/> <l level="1" sID="gen12943"/>assimilavi te, amica mea. <l eID="gen12943" level="1"/>

** Song of Solomon 1:9

Pulchræ sunt genæ tuæ sicut turturis ; <l eID="gen12944" level="1"/> <l level="1" sID="gen12945"/>collum tuum sicut monilia. <l eID="gen12945" level="1"/>

** Song of Solomon 1:10

Murenulas aureas faciemus tibi, <l eID="gen12946" level="1"/> <l level="1" sID="gen12947"/>vermiculatas argento. <l eID="gen12947" level="1"/> <lg eID="gen12938"/>

** Song of Solomon 1:11

Dum esset rex in accubitu suo, <l eID="gen12949" level="1"/> <l level="1" sID="gen12950"/>nardus mea dedit odorem suum. <l eID="gen12950" level="1"/>

** Song of Solomon 1:12

Fasciculus myrrhæ dilectus meus mihi ; <l eID="gen12951" level="1"/> <l level="1" sID="gen12952"/>inter ubera mea commorabitur. <l eID="gen12952" level="1"/>

** Song of Solomon 1:13

Botrus cypri dilectus meus mihi <l eID="gen12953" level="1"/> <l level="1" sID="gen12954"/>in vineis Engaddi. <l eID="gen12954" level="1"/> <lg eID="gen12948"/>

** Song of Solomon 1:14

Ecce tu pulchra es, amica mea ! ecce tu pulchra es ! <l eID="gen12956" level="1"/> <l level="1" sID="gen12957"/>Oculi tui columbarum. <l eID="gen12957" level="1"/> <lg eID="gen12955"/>

** Song of Solomon 1:15

Ecce tu pulcher es, dilecte mi, et decorus ! <l eID="gen12959" level="1"/> <l level="1" sID="gen12960"/>Lectulus noster floridus. <l eID="gen12960" level="1"/>

** Song of Solomon 1:16

Tigna domorum nostrarum cedrina, <l eID="gen12961" level="1"/> <l level="1" sID="gen12962"/>laquearia nostra cypressina.  <chapter eID="Song.1"/>

* Song of Solomon 2

** Song of Solomon 2:1

Ego flos campi, <l eID="gen12963" level="1"/> <l level="1" sID="gen12964"/>et lilium convallium. <l eID="gen12964" level="1"/> <lg eID="gen12958"/>

** Song of Solomon 2:2

Sicut lilium inter spinas, <l eID="gen12966" level="1"/> <l level="1" sID="gen12967"/>sic amica mea inter filias. <l eID="gen12967" level="1"/> <lg eID="gen12965"/>

** Song of Solomon 2:3

Sicut malus inter ligna silvarum, <l eID="gen12969" level="1"/> <l level="1" sID="gen12970"/>sic dilectus meus inter filios. <l eID="gen12970" level="1"/> <l level="1" sID="gen12971"/>Sub umbra illius quem desideraveram sedi, <l eID="gen12971" level="1"/> <l level="1" sID="gen12972"/>et fructus ejus dulcis gutturi meo. <l eID="gen12972" level="1"/>

** Song of Solomon 2:4

Introduxit me in cellam vinariam ; <l eID="gen12973" level="1"/> <l level="1" sID="gen12974"/>ordinavit in me caritatem. <l eID="gen12974" level="1"/>

** Song of Solomon 2:5

Fulcite me floribus, <l eID="gen12975" level="1"/> <l level="1" sID="gen12976"/>stipate me malis, <l eID="gen12976" level="1"/> <l level="1" sID="gen12977"/>quia amore langueo. <l eID="gen12977" level="1"/>

** Song of Solomon 2:6

Læva ejus sub capite meo, <l eID="gen12978" level="1"/> <l level="1" sID="gen12979"/>et dextera illius amplexabitur me. <l eID="gen12979" level="1"/> <lg eID="gen12968"/>

** Song of Solomon 2:7

Adjuro vos, filiæ Jerusalem, <l eID="gen12981" level="1"/> <l level="1" sID="gen12982"/>per capreas cervosque camporum, <l eID="gen12982" level="1"/> <l level="1" sID="gen12983"/>ne suscitetis, neque evigilare faciatis dilectam, <l eID="gen12983" level="1"/> <l level="1" sID="gen12984"/>quoadusque ipsa velit. <l eID="gen12984" level="1"/> <lg eID="gen12980"/>

** Song of Solomon 2:8

Vox dilecti mei ; ecce iste venit, <l eID="gen12986" level="1"/> <l level="1" sID="gen12987"/>saliens in montibus, transiliens colles. <l eID="gen12987" level="1"/>

** Song of Solomon 2:9

Similis est dilectus meus capreæ, <l eID="gen12988" level="1"/> <l level="1" sID="gen12989"/>hinnuloque cervorum. <l eID="gen12989" level="1"/> <l level="1" sID="gen12990"/>En ipse stat post parietem nostrum, <l eID="gen12990" level="1"/> <l level="1" sID="gen12991"/>respiciens per fenestras, <l eID="gen12991" level="1"/> <l level="1" sID="gen12992"/>prospiciens per cancellos. <l eID="gen12992" level="1"/>

** Song of Solomon 2:10

En dilectus meus loquitur mihi. <l eID="gen12993" level="1"/> <lg eID="gen12985"/>  <lg sID="gen12994"/> <l level="1" sID="gen12995"/>Surge, propera, amica mea, <l eID="gen12995" level="1"/> <l level="1" sID="gen12996"/>columba mea, formosa mea, et veni : <l eID="gen12996" level="1"/>

** Song of Solomon 2:11

jam enim hiems transiit ; <l eID="gen12997" level="1"/> <l level="1" sID="gen12998"/>imber abiit, et recessit. <l eID="gen12998" level="1"/>

** Song of Solomon 2:12

Flores apparuerunt in terra nostra ; <l eID="gen12999" level="1"/> <l level="1" sID="gen13000"/>tempus putationis advenit : <l eID="gen13000" level="1"/> <l level="1" sID="gen13001"/>vox turturis audita est in terra nostra ; <l eID="gen13001" level="1"/>

** Song of Solomon 2:13

ficus protulit grossos suos ; <l eID="gen13002" level="1"/> <l level="1" sID="gen13003"/>vineæ florentes dederunt odorem suum. <l eID="gen13003" level="1"/> <l level="1" sID="gen13004"/>Surge, amica mea, speciosa mea, et veni : <l eID="gen13004" level="1"/>

** Song of Solomon 2:14

columba mea, in foraminibus petræ, in caverna maceriæ, <l eID="gen13005" level="1"/> <l level="1" sID="gen13006"/>ostende mihi faciem tuam, <l eID="gen13006" level="1"/> <l level="1" sID="gen13007"/>sonet vox tua in auribus meis : <l eID="gen13007" level="1"/> <l level="1" sID="gen13008"/>vox enim tua dulcis, et facies tua decora. <l eID="gen13008" level="1"/> <lg eID="gen12994"/>

** Song of Solomon 2:15

Capite nobis vulpes parvulas <l eID="gen13010" level="1"/> <l level="1" sID="gen13011"/>quæ demoliuntur vineas : <l eID="gen13011" level="1"/> <l level="1" sID="gen13012"/>nam vinea nostra floruit. <l eID="gen13012" level="1"/>

** Song of Solomon 2:16

Dilectus meus mihi, et ego illi, <l eID="gen13013" level="1"/> <l level="1" sID="gen13014"/>qui pascitur inter lilia, <l eID="gen13014" level="1"/>

** Song of Solomon 2:17

donec aspiret dies, et inclinentur umbræ. <l eID="gen13015" level="1"/> <l level="1" sID="gen13016"/>Revertere ; similis esto, dilecte mi, capreæ, <l eID="gen13016" level="1"/> <l level="1" sID="gen13017"/>hinnuloque cervorum super montes Bether.  <chapter eID="Song.2"/>

* Song of Solomon 3

** Song of Solomon 3:1

In lectulo meo, per noctes, <l eID="gen13018" level="1"/> <l level="1" sID="gen13019"/>quæsivi quem diligit anima mea : <l eID="gen13019" level="1"/> <l level="1" sID="gen13020"/>quæsivi illum, et non inveni. <l eID="gen13020" level="1"/>

** Song of Solomon 3:2

Surgam, et circuibo civitatem : <l eID="gen13021" level="1"/> <l level="1" sID="gen13022"/>per vicos et plateas <l eID="gen13022" level="1"/> <l level="1" sID="gen13023"/>quæram quem diligit anima mea : <l eID="gen13023" level="1"/> <l level="1" sID="gen13024"/>quæsivi illum, et non inveni. <l eID="gen13024" level="1"/>

** Song of Solomon 3:3

Invenerunt me vigiles qui custodiunt civitatem : <l eID="gen13025" level="1"/> <l level="1" sID="gen13026"/>Num quem diligit anima mea vidistis ? <l eID="gen13026" level="1"/>

** Song of Solomon 3:4

Paululum cum pertransissem eos, <l eID="gen13027" level="1"/> <l level="1" sID="gen13028"/>inveni quem diligit anima mea : <l eID="gen13028" level="1"/> <l level="1" sID="gen13029"/>tenui eum, nec dimittam, <l eID="gen13029" level="1"/> <l level="1" sID="gen13030"/>donec introducam illum in domum matris meæ, <l eID="gen13030" level="1"/> <l level="1" sID="gen13031"/>et in cubiculum genetricis meæ. <l eID="gen13031" level="1"/> <lg eID="gen13009"/>

** Song of Solomon 3:5

Adjuro vos, filiæ Jerusalem, <l eID="gen13033" level="1"/> <l level="1" sID="gen13034"/>per capreas cervosque camporum, <l eID="gen13034" level="1"/> <l level="1" sID="gen13035"/>ne suscitetis, neque evigilare faciatis dilectam, <l eID="gen13035" level="1"/> <l level="1" sID="gen13036"/>donec ipsa velit. <l eID="gen13036" level="1"/> <lg eID="gen13032"/>

** Song of Solomon 3:6

Quæ est ista quæ ascendit per desertum <l eID="gen13038" level="1"/> <l level="1" sID="gen13039"/>sicut virgula fumi ex aromatibus myrrhæ, <l eID="gen13039" level="1"/> <l level="1" sID="gen13040"/>et thuris, et universi pulveris pigmentarii ? <l eID="gen13040" level="1"/>

** Song of Solomon 3:7

En lectulum Salomonis sexaginta fortes ambiunt <l eID="gen13041" level="1"/> <l level="1" sID="gen13042"/>ex fortissimis Israël, <l eID="gen13042" level="1"/>

** Song of Solomon 3:8

omnes tenentes gladios, et ad bella doctissimi : <l eID="gen13043" level="1"/> <l level="1" sID="gen13044"/>uniuscujusque ensis super femur suum <l eID="gen13044" level="1"/> <l level="1" sID="gen13045"/>propter timores nocturnos. <l eID="gen13045" level="1"/>

** Song of Solomon 3:9

Ferculum fecit sibi rex Salomon <l eID="gen13046" level="1"/> <l level="1" sID="gen13047"/>de lignis Libani ; <l eID="gen13047" level="1"/>

** Song of Solomon 3:10

columnas ejus fecit argenteas, <l eID="gen13048" level="1"/> <l level="1" sID="gen13049"/>reclinatorium aureum, ascensum purpureum ; <l eID="gen13049" level="1"/> <l level="1" sID="gen13050"/>media caritate constravit, <l eID="gen13050" level="1"/> <l level="1" sID="gen13051"/>propter filias Jerusalem. <l eID="gen13051" level="1"/>

** Song of Solomon 3:11

Egredimini et videte, filiæ Sion, <l eID="gen13052" level="1"/> <l level="1" sID="gen13053"/>regem Salomonem in diademate quo coronavit illum mater sua <l eID="gen13053" level="1"/> <l level="1" sID="gen13054"/>in die desponsationis illius, <l eID="gen13054" level="1"/> <l level="1" sID="gen13055"/>et in die lætitiæ cordis ejus. <l eID="gen13055" level="1"/><lg eID="gen13037"/> <chapter eID="Song.3"/>

* Song of Solomon 4

** Song of Solomon 4:1

Quam pulchra es, amica mea ! quam pulchra es ! <l eID="gen13057" level="1"/> <l level="1" sID="gen13058"/>Oculi tui columbarum, <l eID="gen13058" level="1"/> <l level="1" sID="gen13059"/>absque eo quod intrinsecus latet. <l eID="gen13059" level="1"/> <l level="1" sID="gen13060"/>Capilli tui sicut greges caprarum <l eID="gen13060" level="1"/> <l level="1" sID="gen13061"/>quæ ascenderunt de monte Galaad. <l eID="gen13061" level="1"/>

** Song of Solomon 4:2

Dentes tui sicut greges tonsarum <l eID="gen13062" level="1"/> <l level="1" sID="gen13063"/>quæ ascenderunt de lavacro ; <l eID="gen13063" level="1"/> <l level="1" sID="gen13064"/>omnes gemellis fœtibus, <l eID="gen13064" level="1"/> <l level="1" sID="gen13065"/>et sterilis non est inter eas. <l eID="gen13065" level="1"/>

** Song of Solomon 4:3

Sicut vitta coccinea labia tua, <l eID="gen13066" level="1"/> <l level="1" sID="gen13067"/>et eloquium tuum dulce. <l eID="gen13067" level="1"/> <l level="1" sID="gen13068"/>Sicut fragmen mali punici, ita genæ tuæ, <l eID="gen13068" level="1"/> <l level="1" sID="gen13069"/>absque eo quod intrinsecus latet. <l eID="gen13069" level="1"/>

** Song of Solomon 4:4

Sicut turris David collum tuum, <l eID="gen13070" level="1"/> <l level="1" sID="gen13071"/>quæ ædificata est cum propugnaculis ; <l eID="gen13071" level="1"/> <l level="1" sID="gen13072"/>mille clypei pendent ex ea, <l eID="gen13072" level="1"/> <l level="1" sID="gen13073"/>omnis armatura fortium. <l eID="gen13073" level="1"/>

** Song of Solomon 4:5

Duo ubera tua sicut duo hinnuli, <l eID="gen13074" level="1"/> <l level="1" sID="gen13075"/>capreæ gemelli, qui pascuntur in liliis. <l eID="gen13075" level="1"/>

** Song of Solomon 4:6

Donec aspiret dies, et inclinentur umbræ, <l eID="gen13076" level="1"/> <l level="1" sID="gen13077"/>vadam ad montem myrrhæ, et ad collem thuris. <l eID="gen13077" level="1"/>

** Song of Solomon 4:7

Tota pulchra es, amica mea, <l eID="gen13078" level="1"/> <l level="1" sID="gen13079"/>et macula non est in te. <l eID="gen13079" level="1"/>

** Song of Solomon 4:8

Veni de Libano, sponsa mea : <l eID="gen13080" level="1"/> <l level="1" sID="gen13081"/>veni de Libano, veni, coronaberis : <l eID="gen13081" level="1"/> <l level="1" sID="gen13082"/>de capite Amana, de vertice Sanir et Hermon, <l eID="gen13082" level="1"/> <l level="1" sID="gen13083"/>de cubilibus leonum, de montibus pardorum. <l eID="gen13083" level="1"/>

** Song of Solomon 4:9

Vulnerasti cor meum, soror mea, sponsa ; <l eID="gen13084" level="1"/> <l level="1" sID="gen13085"/>vulnerasti cor meum in uno oculorum tuorum, <l eID="gen13085" level="1"/> <l level="1" sID="gen13086"/>et in uno crine colli tui. <l eID="gen13086" level="1"/>

** Song of Solomon 4:10

Quam pulchræ sunt mammæ tuæ, soror mea sponsa ! <l eID="gen13087" level="1"/> <l level="1" sID="gen13088"/>pulchriora sunt ubera tua vino, <l eID="gen13088" level="1"/> <l level="1" sID="gen13089"/>et odor unguentorum tuorum super omnia aromata. <l eID="gen13089" level="1"/>

** Song of Solomon 4:11

Favus distillans labia tua, sponsa ; <l eID="gen13090" level="1"/> <l level="1" sID="gen13091"/>mel et lac sub lingua tua : <l eID="gen13091" level="1"/> <l level="1" sID="gen13092"/>et odor vestimentorum tuorum sicut odor thuris. <l eID="gen13092" level="1"/>

** Song of Solomon 4:12

Hortus conclusus soror mea, sponsa, <l eID="gen13093" level="1"/> <l level="1" sID="gen13094"/>hortus conclusus, fons signatus. <l eID="gen13094" level="1"/>

** Song of Solomon 4:13

Emissiones tuæ paradisus malorum punicorum, <l eID="gen13095" level="1"/> <l level="1" sID="gen13096"/>cum pomorum fructibus, cypri cum nardo. <l eID="gen13096" level="1"/>

** Song of Solomon 4:14

Nardus et crocus, fistula et cinnamomum, <l eID="gen13097" level="1"/> <l level="1" sID="gen13098"/>cum universis lignis Libani ; <l eID="gen13098" level="1"/> <l level="1" sID="gen13099"/>myrrha et aloë, cum omnibus primis unguentis. <l eID="gen13099" level="1"/>

** Song of Solomon 4:15

Fons hortorum, puteus aquarum viventium, <l eID="gen13100" level="1"/> <l level="1" sID="gen13101"/>quæ fluunt impetu de Libano. <l eID="gen13101" level="1"/> <lg eID="gen13056"/>

** Song of Solomon 4:16

Surge, aquilo, et veni, auster : <l eID="gen13103" level="1"/> <l level="1" sID="gen13104"/>perfla hortum meum, et fluant aromata illius.  <chapter eID="Song.4"/>

* Song of Solomon 5

** Song of Solomon 5:1

Veniat dilectus meus in hortum suum, <l eID="gen13105" level="1"/> <l level="1" sID="gen13106"/>et comedat fructum pomorum suorum. <l eID="gen13106" level="1"/> <lg eID="gen13102"/>  <lg sID="gen13107"/> <l level="1" sID="gen13108"/>Veni in hortum meum, soror mea, sponsa ; <l eID="gen13108" level="1"/> <l level="1" sID="gen13109"/>messui myrrham meam cum aromatibus meis ; <l eID="gen13109" level="1"/> <l level="1" sID="gen13110"/>comedi favum cum melle meo ; <l eID="gen13110" level="1"/> <l level="1" sID="gen13111"/>bibi vinum meum cum lacte meo ; <l eID="gen13111" level="1"/> <l level="1" sID="gen13112"/>comedite, amici, et bibite, <l eID="gen13112" level="1"/> <l level="1" sID="gen13113"/>et inebriamini, carissimi. <l eID="gen13113" level="1"/> <lg eID="gen13107"/>

** Song of Solomon 5:2

Ego dormio, et cor meum vigilat. <l eID="gen13115" level="1"/> <l level="1" sID="gen13116"/>Vox dilecti mei pulsantis : <l eID="gen13116" level="1"/> <lg eID="gen13114"/>  <lg sID="gen13117"/> <l level="1" sID="gen13118"/>Aperi mihi, soror mea, amica mea, <l eID="gen13118" level="1"/> <l level="1" sID="gen13119"/>columba mea, immaculata mea, <l eID="gen13119" level="1"/> <l level="1" sID="gen13120"/>quia caput meum plenum est rore, <l eID="gen13120" level="1"/> <l level="1" sID="gen13121"/>et cincinni mei guttis noctium. <l eID="gen13121" level="1"/> <lg eID="gen13117"/>

** Song of Solomon 5:3

Expoliavi me tunica mea : quomodo induar illa ? <l eID="gen13123" level="1"/> <l level="1" sID="gen13124"/>lavi pedes meos : quomodo inquinabo illos ? <l eID="gen13124" level="1"/>

** Song of Solomon 5:4

Dilectus meus misit manum suam per foramen, <l eID="gen13125" level="1"/> <l level="1" sID="gen13126"/>et venter meus intremuit ad tactum ejus. <l eID="gen13126" level="1"/>

** Song of Solomon 5:5

Surrexi ut aperirem dilecto meo ; <l eID="gen13127" level="1"/> <l level="1" sID="gen13128"/>manus meæ stillaverunt myrrham, <l eID="gen13128" level="1"/> <l level="1" sID="gen13129"/>et digiti mei pleni myrrha probatissima. <l eID="gen13129" level="1"/>

** Song of Solomon 5:6

Pessulum ostii mei aperui dilecto meo, <l eID="gen13130" level="1"/> <l level="1" sID="gen13131"/>at ille declinaverat, atque transierat. <l eID="gen13131" level="1"/> <l level="1" sID="gen13132"/>Anima mea liquefacta est, ut locutus est ; <l eID="gen13132" level="1"/> <l level="1" sID="gen13133"/>quæsivi, et non inveni illum ; <l eID="gen13133" level="1"/> <l level="1" sID="gen13134"/>vocavi, et non respondit mihi. <l eID="gen13134" level="1"/>

** Song of Solomon 5:7

Invenerunt me custodes qui circumeunt civitatem ; <l eID="gen13135" level="1"/> <l level="1" sID="gen13136"/>percusserunt me, et vulneraverunt me. <l eID="gen13136" level="1"/> <l level="1" sID="gen13137"/>Tulerunt pallium meum mihi custodes murorum. <l eID="gen13137" level="1"/>

** Song of Solomon 5:8

Adjuro vos, filiæ Jerusalem, <l eID="gen13138" level="1"/> <l level="1" sID="gen13139"/>si inveneritis dilectum meum, <l eID="gen13139" level="1"/> <l level="1" sID="gen13140"/>ut nuntietis ei quia amore langueo. <l eID="gen13140" level="1"/> <lg eID="gen13122"/>

** Song of Solomon 5:9

Qualis est dilectus tuus ex dilecto, o pulcherrima mulierum ? <l eID="gen13142" level="1"/> <l level="1" sID="gen13143"/>qualis est dilectus tuus ex dilecto, quia sic adjurasti nos ? <l eID="gen13143" level="1"/> <lg eID="gen13141"/>

** Song of Solomon 5:10

Dilectus meus candidus et rubicundus ; <l eID="gen13145" level="1"/> <l level="1" sID="gen13146"/>electus ex millibus. <l eID="gen13146" level="1"/>

** Song of Solomon 5:11

Caput ejus aurum optimum ; <l eID="gen13147" level="1"/> <l level="1" sID="gen13148"/>comæ ejus sicut elatæ palmarum, nigræ quasi corvus. <l eID="gen13148" level="1"/>

** Song of Solomon 5:12

Oculi ejus sicut columbæ super rivulos aquarum, <l eID="gen13149" level="1"/> <l level="1" sID="gen13150"/>quæ lacte sunt lotæ, et resident juxta fluenta plenissima. <l eID="gen13150" level="1"/>

** Song of Solomon 5:13

Genæ illius sicut areolæ aromatum, <l eID="gen13151" level="1"/> <l level="1" sID="gen13152"/>consitæ a pigmentariis. <l eID="gen13152" level="1"/> <l level="1" sID="gen13153"/>Labia ejus lilia, <l eID="gen13153" level="1"/> <l level="1" sID="gen13154"/>distillantia myrrham primam. <l eID="gen13154" level="1"/>

** Song of Solomon 5:14

Manus illius tornatiles, aureæ, <l eID="gen13155" level="1"/> <l level="1" sID="gen13156"/>plenæ hyacinthis. <l eID="gen13156" level="1"/> <l level="1" sID="gen13157"/>Venter ejus eburneus, <l eID="gen13157" level="1"/> <l level="1" sID="gen13158"/>distinctus sapphiris. <l eID="gen13158" level="1"/>

** Song of Solomon 5:15

Crura illius columnæ marmoreæ <l eID="gen13159" level="1"/> <l level="1" sID="gen13160"/>quæ fundatæ sunt super bases aureas. <l eID="gen13160" level="1"/> <l level="1" sID="gen13161"/>Species ejus ut Libani, <l eID="gen13161" level="1"/> <l level="1" sID="gen13162"/>electus ut cedri. <l eID="gen13162" level="1"/>

** Song of Solomon 5:16

Guttur illius suavissimum, <l eID="gen13163" level="1"/> <l level="1" sID="gen13164"/>et totus desiderabilis. <l eID="gen13164" level="1"/> <l level="1" sID="gen13165"/>Talis est dilectus meus, <l eID="gen13165" level="1"/> <l level="1" sID="gen13166"/>et ipse est amicus meus, filiæ Jerusalem. <l eID="gen13166" level="1"/> <lg eID="gen13144"/>

** Song of Solomon 5:17

Quo abiit dilectus tuus, o pulcherrima mulierum ? <l eID="gen13168" level="1"/> <l level="1" sID="gen13169"/>quo declinavit dilectus tuus ? <l eID="gen13169" level="1"/> <l level="1" sID="gen13170"/>et quæremus eum tecum. <l eID="gen13170" level="1"/><lg eID="gen13167"/> <chapter eID="Song.5"/>

* Song of Solomon 6

** Song of Solomon 6:1

Dilectus meus descendit in hortum suum ad areolam aromatum, <l eID="gen13172" level="1"/> <l level="1" sID="gen13173"/>ut pascatur in hortis, et lilia colligat. <l eID="gen13173" level="1"/>

** Song of Solomon 6:2

Ego dilecto meo, et dilectus meus mihi, <l eID="gen13174" level="1"/> <l level="1" sID="gen13175"/>qui pascitur inter lilia. <l eID="gen13175" level="1"/> <lg eID="gen13171"/>

** Song of Solomon 6:3

Pulchra es, amica mea ; <l eID="gen13177" level="1"/> <l level="1" sID="gen13178"/>suavis, et decora sicut Jerusalem ; <l eID="gen13178" level="1"/> <l level="1" sID="gen13179"/>terribilis ut castrorum acies ordinata. <l eID="gen13179" level="1"/>

** Song of Solomon 6:4

Averte oculos tuos a me, <l eID="gen13180" level="1"/> <l level="1" sID="gen13181"/>quia ipsi me avolare fecerunt. <l eID="gen13181" level="1"/> <l level="1" sID="gen13182"/>Capilli tui sicut grex caprarum <l eID="gen13182" level="1"/> <l level="1" sID="gen13183"/>quæ apparuerunt de Galaad. <l eID="gen13183" level="1"/>

** Song of Solomon 6:5

Dentes tui sicut grex ovium <l eID="gen13184" level="1"/> <l level="1" sID="gen13185"/>quæ ascenderunt de lavacro : <l eID="gen13185" level="1"/> <l level="1" sID="gen13186"/>omnes gemellis fœtibus, <l eID="gen13186" level="1"/> <l level="1" sID="gen13187"/>et sterilis non est in eis. <l eID="gen13187" level="1"/>

** Song of Solomon 6:6

Sicut cortex mali punici, sic genæ tuæ, <l eID="gen13188" level="1"/> <l level="1" sID="gen13189"/>absque occultis tuis. <l eID="gen13189" level="1"/>

** Song of Solomon 6:7

Sexaginta sunt reginæ, et octoginta concubinæ, <l eID="gen13190" level="1"/> <l level="1" sID="gen13191"/>et adolescentularum non est numerus. <l eID="gen13191" level="1"/>

** Song of Solomon 6:8

Una est columba mea, perfecta mea, <l eID="gen13192" level="1"/> <l level="1" sID="gen13193"/>una est matris suæ, electa genetrici suæ. <l eID="gen13193" level="1"/> <l level="1" sID="gen13194"/>Viderunt eam filiæ, et beatissimam prædicaverunt ; <l eID="gen13194" level="1"/> <l level="1" sID="gen13195"/>reginæ et concubinæ, et laudaverunt eam. <l eID="gen13195" level="1"/>

** Song of Solomon 6:9

Quæ est ista quæ progreditur quasi aurora consurgens, <l eID="gen13196" level="1"/> <l level="1" sID="gen13197"/>pulchra ut luna, electa ut sol, <l eID="gen13197" level="1"/> <l level="1" sID="gen13198"/>terribilis ut castrorum acies ordinata ? <l eID="gen13198" level="1"/> <lg eID="gen13176"/>

** Song of Solomon 6:10

Descendi in hortum nucum, <l eID="gen13200" level="1"/> <l level="1" sID="gen13201"/>ut viderem poma convallium, <l eID="gen13201" level="1"/> <l level="1" sID="gen13202"/>et inspicerem si floruisset vinea, <l eID="gen13202" level="1"/> <l level="1" sID="gen13203"/>et germinassent mala punica. <l eID="gen13203" level="1"/>

** Song of Solomon 6:11

Nescivi : anima mea conturbavit me, <l eID="gen13204" level="1"/> <l level="1" sID="gen13205"/>propter quadrigas Aminadab. <l eID="gen13205" level="1"/> <lg eID="gen13199"/>

** Song of Solomon 6:12

Revertere, revertere, Sulamitis ! <l eID="gen13207" level="1"/> <l level="1" sID="gen13208"/>revertere, revertere ut intueamur te. <l eID="gen13208" level="1"/><lg eID="gen13206"/> <chapter eID="Song.6"/>

* Song of Solomon 7

** Song of Solomon 7:1

Quid videbis in Sulamite, nisi choros castrorum ? <l eID="gen13210" level="1"/> <lg eID="gen13209"/>  <lg sID="gen13211"/> <l level="1" sID="gen13212"/>Quam pulchri sunt gressus tui in calceamentis, filia principis ! <l eID="gen13212" level="1"/> <l level="1" sID="gen13213"/>Juncturæ femorum tuorum sicut monilia <l eID="gen13213" level="1"/> <l level="1" sID="gen13214"/>quæ fabricata sunt manu artificis. <l eID="gen13214" level="1"/>

** Song of Solomon 7:2

Umbilicus tuus crater tornatilis, <l eID="gen13215" level="1"/> <l level="1" sID="gen13216"/>numquam indigens poculis. <l eID="gen13216" level="1"/> <l level="1" sID="gen13217"/>Venter tuus sicut acervus tritici vallatus liliis. <l eID="gen13217" level="1"/>

** Song of Solomon 7:3

Duo ubera tua sicut duo hinnuli, <l eID="gen13218" level="1"/> <l level="1" sID="gen13219"/>gemelli capreæ. <l eID="gen13219" level="1"/>

** Song of Solomon 7:4

Collum tuum sicut turris eburnea ; <l eID="gen13220" level="1"/> <l level="1" sID="gen13221"/>oculi tui sicut piscinæ in Hesebon <l eID="gen13221" level="1"/> <l level="1" sID="gen13222"/>quæ sunt in porta filiæ multitudinis. <l eID="gen13222" level="1"/> <l level="1" sID="gen13223"/>Nasus tuus sicut turris Libani, <l eID="gen13223" level="1"/> <l level="1" sID="gen13224"/>quæ respicit contra Damascum. <l eID="gen13224" level="1"/>

** Song of Solomon 7:5

Caput tuum ut Carmelus ; <l eID="gen13225" level="1"/> <l level="1" sID="gen13226"/>et comæ capitis tui sicut purpura regis <l eID="gen13226" level="1"/> <l level="1" sID="gen13227"/>vincta canalibus. <l eID="gen13227" level="1"/> <lg eID="gen13211"/>

** Song of Solomon 7:6

Quam pulchra es, et quam decora, <l eID="gen13229" level="1"/> <l level="1" sID="gen13230"/>carissima, in deliciis ! <l eID="gen13230" level="1"/>

** Song of Solomon 7:7

Statura tua assimilata est palmæ, <l eID="gen13231" level="1"/> <l level="1" sID="gen13232"/>et ubera tua botris. <l eID="gen13232" level="1"/>

** Song of Solomon 7:8

Dixi : Ascendam in palmam, <l eID="gen13233" level="1"/> <l level="1" sID="gen13234"/>et apprehendam fructus ejus ; <l eID="gen13234" level="1"/> <l level="1" sID="gen13235"/>et erunt ubera tua sicut botri vineæ, <l eID="gen13235" level="1"/> <l level="1" sID="gen13236"/>et odor oris tui sicut malorum. <l eID="gen13236" level="1"/>

** Song of Solomon 7:9

Guttur tuum sicut vinum optimum, <l eID="gen13237" level="1"/> <l level="1" sID="gen13238"/>dignum dilecto meo ad potandum, <l eID="gen13238" level="1"/> <l level="1" sID="gen13239"/>labiisque et dentibus illius ad ruminandum. <l eID="gen13239" level="1"/> <lg eID="gen13228"/>

** Song of Solomon 7:10

Ego dilecto meo, <l eID="gen13241" level="1"/> <l level="1" sID="gen13242"/>et ad me conversio ejus. <l eID="gen13242" level="1"/>

** Song of Solomon 7:11

Veni, dilecte mi, egrediamur in agrum, <l eID="gen13243" level="1"/> <l level="1" sID="gen13244"/>commoremur in villis. <l eID="gen13244" level="1"/>

** Song of Solomon 7:12

Mane surgamus ad vineas : <l eID="gen13245" level="1"/> <l level="1" sID="gen13246"/>videamus si floruit vinea, <l eID="gen13246" level="1"/> <l level="1" sID="gen13247"/>si flores fructus parturiunt, <l eID="gen13247" level="1"/> <l level="1" sID="gen13248"/>si floruerunt mala punica ; <l eID="gen13248" level="1"/> <l level="1" sID="gen13249"/>ibi dabo tibi ubera mea. <l eID="gen13249" level="1"/>

** Song of Solomon 7:13

Mandragoræ dederunt odorem <l eID="gen13250" level="1"/> <l level="1" sID="gen13251"/>in portis nostris omnia poma : <l eID="gen13251" level="1"/> <l level="1" sID="gen13252"/>nova et vetera, dilecte mi, servavi tibi.  <chapter eID="Song.7"/>

* Song of Solomon 8

** Song of Solomon 8:1

Quis mihi det te fratrem meum, <l eID="gen13253" level="1"/> <l level="1" sID="gen13254"/>sugentem ubera matris meæ, <l eID="gen13254" level="1"/> <l level="1" sID="gen13255"/>ut inveniam te foris, et deosculer te, <l eID="gen13255" level="1"/> <l level="1" sID="gen13256"/>et jam me nemo despiciat ? <l eID="gen13256" level="1"/>

** Song of Solomon 8:2

Apprehendam te, et ducam in domum matris meæ : <l eID="gen13257" level="1"/> <l level="1" sID="gen13258"/>ibi me docebis, <l eID="gen13258" level="1"/> <l level="1" sID="gen13259"/>et dabo tibi poculum ex vino condito, <l eID="gen13259" level="1"/> <l level="1" sID="gen13260"/>et mustum malorum granatorum meorum. <l eID="gen13260" level="1"/>

** Song of Solomon 8:3

Læva ejus sub capite meo, <l eID="gen13261" level="1"/> <l level="1" sID="gen13262"/>et dextera illius amplexabitur me. <l eID="gen13262" level="1"/> <lg eID="gen13240"/>

** Song of Solomon 8:4

Adjuro vos, filiæ Jerusalem, <l eID="gen13264" level="1"/> <l level="1" sID="gen13265"/>ne suscitetis, neque evigilare faciatis dilectam, <l eID="gen13265" level="1"/> <l level="1" sID="gen13266"/>donec ipsa velit. <l eID="gen13266" level="1"/> <lg eID="gen13263"/>

** Song of Solomon 8:5

Quæ est ista quæ ascendit de deserto, deliciis affluens, <l eID="gen13268" level="1"/> <l level="1" sID="gen13269"/>innixa super dilectum suum ? <l eID="gen13269" level="1"/> <lg eID="gen13267"/>  <lg sID="gen13270"/> <l level="1" sID="gen13271"/>Sub arbore malo suscitavi te ; <l eID="gen13271" level="1"/> <l level="1" sID="gen13272"/>ibi corrupta est mater tua, <l eID="gen13272" level="1"/> <l level="1" sID="gen13273"/>ibi violata est genitrix tua. <l eID="gen13273" level="1"/> <lg eID="gen13270"/>

** Song of Solomon 8:6

Pone me ut signaculum super cor tuum, <l eID="gen13275" level="1"/> <l level="1" sID="gen13276"/>ut signaculum super brachium tuum, <l eID="gen13276" level="1"/> <l level="1" sID="gen13277"/>quia fortis est ut mors dilectio, <l eID="gen13277" level="1"/> <l level="1" sID="gen13278"/>dura sicut infernus æmulatio : <l eID="gen13278" level="1"/> <l level="1" sID="gen13279"/>lampades ejus lampades ignis atque flammarum. <l eID="gen13279" level="1"/>

** Song of Solomon 8:7

Aquæ multæ non potuerunt extinguere caritatem, <l eID="gen13280" level="1"/> <l level="1" sID="gen13281"/>nec flumina obruent illam. <l eID="gen13281" level="1"/> <l level="1" sID="gen13282"/>Si dederit homo omnem substantiam domus suæ pro dilectione, <l eID="gen13282" level="1"/> <l level="1" sID="gen13283"/>quasi nihil despiciet eam. <l eID="gen13283" level="1"/> <lg eID="gen13274"/>

** Song of Solomon 8:8

Soror nostra parva, <l eID="gen13285" level="1"/> <l level="1" sID="gen13286"/>et ubera non habet ; <l eID="gen13286" level="1"/> <l level="1" sID="gen13287"/>quid faciemus sorori nostræ <l eID="gen13287" level="1"/> <l level="1" sID="gen13288"/>in die quando alloquenda est ? <l eID="gen13288" level="1"/>

** Song of Solomon 8:9

Si murus est, <l eID="gen13289" level="1"/> <l level="1" sID="gen13290"/>ædificemus super eum propugnacula argentea ; <l eID="gen13290" level="1"/> <l level="1" sID="gen13291"/>si ostium est, compingamus illud tabulis cedrinis. <l eID="gen13291" level="1"/> <lg eID="gen13284"/>

** Song of Solomon 8:10

Ego murus, et ubera mea sicut turris, <l eID="gen13293" level="1"/> <l level="1" sID="gen13294"/>ex quo facta sum coram eo, quasi pacem reperiens. <l eID="gen13294" level="1"/> <lg eID="gen13292"/>

** Song of Solomon 8:11

Vinea fuit pacifico in ea quæ habet populos : <l eID="gen13296" level="1"/> <l level="1" sID="gen13297"/>tradidit eam custodibus ; <l eID="gen13297" level="1"/> <l level="1" sID="gen13298"/>vir affert pro fructu ejus mille argenteos. <l eID="gen13298" level="1"/> <lg eID="gen13295"/>

** Song of Solomon 8:12

Vinea mea coram me est. <l eID="gen13300" level="1"/> <l level="1" sID="gen13301"/>Mille tui pacifici, <l eID="gen13301" level="1"/> <l level="1" sID="gen13302"/>et ducenti his qui custodiunt fructus ejus. <l eID="gen13302" level="1"/> <lg eID="gen13299"/>

** Song of Solomon 8:13

Quæ habitas in hortis, amici auscultant ; <l eID="gen13304" level="1"/> <l level="1" sID="gen13305"/>fac me audire vocem tuam. <l eID="gen13305" level="1"/> <lg eID="gen13303"/>

** Song of Solomon 8:14

Fuge, dilecte mi, et assimilare capreæ, <l eID="gen13307" level="1"/> <l level="1" sID="gen13308"/>hinnuloque cervorum super montes aromatum. <l eID="gen13308" level="1"/> <lg eID="gen13306"/> <chapter eID="Song.8"/> <div eID="gen12913" osisID="Song" type="book"/>

