* Wisdom 1

** Wisdom 1:1

Diligite justitiam, qui judicatis terram. <l eID="gen13311" level="1"/> <l level="1" sID="gen13312"/>Sentite de Domino in bonitate, <l eID="gen13312" level="1"/> <l level="1" sID="gen13313"/>et in simplicitate cordis quærite illum : <l eID="gen13313" level="1"/>

** Wisdom 1:2

quoniam invenitur ab his qui non tentant illum, <l eID="gen13314" level="1"/> <l level="1" sID="gen13315"/>apparet autem eis qui fidem habent in illum. <l eID="gen13315" level="1"/>

** Wisdom 1:3

Perversæ enim cogitationes separant a Deo ; <l eID="gen13316" level="1"/> <l level="1" sID="gen13317"/>probata autem virtus corripit insipientes. <l eID="gen13317" level="1"/>

** Wisdom 1:4

Quoniam in malevolam animam non introibit sapientia, <l eID="gen13318" level="1"/> <l level="1" sID="gen13319"/>nec habitabit in corpore subdito peccatis. <l eID="gen13319" level="1"/>

** Wisdom 1:5

Spiritus enim sanctus disciplinæ effugiet fictum, <l eID="gen13320" level="1"/> <l level="1" sID="gen13321"/>et auferet se a cogitationibus quæ sunt sine intellectu, <l eID="gen13321" level="1"/> <l level="1" sID="gen13322"/>et corripietur a superveniente iniquitate. <l eID="gen13322" level="1"/>

** Wisdom 1:6

Benignus est enim spiritus sapientiæ, <l eID="gen13323" level="1"/> <l level="1" sID="gen13324"/>et non liberabit maledicum a labiis suis : <l eID="gen13324" level="1"/> <l level="1" sID="gen13325"/>quoniam renum illius testis est Deus, <l eID="gen13325" level="1"/> <l level="1" sID="gen13326"/>et cordis illius scrutator est verus, <l eID="gen13326" level="1"/> <l level="1" sID="gen13327"/>et linguæ ejus auditor. <l eID="gen13327" level="1"/>

** Wisdom 1:7

Quoniam spiritus Domini replevit orbem terrarum, <l eID="gen13328" level="1"/> <l level="1" sID="gen13329"/>et hoc quod continet omnia, scientiam habet vocis. <l eID="gen13329" level="1"/>

** Wisdom 1:8

Propter hoc qui loquitur iniqua non potest latere, <l eID="gen13330" level="1"/> <l level="1" sID="gen13331"/>nec præteriet illum corripiens judicium. <l eID="gen13331" level="1"/>

** Wisdom 1:9

In cogitationibus enim impii interrogatio erit ; <l eID="gen13332" level="1"/> <l level="1" sID="gen13333"/>sermonum autem illius auditio ad Deum veniet, <l eID="gen13333" level="1"/> <l level="1" sID="gen13334"/>ad correptionem iniquitatum illius. <l eID="gen13334" level="1"/>

** Wisdom 1:10

Quoniam auris zeli audit omnia, <l eID="gen13335" level="1"/> <l level="1" sID="gen13336"/>et tumultus murmurationum non abscondetur. <l eID="gen13336" level="1"/>

** Wisdom 1:11

Custodite ergo vos a murmuratione quæ nihil prodest, <l eID="gen13337" level="1"/> <l level="1" sID="gen13338"/>et a detractione parcite linguæ : <l eID="gen13338" level="1"/> <l level="1" sID="gen13339"/>quoniam sermo obscurus in vacuum non ibit, <l eID="gen13339" level="1"/> <l level="1" sID="gen13340"/>os autem quod mentitur occidit animam. <l eID="gen13340" level="1"/>

** Wisdom 1:12

Nolite zelare mortem in errore vitæ vestræ, <l eID="gen13341" level="1"/> <l level="1" sID="gen13342"/>neque acquiratis perditionem in operibus manuum vestrarum. <l eID="gen13342" level="1"/>

** Wisdom 1:13

Quoniam Deus mortem non fecit, <l eID="gen13343" level="1"/> <l level="1" sID="gen13344"/>nec lætatur in perditione vivorum. <l eID="gen13344" level="1"/>

** Wisdom 1:14

Creavit enim ut essent omnia, <l eID="gen13345" level="1"/> <l level="1" sID="gen13346"/>et sanabiles fecit nationes orbis terrarum : <l eID="gen13346" level="1"/> <l level="1" sID="gen13347"/>et non est in illis medicamentum exterminii, <l eID="gen13347" level="1"/> <l level="1" sID="gen13348"/>nec inferorum regnum in terra. <l eID="gen13348" level="1"/>

** Wisdom 1:15

Justitia enim perpetua est, et immortalis. <l eID="gen13349" level="1"/>

** Wisdom 1:16

Impii autem manibus et verbis accersierunt illam, <l eID="gen13350" level="1"/> <l level="1" sID="gen13351"/>et æstimantes illam amicam, defluxerunt ; <l eID="gen13351" level="1"/> <l level="1" sID="gen13352"/>et sponsiones posuerunt ad illam, <l eID="gen13352" level="1"/> <l level="1" sID="gen13353"/>quoniam digni sunt qui sint ex parte illius.  <chapter eID="Wis.1"/>

* Wisdom 2

** Wisdom 2:1

Dixerunt enim cogitantes apud se non recte : <l eID="gen13354" level="1"/> <l level="1" sID="gen13355"/>Exiguum et cum tædio est tempus vitæ nostræ, <l eID="gen13355" level="1"/> <l level="1" sID="gen13356"/>et non est refrigerium in fine hominis, <l eID="gen13356" level="1"/> <l level="1" sID="gen13357"/>et non est qui agnitus sit reversus ab inferis. <l eID="gen13357" level="1"/>

** Wisdom 2:2

Quia ex nihilo nati sumus, <l eID="gen13358" level="1"/> <l level="1" sID="gen13359"/>et post hoc erimus tamquam non fuerimus. <l eID="gen13359" level="1"/> <l level="1" sID="gen13360"/>Quoniam fumus flatus est in naribus nostris, <l eID="gen13360" level="1"/> <l level="1" sID="gen13361"/>et sermo scintilla ad commovendum cor nostrum : <l eID="gen13361" level="1"/>

** Wisdom 2:3

qua extincta, cinis erit corpus nostrum, <l eID="gen13362" level="1"/> <l level="1" sID="gen13363"/>et spiritus diffundetur tamquam mollis aër ; <l eID="gen13363" level="1"/> <l level="1" sID="gen13364"/>et transibit vita nostra tamquam vestigium nubis, <l eID="gen13364" level="1"/> <l level="1" sID="gen13365"/>et sicut nebula dissolvetur quæ fugata est a radiis solis, <l eID="gen13365" level="1"/> <l level="1" sID="gen13366"/>et a calore illius aggravata. <l eID="gen13366" level="1"/>

** Wisdom 2:4

Et nomen nostrum oblivionem accipiet per tempus, <l eID="gen13367" level="1"/> <l level="1" sID="gen13368"/>et nemo memoriam habebit operum nostrorum. <l eID="gen13368" level="1"/>

** Wisdom 2:5

Umbræ enim transitus est tempus nostrum, <l eID="gen13369" level="1"/> <l level="1" sID="gen13370"/>et non est reversio finis nostri : <l eID="gen13370" level="1"/> <l level="1" sID="gen13371"/>quoniam consignata est, et nemo revertitur. <l eID="gen13371" level="1"/>

** Wisdom 2:6

Venite ergo, et fruamur bonis quæ sunt, <l eID="gen13372" level="1"/> <l level="1" sID="gen13373"/>et utamur creatura tamquam in juventute celeriter. <l eID="gen13373" level="1"/>

** Wisdom 2:7

Vino pretioso et unguentis nos impleamus, <l eID="gen13374" level="1"/> <l level="1" sID="gen13375"/>et non prætereat nos flos temporis. <l eID="gen13375" level="1"/>

** Wisdom 2:8

Coronemus nos rosis antequam marcescant ; <l eID="gen13376" level="1"/> <l level="1" sID="gen13377"/>nullum pratum sit quod non pertranseat luxuria nostra : <l eID="gen13377" level="1"/>

** Wisdom 2:9

nemo nostrum exsors sit luxuriæ nostræ. <l eID="gen13378" level="1"/> <l level="1" sID="gen13379"/>Ubique relinquamus signa lætitiæ, <l eID="gen13379" level="1"/> <l level="1" sID="gen13380"/>quoniam hæc est pars nostra, et hæc est sors. <l eID="gen13380" level="1"/>

** Wisdom 2:10

Opprimamus pauperem justum, et non parcamus viduæ, <l eID="gen13381" level="1"/> <l level="1" sID="gen13382"/>nec veterani revereamur canos multi temporis : <l eID="gen13382" level="1"/>

** Wisdom 2:11

sit autem fortitudo nostra lex justitiæ ; <l eID="gen13383" level="1"/> <l level="1" sID="gen13384"/>quod enim infirmum est, inutile invenitur. <l eID="gen13384" level="1"/>

** Wisdom 2:12

Circumveniamus ergo justum, quoniam inutilis est nobis, <l eID="gen13385" level="1"/> <l level="1" sID="gen13386"/>et contrarius est operibus nostris, <l eID="gen13386" level="1"/> <l level="1" sID="gen13387"/>et improperat nobis peccata legis, <l eID="gen13387" level="1"/> <l level="1" sID="gen13388"/>et diffamat in nos peccata disciplinæ nostræ. <l eID="gen13388" level="1"/>

** Wisdom 2:13

Promittit se scientiam Dei habere, <l eID="gen13389" level="1"/> <l level="1" sID="gen13390"/>et filium Dei se nominat. <l eID="gen13390" level="1"/>

** Wisdom 2:14

Factus est nobis in traductionem cogitationum nostrarum. <l eID="gen13391" level="1"/>

** Wisdom 2:15

Gravis est nobis etiam ad videndum, <l eID="gen13392" level="1"/> <l level="1" sID="gen13393"/>quoniam dissimilis est aliis vita illius, <l eID="gen13393" level="1"/> <l level="1" sID="gen13394"/>et immutatæ sunt viæ ejus. <l eID="gen13394" level="1"/>

** Wisdom 2:16

Tamquam nugaces æstimati sumus ab illo, <l eID="gen13395" level="1"/> <l level="1" sID="gen13396"/>et abstinet se a viis nostris tamquam ab immunditiis, <l eID="gen13396" level="1"/> <l level="1" sID="gen13397"/>et præfert novissima justorum, <l eID="gen13397" level="1"/> <l level="1" sID="gen13398"/>et gloriatur patrem se habere Deum. <l eID="gen13398" level="1"/>

** Wisdom 2:17

Videamus ergo si sermones illius veri sint, <l eID="gen13399" level="1"/> <l level="1" sID="gen13400"/>et tentemus quæ ventura sunt illi, <l eID="gen13400" level="1"/> <l level="1" sID="gen13401"/>et sciemus quæ erunt novissima illius. <l eID="gen13401" level="1"/>

** Wisdom 2:18

Si enim est verus filius Dei, suscipiet illum, <l eID="gen13402" level="1"/> <l level="1" sID="gen13403"/>et liberabit eum de manibus contrariorum. <l eID="gen13403" level="1"/>

** Wisdom 2:19

Contumelia et tormento interrogemus eum, <l eID="gen13404" level="1"/> <l level="1" sID="gen13405"/>ut sciamus reverentiam ejus, <l eID="gen13405" level="1"/> <l level="1" sID="gen13406"/>et probemus patientiam illius. <l eID="gen13406" level="1"/>

** Wisdom 2:20

Morte turpissima condemnemus eum ; <l eID="gen13407" level="1"/> <l level="1" sID="gen13408"/>erit enim ei respectus ex sermonibus illius. <l eID="gen13408" level="1"/>

** Wisdom 2:21

Hæc cogitaverunt, et erraverunt : <l eID="gen13409" level="1"/> <l level="1" sID="gen13410"/>excæcavit enim illos malitia eorum. <l eID="gen13410" level="1"/>

** Wisdom 2:22

Et nescierunt sacramenta Dei : <l eID="gen13411" level="1"/> <l level="1" sID="gen13412"/>neque mercedem speraverunt justitiæ, <l eID="gen13412" level="1"/> <l level="1" sID="gen13413"/>nec judicaverunt honorem animarum sanctarum. <l eID="gen13413" level="1"/>

** Wisdom 2:23

Quoniam Deus creavit hominem inexterminabilem, <l eID="gen13414" level="1"/> <l level="1" sID="gen13415"/>et ad imaginem similitudinis suæ fecit illum. <l eID="gen13415" level="1"/>

** Wisdom 2:24

Invidia autem diaboli mors introivit in orbem terrarum : <l eID="gen13416" level="1"/>

** Wisdom 2:25

imitantur autem illum qui sunt ex parte illius.  <chapter eID="Wis.2"/>

* Wisdom 3

** Wisdom 3:1

Justorum autem animæ in manu Dei sunt, <l eID="gen13418" level="1"/> <l level="1" sID="gen13419"/>et non tanget illos tormentum mortis. <l eID="gen13419" level="1"/>

** Wisdom 3:2

Visi sunt oculis insipientium mori, <l eID="gen13420" level="1"/> <l level="1" sID="gen13421"/>et æstimata est afflictio exitus illorum, <l eID="gen13421" level="1"/>

** Wisdom 3:3

et quod a nobis est iter exterminium ; <l eID="gen13422" level="1"/> <l level="1" sID="gen13423"/>illi autem sunt in pace : <l eID="gen13423" level="1"/>

** Wisdom 3:4

etsi coram hominibus tormenta passi sunt, <l eID="gen13424" level="1"/> <l level="1" sID="gen13425"/>spes illorum immortalitate plena est. <l eID="gen13425" level="1"/>

** Wisdom 3:5

In paucis vexati sunt, in multis bene disponentur, <l eID="gen13426" level="1"/> <l level="1" sID="gen13427"/>quoniam Deus tentavit eos, <l eID="gen13427" level="1"/> <l level="1" sID="gen13428"/>et invenit illos dignos se. <l eID="gen13428" level="1"/>

** Wisdom 3:6

Tamquam aurum in fornace probavit illos, <l eID="gen13429" level="1"/> <l level="1" sID="gen13430"/>et quasi holocausti hostiam accepit illos, <l eID="gen13430" level="1"/> <l level="1" sID="gen13431"/>et in tempore erit respectus illorum. <l eID="gen13431" level="1"/>

** Wisdom 3:7

Fulgebunt justi <l eID="gen13432" level="1"/> <l level="1" sID="gen13433"/>et tamquam scintillæ in arundineto discurrent. <l eID="gen13433" level="1"/>

** Wisdom 3:8

Judicabunt nationes, et dominabuntur populis, <l eID="gen13434" level="1"/> <l level="1" sID="gen13435"/>et regnabit Dominus illorum in perpetuum. <l eID="gen13435" level="1"/>

** Wisdom 3:9

Qui confidunt in illo intelligent veritatem, <l eID="gen13436" level="1"/> <l level="1" sID="gen13437"/>et fideles in dilectione acquiescent illi, <l eID="gen13437" level="1"/> <l level="1" sID="gen13438"/>quoniam donum et pax est electis ejus. <l eID="gen13438" level="1"/>

** Wisdom 3:10

Impii autem secundum quæ cogitaverunt <l eID="gen13439" level="1"/> <l level="1" sID="gen13440"/>correptionem habebunt : <l eID="gen13440" level="1"/> <l level="1" sID="gen13441"/>qui neglexerunt justum, <l eID="gen13441" level="1"/> <l level="1" sID="gen13442"/>et a Domino recesserunt. <l eID="gen13442" level="1"/>

** Wisdom 3:11

Sapientiam enim et disciplinam qui abjicit infelix est : <l eID="gen13443" level="1"/> <l level="1" sID="gen13444"/>et vacua est spes illorum, <l eID="gen13444" level="1"/> <l level="1" sID="gen13445"/>et labores sine fructu, <l eID="gen13445" level="1"/> <l level="1" sID="gen13446"/>et inutilia opera eorum. <l eID="gen13446" level="1"/>

** Wisdom 3:12

Mulieres eorum insensatæ sunt, <l eID="gen13447" level="1"/> <l level="1" sID="gen13448"/>et nequissimi filii eorum. <l eID="gen13448" level="1"/>

** Wisdom 3:13

Maledicta creatura eorum, quoniam felix est sterilis ; <l eID="gen13449" level="1"/> <l level="1" sID="gen13450"/>et incoinquinata, quæ nescivit thorum in delicto, <l eID="gen13450" level="1"/> <l level="1" sID="gen13451"/>habebit fructum in respectione animarum sanctarum ; <l eID="gen13451" level="1"/>

** Wisdom 3:14

et spado qui non operatus est per manus suas iniquitatem, <l eID="gen13452" level="1"/> <l level="1" sID="gen13453"/>nec cogitavit adversus Deum nequissima : <l eID="gen13453" level="1"/> <l level="1" sID="gen13454"/>dabitur enim illi fidei donum electum, <l eID="gen13454" level="1"/> <l level="1" sID="gen13455"/>et sors in templo Dei acceptissima. <l eID="gen13455" level="1"/>

** Wisdom 3:15

Bonorum enim laborum gloriosus est fructus, <l eID="gen13456" level="1"/> <l level="1" sID="gen13457"/>et quæ non concidat radix sapientiæ. <l eID="gen13457" level="1"/>

** Wisdom 3:16

Filii autem adulterorum in inconsummatione erunt, <l eID="gen13458" level="1"/> <l level="1" sID="gen13459"/>et ab iniquo thoro semen exterminabitur. <l eID="gen13459" level="1"/>

** Wisdom 3:17

Et si quidem longæ vitæ erunt, in nihilum computabuntur, <l eID="gen13460" level="1"/> <l level="1" sID="gen13461"/>et sine honore erit novissima senectus illorum : <l eID="gen13461" level="1"/>

** Wisdom 3:18

et si celerius defuncti fuerint, non habebunt spem, <l eID="gen13462" level="1"/> <l level="1" sID="gen13463"/>nec in die agnitionis allocutionem. <l eID="gen13463" level="1"/>

** Wisdom 3:19

Nationis enim iniquæ diræ sunt consummationes.  <chapter eID="Wis.3"/>

* Wisdom 4

** Wisdom 4:1

O quam pulchra est casta generatio, cum claritate ! <l eID="gen13465" level="1"/> <l level="1" sID="gen13466"/>immortalis est enim memoria illius, <l eID="gen13466" level="1"/> <l level="1" sID="gen13467"/>quoniam et apud Deum nota est, et apud homines. <l eID="gen13467" level="1"/>

** Wisdom 4:2

Cum præsens est, imitantur illam, <l eID="gen13468" level="1"/> <l level="1" sID="gen13469"/>et desiderant eam cum se eduxerit ; <l eID="gen13469" level="1"/> <l level="1" sID="gen13470"/>et in perpetuum coronata triumphat, <l eID="gen13470" level="1"/> <l level="1" sID="gen13471"/>incoinquinatorum certaminum præmium vincens. <l eID="gen13471" level="1"/>

** Wisdom 4:3

Multigena autem impiorum multitudo non erit utilis, <l eID="gen13472" level="1"/> <l level="1" sID="gen13473"/>et spuria vitulamina non dabunt radices altas, <l eID="gen13473" level="1"/> <l level="1" sID="gen13474"/>nec stabile firmamentum collocabunt. <l eID="gen13474" level="1"/>

** Wisdom 4:4

Etsi in ramis in tempore germinaverint, <l eID="gen13475" level="1"/> <l level="1" sID="gen13476"/>infirmiter posita, a vento commovebuntur, <l eID="gen13476" level="1"/> <l level="1" sID="gen13477"/>et a nimietate ventorum eradicabuntur. <l eID="gen13477" level="1"/>

** Wisdom 4:5

Confringentur enim rami inconsummati ; <l eID="gen13478" level="1"/> <l level="1" sID="gen13479"/>et fructus illorum inutiles et acerbi ad manducandum, <l eID="gen13479" level="1"/> <l level="1" sID="gen13480"/>et ad nihilum apti. <l eID="gen13480" level="1"/>

** Wisdom 4:6

Ex iniquis enim somnis filii qui nascuntur, <l eID="gen13481" level="1"/> <l level="1" sID="gen13482"/>testes sunt nequitiæ adversus parentes in interrogatione sua. <l eID="gen13482" level="1"/>

** Wisdom 4:7

Justus autem si morte præoccupatus fuerit, <l eID="gen13483" level="1"/> <l level="1" sID="gen13484"/>in refrigerio erit ; <l eID="gen13484" level="1"/>

** Wisdom 4:8

senectus enim venerabilis est non diuturna, <l eID="gen13485" level="1"/> <l level="1" sID="gen13486"/>neque annorum numero computata : <l eID="gen13486" level="1"/> <l level="1" sID="gen13487"/>cani autem sunt sensus hominis, <l eID="gen13487" level="1"/>

** Wisdom 4:9

et ætas senectutis vita immaculata. <l eID="gen13488" level="1"/>

** Wisdom 4:10

Placens Deo factus est dilectus, <l eID="gen13489" level="1"/> <l level="1" sID="gen13490"/>et vivens inter peccatores translatus est. <l eID="gen13490" level="1"/>

** Wisdom 4:11

Raptus est, ne malitia mutaret intellectum ejus, <l eID="gen13491" level="1"/> <l level="1" sID="gen13492"/>aut ne fictio deciperet animam illius. <l eID="gen13492" level="1"/>

** Wisdom 4:12

Fascinatio enim nugacitatis obscurat bona, <l eID="gen13493" level="1"/> <l level="1" sID="gen13494"/>et inconstantia concupiscentiæ transvertit sensum sine malitia. <l eID="gen13494" level="1"/>

** Wisdom 4:13

Consummatus in brevi, <l eID="gen13495" level="1"/> <l level="1" sID="gen13496"/>explevit tempora multa ; <l eID="gen13496" level="1"/>

** Wisdom 4:14

placita enim erat Deo anima illius : <l eID="gen13497" level="1"/> <l level="1" sID="gen13498"/>propter hoc properavit educere illum de medio iniquitatum. <l eID="gen13498" level="1"/> <l level="1" sID="gen13499"/>Populi autem videntes, et non intelligentes, <l eID="gen13499" level="1"/> <l level="1" sID="gen13500"/>nec ponentes in præcordiis talia, <l eID="gen13500" level="1"/>

** Wisdom 4:15

quoniam gratia Dei et misericordia est in sanctos ejus, <l eID="gen13501" level="1"/> <l level="1" sID="gen13502"/>et respectus in electos illius. <l eID="gen13502" level="1"/>

** Wisdom 4:16

Condemnat autem justus mortuus vivos impios, <l eID="gen13503" level="1"/> <l level="1" sID="gen13504"/>et juventus celerius consummata longam vitam injusti. <l eID="gen13504" level="1"/>

** Wisdom 4:17

Videbunt enim finem sapientis, <l eID="gen13505" level="1"/> <l level="1" sID="gen13506"/>et non intelligent quid cogitaverit de illo Deus, <l eID="gen13506" level="1"/> <l level="1" sID="gen13507"/>et quare munierit illum Dominus. <l eID="gen13507" level="1"/>

** Wisdom 4:18

Videbunt, et contemnent eum ; <l eID="gen13508" level="1"/> <l level="1" sID="gen13509"/>illos autem Dominus irridebit. <l eID="gen13509" level="1"/>

** Wisdom 4:19

Et erunt post hæc decidentes sine honore, <l eID="gen13510" level="1"/> <l level="1" sID="gen13511"/>et in contumelia inter mortuos in perpetuum : <l eID="gen13511" level="1"/> <l level="1" sID="gen13512"/>quoniam disrumpet illos inflatos sine voce, <l eID="gen13512" level="1"/> <l level="1" sID="gen13513"/>et commovebit illos a fundamentis, <l eID="gen13513" level="1"/> <l level="1" sID="gen13514"/>et usque ad supremum desolabuntur, <l eID="gen13514" level="1"/> <l level="1" sID="gen13515"/>et erunt gementes, et memoria illorum peribit. <l eID="gen13515" level="1"/>

** Wisdom 4:20

Venient in cogitatione peccatorum suorum timidi, <l eID="gen13516" level="1"/> <l level="1" sID="gen13517"/>et traducent illos ex adverso iniquitates ipsorum.  <chapter eID="Wis.4"/>

* Wisdom 5

** Wisdom 5:1

Tunc stabunt justi in magna constantia <l eID="gen13518" level="1"/> <l level="1" sID="gen13519"/>adversus eos qui se angustiaverunt, <l eID="gen13519" level="1"/> <l level="1" sID="gen13520"/>et qui abstulerunt labores eorum. <l eID="gen13520" level="1"/>

** Wisdom 5:2

Videntes turbabuntur timore horribili, <l eID="gen13521" level="1"/> <l level="1" sID="gen13522"/>et mirabuntur in subitatione insperatæ salutis ; <l eID="gen13522" level="1"/>

** Wisdom 5:3

dicentes intra se, pœnitentiam agentes, <l eID="gen13523" level="1"/> <l level="1" sID="gen13524"/>et præ angustia spiritus gementes : <l eID="gen13524" level="1"/> <l level="1" sID="gen13525"/>Hi sunt quos habuimus aliquando in derisum, <l eID="gen13525" level="1"/> <l level="1" sID="gen13526"/>et in similitudinem improperii. <l eID="gen13526" level="1"/>

** Wisdom 5:4

Nos insensati, vitam illorum æstimabamus insaniam, <l eID="gen13527" level="1"/> <l level="1" sID="gen13528"/>et finem illorum sine honore ; <l eID="gen13528" level="1"/>

** Wisdom 5:5

ecce quomodo computati sunt inter filios Dei, <l eID="gen13529" level="1"/> <l level="1" sID="gen13530"/>et inter sanctos sors illorum est. <l eID="gen13530" level="1"/>

** Wisdom 5:6

Ergo erravimus a via veritatis, <l eID="gen13531" level="1"/> <l level="1" sID="gen13532"/>et justitiæ lumen non luxit nobis, <l eID="gen13532" level="1"/> <l level="1" sID="gen13533"/>et sol intelligentiæ non est ortus nobis. <l eID="gen13533" level="1"/>

** Wisdom 5:7

Lassati sumus in via iniquitatis et perditionis, <l eID="gen13534" level="1"/> <l level="1" sID="gen13535"/>et ambulavimus vias difficiles : <l eID="gen13535" level="1"/> <l level="1" sID="gen13536"/>viam autem Domini ignoravimus. <l eID="gen13536" level="1"/>

** Wisdom 5:8

Quid nobis profuit superbia ? <l eID="gen13537" level="1"/> <l level="1" sID="gen13538"/>aut divitiarum jactantia quid contulit nobis ? <l eID="gen13538" level="1"/>

** Wisdom 5:9

Transierunt omnia illa tamquam umbra, <l eID="gen13539" level="1"/> <l level="1" sID="gen13540"/>et tamquam nuntius percurrens, <l eID="gen13540" level="1"/>

** Wisdom 5:10

et tamquam navis quæ pertransit fluctuantem aquam, <l eID="gen13541" level="1"/> <l level="1" sID="gen13542"/>cujus cum præterierit non est vestigium invenire, <l eID="gen13542" level="1"/> <l level="1" sID="gen13543"/>neque semitam carinæ illius in fluctibus ; <l eID="gen13543" level="1"/>

** Wisdom 5:11

aut tamquam avis quæ transvolat in aëre, <l eID="gen13544" level="1"/> <l level="1" sID="gen13545"/>cujus nullum invenitur argumentum itineris, <l eID="gen13545" level="1"/> <l level="1" sID="gen13546"/>sed tantum sonitus alarum verberans levem ventum, <l eID="gen13546" level="1"/> <l level="1" sID="gen13547"/>et scindens per vim itineris aërem : <l eID="gen13547" level="1"/> <l level="1" sID="gen13548"/>commotis alis transvolavit, <l eID="gen13548" level="1"/> <l level="1" sID="gen13549"/>et post hoc nullum signum invenitur itineris illius ; <l eID="gen13549" level="1"/>

** Wisdom 5:12

aut tamquam sagitta emissa in locum destinatum, <l eID="gen13550" level="1"/> <l level="1" sID="gen13551"/>divisus aër continuo in se reclusus est, <l eID="gen13551" level="1"/> <l level="1" sID="gen13552"/>ut ignoretur transitus illius : <l eID="gen13552" level="1"/>

** Wisdom 5:13

sic et nos nati continuo desivimus esse ; <l eID="gen13553" level="1"/> <l level="1" sID="gen13554"/>et virtutis quidem nullum signum valuimus ostendere, <l eID="gen13554" level="1"/> <l level="1" sID="gen13555"/>in malignitate autem nostra consumpti sumus. <l eID="gen13555" level="1"/>

** Wisdom 5:14

Talia dixerunt in inferno hi qui peccaverunt : <l eID="gen13556" level="1"/>

** Wisdom 5:15

quoniam spes impii tamquam lanugo est quæ a vento tollitur, <l eID="gen13557" level="1"/> <l level="1" sID="gen13558"/>et tamquam spuma gracilis quæ a procella dispergitur, <l eID="gen13558" level="1"/> <l level="1" sID="gen13559"/>et tamquam fumus qui a vento diffusus est, <l eID="gen13559" level="1"/> <l level="1" sID="gen13560"/>et tamquam memoria hospitis unius diei prætereuntis. <l eID="gen13560" level="1"/>

** Wisdom 5:16

Justi autem in perpetuum vivent, <l eID="gen13561" level="1"/> <l level="1" sID="gen13562"/>et apud Dominum est merces eorum, <l eID="gen13562" level="1"/> <l level="1" sID="gen13563"/>et cogitatio illorum apud Altissimum. <l eID="gen13563" level="1"/>

** Wisdom 5:17

Ideo accipient regnum decoris, <l eID="gen13564" level="1"/> <l level="1" sID="gen13565"/>et diadema speciei de manu Domini : <l eID="gen13565" level="1"/> <l level="1" sID="gen13566"/>quoniam dextera sua teget eos, <l eID="gen13566" level="1"/> <l level="1" sID="gen13567"/>et brachio sancto suo defendet illos. <l eID="gen13567" level="1"/>

** Wisdom 5:18

Accipiet armaturam zelus illius, <l eID="gen13568" level="1"/> <l level="1" sID="gen13569"/>et armabit creaturam ad ultionem inimicorum. <l eID="gen13569" level="1"/>

** Wisdom 5:19

Induet pro thorace justitiam, <l eID="gen13570" level="1"/> <l level="1" sID="gen13571"/>et accipiet pro galea judicium certum ; <l eID="gen13571" level="1"/>

** Wisdom 5:20

sumet scutum inexpugnabile æquitatem. <l eID="gen13572" level="1"/>

** Wisdom 5:21

Acuet autem duram iram in lanceam, <l eID="gen13573" level="1"/> <l level="1" sID="gen13574"/>et pugnabit cum illo orbis terrarum contra insensatos. <l eID="gen13574" level="1"/>

** Wisdom 5:22

Ibunt directe emissiones fulgurum, <l eID="gen13575" level="1"/> <l level="1" sID="gen13576"/>et tamquam a bene curvato arcu nubium exterminabuntur, <l eID="gen13576" level="1"/> <l level="1" sID="gen13577"/>et ad certum locum insilient. <l eID="gen13577" level="1"/>

** Wisdom 5:23

Et a petrosa ira plenæ mittentur grandines ; <l eID="gen13578" level="1"/> <l level="1" sID="gen13579"/>excandescet in illos aqua maris, <l eID="gen13579" level="1"/> <l level="1" sID="gen13580"/>et flumina concurrent duriter. <l eID="gen13580" level="1"/>

** Wisdom 5:24

Contra illos stabit spiritus virtutis, <l eID="gen13581" level="1"/> <l level="1" sID="gen13582"/>et tamquam turbo venti dividet illos ; <l eID="gen13582" level="1"/> <l level="1" sID="gen13583"/>et ad eremum perducet omnem terram iniquitas illorum, <l eID="gen13583" level="1"/> <l level="1" sID="gen13584"/>et malignitas evertet sedes potentium.  <chapter eID="Wis.5"/>

* Wisdom 6

** Wisdom 6:1

Melior est sapientia quam vires, <l eID="gen13585" level="1"/> <l level="1" sID="gen13586"/>et vir prudens quam fortis. <l eID="gen13586" level="1"/>

** Wisdom 6:2

Audite ergo, reges, et intelligite ; <l eID="gen13587" level="1"/> <l level="1" sID="gen13588"/>discite, judices finium terræ. <l eID="gen13588" level="1"/>

** Wisdom 6:3

Præbete aures, vos qui continetis multitudines, <l eID="gen13589" level="1"/> <l level="1" sID="gen13590"/>et placetis vobis in turbis nationum. <l eID="gen13590" level="1"/>

** Wisdom 6:4

Quoniam data est a Domino potestas vobis, <l eID="gen13591" level="1"/> <l level="1" sID="gen13592"/>et virtus ab Altissimo : <l eID="gen13592" level="1"/> <l level="1" sID="gen13593"/>qui interrogabit opera vestra, et cogitationes scrutabitur. <l eID="gen13593" level="1"/>

** Wisdom 6:5

Quoniam cum essetis ministri regni illius, <l eID="gen13594" level="1"/> <l level="1" sID="gen13595"/>non recte judicastis, nec custodistis legem justitiæ, <l eID="gen13595" level="1"/> <l level="1" sID="gen13596"/>neque secundum voluntatem Dei ambulastis. <l eID="gen13596" level="1"/>

** Wisdom 6:6

Horrende et cito apparebit vobis, <l eID="gen13597" level="1"/> <l level="1" sID="gen13598"/>quoniam judicium durissimum his qui præsunt fiet. <l eID="gen13598" level="1"/>

** Wisdom 6:7

Exiguo enim conceditur misericordia ; <l eID="gen13599" level="1"/> <l level="1" sID="gen13600"/>potentes autem potenter tormenta patientur. <l eID="gen13600" level="1"/>

** Wisdom 6:8

Non enim subtrahet personam cujusquam Deus, <l eID="gen13601" level="1"/> <l level="1" sID="gen13602"/>nec verebitur magnitudinem ejus cujusquam, <l eID="gen13602" level="1"/> <l level="1" sID="gen13603"/>quoniam pusillum et magnum ipse fecit, <l eID="gen13603" level="1"/> <l level="1" sID="gen13604"/>et æqualiter cura est illi de omnibus. <l eID="gen13604" level="1"/>

** Wisdom 6:9

Fortioribus autem fortior instat cruciatio. <l eID="gen13605" level="1"/>

** Wisdom 6:10

Ad vos ergo, reges, sunt hi sermones mei : <l eID="gen13606" level="1"/> <l level="1" sID="gen13607"/>ut discatis sapientiam, et non excidatis. <l eID="gen13607" level="1"/>

** Wisdom 6:11

Qui enim custodierint justa juste, justificabuntur ; <l eID="gen13608" level="1"/> <l level="1" sID="gen13609"/>et qui didicerint ista, invenient quid respondeant. <l eID="gen13609" level="1"/>

** Wisdom 6:12

Concupiscite ergo sermones meos ; <l eID="gen13610" level="1"/> <l level="1" sID="gen13611"/>diligite illos, et habebitis disciplinam. <l eID="gen13611" level="1"/>

** Wisdom 6:13

Clara est, et quæ numquam marcescit, sapientia : <l eID="gen13612" level="1"/> <l level="1" sID="gen13613"/>et facile videtur ab his qui diligunt eam, <l eID="gen13613" level="1"/> <l level="1" sID="gen13614"/>et invenitur ab his qui quærunt illam. <l eID="gen13614" level="1"/>

** Wisdom 6:14

Præoccupat qui se concupiscunt, <l eID="gen13615" level="1"/> <l level="1" sID="gen13616"/>ut illis se prior ostendat. <l eID="gen13616" level="1"/>

** Wisdom 6:15

Qui de luce vigilaverit ad illam non laborabit ; <l eID="gen13617" level="1"/> <l level="1" sID="gen13618"/>assidentem enim illam foribus suis inveniet. <l eID="gen13618" level="1"/>

** Wisdom 6:16

Cogitare ergo de illa sensus est consummatus, <l eID="gen13619" level="1"/> <l level="1" sID="gen13620"/>et qui vigilaverit propter illam cito securus erit. <l eID="gen13620" level="1"/>

** Wisdom 6:17

Quoniam dignos se ipsa circuit quærens, <l eID="gen13621" level="1"/> <l level="1" sID="gen13622"/>et in viis ostendit se hilariter, <l eID="gen13622" level="1"/> <l level="1" sID="gen13623"/>et in omni providentia occurrit illis. <l eID="gen13623" level="1"/>

** Wisdom 6:18

Initium enim illius verissima est disciplinæ concupiscentia. <l eID="gen13624" level="1"/>

** Wisdom 6:19

Cura ergo disciplinæ dilectio est, <l eID="gen13625" level="1"/> <l level="1" sID="gen13626"/>et dilectio custodia legum illius est ; <l eID="gen13626" level="1"/> <l level="1" sID="gen13627"/>custoditio autem legum consummatio incorruptionis est ; <l eID="gen13627" level="1"/>

** Wisdom 6:20

incorruptio autem facit esse proximum Deo. <l eID="gen13628" level="1"/>

** Wisdom 6:21

Concupiscentia itaque sapientiæ deducit ad regnum perpetuum. <l eID="gen13629" level="1"/>

** Wisdom 6:22

Si ergo delectamini sedibus et sceptris, o reges populi, <l eID="gen13630" level="1"/> <l level="1" sID="gen13631"/>diligite sapientiam, ut in perpetuum regnetis : <l eID="gen13631" level="1"/>

** Wisdom 6:23

diligite lumen sapientiæ, omnes qui præestis populis. <l eID="gen13632" level="1"/>

** Wisdom 6:24

Quid est autem sapientia, et quemadmodum facta sit, referam, <l eID="gen13633" level="1"/> <l level="1" sID="gen13634"/>et non abscondam a vobis sacramenta Dei : <l eID="gen13634" level="1"/> <l level="1" sID="gen13635"/>sed ab initio nativitatis investigabo, <l eID="gen13635" level="1"/> <l level="1" sID="gen13636"/>et ponam in lucem scientiam illius, <l eID="gen13636" level="1"/> <l level="1" sID="gen13637"/>et non præteribo veritatem. <l eID="gen13637" level="1"/>

** Wisdom 6:25

Neque cum invidia tabescente iter habebo, <l eID="gen13638" level="1"/> <l level="1" sID="gen13639"/>quoniam talis homo non erit particeps sapientiæ. <l eID="gen13639" level="1"/>

** Wisdom 6:26

Multitudo autem sapientium sanitas est orbis terrarum, <l eID="gen13640" level="1"/> <l level="1" sID="gen13641"/>et rex sapiens stabilimentum populi est. <l eID="gen13641" level="1"/>

** Wisdom 6:27

Ergo accipite disciplinam per sermones meos, <l eID="gen13642" level="1"/> <l level="1" sID="gen13643"/>et proderit vobis.  <chapter eID="Wis.6"/>

* Wisdom 7

** Wisdom 7:1

Sum quidem et ego mortalis homo, similis omnibus, <l eID="gen13644" level="1"/> <l level="1" sID="gen13645"/>et ex genere terreni illius qui prior factus est : <l eID="gen13645" level="1"/> <l level="1" sID="gen13646"/>et in ventre matris figuratus sum caro ; <l eID="gen13646" level="1"/>

** Wisdom 7:2

decem mensium tempore coagulatus sum in sanguine : <l eID="gen13647" level="1"/> <l level="1" sID="gen13648"/>ex semine hominis, et delectamento somni conveniente. <l eID="gen13648" level="1"/>

** Wisdom 7:3

Et ego natus accepi communem aërem, <l eID="gen13649" level="1"/> <l level="1" sID="gen13650"/>et in similiter factam decidi terram, <l eID="gen13650" level="1"/> <l level="1" sID="gen13651"/>et primam vocem similem omnibus emisi plorans. <l eID="gen13651" level="1"/>

** Wisdom 7:4

In involumentis nutritus sum, et curis magnis : <l eID="gen13652" level="1"/>

** Wisdom 7:5

nemo enim ex regibus aliud habuit nativitatis initium. <l eID="gen13653" level="1"/>

** Wisdom 7:6

Unus ergo introitus est omnibus ad vitam, <l eID="gen13654" level="1"/> <l level="1" sID="gen13655"/>et similis exitus. <l eID="gen13655" level="1"/>

** Wisdom 7:7

Propter hoc optavi, et datus est mihi sensus ; <l eID="gen13656" level="1"/> <l level="1" sID="gen13657"/>et invocavi, et venit in me spiritus sapientiæ : <l eID="gen13657" level="1"/>

** Wisdom 7:8

et præposui illam regnis et sedibus, <l eID="gen13658" level="1"/> <l level="1" sID="gen13659"/>et divitias nihil esse duxi in comparatione illius. <l eID="gen13659" level="1"/>

** Wisdom 7:9

Nec comparavi illi lapidem pretiosum, <l eID="gen13660" level="1"/> <l level="1" sID="gen13661"/>quoniam omne aurum in comparatione illius arena est exigua, <l eID="gen13661" level="1"/> <l level="1" sID="gen13662"/>et tamquam lutum æstimabitur argentum in conspectu illius. <l eID="gen13662" level="1"/>

** Wisdom 7:10

Super salutem et speciem dilexi illam, <l eID="gen13663" level="1"/> <l level="1" sID="gen13664"/>et proposui pro luce habere illam, <l eID="gen13664" level="1"/> <l level="1" sID="gen13665"/>quoniam inextinguibile est lumen illius. <l eID="gen13665" level="1"/>

** Wisdom 7:11

Venerunt autem mihi omnia bona pariter cum illa, <l eID="gen13666" level="1"/> <l level="1" sID="gen13667"/>et innumerabilis honestas per manus illius ; <l eID="gen13667" level="1"/>

** Wisdom 7:12

et lætatus sum in omnibus, <l eID="gen13668" level="1"/> <l level="1" sID="gen13669"/>quoniam antecedebat me ista sapientia, <l eID="gen13669" level="1"/> <l level="1" sID="gen13670"/>et ignorabam quoniam horum omnium mater est. <l eID="gen13670" level="1"/>

** Wisdom 7:13

Quam sine fictione didici, <l eID="gen13671" level="1"/> <l level="1" sID="gen13672"/>et sine invidia communico, <l eID="gen13672" level="1"/> <l level="1" sID="gen13673"/>et honestatem illius non abscondo. <l eID="gen13673" level="1"/>

** Wisdom 7:14

Infinitus enim thesaurus est hominibus ; <l eID="gen13674" level="1"/> <l level="1" sID="gen13675"/>quo qui usi sunt, participes facti sunt amicitiæ Dei, <l eID="gen13675" level="1"/> <l level="1" sID="gen13676"/>propter disciplinæ dona commendati. <l eID="gen13676" level="1"/>

** Wisdom 7:15

Mihi autem dedit Deus dicere ex sententia, <l eID="gen13677" level="1"/> <l level="1" sID="gen13678"/>et præsumere digna horum quæ mihi dantur : <l eID="gen13678" level="1"/> <l level="1" sID="gen13679"/>quoniam ipse sapientiæ dux est, <l eID="gen13679" level="1"/> <l level="1" sID="gen13680"/>et sapientium emendator. <l eID="gen13680" level="1"/>

** Wisdom 7:16

In manu enim illius et nos et sermones nostri, <l eID="gen13681" level="1"/> <l level="1" sID="gen13682"/>et omnis sapientia, et operum scientia, et disciplina. <l eID="gen13682" level="1"/>

** Wisdom 7:17

Ipse enim dedit mihi horum quæ sunt scientiam veram, <l eID="gen13683" level="1"/> <l level="1" sID="gen13684"/>ut sciam dispositionem orbis terrarum, et virtutes elementorum, <l eID="gen13684" level="1"/>

** Wisdom 7:18

initium, et consummationem, et medietatem temporum, <l eID="gen13685" level="1"/> <l level="1" sID="gen13686"/>vicissitudinum permutationes, et commutationes temporum, <l eID="gen13686" level="1"/>

** Wisdom 7:19

anni cursus, et stellarum dispositiones, <l eID="gen13687" level="1"/>

** Wisdom 7:20

naturas animalium, et iras bestiarum, <l eID="gen13688" level="1"/> <l level="1" sID="gen13689"/>vim ventorum, et cogitationes hominum, <l eID="gen13689" level="1"/> <l level="1" sID="gen13690"/>differentias virgultorum, et virtutes radicum. <l eID="gen13690" level="1"/>

** Wisdom 7:21

Et quæcumque sunt absconsa et improvisa didici : <l eID="gen13691" level="1"/> <l level="1" sID="gen13692"/>omnium enim artifex docuit me sapientia. <l eID="gen13692" level="1"/>

** Wisdom 7:22

Est enim in illa spiritus intelligentiæ, <l eID="gen13693" level="1"/> <l level="1" sID="gen13694"/>sanctus, unicus, multiplex, subtilis, <l eID="gen13694" level="1"/> <l level="1" sID="gen13695"/>disertus, mobilis, incoinquinatus, certus, <l eID="gen13695" level="1"/> <l level="1" sID="gen13696"/>suavis, amans bonum, acutus, <l eID="gen13696" level="1"/> <l level="1" sID="gen13697"/>quem nihil vetat, benefaciens, <l eID="gen13697" level="1"/>

** Wisdom 7:23

humanus, benignus, stabilis, certus, securus, <l eID="gen13698" level="1"/> <l level="1" sID="gen13699"/>omnem habens virtutem, omnia prospiciens, <l eID="gen13699" level="1"/> <l level="1" sID="gen13700"/>et qui capiat omnes spiritus, <l eID="gen13700" level="1"/> <l level="1" sID="gen13701"/>intelligibilis, mundus, subtilis. <l eID="gen13701" level="1"/>

** Wisdom 7:24

Omnibus enim mobilibus mobilior est sapientia : <l eID="gen13702" level="1"/> <l level="1" sID="gen13703"/>attingit autem ubique propter suam munditiam. <l eID="gen13703" level="1"/>

** Wisdom 7:25

Vapor est enim virtutis Dei, <l eID="gen13704" level="1"/> <l level="1" sID="gen13705"/>et emanatio quædam est claritatis omnipotentis Dei sincera, <l eID="gen13705" level="1"/> <l level="1" sID="gen13706"/>et ideo nihil inquinatum in eam incurrit : <l eID="gen13706" level="1"/>

** Wisdom 7:26

candor est enim lucis æternæ, <l eID="gen13707" level="1"/> <l level="1" sID="gen13708"/>et speculum sine macula Dei majestatis, <l eID="gen13708" level="1"/> <l level="1" sID="gen13709"/>et imago bonitatis illius. <l eID="gen13709" level="1"/>

** Wisdom 7:27

Et cum sit una, omnia potest ; <l eID="gen13710" level="1"/> <l level="1" sID="gen13711"/>et in se permanens omnia innovat : <l eID="gen13711" level="1"/> <l level="1" sID="gen13712"/>et per nationes in animas sanctas se transfert ; <l eID="gen13712" level="1"/> <l level="1" sID="gen13713"/>amicos Dei et prophetas constituit. <l eID="gen13713" level="1"/>

** Wisdom 7:28

Neminem enim diligit Deus, <l eID="gen13714" level="1"/> <l level="1" sID="gen13715"/>nisi eum qui cum sapientia inhabitat. <l eID="gen13715" level="1"/>

** Wisdom 7:29

Est enim hæc speciosior sole, <l eID="gen13716" level="1"/> <l level="1" sID="gen13717"/>et super omnem dispositionem stellarum : <l eID="gen13717" level="1"/> <l level="1" sID="gen13718"/>luci comparata, invenitur prior. <l eID="gen13718" level="1"/>

** Wisdom 7:30

Illi enim succedit nox ; <l eID="gen13719" level="1"/> <l level="1" sID="gen13720"/>sapientiam autem non vincit malitia.  <chapter eID="Wis.7"/>

* Wisdom 8

** Wisdom 8:1

Attingit ergo a fine usque ad finem fortiter, <l eID="gen13721" level="1"/> <l level="1" sID="gen13722"/>et disponit omnia suaviter. <l eID="gen13722" level="1"/>

** Wisdom 8:2

Hanc amavi, et exquisivi a juventute mea, <l eID="gen13723" level="1"/> <l level="1" sID="gen13724"/>et quæsivi sponsam mihi eam assumere, <l eID="gen13724" level="1"/> <l level="1" sID="gen13725"/>et amator factus sum formæ illius. <l eID="gen13725" level="1"/>

** Wisdom 8:3

Generositatem illius glorificat, <l eID="gen13726" level="1"/> <l level="1" sID="gen13727"/>contubernium habens Dei ; <l eID="gen13727" level="1"/> <l level="1" sID="gen13728"/>sed et omnium Dominus dilexit illam. <l eID="gen13728" level="1"/>

** Wisdom 8:4

Doctrix enim est disciplinæ Dei, <l eID="gen13729" level="1"/> <l level="1" sID="gen13730"/>et electrix operum illius. <l eID="gen13730" level="1"/>

** Wisdom 8:5

Et si divitiæ appetuntur in vita, <l eID="gen13731" level="1"/> <l level="1" sID="gen13732"/>quid sapientia locupletius quæ operatur omnia ? <l eID="gen13732" level="1"/>

** Wisdom 8:6

Si autem sensus operatur, <l eID="gen13733" level="1"/> <l level="1" sID="gen13734"/>quis horum quæ sunt magis quam illa est artifex ? <l eID="gen13734" level="1"/>

** Wisdom 8:7

Et si justitiam quis diligit, <l eID="gen13735" level="1"/> <l level="1" sID="gen13736"/>labores hujus magnas habent virtutes : <l eID="gen13736" level="1"/> <l level="1" sID="gen13737"/>sobrietatem enim et prudentiam docet, <l eID="gen13737" level="1"/> <l level="1" sID="gen13738"/>et justitiam, et virtutem, <l eID="gen13738" level="1"/> <l level="1" sID="gen13739"/>quibus utilius nihil est in vita hominibus. <l eID="gen13739" level="1"/>

** Wisdom 8:8

Et si multitudinem scientiæ desiderat quis, <l eID="gen13740" level="1"/> <l level="1" sID="gen13741"/>scit præterita, et de futuris æstimat ; <l eID="gen13741" level="1"/> <l level="1" sID="gen13742"/>scit versutias sermonum, et dissolutiones argumentorum ; <l eID="gen13742" level="1"/> <l level="1" sID="gen13743"/>signa et monstra scit antequam fiant, <l eID="gen13743" level="1"/> <l level="1" sID="gen13744"/>et eventus temporum et sæculorum. <l eID="gen13744" level="1"/>

** Wisdom 8:9

Proposui ergo hanc adducere mihi ad convivendum, <l eID="gen13745" level="1"/> <l level="1" sID="gen13746"/>sciens quoniam mecum communicabit de bonis, <l eID="gen13746" level="1"/> <l level="1" sID="gen13747"/>et erit allocutio cogitationis et tædii mei. <l eID="gen13747" level="1"/>

** Wisdom 8:10

Habebo propter hanc claritatem ad turbas, <l eID="gen13748" level="1"/> <l level="1" sID="gen13749"/>et honorem apud seniores juvenis ; <l eID="gen13749" level="1"/>

** Wisdom 8:11

et acutus inveniar in judicio, <l eID="gen13750" level="1"/> <l level="1" sID="gen13751"/>et in conspectu potentium admirabilis ero, <l eID="gen13751" level="1"/> <l level="1" sID="gen13752"/>et facies principum mirabuntur me : <l eID="gen13752" level="1"/>

** Wisdom 8:12

tacentem me sustinebunt, <l eID="gen13753" level="1"/> <l level="1" sID="gen13754"/>et loquentem me respicient, <l eID="gen13754" level="1"/> <l level="1" sID="gen13755"/>et sermocinante me plura, manus ori suo imponent. <l eID="gen13755" level="1"/>

** Wisdom 8:13

Præterea habebo per hanc immortalitatem, <l eID="gen13756" level="1"/> <l level="1" sID="gen13757"/>et memoriam æternam his qui post me futuri sunt relinquam. <l eID="gen13757" level="1"/>

** Wisdom 8:14

Disponam populos, <l eID="gen13758" level="1"/> <l level="1" sID="gen13759"/>et nationes mihi erunt subditæ : <l eID="gen13759" level="1"/>

** Wisdom 8:15

timebunt me audientes reges horrendi. <l eID="gen13760" level="1"/> <l level="1" sID="gen13761"/>In multitudine videbor bonus, <l eID="gen13761" level="1"/> <l level="1" sID="gen13762"/>et in bello fortis. <l eID="gen13762" level="1"/>

** Wisdom 8:16

Intrans in domum meam, conquiescam cum illa : <l eID="gen13763" level="1"/> <l level="1" sID="gen13764"/>non enim habet amaritudinem conversatio illius, <l eID="gen13764" level="1"/> <l level="1" sID="gen13765"/>nec tædium convictus illius, <l eID="gen13765" level="1"/> <l level="1" sID="gen13766"/>sed lætitiam et gaudium. <l eID="gen13766" level="1"/>

** Wisdom 8:17

Hæc cogitans apud me <l eID="gen13767" level="1"/> <l level="1" sID="gen13768"/>et commemorans in corde meo, <l eID="gen13768" level="1"/> <l level="1" sID="gen13769"/>quoniam immortalitas est in cognatione sapientiæ, <l eID="gen13769" level="1"/>

** Wisdom 8:18

et in amicitia illius delectatio bona, <l eID="gen13770" level="1"/> <l level="1" sID="gen13771"/>et in operibus manuum illius honestas sine defectione, <l eID="gen13771" level="1"/> <l level="1" sID="gen13772"/>et in certamine loquelæ illius sapientia, <l eID="gen13772" level="1"/> <l level="1" sID="gen13773"/>et præclaritas in communicatione sermonum ipsius : <l eID="gen13773" level="1"/> <l level="1" sID="gen13774"/>circuibam quærens, ut mihi illam assumerem. <l eID="gen13774" level="1"/>

** Wisdom 8:19

Puer autem eram ingeniosus, <l eID="gen13775" level="1"/> <l level="1" sID="gen13776"/>et sortitus sum animam bonam. <l eID="gen13776" level="1"/>

** Wisdom 8:20

Et cum essem magis bonus, <l eID="gen13777" level="1"/> <l level="1" sID="gen13778"/>veni ad corpus incoinquinatum. <l eID="gen13778" level="1"/>

** Wisdom 8:21

Et ut scivi quoniam aliter non possem esse continens, nisi Deus det ; <l eID="gen13779" level="1"/> <l level="1" sID="gen13780"/>et hoc ipsum erat sapientiæ, scire cujus esset hoc donum : <l eID="gen13780" level="1"/> <l level="1" sID="gen13781"/>adii Dominum, et deprecatus sum illum, <l eID="gen13781" level="1"/> <l level="1" sID="gen13782"/>et dixi ex totis præcordiis meis :  <chapter eID="Wis.8"/>

* Wisdom 9

** Wisdom 9:1

Deus patrum meorum, et Domine misericordiæ, <l eID="gen13783" level="1"/> <l level="1" sID="gen13784"/>qui fecisti omnia verbo tuo, <l eID="gen13784" level="1"/>

** Wisdom 9:2

et sapientia tua constituisti hominem, <l eID="gen13785" level="1"/> <l level="1" sID="gen13786"/>ut dominaretur creaturæ quæ a te facta est, <l eID="gen13786" level="1"/>

** Wisdom 9:3

ut disponat orbem terrarum in æquitate et justitia, <l eID="gen13787" level="1"/> <l level="1" sID="gen13788"/>et in directione cordis judicium judicet : <l eID="gen13788" level="1"/>

** Wisdom 9:4

da mihi sedium tuarum assistricem sapientiam, <l eID="gen13789" level="1"/> <l level="1" sID="gen13790"/>et noli me reprobare a pueris tuis : <l eID="gen13790" level="1"/>

** Wisdom 9:5

quoniam servus tuus sum ego, et filius ancillæ tuæ ; <l eID="gen13791" level="1"/> <l level="1" sID="gen13792"/>homo infirmus, et exigui temporis, <l eID="gen13792" level="1"/> <l level="1" sID="gen13793"/>et minor ad intellectum judicii et legum. <l eID="gen13793" level="1"/>

** Wisdom 9:6

Nam etsi quis erit consummatus inter filios hominum, <l eID="gen13794" level="1"/> <l level="1" sID="gen13795"/>si ab illo abfuerit sapientia tua, in nihilum computabitur. <l eID="gen13795" level="1"/>

** Wisdom 9:7

Tu elegisti me regem populo tuo, <l eID="gen13796" level="1"/> <l level="1" sID="gen13797"/>et judicem filiorum tuorum et filiarum : <l eID="gen13797" level="1"/>

** Wisdom 9:8

et dixisti me ædificare templum in monte sancto tuo, <l eID="gen13798" level="1"/> <l level="1" sID="gen13799"/>et in civitate habitationis tuæ altare : <l eID="gen13799" level="1"/> <l level="1" sID="gen13800"/>similitudinem tabernaculi sancti tui quod præparasti ab initio. <l eID="gen13800" level="1"/>

** Wisdom 9:9

Et tecum sapientia tua, quæ novit opera tua, <l eID="gen13801" level="1"/> <l level="1" sID="gen13802"/>quæ et affuit tunc cum orbem terrarum faceres, <l eID="gen13802" level="1"/> <l level="1" sID="gen13803"/>et sciebat quid esset placitum oculis tuis, <l eID="gen13803" level="1"/> <l level="1" sID="gen13804"/>et quid directum in præceptis tuis. <l eID="gen13804" level="1"/>

** Wisdom 9:10

Mitte illam de cælis sanctis tuis, <l eID="gen13805" level="1"/> <l level="1" sID="gen13806"/>et a sede magnitudinis tuæ, <l eID="gen13806" level="1"/> <l level="1" sID="gen13807"/>ut mecum sit et mecum laboret, <l eID="gen13807" level="1"/> <l level="1" sID="gen13808"/>ut sciam quid acceptum sit apud te : <l eID="gen13808" level="1"/>

** Wisdom 9:11

scit enim illa omnia, et intelligit, <l eID="gen13809" level="1"/> <l level="1" sID="gen13810"/>et deducet me in operibus meis sobrie, <l eID="gen13810" level="1"/> <l level="1" sID="gen13811"/>et custodiet me in sua potentia. <l eID="gen13811" level="1"/>

** Wisdom 9:12

Et erunt accepta opera mea, <l eID="gen13812" level="1"/> <l level="1" sID="gen13813"/>et disponam populum tuum juste, <l eID="gen13813" level="1"/> <l level="1" sID="gen13814"/>et ero dignus sedium patris mei. <l eID="gen13814" level="1"/>

** Wisdom 9:13

Quis enim hominum poterit scire consilium Dei ? <l eID="gen13815" level="1"/> <l level="1" sID="gen13816"/>aut quis poterit cogitare quid velit Deus ? <l eID="gen13816" level="1"/>

** Wisdom 9:14

Cogitationes enim mortalium timidæ, <l eID="gen13817" level="1"/> <l level="1" sID="gen13818"/>et incertæ providentiæ nostræ ; <l eID="gen13818" level="1"/>

** Wisdom 9:15

corpus enim quod corrumpitur aggravat animam, <l eID="gen13819" level="1"/> <l level="1" sID="gen13820"/>et terrena inhabitatio deprimit sensum multa cogitantem. <l eID="gen13820" level="1"/>

** Wisdom 9:16

Et difficile æstimamus quæ in terra sunt, <l eID="gen13821" level="1"/> <l level="1" sID="gen13822"/>et quæ in prospectu sunt invenimus cum labore : <l eID="gen13822" level="1"/> <l level="1" sID="gen13823"/>quæ autem in cælis sunt, quis investigabit ? <l eID="gen13823" level="1"/>

** Wisdom 9:17

Sensum autem tuum, quis sciet, nisi tu dederis sapientiam, <l eID="gen13824" level="1"/> <l level="1" sID="gen13825"/>et miseris spiritum sanctum tuum de altissimis, <l eID="gen13825" level="1"/>

** Wisdom 9:18

et sic correctæ sint semitæ eorum qui sunt in terris, <l eID="gen13826" level="1"/> <l level="1" sID="gen13827"/>et quæ tibi placent didicerint homines ? <l eID="gen13827" level="1"/>

** Wisdom 9:19

Nam per sapientiam sanati sunt <l eID="gen13828" level="1"/> <l level="1" sID="gen13829"/>quicumque placuerunt tibi, Domine, a principio.  <chapter eID="Wis.9"/>

* Wisdom 10

** Wisdom 10:1

Hæc illum qui primus formatus est a Deo patre orbis terrarum, <l eID="gen13830" level="1"/> <l level="1" sID="gen13831"/>cum solus esset creatus, custodivit, <l eID="gen13831" level="1"/>

** Wisdom 10:2

et eduxit illum a delicto suo, <l eID="gen13832" level="1"/> <l level="1" sID="gen13833"/>et dedit illi virtutem continendi omnia. <l eID="gen13833" level="1"/>

** Wisdom 10:3

Ab hac ut recessit injustus in ira sua, <l eID="gen13834" level="1"/> <l level="1" sID="gen13835"/>per iram homicidii fraterni deperiit. <l eID="gen13835" level="1"/>

** Wisdom 10:4

Propter quem cum aqua deleret terram, sanavit iterum sapientia, <l eID="gen13836" level="1"/> <l level="1" sID="gen13837"/>per contemptibile lignum justum gubernans. <l eID="gen13837" level="1"/>

** Wisdom 10:5

Hæc et in consensu nequitiæ, cum se nationes contulissent, <l eID="gen13838" level="1"/> <l level="1" sID="gen13839"/>scivit justum, et conservavit sine querela Deo, <l eID="gen13839" level="1"/> <l level="1" sID="gen13840"/>et in filii misericordia fortem custodivit. <l eID="gen13840" level="1"/>

** Wisdom 10:6

Hæc justum a pereuntibus impiis liberavit fugientem, <l eID="gen13841" level="1"/> <l level="1" sID="gen13842"/>descendente igne in Pentapolim : <l eID="gen13842" level="1"/>

** Wisdom 10:7

quibus in testimonium nequitiæ <l eID="gen13843" level="1"/> <l level="1" sID="gen13844"/>fumigabunda constat deserta terra, <l eID="gen13844" level="1"/> <l level="1" sID="gen13845"/>et incerto tempore fructus habentes arbores : <l eID="gen13845" level="1"/> <l level="1" sID="gen13846"/>et incredibilis animæ memoria stans figmentum salis. <l eID="gen13846" level="1"/>

** Wisdom 10:8

Sapientiam enim prætereuntes, <l eID="gen13847" level="1"/> <l level="1" sID="gen13848"/>non tantum in hoc lapsi sunt ut ignorarent bona, <l eID="gen13848" level="1"/> <l level="1" sID="gen13849"/>sed et insipientiæ suæ reliquerunt hominibus memoriam, <l eID="gen13849" level="1"/> <l level="1" sID="gen13850"/>ut in his quæ peccaverunt nec latere potuissent. <l eID="gen13850" level="1"/>

** Wisdom 10:9

Sapientia autem hos qui se observant <l eID="gen13851" level="1"/> <l level="1" sID="gen13852"/>a doloribus liberavit. <l eID="gen13852" level="1"/>

** Wisdom 10:10

Hæc profugum iræ fratris justum deduxit per vias rectas, <l eID="gen13853" level="1"/> <l level="1" sID="gen13854"/>et ostendit illi regnum Dei, <l eID="gen13854" level="1"/> <l level="1" sID="gen13855"/>et dedit illi scientiam sanctorum ; <l eID="gen13855" level="1"/> <l level="1" sID="gen13856"/>honestavit illum in laboribus, <l eID="gen13856" level="1"/> <l level="1" sID="gen13857"/>et complevit labores illius. <l eID="gen13857" level="1"/>

** Wisdom 10:11

In fraude circumvenientium illum affuit illi, <l eID="gen13858" level="1"/> <l level="1" sID="gen13859"/>et honestum fecit illum. <l eID="gen13859" level="1"/>

** Wisdom 10:12

Custodivit illum ab inimicis, <l eID="gen13860" level="1"/> <l level="1" sID="gen13861"/>et a seductoribus tutavit illum : <l eID="gen13861" level="1"/> <l level="1" sID="gen13862"/>et certamen forte dedit illi ut vinceret, <l eID="gen13862" level="1"/> <l level="1" sID="gen13863"/>et sciret quoniam omnium potentior est sapientia. <l eID="gen13863" level="1"/>

** Wisdom 10:13

Hæc venditum justum non dereliquit, <l eID="gen13864" level="1"/> <l level="1" sID="gen13865"/>sed a peccatoribus liberavit eum ; <l eID="gen13865" level="1"/> <l level="1" sID="gen13866"/>descenditque cum illo in foveam, <l eID="gen13866" level="1"/>

** Wisdom 10:14

et in vinculis non dereliquit illum, <l eID="gen13867" level="1"/> <l level="1" sID="gen13868"/>donec afferret illi sceptrum regni, <l eID="gen13868" level="1"/> <l level="1" sID="gen13869"/>et potentiam adversus eos qui eum deprimebant : <l eID="gen13869" level="1"/> <l level="1" sID="gen13870"/>et mendaces ostendit qui maculaverunt illum, <l eID="gen13870" level="1"/> <l level="1" sID="gen13871"/>et dedit illi claritatem æternam. <l eID="gen13871" level="1"/>

** Wisdom 10:15

Hæc populum justum et semen sine querela liberavit <l eID="gen13872" level="1"/> <l level="1" sID="gen13873"/>a nationibus quæ illum deprimebant. <l eID="gen13873" level="1"/>

** Wisdom 10:16

Intravit in animam servi Dei, <l eID="gen13874" level="1"/> <l level="1" sID="gen13875"/>et stetit contra reges horrendos in portentis et signis. <l eID="gen13875" level="1"/>

** Wisdom 10:17

Et reddidit justis mercedem laborum suorum, <l eID="gen13876" level="1"/> <l level="1" sID="gen13877"/>et deduxit illos in via mirabili : <l eID="gen13877" level="1"/> <l level="1" sID="gen13878"/>et fuit illis in velamento diei, <l eID="gen13878" level="1"/> <l level="1" sID="gen13879"/>et in luce stellarum per noctem ; <l eID="gen13879" level="1"/>

** Wisdom 10:18

transtulit illos per mare Rubrum, <l eID="gen13880" level="1"/> <l level="1" sID="gen13881"/>et transvexit illos per aquam nimiam. <l eID="gen13881" level="1"/>

** Wisdom 10:19

Inimicos autem illorum demersit in mare, <l eID="gen13882" level="1"/> <l level="1" sID="gen13883"/>et ab altitudine inferorum eduxit illos. <l eID="gen13883" level="1"/> <l level="1" sID="gen13884"/>Ideo justi tulerunt spolia impiorum, <l eID="gen13884" level="1"/>

** Wisdom 10:20

et decantaverunt, Domine, nomen sanctum tuum, <l eID="gen13885" level="1"/> <l level="1" sID="gen13886"/>et victricem manum tuam laudaverunt pariter : <l eID="gen13886" level="1"/>

** Wisdom 10:21

quoniam sapientia aperuit os mutorum, <l eID="gen13887" level="1"/> <l level="1" sID="gen13888"/>et linguas infantium fecit disertas.  <chapter eID="Wis.10"/>

* Wisdom 11

** Wisdom 11:1

Direxit opera eorum in manibus prophetæ sancti. <l eID="gen13889" level="1"/>

** Wisdom 11:2

Iter fecerunt per deserta quæ non habitabantur, <l eID="gen13890" level="1"/> <l level="1" sID="gen13891"/>et in locis desertis fixerunt casas. <l eID="gen13891" level="1"/>

** Wisdom 11:3

Steterunt contra hostes, <l eID="gen13892" level="1"/> <l level="1" sID="gen13893"/>et de inimicis se vindicaverunt. <l eID="gen13893" level="1"/>

** Wisdom 11:4

Sitierunt, et invocaverunt te, <l eID="gen13894" level="1"/> <l level="1" sID="gen13895"/>et data est illis aqua de petra altissima, <l eID="gen13895" level="1"/> <l level="1" sID="gen13896"/>et requies sitis de lapide duro. <l eID="gen13896" level="1"/>

** Wisdom 11:5

Per quæ enim pœnas passi sunt inimici illorum <l eID="gen13897" level="1"/> <l level="1" sID="gen13898"/>a defectione potus sui, <l eID="gen13898" level="1"/> <l level="1" sID="gen13899"/>et in eis cum abundarent filii Israël lætati sunt : <l eID="gen13899" level="1"/>

** Wisdom 11:6

per hæc, cum illis deessent, bene cum illis actum est. <l eID="gen13900" level="1"/>

** Wisdom 11:7

Nam pro fonte quidem sempiterni fluminis, <l eID="gen13901" level="1"/> <l level="1" sID="gen13902"/>humanum sanguinem dedisti injustis. <l eID="gen13902" level="1"/>

** Wisdom 11:8

Qui cum minuerentur in traductione infantium occisorum, <l eID="gen13903" level="1"/> <l level="1" sID="gen13904"/>dedisti illis abundantem aquam insperate, <l eID="gen13904" level="1"/>

** Wisdom 11:9

ostendens per sitim quæ tunc fuit, <l eID="gen13905" level="1"/> <l level="1" sID="gen13906"/>quemadmodum tuos exaltares, <l eID="gen13906" level="1"/> <l level="1" sID="gen13907"/>et adversarios illorum necares. <l eID="gen13907" level="1"/>

** Wisdom 11:10

Cum enim tentati sunt, <l eID="gen13908" level="1"/> <l level="1" sID="gen13909"/>et quidem cum misericordia disciplinam accipientes, <l eID="gen13909" level="1"/> <l level="1" sID="gen13910"/>scierunt quemadmodum cum ira judicati impii tormenta paterentur. <l eID="gen13910" level="1"/>

** Wisdom 11:11

Hos quidem tamquam pater monens probasti ; <l eID="gen13911" level="1"/> <l level="1" sID="gen13912"/>illos autem tamquam durus rex interrogans condemnasti. <l eID="gen13912" level="1"/>

** Wisdom 11:12

Absentes enim, et præsentes, similiter torquebantur. <l eID="gen13913" level="1"/>

** Wisdom 11:13

Duplex enim illos acceperat tædium et gemitus, <l eID="gen13914" level="1"/> <l level="1" sID="gen13915"/>cum memoria præteritorum. <l eID="gen13915" level="1"/>

** Wisdom 11:14

Cum enim audirent per sua tormenta bene secum agi, <l eID="gen13916" level="1"/> <l level="1" sID="gen13917"/>commemorati sunt Dominum, admirantes in finem exitus. <l eID="gen13917" level="1"/>

** Wisdom 11:15

Quem enim in expositione prava projectum deriserunt, <l eID="gen13918" level="1"/> <l level="1" sID="gen13919"/>in finem eventus mirati sunt, <l eID="gen13919" level="1"/> <l level="1" sID="gen13920"/>non similiter justis sitientes. <l eID="gen13920" level="1"/>

** Wisdom 11:16

Pro cogitationibus autem insensatis iniquitatis illorum, <l eID="gen13921" level="1"/> <l level="1" sID="gen13922"/>quod quidam errantes colebant mutos serpentes <l eID="gen13922" level="1"/> <l level="1" sID="gen13923"/>et bestias supervacuas, <l eID="gen13923" level="1"/> <l level="1" sID="gen13924"/>immisisti illis multitudinem mutorum animalium in vindictam ; <l eID="gen13924" level="1"/>

** Wisdom 11:17

ut scirent quia per quæ peccat quis, per hæc et torquetur. <l eID="gen13925" level="1"/>

** Wisdom 11:18

Non enim impossibilis erat omnipotens manus tua, <l eID="gen13926" level="1"/> <l level="1" sID="gen13927"/>quæ creavit orbem terrarum ex materia invisa, <l eID="gen13927" level="1"/> <l level="1" sID="gen13928"/>immittere illis multitudinem ursorum, aut audaces leones, <l eID="gen13928" level="1"/>

** Wisdom 11:19

aut novi generis ira plenas ignotas bestias, <l eID="gen13929" level="1"/> <l level="1" sID="gen13930"/>aut vaporem ignium spirantes, <l eID="gen13930" level="1"/> <l level="1" sID="gen13931"/>aut fumi odorem proferentes, <l eID="gen13931" level="1"/> <l level="1" sID="gen13932"/>aut horrendas ab oculis scintillas emittentes ; <l eID="gen13932" level="1"/>

** Wisdom 11:20

quarum non solum læsura poterat illos exterminare, <l eID="gen13933" level="1"/> <l level="1" sID="gen13934"/>sed et aspectus per timorem occidere. <l eID="gen13934" level="1"/>

** Wisdom 11:21

Sed et sine his uno spiritu poterant occidi, <l eID="gen13935" level="1"/> <l level="1" sID="gen13936"/>persecutionem passi ab ipsis factis suis, <l eID="gen13936" level="1"/> <l level="1" sID="gen13937"/>et dispersi per spiritum virtutis tuæ : <l eID="gen13937" level="1"/> <l level="1" sID="gen13938"/>sed omnia in mensura, et numero et pondere disposuisti. <l eID="gen13938" level="1"/>

** Wisdom 11:22

Multum enim valere, tibi soli supererat semper : <l eID="gen13939" level="1"/> <l level="1" sID="gen13940"/>et virtuti brachii tui quis resistet ? <l eID="gen13940" level="1"/>

** Wisdom 11:23

Quoniam tamquam momentum stateræ, <l eID="gen13941" level="1"/> <l level="1" sID="gen13942"/>sic est ante te orbis terrarum, <l eID="gen13942" level="1"/> <l level="1" sID="gen13943"/>et tamquam gutta roris antelucani quæ descendit in terram. <l eID="gen13943" level="1"/>

** Wisdom 11:24

Sed misereris omnium, quia omnia potes ; <l eID="gen13944" level="1"/> <l level="1" sID="gen13945"/>et dissimulas peccata hominum, propter pœnitentiam. <l eID="gen13945" level="1"/>

** Wisdom 11:25

Diligis enim omnia quæ sunt, <l eID="gen13946" level="1"/> <l level="1" sID="gen13947"/>et nihil odisti eorum quæ fecisti ; <l eID="gen13947" level="1"/> <l level="1" sID="gen13948"/>nec enim odiens aliquid constituisti aut fecisti. <l eID="gen13948" level="1"/>

** Wisdom 11:26

Quomodo autem posset aliquid permanere, nisi tu voluisses ? <l eID="gen13949" level="1"/> <l level="1" sID="gen13950"/>aut quod a te vocatum non esset conservaretur ? <l eID="gen13950" level="1"/>

** Wisdom 11:27

Parcis autem omnibus, quoniam tua sunt, Domine, <l eID="gen13951" level="1"/> <l level="1" sID="gen13952"/>qui amas animas.  <chapter eID="Wis.11"/>

* Wisdom 12

** Wisdom 12:1

O quam bonus et suavis est, Domine, spiritus tuus in omnibus ! <l eID="gen13953" level="1"/>

** Wisdom 12:2

Ideoque eos qui exerrant partibus corripis, <l eID="gen13954" level="1"/> <l level="1" sID="gen13955"/>et de quibus peccant admones et alloqueris, <l eID="gen13955" level="1"/> <l level="1" sID="gen13956"/>ut relicta malitia credant in te, Domine. <l eID="gen13956" level="1"/>

** Wisdom 12:3

Illos enim antiquos inhabitatores terræ sanctæ tuæ, <l eID="gen13957" level="1"/> <l level="1" sID="gen13958"/>quos exhorruisti, <l eID="gen13958" level="1"/>

** Wisdom 12:4

quoniam odibilia opera tibi faciebant <l eID="gen13959" level="1"/> <l level="1" sID="gen13960"/>per medicamina et sacrificia injusta, <l eID="gen13960" level="1"/>

** Wisdom 12:5

et filiorum suorum necatores sine misericordia, <l eID="gen13961" level="1"/> <l level="1" sID="gen13962"/>et comestores viscerum hominum, <l eID="gen13962" level="1"/> <l level="1" sID="gen13963"/>et devoratores sanguinis a medio sacramento tuo, <l eID="gen13963" level="1"/>

** Wisdom 12:6

et auctores parentes animarum inauxiliatarum, <l eID="gen13964" level="1"/> <l level="1" sID="gen13965"/>perdere voluisti per manus parentum nostrorum : <l eID="gen13965" level="1"/>

** Wisdom 12:7

ut dignam perciperent peregrinationem puerorum Dei, <l eID="gen13966" level="1"/> <l level="1" sID="gen13967"/>quæ tibi omnium carior est terra. <l eID="gen13967" level="1"/>

** Wisdom 12:8

Sed et his tamquam hominibus pepercisti, <l eID="gen13968" level="1"/> <l level="1" sID="gen13969"/>et misisti antecessores exercitus tui vespas, <l eID="gen13969" level="1"/> <l level="1" sID="gen13970"/>ut illos paulatim exterminarent. <l eID="gen13970" level="1"/>

** Wisdom 12:9

Non quia impotens eras in bello subjicere impios justis, <l eID="gen13971" level="1"/> <l level="1" sID="gen13972"/>aut bestiis sævis, aut verbo duro simul exterminare : <l eID="gen13972" level="1"/>

** Wisdom 12:10

sed partibus judicans, <l eID="gen13973" level="1"/> <l level="1" sID="gen13974"/>dabas locum pœnitentiæ, <l eID="gen13974" level="1"/> <l level="1" sID="gen13975"/>non ignorans quoniam nequam est natio eorum, <l eID="gen13975" level="1"/> <l level="1" sID="gen13976"/>et naturalis malitia ipsorum, <l eID="gen13976" level="1"/> <l level="1" sID="gen13977"/>et quoniam non poterat mutari cogitatio illorum in perpetuum. <l eID="gen13977" level="1"/>

** Wisdom 12:11

Semen enim erat maledictum ab initio ; <l eID="gen13978" level="1"/> <l level="1" sID="gen13979"/>nec timens aliquem, veniam dabas peccatis illorum. <l eID="gen13979" level="1"/>

** Wisdom 12:12

Quis enim dicet tibi : Quid fecisti ? <l eID="gen13980" level="1"/> <l level="1" sID="gen13981"/>aut quis stabit contra judicium tuum ? <l eID="gen13981" level="1"/> <l level="1" sID="gen13982"/>aut quis in conspectu tuo veniet vindex iniquorum hominum ? <l eID="gen13982" level="1"/> <l level="1" sID="gen13983"/>aut quis tibi imputabit, si perierint nationes quas tu fecisti ? <l eID="gen13983" level="1"/>

** Wisdom 12:13

Non enim est alius deus quam tu, <l eID="gen13984" level="1"/> <l level="1" sID="gen13985"/>cui cura est de omnibus, <l eID="gen13985" level="1"/> <l level="1" sID="gen13986"/>ut ostendas quoniam non injuste judicas judicium. <l eID="gen13986" level="1"/>

** Wisdom 12:14

Neque rex, neque tyrannus in conspectu tuo inquirent <l eID="gen13987" level="1"/> <l level="1" sID="gen13988"/>de his quos perdidisti. <l eID="gen13988" level="1"/>

** Wisdom 12:15

Cum ergo sis justus, juste omnia disponis ; <l eID="gen13989" level="1"/> <l level="1" sID="gen13990"/>ipsum quoque qui non debet puniri, condemnare, <l eID="gen13990" level="1"/> <l level="1" sID="gen13991"/>exterum æstimas a tua virtute. <l eID="gen13991" level="1"/>

** Wisdom 12:16

Virtus enim tua justitiæ initium est, <l eID="gen13992" level="1"/> <l level="1" sID="gen13993"/>et ob hoc quod Dominus es, <l eID="gen13993" level="1"/> <l level="1" sID="gen13994"/>omnibus te parcere facis. <l eID="gen13994" level="1"/>

** Wisdom 12:17

Virtutem enim ostendis tu, <l eID="gen13995" level="1"/> <l level="1" sID="gen13996"/>qui non crederis esse in virtute consummatus, <l eID="gen13996" level="1"/> <l level="1" sID="gen13997"/>et horum qui te nesciunt audaciam traducis. <l eID="gen13997" level="1"/>

** Wisdom 12:18

Tu autem dominator virtutis, cum tranquillitate judicas, <l eID="gen13998" level="1"/> <l level="1" sID="gen13999"/>et cum magna reverentia disponis nos : <l eID="gen13999" level="1"/> <l level="1" sID="gen14000"/>subest enim tibi, cum volueris posse. <l eID="gen14000" level="1"/>

** Wisdom 12:19

Docuisti autem populum tuum per talia opera, <l eID="gen14001" level="1"/> <l level="1" sID="gen14002"/>quoniam oportet justum esse et humanum ; <l eID="gen14002" level="1"/> <l level="1" sID="gen14003"/>et bonæ spei fecisti filios tuos, <l eID="gen14003" level="1"/> <l level="1" sID="gen14004"/>quoniam judicans das locum in peccatis pœnitentiæ. <l eID="gen14004" level="1"/>

** Wisdom 12:20

Si enim inimicos servorum tuorum, et debitos morti, <l eID="gen14005" level="1"/> <l level="1" sID="gen14006"/>cum tanta cruciasti attentione, <l eID="gen14006" level="1"/> <l level="1" sID="gen14007"/>dans tempus et locum per quæ possent mutari a malitia : <l eID="gen14007" level="1"/>

** Wisdom 12:21

cum quanta diligentia judicasti filios tuos, <l eID="gen14008" level="1"/> <l level="1" sID="gen14009"/>quorum parentibus juramenta et conventiones dedisti bonarum promissionum ! <l eID="gen14009" level="1"/>

** Wisdom 12:22

Cum ergo das nobis disciplinam, <l eID="gen14010" level="1"/> <l level="1" sID="gen14011"/>inimicos nostros multipliciter flagellas, <l eID="gen14011" level="1"/> <l level="1" sID="gen14012"/>ut bonitatem tuam cogitemus judicantes, <l eID="gen14012" level="1"/> <l level="1" sID="gen14013"/>et cum de nobis judicatur, speremus misericordiam tuam. <l eID="gen14013" level="1"/>

** Wisdom 12:23

Unde et illis qui in vita sua insensate et injuste vixerunt, <l eID="gen14014" level="1"/> <l level="1" sID="gen14015"/>per hæc quæ coluerunt dedisti summa tormenta. <l eID="gen14015" level="1"/>

** Wisdom 12:24

Etenim in erroris via diutius erraverunt, <l eID="gen14016" level="1"/> <l level="1" sID="gen14017"/>deos æstimantes hæc quæ in animalibus sunt supervacua, <l eID="gen14017" level="1"/> <l level="1" sID="gen14018"/>infantium insensatorum more viventes. <l eID="gen14018" level="1"/>

** Wisdom 12:25

Propter hoc tamquam pueris insensatis judicium in derisum dedisti. <l eID="gen14019" level="1"/>

** Wisdom 12:26

Qui autem ludibriis et increpationibus non sunt correcti, <l eID="gen14020" level="1"/> <l level="1" sID="gen14021"/>dignum Dei judicium experti sunt. <l eID="gen14021" level="1"/>

** Wisdom 12:27

In quibus enim patientes indignabantur <l eID="gen14022" level="1"/> <l level="1" sID="gen14023"/>per hæc quos putabant deos, <l eID="gen14023" level="1"/> <l level="1" sID="gen14024"/>in ipsis cum exterminarentur videntes, <l eID="gen14024" level="1"/> <l level="1" sID="gen14025"/>illum quem olim negabant se nosse, verum Deum agnoverunt ; <l eID="gen14025" level="1"/> <l level="1" sID="gen14026"/>propter quod et finis condemnationis eorum venit super illos.  <chapter eID="Wis.12"/>

* Wisdom 13

** Wisdom 13:1

Vani autem sunt omnes homines <l eID="gen14027" level="1"/> <l level="1" sID="gen14028"/>in quibus non subest scientia Dei ; <l eID="gen14028" level="1"/> <l level="1" sID="gen14029"/>et de his quæ videntur bona, <l eID="gen14029" level="1"/> <l level="1" sID="gen14030"/>non potuerunt intelligere eum qui est, <l eID="gen14030" level="1"/> <l level="1" sID="gen14031"/>neque operibus attendentes agnoverunt quis esset artifex : <l eID="gen14031" level="1"/>

** Wisdom 13:2

sed aut ignem, aut spiritum, aut citatum aërem, <l eID="gen14032" level="1"/> <l level="1" sID="gen14033"/>aut gyrum stellarum, aut nimiam aquam, aut solem et lunam, <l eID="gen14033" level="1"/> <l level="1" sID="gen14034"/>rectores orbis terrarum deos putaverunt. <l eID="gen14034" level="1"/>

** Wisdom 13:3

Quorum si specie delectati, deos putaverunt, <l eID="gen14035" level="1"/> <l level="1" sID="gen14036"/>sciant quanto his dominator eorum speciosior est : <l eID="gen14036" level="1"/> <l level="1" sID="gen14037"/>speciei enim generator hæc omnia constituit. <l eID="gen14037" level="1"/>

** Wisdom 13:4

Aut si virtutem et opera eorum mirati sunt, <l eID="gen14038" level="1"/> <l level="1" sID="gen14039"/>intelligant ab illis quoniam qui hæc fecit fortior est illis : <l eID="gen14039" level="1"/>

** Wisdom 13:5

a magnitudine enim speciei et creaturæ <l eID="gen14040" level="1"/> <l level="1" sID="gen14041"/>cognoscibiliter poterit creator horum videri. <l eID="gen14041" level="1"/>

** Wisdom 13:6

Sed tamen adhuc in his minor est querela ; <l eID="gen14042" level="1"/> <l level="1" sID="gen14043"/>et hi enim fortasse errant, <l eID="gen14043" level="1"/> <l level="1" sID="gen14044"/>Deum quærentes, et volentes invenire. <l eID="gen14044" level="1"/>

** Wisdom 13:7

Etenim cum in operibus illius conversentur inquirunt, <l eID="gen14045" level="1"/> <l level="1" sID="gen14046"/>et persuasum habent quoniam bona sunt quæ videntur. <l eID="gen14046" level="1"/>

** Wisdom 13:8

Iterum autem nec his debet ignosci. <l eID="gen14047" level="1"/>

** Wisdom 13:9

Si enim tantum potuerunt scire <l eID="gen14048" level="1"/> <l level="1" sID="gen14049"/>ut possent æstimare sæculum, <l eID="gen14049" level="1"/> <l level="1" sID="gen14050"/>quomodo hujus Dominum non facilius invenerunt ? <l eID="gen14050" level="1"/>

** Wisdom 13:10

Infelices autem sunt, <l eID="gen14051" level="1"/> <l level="1" sID="gen14052"/>et inter mortuos spes illorum est, <l eID="gen14052" level="1"/> <l level="1" sID="gen14053"/>qui appellaverunt deos opera manuum hominum : <l eID="gen14053" level="1"/> <l level="1" sID="gen14054"/>aurum et argentum, artis inventionem, <l eID="gen14054" level="1"/> <l level="1" sID="gen14055"/>et similitudines animalium, aut lapidem inutilem, <l eID="gen14055" level="1"/> <l level="1" sID="gen14056"/>opus manus antiquæ. <l eID="gen14056" level="1"/>

** Wisdom 13:11

Aut si quis artifex faber de silva lignum rectum secuerit, <l eID="gen14057" level="1"/> <l level="1" sID="gen14058"/>et hujus docte eradat omnem corticem, <l eID="gen14058" level="1"/> <l level="1" sID="gen14059"/>et arte sua usus <l eID="gen14059" level="1"/> <l level="1" sID="gen14060"/>diligenter fabricet vas utile in conversationem vitæ ; <l eID="gen14060" level="1"/>

** Wisdom 13:12

reliquiis autem ejus operis <l eID="gen14061" level="1"/> <l level="1" sID="gen14062"/>ad præparationem escæ abutatur, <l eID="gen14062" level="1"/>

** Wisdom 13:13

et reliquum horum quod ad nullos usus facit, <l eID="gen14063" level="1"/> <l level="1" sID="gen14064"/>lignum curvum et vorticibus plenum <l eID="gen14064" level="1"/> <l level="1" sID="gen14065"/>sculpat diligenter per vacuitatem suam, <l eID="gen14065" level="1"/> <l level="1" sID="gen14066"/>et per scientiam suæ artis figuret illud, <l eID="gen14066" level="1"/> <l level="1" sID="gen14067"/>et assimilet illud imagini hominis, <l eID="gen14067" level="1"/>

** Wisdom 13:14

aut alicui ex animalibus illud comparet : <l eID="gen14068" level="1"/> <l level="1" sID="gen14069"/>perliniens rubrica, et rubicundum faciens fuco colorem illius, <l eID="gen14069" level="1"/> <l level="1" sID="gen14070"/>et omnem maculam quæ in illo est perliniens ; <l eID="gen14070" level="1"/>

** Wisdom 13:15

et faciat ei dignam habitationem, <l eID="gen14071" level="1"/> <l level="1" sID="gen14072"/>et in pariete ponens illud, <l eID="gen14072" level="1"/> <l level="1" sID="gen14073"/>et confirmans ferro

** Wisdom 13:16

ne forte cadat, <l eID="gen14073" level="1"/> <l level="1" sID="gen14074"/>prospiciens illi : <l eID="gen14074" level="1"/> <l level="1" sID="gen14075"/>sciens quoniam non potest adjuvare se : <l eID="gen14075" level="1"/> <l level="1" sID="gen14076"/>imago enim est, et opus est illi adjutorium. <l eID="gen14076" level="1"/>

** Wisdom 13:17

Et de substantia sua, et de filiis suis, <l eID="gen14077" level="1"/> <l level="1" sID="gen14078"/>et de nuptiis votum faciens inquirit : <l eID="gen14078" level="1"/> <l level="1" sID="gen14079"/>non erubescit loqui cum illo qui sine anima est. <l eID="gen14079" level="1"/>

** Wisdom 13:18

Et pro sanitate quidem infirmum deprecatur, <l eID="gen14080" level="1"/> <l level="1" sID="gen14081"/>et pro vita rogat mortuum, <l eID="gen14081" level="1"/> <l level="1" sID="gen14082"/>et in adjutorium inutilem invocat. <l eID="gen14082" level="1"/>

** Wisdom 13:19

Et pro itinere petit ab eo qui ambulare non potest ; <l eID="gen14083" level="1"/> <l level="1" sID="gen14084"/>et de acquirendo, et de operando, <l eID="gen14084" level="1"/> <l level="1" sID="gen14085"/>et de omnium rerum eventu, <l eID="gen14085" level="1"/> <l level="1" sID="gen14086"/>petit ab eo qui in omnibus est inutilis.  <chapter eID="Wis.13"/>

* Wisdom 14

** Wisdom 14:1

Iterum alius navigare cogitans, <l eID="gen14087" level="1"/> <l level="1" sID="gen14088"/>et per feros fluctus iter facere incipiens, <l eID="gen14088" level="1"/> <l level="1" sID="gen14089"/>ligno portante se, fragilius lignum invocat. <l eID="gen14089" level="1"/>

** Wisdom 14:2

Illud enim cupiditas acquirendi excogitavit, <l eID="gen14090" level="1"/> <l level="1" sID="gen14091"/>et artifex sapientia fabricavit sua. <l eID="gen14091" level="1"/>

** Wisdom 14:3

Tua autem, Pater, providentia gubernat : <l eID="gen14092" level="1"/> <l level="1" sID="gen14093"/>quoniam dedisti et in mari viam, <l eID="gen14093" level="1"/> <l level="1" sID="gen14094"/>et inter fluctus semitam firmissimam, <l eID="gen14094" level="1"/>

** Wisdom 14:4

ostendens quoniam potens es ex omnibus salvare, <l eID="gen14095" level="1"/> <l level="1" sID="gen14096"/>etiam si sine arte aliquis adeat mare. <l eID="gen14096" level="1"/>

** Wisdom 14:5

Sed ut non essent vacua sapientiæ tuæ opera, <l eID="gen14097" level="1"/> <l level="1" sID="gen14098"/>propter hoc etiam et exiguo ligno credunt homines animas suas, <l eID="gen14098" level="1"/> <l level="1" sID="gen14099"/>et transeuntes mare per ratem liberati sunt. <l eID="gen14099" level="1"/>

** Wisdom 14:6

Sed et ab initio cum perirent superbi gigantes, <l eID="gen14100" level="1"/> <l level="1" sID="gen14101"/>spes orbis terrarum ad ratem confugiens, <l eID="gen14101" level="1"/> <l level="1" sID="gen14102"/>remisit sæculo semen nativitatis quæ manu tua erat gubernata. <l eID="gen14102" level="1"/>

** Wisdom 14:7

Benedictum est enim lignum per quod fit justitia ; <l eID="gen14103" level="1"/>

** Wisdom 14:8

per manus autem quod fit idolum, <l eID="gen14104" level="1"/> <l level="1" sID="gen14105"/>maledictum est et ipsum, et qui fecit illud : <l eID="gen14105" level="1"/> <l level="1" sID="gen14106"/>quia ille quidem operatus est, <l eID="gen14106" level="1"/> <l level="1" sID="gen14107"/>illud autem cum esset fragile, deus cognominatus est. <l eID="gen14107" level="1"/>

** Wisdom 14:9

Similiter autem odio sunt Deo impius et impietas ejus ; <l eID="gen14108" level="1"/>

** Wisdom 14:10

etenim quod factum est, cum illo qui fecit tormenta patietur. <l eID="gen14109" level="1"/>

** Wisdom 14:11

Propter hoc et in idolis nationum non erit respectus, <l eID="gen14110" level="1"/> <l level="1" sID="gen14111"/>quoniam creaturæ Dei in odium factæ sunt, <l eID="gen14111" level="1"/> <l level="1" sID="gen14112"/>et in tentationem animabus hominum, <l eID="gen14112" level="1"/> <l level="1" sID="gen14113"/>et in muscipulam pedibus insipientium. <l eID="gen14113" level="1"/>

** Wisdom 14:12

Initium enim fornicationis est exquisitio idolorum, <l eID="gen14114" level="1"/> <l level="1" sID="gen14115"/>et adinventio illorum corruptio vitæ est : <l eID="gen14115" level="1"/>

** Wisdom 14:13

neque enim erant ab initio, <l eID="gen14116" level="1"/> <l level="1" sID="gen14117"/>neque erunt in perpetuum. <l eID="gen14117" level="1"/>

** Wisdom 14:14

Supervacuitas enim hominum hæc advenit in orbem terrarum, <l eID="gen14118" level="1"/> <l level="1" sID="gen14119"/>et ideo brevis illorum finis est inventus. <l eID="gen14119" level="1"/>

** Wisdom 14:15

Acerbo enim luctu dolens pater, <l eID="gen14120" level="1"/> <l level="1" sID="gen14121"/>cito sibi rapti filii fecit imaginem ; <l eID="gen14121" level="1"/> <l level="1" sID="gen14122"/>et illum qui tunc quasi homo mortuus fuerat, <l eID="gen14122" level="1"/> <l level="1" sID="gen14123"/>nunc tamquam deum colere cœpit, <l eID="gen14123" level="1"/> <l level="1" sID="gen14124"/>et constituit inter servos suos sacra et sacrificia. <l eID="gen14124" level="1"/>

** Wisdom 14:16

Deinde interveniente tempore, convalescente iniqua consuetudine, <l eID="gen14125" level="1"/> <l level="1" sID="gen14126"/>hic error tamquam lex custoditus est, <l eID="gen14126" level="1"/> <l level="1" sID="gen14127"/>et tyrannorum imperio colebantur figmenta. <l eID="gen14127" level="1"/>

** Wisdom 14:17

Et hos quos in palam homines honorare non poterant <l eID="gen14128" level="1"/> <l level="1" sID="gen14129"/>propter hoc quod longe essent, <l eID="gen14129" level="1"/> <l level="1" sID="gen14130"/>e longinquo figura eorum allata, <l eID="gen14130" level="1"/> <l level="1" sID="gen14131"/>evidentem imaginem regis quem honorare volebant fecerunt, <l eID="gen14131" level="1"/> <l level="1" sID="gen14132"/>ut illum qui aberat, tamquam præsentem colerent sua sollicitudine. <l eID="gen14132" level="1"/>

** Wisdom 14:18

Provexit autem ad horum culturam <l eID="gen14133" level="1"/> <l level="1" sID="gen14134"/>et hos qui ignorabant artificis eximia diligentia. <l eID="gen14134" level="1"/>

** Wisdom 14:19

Ille enim, volens placere illi qui se assumpsit, <l eID="gen14135" level="1"/> <l level="1" sID="gen14136"/>elaboravit arte sua ut similitudinem in melius figuraret. <l eID="gen14136" level="1"/>

** Wisdom 14:20

Multitudo autem hominum, abducta per speciem operis, <l eID="gen14137" level="1"/> <l level="1" sID="gen14138"/>eum qui ante tempus tamquam homo honoratus fuerat, <l eID="gen14138" level="1"/> <l level="1" sID="gen14139"/>nunc deum æstimaverunt. <l eID="gen14139" level="1"/>

** Wisdom 14:21

Et hæc fuit vitæ humanæ deceptio, <l eID="gen14140" level="1"/> <l level="1" sID="gen14141"/>quoniam aut affectui aut regibus deservientes homines, <l eID="gen14141" level="1"/> <l level="1" sID="gen14142"/>incommunicabile nomen lapidibus et lignis imposuerunt. <l eID="gen14142" level="1"/>

** Wisdom 14:22

Et non suffecerat errasse eos circa Dei scientiam, <l eID="gen14143" level="1"/> <l level="1" sID="gen14144"/>sed et in magno viventes inscientiæ bello, <l eID="gen14144" level="1"/> <l level="1" sID="gen14145"/>tot et tam magna mala pacem appellant. <l eID="gen14145" level="1"/>

** Wisdom 14:23

Aut enim filios suos sacrificantes, <l eID="gen14146" level="1"/> <l level="1" sID="gen14147"/>aut obscura sacrificia facientes, <l eID="gen14147" level="1"/> <l level="1" sID="gen14148"/>aut insaniæ plenas vigilias habentes, <l eID="gen14148" level="1"/>

** Wisdom 14:24

neque vitam, neque nuptias mundas jam custodiunt : <l eID="gen14149" level="1"/> <l level="1" sID="gen14150"/>sed alius alium per invidiam occidit, <l eID="gen14150" level="1"/> <l level="1" sID="gen14151"/>aut adulterans contristat, <l eID="gen14151" level="1"/>

** Wisdom 14:25

et omnia commista sunt : sanguis, homicidium, <l eID="gen14152" level="1"/> <l level="1" sID="gen14153"/>furtum et fictio, corruptio et infidelitas, <l eID="gen14153" level="1"/> <l level="1" sID="gen14154"/>turbatio et perjurium, tumultus bonorum, <l eID="gen14154" level="1"/>

** Wisdom 14:26

Dei immemoratio, animarum inquinatio, <l eID="gen14155" level="1"/> <l level="1" sID="gen14156"/>nativitatis immutatio, nuptiarum inconstantia, <l eID="gen14156" level="1"/> <l level="1" sID="gen14157"/>inordinatio mœchiæ et impudicitiæ. <l eID="gen14157" level="1"/>

** Wisdom 14:27

Infandorum enim idolorum cultura <l eID="gen14158" level="1"/> <l level="1" sID="gen14159"/>omnis mali causa est, et initium et finis. <l eID="gen14159" level="1"/>

** Wisdom 14:28

Aut enim dum lætantur insaniunt, <l eID="gen14160" level="1"/> <l level="1" sID="gen14161"/>aut certe vaticinantur falsa, <l eID="gen14161" level="1"/> <l level="1" sID="gen14162"/>aut vivunt injuste, aut pejerant cito. <l eID="gen14162" level="1"/>

** Wisdom 14:29

Dum enim confidunt in idolis quæ sine anima sunt, <l eID="gen14163" level="1"/> <l level="1" sID="gen14164"/>male jurantes noceri se non sperant. <l eID="gen14164" level="1"/>

** Wisdom 14:30

Utraque ergo illis evenient digne, <l eID="gen14165" level="1"/> <l level="1" sID="gen14166"/>quoniam male senserunt de Deo, attendentes idolis, <l eID="gen14166" level="1"/> <l level="1" sID="gen14167"/>et juraverunt injuste, <l eID="gen14167" level="1"/> <l level="1" sID="gen14168"/>in dolo contemnentes justitiam. <l eID="gen14168" level="1"/>

** Wisdom 14:31

Non enim juratorum virtus, <l eID="gen14169" level="1"/> <l level="1" sID="gen14170"/>sed peccantium pœna, <l eID="gen14170" level="1"/> <l level="1" sID="gen14171"/>perambulat semper injustorum prævaricationem.  <chapter eID="Wis.14"/>

* Wisdom 15

** Wisdom 15:1

Tu autem, Deus noster, suavis et verus es, <l eID="gen14172" level="1"/> <l level="1" sID="gen14173"/>patiens, et in misericordia disponens omnia. <l eID="gen14173" level="1"/>

** Wisdom 15:2

Etenim si peccaverimus, tui sumus, <l eID="gen14174" level="1"/> <l level="1" sID="gen14175"/>scientes magnitudinem tuam ; <l eID="gen14175" level="1"/> <l level="1" sID="gen14176"/>et si non peccaverimus, <l eID="gen14176" level="1"/> <l level="1" sID="gen14177"/>scimus quoniam apud te sumus computati. <l eID="gen14177" level="1"/>

** Wisdom 15:3

Nosse enim te, consummata justitia est ; <l eID="gen14178" level="1"/> <l level="1" sID="gen14179"/>et scire justitiam et virtutem tuam, radix est immortalitatis. <l eID="gen14179" level="1"/>

** Wisdom 15:4

Non enim in errorem induxit nos <l eID="gen14180" level="1"/> <l level="1" sID="gen14181"/>hominum malæ artis excogitatio, <l eID="gen14181" level="1"/> <l level="1" sID="gen14182"/>nec umbra picturæ labor sine fructu, <l eID="gen14182" level="1"/> <l level="1" sID="gen14183"/>effigies sculpta per varios colores : <l eID="gen14183" level="1"/>

** Wisdom 15:5

cujus aspectus insensato dat concupiscentiam, <l eID="gen14184" level="1"/> <l level="1" sID="gen14185"/>et diligit mortuæ imaginis effigiem sine anima. <l eID="gen14185" level="1"/>

** Wisdom 15:6

Malorum amatores digni sunt qui spem habeant in talibus, <l eID="gen14186" level="1"/> <l level="1" sID="gen14187"/>et qui faciunt illos, et qui diligunt, et qui colunt. <l eID="gen14187" level="1"/>

** Wisdom 15:7

Sed et figulus mollem terram premens, <l eID="gen14188" level="1"/> <l level="1" sID="gen14189"/>laboriose fingit ad usus nostros unumquodque vas ; <l eID="gen14189" level="1"/> <l level="1" sID="gen14190"/>et de eodem luto fingit quæ munda sunt in usum vasa, <l eID="gen14190" level="1"/> <l level="1" sID="gen14191"/>et similiter quæ his sunt contraria : <l eID="gen14191" level="1"/> <l level="1" sID="gen14192"/>horum autem vasorum quis sit usus, <l eID="gen14192" level="1"/> <l level="1" sID="gen14193"/>judex est figulus. <l eID="gen14193" level="1"/>

** Wisdom 15:8

Et cum labore vano deum fingit de eodem luto <l eID="gen14194" level="1"/> <l level="1" sID="gen14195"/>ille qui paulo ante de terra factus fuerat, <l eID="gen14195" level="1"/> <l level="1" sID="gen14196"/>et post pusillum reducit se unde acceptus est, <l eID="gen14196" level="1"/> <l level="1" sID="gen14197"/>repetitus animæ debitum quam habebat. <l eID="gen14197" level="1"/>

** Wisdom 15:9

Sed cura est illi non quia laboraturus est, <l eID="gen14198" level="1"/> <l level="1" sID="gen14199"/>nec quoniam brevis illi vita est : <l eID="gen14199" level="1"/> <l level="1" sID="gen14200"/>sed concertatur aurificibus et argentariis ; <l eID="gen14200" level="1"/> <l level="1" sID="gen14201"/>sed et ærarios imitatur, <l eID="gen14201" level="1"/> <l level="1" sID="gen14202"/>et gloriam præfert, quoniam res supervacuas fingit. <l eID="gen14202" level="1"/>

** Wisdom 15:10

Cinis est enim cor ejus, <l eID="gen14203" level="1"/> <l level="1" sID="gen14204"/>et terra supervacua spes illius, <l eID="gen14204" level="1"/> <l level="1" sID="gen14205"/>et luto vilior vita ejus : <l eID="gen14205" level="1"/>

** Wisdom 15:11

quoniam ignoravit qui se finxit, <l eID="gen14206" level="1"/> <l level="1" sID="gen14207"/>et qui inspiravit illi animam quæ operatur, <l eID="gen14207" level="1"/> <l level="1" sID="gen14208"/>et qui insufflavit ei spiritum vitalem. <l eID="gen14208" level="1"/>

** Wisdom 15:12

Sed et æstimaverunt ludum esse vitam nostram, <l eID="gen14209" level="1"/> <l level="1" sID="gen14210"/>et conversationem vitæ compositam ad lucrum, <l eID="gen14210" level="1"/> <l level="1" sID="gen14211"/>et oportere undecumque etiam ex malo acquirere. <l eID="gen14211" level="1"/>

** Wisdom 15:13

Hic enim scit se super omnes delinquere, <l eID="gen14212" level="1"/> <l level="1" sID="gen14213"/>qui ex terræ materia fragilia vasa et sculptilia fingit. <l eID="gen14213" level="1"/>

** Wisdom 15:14

Omnes enim insipientes, <l eID="gen14214" level="1"/> <l level="1" sID="gen14215"/>et infelices supra modum animæ superbi, <l eID="gen14215" level="1"/> <l level="1" sID="gen14216"/>sunt inimici populi tui, et imperantes illi : <l eID="gen14216" level="1"/>

** Wisdom 15:15

quoniam omnia idola nationum deos æstimaverunt, <l eID="gen14217" level="1"/> <l level="1" sID="gen14218"/>quibus neque oculorum usus est ad videndum, <l eID="gen14218" level="1"/> <l level="1" sID="gen14219"/>neque nares ad percipiendum spiritum, <l eID="gen14219" level="1"/> <l level="1" sID="gen14220"/>neque aures ad audiendum, <l eID="gen14220" level="1"/> <l level="1" sID="gen14221"/>neque digiti manuum ad tractandum, <l eID="gen14221" level="1"/> <l level="1" sID="gen14222"/>sed et pedes eorum pigri ad ambulandum. <l eID="gen14222" level="1"/>

** Wisdom 15:16

Homo enim fecit illos ; <l eID="gen14223" level="1"/> <l level="1" sID="gen14224"/>et qui spiritum mutuatus est, is finxit illos. <l eID="gen14224" level="1"/> <l level="1" sID="gen14225"/>Nemo enim sibi similem homo poterit deum fingere. <l eID="gen14225" level="1"/>

** Wisdom 15:17

Cum enim sit mortalis, mortuum fingit manibus iniquis. <l eID="gen14226" level="1"/> <l level="1" sID="gen14227"/>Melior enim est ipse his quos colit, <l eID="gen14227" level="1"/> <l level="1" sID="gen14228"/>quia ipse quidem vixit, cum esset mortalis, illi autem numquam. <l eID="gen14228" level="1"/>

** Wisdom 15:18

Sed et animalia miserrima colunt ; <l eID="gen14229" level="1"/> <l level="1" sID="gen14230"/>insensata enim comparata his, illis sunt deteriora. <l eID="gen14230" level="1"/>

** Wisdom 15:19

Sed nec aspectu aliquis ex his animalibus bona potest conspicere : <l eID="gen14231" level="1"/> <l level="1" sID="gen14232"/>effugerunt autem Dei laudem et benedictionem ejus.  <chapter eID="Wis.15"/>

* Wisdom 16

** Wisdom 16:1

Propter hæc et per his similia passi sunt digne tormenta, <l eID="gen14233" level="1"/> <l level="1" sID="gen14234"/>et per multitudinem bestiarum exterminati sunt. <l eID="gen14234" level="1"/>

** Wisdom 16:2

Pro quibus tormentis bene disposuisti populum tuum, <l eID="gen14235" level="1"/> <l level="1" sID="gen14236"/>quibus dedisti concupiscentiam delectamenti sui novum saporem, <l eID="gen14236" level="1"/> <l level="1" sID="gen14237"/>escam parans eis ortygometram : <l eID="gen14237" level="1"/>

** Wisdom 16:3

ut illi quidem, concupiscentes escam <l eID="gen14238" level="1"/> <l level="1" sID="gen14239"/>propter ea quæ illis ostensa et missa sunt, <l eID="gen14239" level="1"/> <l level="1" sID="gen14240"/>etiam a necessaria concupiscentia averterentur. <l eID="gen14240" level="1"/> <l level="1" sID="gen14241"/>Hi autem in brevi inopes facti, novam gustaverunt escam. <l eID="gen14241" level="1"/>

** Wisdom 16:4

Oportebat enim illis sine excusatione quidem <l eID="gen14242" level="1"/> <l level="1" sID="gen14243"/>supervenire interitum exercentibus tyrannidem ; <l eID="gen14243" level="1"/> <l level="1" sID="gen14244"/>his autem tantum ostendere <l eID="gen14244" level="1"/> <l level="1" sID="gen14245"/>quemadmodum inimici eorum exterminabantur. <l eID="gen14245" level="1"/>

** Wisdom 16:5

Etenim cum illis supervenit sæva bestiarum ira, <l eID="gen14246" level="1"/> <l level="1" sID="gen14247"/>morsibus perversorum colubrorum exterminabantur. <l eID="gen14247" level="1"/>

** Wisdom 16:6

Sed non in perpetuum ira tua permansit, <l eID="gen14248" level="1"/> <l level="1" sID="gen14249"/>sed ad correptionem in brevi turbati sunt, <l eID="gen14249" level="1"/> <l level="1" sID="gen14250"/>signum habentes salutis ad commemorationem mandati legis tuæ. <l eID="gen14250" level="1"/>

** Wisdom 16:7

Qui enim conversus est, <l eID="gen14251" level="1"/> <l level="1" sID="gen14252"/>non per hoc quod videbat sanabatur, <l eID="gen14252" level="1"/> <l level="1" sID="gen14253"/>sed per te, omnium salvatorem. <l eID="gen14253" level="1"/>

** Wisdom 16:8

In hoc autem ostendisti inimicis nostris <l eID="gen14254" level="1"/> <l level="1" sID="gen14255"/>quia tu es qui liberas ab omni malo. <l eID="gen14255" level="1"/>

** Wisdom 16:9

Illos enim locustarum et muscarum occiderunt morsus, <l eID="gen14256" level="1"/> <l level="1" sID="gen14257"/>et non est inventa sanitas animæ illorum, <l eID="gen14257" level="1"/> <l level="1" sID="gen14258"/>quia digni erant ab hujuscemodi exterminari. <l eID="gen14258" level="1"/>

** Wisdom 16:10

Filios autem tuos nec draconum venenatorum vicerunt dentes : <l eID="gen14259" level="1"/> <l level="1" sID="gen14260"/>misericordia enim tua adveniens sanabat illos. <l eID="gen14260" level="1"/>

** Wisdom 16:11

In memoria enim sermonum tuorum examinabantur, <l eID="gen14261" level="1"/> <l level="1" sID="gen14262"/>et velociter salvabantur : <l eID="gen14262" level="1"/> <l level="1" sID="gen14263"/>ne in altam incidentes oblivionem <l eID="gen14263" level="1"/> <l level="1" sID="gen14264"/>non possent tuo uti adjutorio. <l eID="gen14264" level="1"/>

** Wisdom 16:12

Etenim neque herba, neque malagma sanavit eos : <l eID="gen14265" level="1"/> <l level="1" sID="gen14266"/>sed tuus, Domine, sermo, qui sanat omnia. <l eID="gen14266" level="1"/>

** Wisdom 16:13

Tu es enim, Domine, qui vitæ et mortis habes potestatem, <l eID="gen14267" level="1"/> <l level="1" sID="gen14268"/>et deducis ad portas mortis, et reducis. <l eID="gen14268" level="1"/>

** Wisdom 16:14

Homo autem occidit quidem per malitiam ; <l eID="gen14269" level="1"/> <l level="1" sID="gen14270"/>et cum exierit spiritus, non revertetur, <l eID="gen14270" level="1"/> <l level="1" sID="gen14271"/>nec revocabit animam quæ recepta est. <l eID="gen14271" level="1"/>

** Wisdom 16:15

Sed tuam manum effugere impossibile est. <l eID="gen14272" level="1"/>

** Wisdom 16:16

Negantes enim te nosse impii, <l eID="gen14273" level="1"/> <l level="1" sID="gen14274"/>per fortitudinem brachii tui flagellati sunt : <l eID="gen14274" level="1"/> <l level="1" sID="gen14275"/>novis aquis, et grandinibus, <l eID="gen14275" level="1"/> <l level="1" sID="gen14276"/>et pluviis persecutionem passi, <l eID="gen14276" level="1"/> <l level="1" sID="gen14277"/>et per ignem consumpti. <l eID="gen14277" level="1"/>

** Wisdom 16:17

Quod enim mirabile erat, in aqua, quæ omnia extinguit, <l eID="gen14278" level="1"/> <l level="1" sID="gen14279"/>plus ignis valebat : <l eID="gen14279" level="1"/> <l level="1" sID="gen14280"/>vindex est enim orbis justorum. <l eID="gen14280" level="1"/>

** Wisdom 16:18

Quodam enim tempore mansuetabatur ignis, <l eID="gen14281" level="1"/> <l level="1" sID="gen14282"/>ne comburerentur quæ ad impios missa erant animalia, <l eID="gen14282" level="1"/> <l level="1" sID="gen14283"/>sed ut ipsi videntes scirent <l eID="gen14283" level="1"/> <l level="1" sID="gen14284"/>quoniam Dei judicio patiuntur persecutionem. <l eID="gen14284" level="1"/>

** Wisdom 16:19

Et quodam tempore in aqua <l eID="gen14285" level="1"/> <l level="1" sID="gen14286"/>supra virtutem ignis exardescebat undique, <l eID="gen14286" level="1"/> <l level="1" sID="gen14287"/>ut iniquæ terræ nationem exterminaret. <l eID="gen14287" level="1"/>

** Wisdom 16:20

Pro quibus angelorum esca nutrivisti populum tuum, <l eID="gen14288" level="1"/> <l level="1" sID="gen14289"/>et paratum panem de cælo præstitisti illis sine labore, <l eID="gen14289" level="1"/> <l level="1" sID="gen14290"/>omne delectamentum in se habentem, <l eID="gen14290" level="1"/> <l level="1" sID="gen14291"/>et omnis saporis suavitatem. <l eID="gen14291" level="1"/>

** Wisdom 16:21

Substantia enim tua dulcedinem tuam, <l eID="gen14292" level="1"/> <l level="1" sID="gen14293"/>quam in filios habes, ostendebat ; <l eID="gen14293" level="1"/> <l level="1" sID="gen14294"/>et deserviens uniuscujusque voluntati, <l eID="gen14294" level="1"/> <l level="1" sID="gen14295"/>ad quod quisque volebat convertebatur. <l eID="gen14295" level="1"/>

** Wisdom 16:22

Nix autem et glacies sustinebant vim ignis, et non tabescebant : <l eID="gen14296" level="1"/> <l level="1" sID="gen14297"/>ut scirent quoniam fructus inimicorum exterminabat <l eID="gen14297" level="1"/> <l level="1" sID="gen14298"/>ignis ardens in grandine et pluvia coruscans ; <l eID="gen14298" level="1"/>

** Wisdom 16:23

hic autem iterum ut nutrirentur justi, <l eID="gen14299" level="1"/> <l level="1" sID="gen14300"/>etiam suæ virtutis oblitus est. <l eID="gen14300" level="1"/>

** Wisdom 16:24

Creatura enim tibi factori deserviens, <l eID="gen14301" level="1"/> <l level="1" sID="gen14302"/>exardescit in tormentum adversus injustos, <l eID="gen14302" level="1"/> <l level="1" sID="gen14303"/>et lenior fit ad benefaciendum pro his qui in te confidunt. <l eID="gen14303" level="1"/>

** Wisdom 16:25

Propter hoc et tunc in omnia transfigurata, <l eID="gen14304" level="1"/> <l level="1" sID="gen14305"/>omnium nutrici gratiæ tuæ deserviebat, <l eID="gen14305" level="1"/> <l level="1" sID="gen14306"/>ad voluntatem eorum qui a te desiderabant : <l eID="gen14306" level="1"/>

** Wisdom 16:26

ut scirent filii tui quos dilexisti, Domine, <l eID="gen14307" level="1"/> <l level="1" sID="gen14308"/>quoniam non nativitatis fructus pascunt homines, <l eID="gen14308" level="1"/> <l level="1" sID="gen14309"/>sed sermo tuus hos qui in te crediderint conservat. <l eID="gen14309" level="1"/>

** Wisdom 16:27

Quod enim ab igne non poterat exterminari, <l eID="gen14310" level="1"/> <l level="1" sID="gen14311"/>statim ab exiguo radio solis calefactum tabescebat : <l eID="gen14311" level="1"/>

** Wisdom 16:28

ut notum omnibus esset <l eID="gen14312" level="1"/> <l level="1" sID="gen14313"/>quoniam oportet prævenire solem ad benedictionem tuam, <l eID="gen14313" level="1"/> <l level="1" sID="gen14314"/>et ad ortum lucis te adorare. <l eID="gen14314" level="1"/>

** Wisdom 16:29

Ingrati enim spes tamquam hibernalis glacies tabescet, <l eID="gen14315" level="1"/> <l level="1" sID="gen14316"/>et disperiet tamquam aqua supervacua.  <chapter eID="Wis.16"/>

* Wisdom 17

** Wisdom 17:1

Magna sunt enim judicia tua, Domine, <l eID="gen14317" level="1"/> <l level="1" sID="gen14318"/>et inenarrabilia verba tua : <l eID="gen14318" level="1"/> <l level="1" sID="gen14319"/>propter hoc indisciplinatæ animæ erraverunt. <l eID="gen14319" level="1"/>

** Wisdom 17:2

Dum enim persuasum habent iniqui <l eID="gen14320" level="1"/> <l level="1" sID="gen14321"/>posse dominari nationi sanctæ, <l eID="gen14321" level="1"/> <l level="1" sID="gen14322"/>vinculis tenebrarum et longæ noctis compediti, <l eID="gen14322" level="1"/> <l level="1" sID="gen14323"/>inclusi sub tectis, <l eID="gen14323" level="1"/> <l level="1" sID="gen14324"/>fugitivi perpetuæ providentiæ jacuerunt. <l eID="gen14324" level="1"/>

** Wisdom 17:3

Et dum putant se latere in obscuris peccatis, <l eID="gen14325" level="1"/> <l level="1" sID="gen14326"/>tenebroso oblivionis velamento dispersi sunt, <l eID="gen14326" level="1"/> <l level="1" sID="gen14327"/>paventes horrende, <l eID="gen14327" level="1"/> <l level="1" sID="gen14328"/>et cum admiratione nimia perturbati. <l eID="gen14328" level="1"/>

** Wisdom 17:4

Neque enim quæ continebat illos spelunca sine timore custodiebat, <l eID="gen14329" level="1"/> <l level="1" sID="gen14330"/>quoniam sonitus descendens perturbabat illos, <l eID="gen14330" level="1"/> <l level="1" sID="gen14331"/>et personæ tristes illis apparentes pavorem illis præstabant. <l eID="gen14331" level="1"/>

** Wisdom 17:5

Et ignis quidem nulla vis poterat illis lumen præbere, <l eID="gen14332" level="1"/> <l level="1" sID="gen14333"/>nec siderum limpidæ flammæ <l eID="gen14333" level="1"/> <l level="1" sID="gen14334"/>illuminare poterant illam noctem horrendam. <l eID="gen14334" level="1"/>

** Wisdom 17:6

Apparebat autem illis subitaneus ignis, timore plenus ; <l eID="gen14335" level="1"/> <l level="1" sID="gen14336"/>et timore perculsi illius quæ non videbatur faciei, <l eID="gen14336" level="1"/> <l level="1" sID="gen14337"/>æstimabant deteriora esse quæ videbantur. <l eID="gen14337" level="1"/>

** Wisdom 17:7

Et magicæ artis appositi erant derisus, <l eID="gen14338" level="1"/> <l level="1" sID="gen14339"/>et sapientiæ gloriæ correptio cum contumelia. <l eID="gen14339" level="1"/>

** Wisdom 17:8

Illi enim qui promittebant <l eID="gen14340" level="1"/> <l level="1" sID="gen14341"/>timores et perturbationes expellere se ab anima languente, <l eID="gen14341" level="1"/> <l level="1" sID="gen14342"/>hi cum derisu pleni timore languebant. <l eID="gen14342" level="1"/>

** Wisdom 17:9

Nam etsi nihil illos ex monstris perturbabat, <l eID="gen14343" level="1"/> <l level="1" sID="gen14344"/>transitu animalium et serpentium sibilatione commoti, <l eID="gen14344" level="1"/> <l level="1" sID="gen14345"/>tremebundi peribant, <l eID="gen14345" level="1"/> <l level="1" sID="gen14346"/>et aërem quem nulla ratione quis effugere posset, negantes se videre. <l eID="gen14346" level="1"/>

** Wisdom 17:10

Cum sit enim timida nequitia, <l eID="gen14347" level="1"/> <l level="1" sID="gen14348"/>dat testimonium condemnationis : <l eID="gen14348" level="1"/> <l level="1" sID="gen14349"/>semper enim præsumit sæva, <l eID="gen14349" level="1"/> <l level="1" sID="gen14350"/>perturbata conscientia : <l eID="gen14350" level="1"/>

** Wisdom 17:11

nihil enim est timor nisi proditio cogitationis auxiliorum. <l eID="gen14351" level="1"/>

** Wisdom 17:12

Et dum ab intus minor est exspectatio, <l eID="gen14352" level="1"/> <l level="1" sID="gen14353"/>majorem computat inscientiam ejus causæ, <l eID="gen14353" level="1"/> <l level="1" sID="gen14354"/>de qua tormentum præstat. <l eID="gen14354" level="1"/>

** Wisdom 17:13

Illi autem qui impotentem vere noctem, <l eID="gen14355" level="1"/> <l level="1" sID="gen14356"/>et ab infimis et ab altissimis inferis supervenientem, <l eID="gen14356" level="1"/> <l level="1" sID="gen14357"/>eumdem somnum dormientes, <l eID="gen14357" level="1"/>

** Wisdom 17:14

aliquando monstrorum exagitabantur timore, <l eID="gen14358" level="1"/> <l level="1" sID="gen14359"/>aliquando animæ deficiebant traductione : <l eID="gen14359" level="1"/> <l level="1" sID="gen14360"/>subitaneus enim illis et insperatus timor supervenerat. <l eID="gen14360" level="1"/>

** Wisdom 17:15

Deinde si quisquam ex illis decidisset, <l eID="gen14361" level="1"/> <l level="1" sID="gen14362"/>custodiebatur in carcere sine ferro reclusus. <l eID="gen14362" level="1"/>

** Wisdom 17:16

Si enim rusticus quis erat, aut pastor, <l eID="gen14363" level="1"/> <l level="1" sID="gen14364"/>aut agri laborum operarius præoccupatus esset, <l eID="gen14364" level="1"/> <l level="1" sID="gen14365"/>ineffugibilem sustinebat necessitatem ; <l eID="gen14365" level="1"/>

** Wisdom 17:17

una enim catena tenebrarum omnes erant colligati. <l eID="gen14366" level="1"/> <l level="1" sID="gen14367"/>Sive spiritus sibilans, <l eID="gen14367" level="1"/> <l level="1" sID="gen14368"/>aut inter spissos arborum ramos avium sonus suavis, <l eID="gen14368" level="1"/> <l level="1" sID="gen14369"/>aut vis aquæ decurrentis nimium, <l eID="gen14369" level="1"/>

** Wisdom 17:18

aut sonus validus præcipitatarum petrarum, <l eID="gen14370" level="1"/> <l level="1" sID="gen14371"/>aut ludentium animalium cursus invisus, <l eID="gen14371" level="1"/> <l level="1" sID="gen14372"/>aut mugientium valida bestiarum vox, <l eID="gen14372" level="1"/> <l level="1" sID="gen14373"/>aut resonans de altissimis montibus echo : <l eID="gen14373" level="1"/> <l level="1" sID="gen14374"/>deficientes faciebant illos præ timore. <l eID="gen14374" level="1"/>

** Wisdom 17:19

Omnis enim orbis terrarum limpido illuminabatur lumine, <l eID="gen14375" level="1"/> <l level="1" sID="gen14376"/>et non impeditis operibus continebatur. <l eID="gen14376" level="1"/>

** Wisdom 17:20

Solis autem illis superposita erat gravis nox, <l eID="gen14377" level="1"/> <l level="1" sID="gen14378"/>imago tenebrarum quæ superventura illis erat : <l eID="gen14378" level="1"/> <l level="1" sID="gen14379"/>ipsi ergo sibi erant graviores tenebris.  <chapter eID="Wis.17"/>

* Wisdom 18

** Wisdom 18:1

Sanctis autem tuis maxima erat lux, <l eID="gen14380" level="1"/> <l level="1" sID="gen14381"/>et horum quidem vocem audiebant, sed figuram non videbant. <l eID="gen14381" level="1"/> <l level="1" sID="gen14382"/>Et quia non et ipsi eadem passi erant, magnificabant te ; <l eID="gen14382" level="1"/>

** Wisdom 18:2

et qui ante læsi erant, quia non lædebantur, gratias agebant, <l eID="gen14383" level="1"/> <l level="1" sID="gen14384"/>et ut esset differentia, donum petebant. <l eID="gen14384" level="1"/>

** Wisdom 18:3

Propter quod ignis ardentem columnam <l eID="gen14385" level="1"/> <l level="1" sID="gen14386"/>ducem habuerunt ignotæ viæ, <l eID="gen14386" level="1"/> <l level="1" sID="gen14387"/>et solem sine læsura boni hospitii præstitisti. <l eID="gen14387" level="1"/>

** Wisdom 18:4

Digni quidem illi carere luce, <l eID="gen14388" level="1"/> <l level="1" sID="gen14389"/>et pati carcerem tenebrarum, <l eID="gen14389" level="1"/> <l level="1" sID="gen14390"/>qui inclusos custodiebant filios tuos, <l eID="gen14390" level="1"/> <l level="1" sID="gen14391"/>per quos incipiebat incorruptum legis lumen sæculo dari. <l eID="gen14391" level="1"/>

** Wisdom 18:5

Cum cogitarent justorum occidere infantes, <l eID="gen14392" level="1"/> <l level="1" sID="gen14393"/>et uno exposito filio et liberato, <l eID="gen14393" level="1"/> <l level="1" sID="gen14394"/>in traductionem illorum, multitudinem filiorum abstulisti, <l eID="gen14394" level="1"/> <l level="1" sID="gen14395"/>et pariter illos perdidisti in aqua valida. <l eID="gen14395" level="1"/>

** Wisdom 18:6

Illa enim nox ante cognita est a patribus nostris, <l eID="gen14396" level="1"/> <l level="1" sID="gen14397"/>ut vere scientes quibus juramentis crediderunt, <l eID="gen14397" level="1"/> <l level="1" sID="gen14398"/>animæquiores essent. <l eID="gen14398" level="1"/>

** Wisdom 18:7

Suscepta est autem a populo tuo sanitas quidem justorum, <l eID="gen14399" level="1"/> <l level="1" sID="gen14400"/>injustorum autem exterminatio. <l eID="gen14400" level="1"/>

** Wisdom 18:8

Sicut enim læsisti adversarios, <l eID="gen14401" level="1"/> <l level="1" sID="gen14402"/>sic et nos provocans magnificasti. <l eID="gen14402" level="1"/>

** Wisdom 18:9

Absconse enim sacrificabant justi pueri bonorum, <l eID="gen14403" level="1"/> <l level="1" sID="gen14404"/>et justitiæ legem in concordia disposuerunt ; <l eID="gen14404" level="1"/> <l level="1" sID="gen14405"/>similiter et bona et mala recepturos justos, <l eID="gen14405" level="1"/> <l level="1" sID="gen14406"/>patrum jam decantantes laudes. <l eID="gen14406" level="1"/>

** Wisdom 18:10

Resonabat autem inconveniens inimicorum vox, <l eID="gen14407" level="1"/> <l level="1" sID="gen14408"/>et flebilis audiebatur planctus ploratorum infantium. <l eID="gen14408" level="1"/>

** Wisdom 18:11

Simili autem pœna servus cum domino afflictus est, <l eID="gen14409" level="1"/> <l level="1" sID="gen14410"/>et popularis homo regi similia passus. <l eID="gen14410" level="1"/>

** Wisdom 18:12

Similiter ergo omnes, uno nomine mortis, <l eID="gen14411" level="1"/> <l level="1" sID="gen14412"/>mortuos habebant innumerabiles : <l eID="gen14412" level="1"/> <l level="1" sID="gen14413"/>nec enim ad sepeliendum vivi sufficiebant, <l eID="gen14413" level="1"/> <l level="1" sID="gen14414"/>quoniam uno momento quæ erat præclarior <l eID="gen14414" level="1"/> <l level="1" sID="gen14415"/>natio illorum exterminata est. <l eID="gen14415" level="1"/>

** Wisdom 18:13

De omnibus enim non credentes, propter veneficia ; <l eID="gen14416" level="1"/> <l level="1" sID="gen14417"/>tunc vero primum cum fuit exterminium primogenitorum, <l eID="gen14417" level="1"/> <l level="1" sID="gen14418"/>spoponderunt populum Dei esse. <l eID="gen14418" level="1"/>

** Wisdom 18:14

Cum enim quietum silentium contineret omnia, <l eID="gen14419" level="1"/> <l level="1" sID="gen14420"/>et nox in suo cursu medium iter haberet, <l eID="gen14420" level="1"/>

** Wisdom 18:15

omnipotens sermo tuus de cælo, a regalibus sedibus, <l eID="gen14421" level="1"/> <l level="1" sID="gen14422"/>durus debellator in mediam exterminii terram prosilivit, <l eID="gen14422" level="1"/>

** Wisdom 18:16

gladius acutus insimulatum imperium tuum portans : <l eID="gen14423" level="1"/> <l level="1" sID="gen14424"/>et stans, replevit omnia morte, <l eID="gen14424" level="1"/> <l level="1" sID="gen14425"/>et usque ad cælum attingebat stans in terra. <l eID="gen14425" level="1"/>

** Wisdom 18:17

Tunc continuo visus somniorum malorum turbaverunt illos, <l eID="gen14426" level="1"/> <l level="1" sID="gen14427"/>et timores supervenerunt insperati. <l eID="gen14427" level="1"/>

** Wisdom 18:18

Et alius alibi projectus semivivus, <l eID="gen14428" level="1"/> <l level="1" sID="gen14429"/>propter quam moriebatur causam demonstrabat mortis. <l eID="gen14429" level="1"/>

** Wisdom 18:19

Visiones enim quæ illos turbaverunt hæc præmonebant, <l eID="gen14430" level="1"/> <l level="1" sID="gen14431"/>ne inscii quare mala patiebantur perirent. <l eID="gen14431" level="1"/>

** Wisdom 18:20

Tetigit autem tunc et justos tentatio mortis, <l eID="gen14432" level="1"/> <l level="1" sID="gen14433"/>et commotio in eremo facta est multitudinis : <l eID="gen14433" level="1"/> <l level="1" sID="gen14434"/>sed non diu permansit ira tua. <l eID="gen14434" level="1"/>

** Wisdom 18:21

Prosperans enim homo sine querela deprecari pro populis, <l eID="gen14435" level="1"/> <l level="1" sID="gen14436"/>proferens servitutis suæ scutum, <l eID="gen14436" level="1"/> <l level="1" sID="gen14437"/>orationem et per incensum deprecationem allegans, <l eID="gen14437" level="1"/> <l level="1" sID="gen14438"/>restitit iræ, et finem imposuit necessitati, <l eID="gen14438" level="1"/> <l level="1" sID="gen14439"/>ostendens quoniam tuus est famulus. <l eID="gen14439" level="1"/>

** Wisdom 18:22

Vicit autem turbas non in virtute corporis, <l eID="gen14440" level="1"/> <l level="1" sID="gen14441"/>nec armaturæ potentia : <l eID="gen14441" level="1"/> <l level="1" sID="gen14442"/>sed verbo illum qui se vexabat subjecit, <l eID="gen14442" level="1"/> <l level="1" sID="gen14443"/>juramenta parentum et testamentum commemorans. <l eID="gen14443" level="1"/>

** Wisdom 18:23

Cum enim jam acervatim cecidissent super alterutrum mortui, <l eID="gen14444" level="1"/> <l level="1" sID="gen14445"/>interstitit, et amputavit impetum, <l eID="gen14445" level="1"/> <l level="1" sID="gen14446"/>et divisit illam quæ ad vivos ducebat viam. <l eID="gen14446" level="1"/>

** Wisdom 18:24

In veste enim poderis quam habebat, totus erat orbis terrarum ; <l eID="gen14447" level="1"/> <l level="1" sID="gen14448"/>et parentum magnalia in quatuor ordinibus lapidum erant sculpta, <l eID="gen14448" level="1"/> <l level="1" sID="gen14449"/>et magnificentia tua in diademate capitis illius sculpta erat. <l eID="gen14449" level="1"/>

** Wisdom 18:25

His autem cessit qui exterminabat, et hæc extimuit : <l eID="gen14450" level="1"/> <l level="1" sID="gen14451"/>erat enim sola tentatio iræ sufficiens.  <chapter eID="Wis.18"/>

* Wisdom 19

** Wisdom 19:1

Impiis autem usque in novissimum <l eID="gen14452" level="1"/> <l level="1" sID="gen14453"/>sine misericordia ira supervenit. <l eID="gen14453" level="1"/> <l level="1" sID="gen14454"/>Præsciebat enim et futura illorum : <l eID="gen14454" level="1"/>

** Wisdom 19:2

quoniam cum ipsi permisissent ut se educerent, <l eID="gen14455" level="1"/> <l level="1" sID="gen14456"/>et cum magna sollicitudine præmisissent illos, <l eID="gen14456" level="1"/> <l level="1" sID="gen14457"/>consequebantur illos, pœnitentia acti. <l eID="gen14457" level="1"/>

** Wisdom 19:3

Adhuc enim inter manus habentes luctum, <l eID="gen14458" level="1"/> <l level="1" sID="gen14459"/>et deplorantes ad monumenta mortuorum, <l eID="gen14459" level="1"/> <l level="1" sID="gen14460"/>aliam sibi assumpserunt cogitationem inscientiæ, <l eID="gen14460" level="1"/> <l level="1" sID="gen14461"/>et quos rogantes projecerant, <l eID="gen14461" level="1"/> <l level="1" sID="gen14462"/>hos tamquam fugitivos persequebantur. <l eID="gen14462" level="1"/>

** Wisdom 19:4

Ducebat enim illos ad hunc finem digna necessitas ; <l eID="gen14463" level="1"/> <l level="1" sID="gen14464"/>et horum quæ acciderant commemorationem amittebant, <l eID="gen14464" level="1"/> <l level="1" sID="gen14465"/>ut quæ deerant tormentis repleret punitio : <l eID="gen14465" level="1"/>

** Wisdom 19:5

et populus quidem tuus mirabiliter transiret, <l eID="gen14466" level="1"/> <l level="1" sID="gen14467"/>illi autem novam mortem invenirent. <l eID="gen14467" level="1"/>

** Wisdom 19:6

Omnis enim creatura ad suum genus ab initio refigurabatur, <l eID="gen14468" level="1"/> <l level="1" sID="gen14469"/>deserviens tuis præceptis, <l eID="gen14469" level="1"/> <l level="1" sID="gen14470"/>ut pueri tui custodirentur illæsi. <l eID="gen14470" level="1"/>

** Wisdom 19:7

Nam nubes castra eorum obumbrabat, <l eID="gen14471" level="1"/> <l level="1" sID="gen14472"/>et ex aqua quæ ante erat, terra arida apparuit, <l eID="gen14472" level="1"/> <l level="1" sID="gen14473"/>et in mari Rubro via sine impedimento, <l eID="gen14473" level="1"/> <l level="1" sID="gen14474"/>et campus germinans de profundo nimio : <l eID="gen14474" level="1"/>

** Wisdom 19:8

per quem omnis natio transivit quæ tegebatur tua manu, <l eID="gen14475" level="1"/> <l level="1" sID="gen14476"/>videntes tua mirabilia et monstra. <l eID="gen14476" level="1"/>

** Wisdom 19:9

Tamquam enim equi depaverunt escam, <l eID="gen14477" level="1"/> <l level="1" sID="gen14478"/>et tamquam agni exsultaverunt, <l eID="gen14478" level="1"/> <l level="1" sID="gen14479"/>magnificantes te, Domine, qui liberasti illos. <l eID="gen14479" level="1"/>

** Wisdom 19:10

Memores enim erant adhuc eorum <l eID="gen14480" level="1"/> <l level="1" sID="gen14481"/>quæ in incolatu illorum facta fuerant : <l eID="gen14481" level="1"/> <l level="1" sID="gen14482"/>quemadmodum pro natione animalium eduxit terra muscas, <l eID="gen14482" level="1"/> <l level="1" sID="gen14483"/>et pro piscibus eructavit fluvius multitudinem ranarum. <l eID="gen14483" level="1"/>

** Wisdom 19:11

Novissime autem viderunt novam creaturam avium, <l eID="gen14484" level="1"/> <l level="1" sID="gen14485"/>cum, adducti concupiscentia, postulaverunt escas epulationis. <l eID="gen14485" level="1"/>

** Wisdom 19:12

In allocutione enim desiderii ascendit illis de mari ortygometra : <l eID="gen14486" level="1"/> <l level="1" sID="gen14487"/>et vexationes peccatoribus supervenerunt, <l eID="gen14487" level="1"/> <l level="1" sID="gen14488"/>non sine illis quæ ante facta erant argumentis per vim fulminum : <l eID="gen14488" level="1"/> <l level="1" sID="gen14489"/>juste enim patiebantur secundum suas nequitias. <l eID="gen14489" level="1"/>

** Wisdom 19:13

Etenim detestabiliorem inhospitalitatem instituerunt : <l eID="gen14490" level="1"/> <l level="1" sID="gen14491"/>alii quidem ignotos non recipiebant advenas ; <l eID="gen14491" level="1"/> <l level="1" sID="gen14492"/>alii autem bonos hospites in servitutem redigebant. <l eID="gen14492" level="1"/>

** Wisdom 19:14

Et non solum hæc, sed et alius quidam respectus illorum erat, <l eID="gen14493" level="1"/> <l level="1" sID="gen14494"/>quoniam inviti recipiebant extraneos. <l eID="gen14494" level="1"/>

** Wisdom 19:15

Qui autem cum lætitia receperunt hos <l eID="gen14495" level="1"/> <l level="1" sID="gen14496"/>qui eisdem usi erant justitiis, <l eID="gen14496" level="1"/> <l level="1" sID="gen14497"/>sævissimis afflixerunt doloribus. <l eID="gen14497" level="1"/>

** Wisdom 19:16

Percussi sunt autem cæcitate : <l eID="gen14498" level="1"/> <l level="1" sID="gen14499"/>sicut illi in foribus justi, <l eID="gen14499" level="1"/> <l level="1" sID="gen14500"/>cum subitaneis cooperti essent tenebris, <l eID="gen14500" level="1"/> <l level="1" sID="gen14501"/>unusquisque transitum ostii sui quærebat. <l eID="gen14501" level="1"/>

** Wisdom 19:17

In se enim elementa dum convertuntur, <l eID="gen14502" level="1"/> <l level="1" sID="gen14503"/>sicut in organo qualitatis sonus immutatur, <l eID="gen14503" level="1"/> <l level="1" sID="gen14504"/>et omnia suum sonum custodiunt : <l eID="gen14504" level="1"/> <l level="1" sID="gen14505"/>unde æstimari ex ipso visu certo potest. <l eID="gen14505" level="1"/>

** Wisdom 19:18

Agrestia enim in aquatica convertebantur, <l eID="gen14506" level="1"/> <l level="1" sID="gen14507"/>et quæcumque erant natantia, in terram transibant. <l eID="gen14507" level="1"/>

** Wisdom 19:19

Ignis in aqua valebat supra suam virtutem, <l eID="gen14508" level="1"/> <l level="1" sID="gen14509"/>et aqua extinguentis naturæ obliviscebatur. <l eID="gen14509" level="1"/>

** Wisdom 19:20

Flammæ e contrario corruptibilium animalium <l eID="gen14510" level="1"/> <l level="1" sID="gen14511"/>non vexaverunt carnes coambulantium, <l eID="gen14511" level="1"/> <l level="1" sID="gen14512"/>nec dissolvebant illam, quæ facile dissolvebatur sicut glacies, bonam escam. <l eID="gen14512" level="1"/> <l level="1" sID="gen14513"/>In omnibus enim magnificasti populum tuum, Domine, <l eID="gen14513" level="1"/> <l level="1" sID="gen14514"/>et honorasti, et non despexisti, <l eID="gen14514" level="1"/> <l level="1" sID="gen14515"/>in omni tempore et in omni loco assistens eis. <l eID="gen14515" level="1"/> <lg eID="gen13310"/> <chapter eID="Wis.19"/> <div eID="gen13309" osisID="Wis" type="book"/>

