* Zephaniah 1

** Zephaniah 1:1

Verbum Domini quod factum est ad Sophoniam, filium Chusi, filii Godoliæ, filii Amariæ, filii Ezeciæ, in diebus Josiæ, filii Amon, regis Judæ.  <div eID="gen31308" type="x-p"/>

** Zephaniah 1:2

Congregans congregabo omnia a facie terræ, dicit Dominus : <l eID="gen31310" level="1"/>

** Zephaniah 1:3

congregans hominem et pecus, <l eID="gen31311" level="1"/> <l level="1" sID="gen31312"/>congregans volatilia cæli et pisces maris : <l eID="gen31312" level="1"/> <l level="1" sID="gen31313"/>et ruinæ impiorum erunt, <l eID="gen31313" level="1"/> <l level="1" sID="gen31314"/>et disperdam homines a facie terræ, dicit Dominus. <l eID="gen31314" level="1"/>

** Zephaniah 1:4

Et extendam manum meam super Judam <l eID="gen31315" level="1"/> <l level="1" sID="gen31316"/>et super omnes habitantes Jerusalem : <l eID="gen31316" level="1"/> <l level="1" sID="gen31317"/>et disperdam de loco hoc reliquias Baal, <l eID="gen31317" level="1"/> <l level="1" sID="gen31318"/>et nomina ædituorum cum sacerdotibus ; <l eID="gen31318" level="1"/>

** Zephaniah 1:5

et eos qui adorant super tecta militiam cæli, <l eID="gen31319" level="1"/> <l level="1" sID="gen31320"/>et adorant et jurant in Domino, <l eID="gen31320" level="1"/> <l level="1" sID="gen31321"/>et jurant in Melchom ; <l eID="gen31321" level="1"/>

** Zephaniah 1:6

et qui avertuntur de post tergum Domini, <l eID="gen31322" level="1"/> <l level="1" sID="gen31323"/>et qui non quæsierunt Dominum, <l eID="gen31323" level="1"/> <l level="1" sID="gen31324"/>nec investigaverunt eum. <l eID="gen31324" level="1"/>

** Zephaniah 1:7

Silete a facie Domini Dei, <l eID="gen31325" level="1"/> <l level="1" sID="gen31326"/>quia juxta est dies Domini : <l eID="gen31326" level="1"/> <l level="1" sID="gen31327"/>quia præparavit Dominus hostiam ; <l eID="gen31327" level="1"/> <l level="1" sID="gen31328"/>sanctificavit vocatos suos. <l eID="gen31328" level="1"/>

** Zephaniah 1:8

Et erit : in die hostiæ Domini, <l eID="gen31329" level="1"/> <l level="1" sID="gen31330"/>visitabo super principes, <l eID="gen31330" level="1"/> <l level="1" sID="gen31331"/>et super filios regis, <l eID="gen31331" level="1"/> <l level="1" sID="gen31332"/>et super omnes qui induti sunt veste peregrina ; <l eID="gen31332" level="1"/>

** Zephaniah 1:9

et visitabo super omnem qui arroganter ingreditur super limen in die illa, <l eID="gen31333" level="1"/> <l level="1" sID="gen31334"/>qui complent domum Domini Dei sui iniquitate et dolo. <l eID="gen31334" level="1"/>

** Zephaniah 1:10

Et erit in die illa, dicit Dominus, <l eID="gen31335" level="1"/> <l level="1" sID="gen31336"/>vox clamoris a porta piscium, <l eID="gen31336" level="1"/> <l level="1" sID="gen31337"/>et ululatus a Secunda, <l eID="gen31337" level="1"/> <l level="1" sID="gen31338"/>et contritio magna a collibus. <l eID="gen31338" level="1"/>

** Zephaniah 1:11

Ululate, habitatores Pilæ : <l eID="gen31339" level="1"/> <l level="1" sID="gen31340"/>conticuit omnis populus Chanaan, <l eID="gen31340" level="1"/> <l level="1" sID="gen31341"/>disperierunt omnes involuti argento. <l eID="gen31341" level="1"/>

** Zephaniah 1:12

Et erit in tempore illo : <l eID="gen31342" level="1"/> <l level="1" sID="gen31343"/>scrutabor Jerusalem in lucernis, <l eID="gen31343" level="1"/> <l level="1" sID="gen31344"/>et visitabo super viros defixos in fæcibus suis, <l eID="gen31344" level="1"/> <l level="1" sID="gen31345"/>qui dicunt in cordibus suis : <l eID="gen31345" level="1"/> <l level="1" sID="gen31346"/>Non faciet bene Dominus, et non faciet male. <l eID="gen31346" level="1"/>

** Zephaniah 1:13

Et erit fortitudo eorum in direptionem, <l eID="gen31347" level="1"/> <l level="1" sID="gen31348"/>et domus eorum in desertum : <l eID="gen31348" level="1"/> <l level="1" sID="gen31349"/>et ædificabunt domos, et non habitabunt ; <l eID="gen31349" level="1"/> <l level="1" sID="gen31350"/>et plantabunt vineas, et non bibent vinum earum. <l eID="gen31350" level="1"/>

** Zephaniah 1:14

Juxta est dies Domini magnus : <l eID="gen31351" level="1"/> <l level="1" sID="gen31352"/>juxta est, et velox nimis. <l eID="gen31352" level="1"/> <l level="1" sID="gen31353"/>Vox diei Domini amara : <l eID="gen31353" level="1"/> <l level="1" sID="gen31354"/>tribulabitur ibi fortis. <l eID="gen31354" level="1"/>

** Zephaniah 1:15

Dies iræ dies illa, <l eID="gen31355" level="1"/> <l level="1" sID="gen31356"/>dies tribulationis et angustiæ, <l eID="gen31356" level="1"/> <l level="1" sID="gen31357"/>dies calamitatis et miseriæ, <l eID="gen31357" level="1"/> <l level="1" sID="gen31358"/>dies tenebrarum et caliginis, <l eID="gen31358" level="1"/> <l level="1" sID="gen31359"/>dies nebulæ et turbinis, <l eID="gen31359" level="1"/>

** Zephaniah 1:16

dies tubæ et clangoris super civitates munitas, <l eID="gen31360" level="1"/> <l level="1" sID="gen31361"/>et super angulos excelsos. <l eID="gen31361" level="1"/>

** Zephaniah 1:17

Et tribulabo homines, et ambulabunt ut cæci, <l eID="gen31362" level="1"/> <l level="1" sID="gen31363"/>quia Domino peccaverunt ; <l eID="gen31363" level="1"/> <l level="1" sID="gen31364"/>et effundetur sanguis eorum sicut humus, <l eID="gen31364" level="1"/> <l level="1" sID="gen31365"/>et corpora eorum sicut stercora. <l eID="gen31365" level="1"/>

** Zephaniah 1:18

Sed et argentum eorum et aurum eorum non poterit liberare eos <l eID="gen31366" level="1"/> <l level="1" sID="gen31367"/>in die iræ Domini : <l eID="gen31367" level="1"/> <l level="1" sID="gen31368"/>in igne zeli ejus devorabitur omnis terra, <l eID="gen31368" level="1"/> <l level="1" sID="gen31369"/>quia consummationem cum festinatione faciet <l eID="gen31369" level="1"/> <l level="1" sID="gen31370"/>cunctis habitantibus terram.  <chapter eID="Zeph.1"/>

* Zephaniah 2

** Zephaniah 2:1

Convenite, congregamini, gens non amabilis, <l eID="gen31371" level="1"/>

** Zephaniah 2:2

priusquam pariat jussio quasi pulverem transeuntem diem, <l eID="gen31372" level="1"/> <l level="1" sID="gen31373"/>antequam veniat super vos ira furoris Domini, <l eID="gen31373" level="1"/> <l level="1" sID="gen31374"/>antequam veniat super vos dies indignationis Domini. <l eID="gen31374" level="1"/>

** Zephaniah 2:3

Quærite Dominum, omnes mansueti terræ, <l eID="gen31375" level="1"/> <l level="1" sID="gen31376"/>qui judicium ejus estis operati ; <l eID="gen31376" level="1"/> <l level="1" sID="gen31377"/>quærite justum, quærite mansuetum, <l eID="gen31377" level="1"/> <l level="1" sID="gen31378"/>si quomodo abscondamini in die furoris Domini. <l eID="gen31378" level="1"/>

** Zephaniah 2:4

Quia Gaza destructa erit, <l eID="gen31379" level="1"/> <l level="1" sID="gen31380"/>et Ascalon in desertum : <l eID="gen31380" level="1"/> <l level="1" sID="gen31381"/>Azotum in meridie ejicient, <l eID="gen31381" level="1"/> <l level="1" sID="gen31382"/>et Accaron eradicabitur. <l eID="gen31382" level="1"/>

** Zephaniah 2:5

Væ qui habitatis funiculum maris, gens perditorum ! <l eID="gen31383" level="1"/> <l level="1" sID="gen31384"/>verbum Domini super vos, Chanaan, terra Philisthinorum ; <l eID="gen31384" level="1"/> <l level="1" sID="gen31385"/>et disperdam te, ita ut non sit inhabitator. <l eID="gen31385" level="1"/>

** Zephaniah 2:6

Et erit funiculus maris requies pastorum, et caulæ pecorum ; <l eID="gen31386" level="1"/>

** Zephaniah 2:7

et erit funiculus ejus qui remanserit de domo Juda : ibi pascentur, <l eID="gen31387" level="1"/> <l level="1" sID="gen31388"/>in domibus Ascalonis ad vesperam requiescent, <l eID="gen31388" level="1"/> <l level="1" sID="gen31389"/>quia visitabit eos Dominus Deus eorum, <l eID="gen31389" level="1"/> <l level="1" sID="gen31390"/>et avertet captivitatem eorum. <l eID="gen31390" level="1"/>

** Zephaniah 2:8

Audivi opprobrium Moab, <l eID="gen31391" level="1"/> <l level="1" sID="gen31392"/>et blasphemias filiorum Ammon, <l eID="gen31392" level="1"/> <l level="1" sID="gen31393"/>quæ exprobraverunt populo meo, <l eID="gen31393" level="1"/> <l level="1" sID="gen31394"/>et magnificati sunt super terminos eorum. <l eID="gen31394" level="1"/>

** Zephaniah 2:9

Propterea vivo ego, dicit Dominus exercituum, Deus Israël, <l eID="gen31395" level="1"/> <l level="1" sID="gen31396"/>quia Moab ut Sodoma erit, <l eID="gen31396" level="1"/> <l level="1" sID="gen31397"/>et filii Ammon quasi Gomorrha : <l eID="gen31397" level="1"/> <l level="1" sID="gen31398"/>siccitas spinarum, et acervi salis, <l eID="gen31398" level="1"/> <l level="1" sID="gen31399"/>et desertum usque in æternum : <l eID="gen31399" level="1"/> <l level="1" sID="gen31400"/>reliquiæ populi mei diripient eos, <l eID="gen31400" level="1"/> <l level="1" sID="gen31401"/>et residui gentis meæ possidebunt illos. <l eID="gen31401" level="1"/>

** Zephaniah 2:10

Hoc eis eveniet pro superbia sua, <l eID="gen31402" level="1"/> <l level="1" sID="gen31403"/>quia blasphemaverunt et magnificati sunt <l eID="gen31403" level="1"/> <l level="1" sID="gen31404"/>super populum Domini exercituum. <l eID="gen31404" level="1"/>

** Zephaniah 2:11

Horribilis Dominus super eos, <l eID="gen31405" level="1"/> <l level="1" sID="gen31406"/>et attenuabit omnes deos terræ : <l eID="gen31406" level="1"/> <l level="1" sID="gen31407"/>et adorabunt eum viri de loco suo, <l eID="gen31407" level="1"/> <l level="1" sID="gen31408"/>omnes insulæ gentium. <l eID="gen31408" level="1"/>

** Zephaniah 2:12

Sed et vos, Æthiopes, interfecti gladio meo eritis. <l eID="gen31409" level="1"/>

** Zephaniah 2:13

Et extendet manum suam super aquilonem, et perdet Assur, <l eID="gen31410" level="1"/> <l level="1" sID="gen31411"/>et ponet speciosam in solitudinem, <l eID="gen31411" level="1"/> <l level="1" sID="gen31412"/>et in invium, et quasi desertum. <l eID="gen31412" level="1"/>

** Zephaniah 2:14

Et accubabunt in medio ejus greges, omnes bestiæ gentium ; <l eID="gen31413" level="1"/> <l level="1" sID="gen31414"/>et onocrotalus et ericius in liminibus ejus morabuntur : <l eID="gen31414" level="1"/> <l level="1" sID="gen31415"/>vox cantantis in fenestra, <l eID="gen31415" level="1"/> <l level="1" sID="gen31416"/>corvus in superliminari, <l eID="gen31416" level="1"/> <l level="1" sID="gen31417"/>quoniam attenuabo robur ejus. <l eID="gen31417" level="1"/>

** Zephaniah 2:15

Hæc est civitas gloriosa habitans in confidentia, <l eID="gen31418" level="1"/> <l level="1" sID="gen31419"/>quæ dicebat in corde suo : <l eID="gen31419" level="1"/> <l level="1" sID="gen31420"/>Ego sum, et extra me non est alia amplius : <l eID="gen31420" level="1"/> <l level="1" sID="gen31421"/>quomodo facta est in desertum cubile bestiæ ? <l eID="gen31421" level="1"/> <l level="1" sID="gen31422"/>omnis qui transit per eam sibilabit, <l eID="gen31422" level="1"/> <l level="1" sID="gen31423"/>et movebit manum suam.  <chapter eID="Zeph.2"/>

* Zephaniah 3

** Zephaniah 3:1

Væ provocatrix, et redempta civitas, columba ! <l eID="gen31424" level="1"/>

** Zephaniah 3:2

non audivit vocem, <l eID="gen31425" level="1"/> <l level="1" sID="gen31426"/>et non suscepit disciplinam ; <l eID="gen31426" level="1"/> <l level="1" sID="gen31427"/>in Domino non est confisa, <l eID="gen31427" level="1"/> <l level="1" sID="gen31428"/>ad Deum suum non appropinquavit. <l eID="gen31428" level="1"/>

** Zephaniah 3:3

Principes ejus in medio ejus quasi leones rugientes ; <l eID="gen31429" level="1"/> <l level="1" sID="gen31430"/>judices ejus lupi vespere, non relinquebant in mane. <l eID="gen31430" level="1"/>

** Zephaniah 3:4

Prophetæ ejus vesani, viri infideles ; <l eID="gen31431" level="1"/> <l level="1" sID="gen31432"/>sacerdotes ejus polluerunt sanctum, <l eID="gen31432" level="1"/> <l level="1" sID="gen31433"/>injuste egerunt contra legem. <l eID="gen31433" level="1"/>

** Zephaniah 3:5

Dominus justus in medio ejus non faciet iniquitatem ; <l eID="gen31434" level="1"/> <l level="1" sID="gen31435"/>mane, mane judicium suum dabit in lucem, et non abscondetur ; <l eID="gen31435" level="1"/> <l level="1" sID="gen31436"/>nescivit autem iniquus confusionem. <l eID="gen31436" level="1"/>

** Zephaniah 3:6

Disperdidi gentes, <l eID="gen31437" level="1"/> <l level="1" sID="gen31438"/>et dissipati sunt anguli earum ; <l eID="gen31438" level="1"/> <l level="1" sID="gen31439"/>desertas feci vias eorum, <l eID="gen31439" level="1"/> <l level="1" sID="gen31440"/>dum non est qui transeat ; <l eID="gen31440" level="1"/> <l level="1" sID="gen31441"/>desolatæ sunt civitates eorum, <l eID="gen31441" level="1"/> <l level="1" sID="gen31442"/>non remanente viro, neque ullo habitatore. <l eID="gen31442" level="1"/>

** Zephaniah 3:7

Dixi : Attamen timebis me, <l eID="gen31443" level="1"/> <l level="1" sID="gen31444"/>suscipies disciplinam ; <l eID="gen31444" level="1"/> <l level="1" sID="gen31445"/>et non peribit habitaculum ejus, <l eID="gen31445" level="1"/> <l level="1" sID="gen31446"/>propter omnia in quibus visitavi eam : <l eID="gen31446" level="1"/> <l level="1" sID="gen31447"/>verumtamen diluculo surgentes corruperunt omnes cogitationes suas. <l eID="gen31447" level="1"/>

** Zephaniah 3:8

Quapropter exspecta me, dicit Dominus, <l eID="gen31448" level="1"/> <l level="1" sID="gen31449"/>in die resurrectionis meæ in futurum : <l eID="gen31449" level="1"/> <l level="1" sID="gen31450"/>quia judicium meum ut congregem gentes, <l eID="gen31450" level="1"/> <l level="1" sID="gen31451"/>et colligam regna, <l eID="gen31451" level="1"/> <l level="1" sID="gen31452"/>et effundam super eos indignationem meam, <l eID="gen31452" level="1"/> <l level="1" sID="gen31453"/>omnem iram furoris mei : <l eID="gen31453" level="1"/> <l level="1" sID="gen31454"/>in igne enim zeli mei devorabitur omnis terra. <l eID="gen31454" level="1"/>

** Zephaniah 3:9

Quia tunc reddam populis labium electum, <l eID="gen31455" level="1"/> <l level="1" sID="gen31456"/>ut invocent omnes in nomine Domini, <l eID="gen31456" level="1"/> <l level="1" sID="gen31457"/>et serviant ei humero uno. <l eID="gen31457" level="1"/>

** Zephaniah 3:10

Ultra flumina Æthiopiæ, inde supplices mei ; <l eID="gen31458" level="1"/> <l level="1" sID="gen31459"/>filii dispersorum meorum deferent munus mihi. <l eID="gen31459" level="1"/>

** Zephaniah 3:11

In die illa non confunderis super cunctis adinventionibus tuis, <l eID="gen31460" level="1"/> <l level="1" sID="gen31461"/>quibus prævaricata es in me, <l eID="gen31461" level="1"/> <l level="1" sID="gen31462"/>quia tunc auferam de medio tui magniloquos superbiæ tuæ, <l eID="gen31462" level="1"/> <l level="1" sID="gen31463"/>et non adjicies exaltari amplius in monte sancto meo. <l eID="gen31463" level="1"/>

** Zephaniah 3:12

Et derelinquam in medio tui populum pauperem et egenum : <l eID="gen31464" level="1"/> <l level="1" sID="gen31465"/>et sperabunt in nomine Domini. <l eID="gen31465" level="1"/>

** Zephaniah 3:13

Reliquiæ Israël non facient iniquitatem, <l eID="gen31466" level="1"/> <l level="1" sID="gen31467"/>nec loquentur mendacium, <l eID="gen31467" level="1"/> <l level="1" sID="gen31468"/>et non invenietur in ore eorum lingua dolosa, <l eID="gen31468" level="1"/> <l level="1" sID="gen31469"/>quoniam ipsi pascentur, et accubabunt, <l eID="gen31469" level="1"/> <l level="1" sID="gen31470"/>et non erit qui exterreat. <l eID="gen31470" level="1"/>

** Zephaniah 3:14

Lauda, filia Sion ; jubila, Israël : <l eID="gen31471" level="1"/> <l level="1" sID="gen31472"/>lætare, et exsulta in omni corde, filia Jerusalem. <l eID="gen31472" level="1"/>

** Zephaniah 3:15

Abstulit Dominus judicium tuum ; <l eID="gen31473" level="1"/> <l level="1" sID="gen31474"/>avertit inimicos tuos. <l eID="gen31474" level="1"/> <l level="1" sID="gen31475"/>Rex Israël Dominus in medio tui : <l eID="gen31475" level="1"/> <l level="1" sID="gen31476"/>non timebis malum ultra. <l eID="gen31476" level="1"/>

** Zephaniah 3:16

In die illa dicetur Jerusalem : <l eID="gen31477" level="1"/> <l level="1" sID="gen31478"/>Noli timere ; Sion : Non dissolvantur manus tuæ. <l eID="gen31478" level="1"/>

** Zephaniah 3:17

Dominus Deus tuus in medio tui fortis, ipse salvabit : <l eID="gen31479" level="1"/> <l level="1" sID="gen31480"/>gaudebit super te in lætitia, <l eID="gen31480" level="1"/> <l level="1" sID="gen31481"/>silebit in dilectione sua, <l eID="gen31481" level="1"/> <l level="1" sID="gen31482"/>exsultabit super te in laude. <l eID="gen31482" level="1"/>

** Zephaniah 3:18

Nugas, qui a lege recesserant, <l eID="gen31483" level="1"/> <l level="1" sID="gen31484"/>congregabo, quia ex te erant : <l eID="gen31484" level="1"/> <l level="1" sID="gen31485"/>ut non ultra habeas super eis opprobrium. <l eID="gen31485" level="1"/>

** Zephaniah 3:19

Ecce ego interficiam omnes qui afflixerunt te in tempore illo : <l eID="gen31486" level="1"/> <l level="1" sID="gen31487"/>et salvabo claudicantem, <l eID="gen31487" level="1"/> <l level="1" sID="gen31488"/>et eam quæ ejecta fuerat congregabo : <l eID="gen31488" level="1"/> <l level="1" sID="gen31489"/>et ponam eos in laudem, et in nomen, <l eID="gen31489" level="1"/> <l level="1" sID="gen31490"/>in omni terra confusionis eorum, <l eID="gen31490" level="1"/>

** Zephaniah 3:20

in tempore illo quo adducam vos, <l eID="gen31491" level="1"/> <l level="1" sID="gen31492"/>et in tempore quo congregabo vos. <l eID="gen31492" level="1"/> <l level="1" sID="gen31493"/>Dabo enim vos in nomen, <l eID="gen31493" level="1"/> <l level="1" sID="gen31494"/>et in laudem omnibus populis terræ, <l eID="gen31494" level="1"/> <l level="1" sID="gen31495"/>cum convertero captivitatem vestram coram oculis vestris, <l eID="gen31495" level="1"/> <l level="1" sID="gen31496"/>dicit Dominus. <l eID="gen31496" level="1"/> <lg eID="gen31309"/> <chapter eID="Zeph.3"/> <div eID="gen31307" osisID="Zeph" type="book"/>

