#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup 

* Zephaniah 1

** Zephaniah 1:1

Verbum Domini quod factum est ad Sophoniam, filium Chusi, filii Godoliæ, filii Amariæ, filii Ezeciæ, in diebus Josiæ, filii Amon, regis Judæ.  <div eID="gen31308" type="x-p"/>

** Zephaniah 1:2

Congregans congregabo omnia a facie terræ, dicit Dominus : <l eID="gen31310" level="1"/>

** Zephaniah 1:3

congregans hominem et pecus, <l eID="gen31311" level="1"/> <l level="1" sID="gen31312"/>congregans volatilia cæli et pisces maris : <l eID="gen31312" level="1"/> <l level="1" sID="gen31313"/>et ruinæ impiorum erunt, <l eID="gen31313" level="1"/> <l level="1" sID="gen31314"/>et disperdam homines a facie terræ, dicit Dominus. <l eID="gen31314" level="1"/>

** Zephaniah 1:4

Et extendam manum meam super Judam <l eID="gen31315" level="1"/> <l level="1" sID="gen31316"/>et super omnes habitantes Jerusalem : <l eID="gen31316" level="1"/> <l level="1" sID="gen31317"/>et disperdam de loco hoc reliquias Baal, <l eID="gen31317" level="1"/> <l level="1" sID="gen31318"/>et nomina ædituorum cum sacerdotibus ; <l eID="gen31318" level="1"/>

** Zephaniah 1:5

et eos qui adorant super tecta militiam cæli, <l eID="gen31319" level="1"/> <l level="1" sID="gen31320"/>et adorant et jurant in Domino, <l eID="gen31320" level="1"/> <l level="1" sID="gen31321"/>et jurant in Melchom ; <l eID="gen31321" level="1"/>

** Zephaniah 1:6

et qui avertuntur de post tergum Domini, <l eID="gen31322" level="1"/> <l level="1" sID="gen31323"/>et qui non quæsierunt Dominum, <l eID="gen31323" level="1"/> <l level="1" sID="gen31324"/>nec investigaverunt eum. <l eID="gen31324" level="1"/>

** Zephaniah 1:7

Silete a facie Domini Dei, <l eID="gen31325" level="1"/> <l level="1" sID="gen31326"/>quia juxta est dies Domini : <l eID="gen31326" level="1"/> <l level="1" sID="gen31327"/>quia præparavit Dominus hostiam ; <l eID="gen31327" level="1"/> <l level="1" sID="gen31328"/>sanctificavit vocatos suos. <l eID="gen31328" level="1"/>

** Zephaniah 1:8

Et erit : in die hostiæ Domini, <l eID="gen31329" level="1"/> <l level="1" sID="gen31330"/>visitabo super principes, <l eID="gen31330" level="1"/> <l level="1" sID="gen31331"/>et super filios regis, <l eID="gen31331" level="1"/> <l level="1" sID="gen31332"/>et super omnes qui induti sunt veste peregrina ; <l eID="gen31332" level="1"/>

** Zephaniah 1:9

et visitabo super omnem qui arroganter ingreditur super limen in die illa, <l eID="gen31333" level="1"/> <l level="1" sID="gen31334"/>qui complent domum Domini Dei sui iniquitate et dolo. <l eID="gen31334" level="1"/>

** Zephaniah 1:10

Et erit in die illa, dicit Dominus, <l eID="gen31335" level="1"/> <l level="1" sID="gen31336"/>vox clamoris a porta piscium, <l eID="gen31336" level="1"/> <l level="1" sID="gen31337"/>et ululatus a Secunda, <l eID="gen31337" level="1"/> <l level="1" sID="gen31338"/>et contritio magna a collibus. <l eID="gen31338" level="1"/>

** Zephaniah 1:11

Ululate, habitatores Pilæ : <l eID="gen31339" level="1"/> <l level="1" sID="gen31340"/>conticuit omnis populus Chanaan, <l eID="gen31340" level="1"/> <l level="1" sID="gen31341"/>disperierunt omnes involuti argento. <l eID="gen31341" level="1"/>

** Zephaniah 1:12

Et erit in tempore illo : <l eID="gen31342" level="1"/> <l level="1" sID="gen31343"/>scrutabor Jerusalem in lucernis, <l eID="gen31343" level="1"/> <l level="1" sID="gen31344"/>et visitabo super viros defixos in fæcibus suis, <l eID="gen31344" level="1"/> <l level="1" sID="gen31345"/>qui dicunt in cordibus suis : <l eID="gen31345" level="1"/> <l level="1" sID="gen31346"/>Non faciet bene Dominus, et non faciet male. <l eID="gen31346" level="1"/>

** Zephaniah 1:13

Et erit fortitudo eorum in direptionem, <l eID="gen31347" level="1"/> <l level="1" sID="gen31348"/>et domus eorum in desertum : <l eID="gen31348" level="1"/> <l level="1" sID="gen31349"/>et ædificabunt domos, et non habitabunt ; <l eID="gen31349" level="1"/> <l level="1" sID="gen31350"/>et plantabunt vineas, et non bibent vinum earum. <l eID="gen31350" level="1"/>

** Zephaniah 1:14

Juxta est dies Domini magnus : <l eID="gen31351" level="1"/> <l level="1" sID="gen31352"/>juxta est, et velox nimis. <l eID="gen31352" level="1"/> <l level="1" sID="gen31353"/>Vox diei Domini amara : <l eID="gen31353" level="1"/> <l level="1" sID="gen31354"/>tribulabitur ibi fortis. <l eID="gen31354" level="1"/>

** Zephaniah 1:15

Dies iræ dies illa, <l eID="gen31355" level="1"/> <l level="1" sID="gen31356"/>dies tribulationis et angustiæ, <l eID="gen31356" level="1"/> <l level="1" sID="gen31357"/>dies calamitatis et miseriæ, <l eID="gen31357" level="1"/> <l level="1" sID="gen31358"/>dies tenebrarum et caliginis, <l eID="gen31358" level="1"/> <l level="1" sID="gen31359"/>dies nebulæ et turbinis, <l eID="gen31359" level="1"/>

** Zephaniah 1:16

dies tubæ et clangoris super civitates munitas, <l eID="gen31360" level="1"/> <l level="1" sID="gen31361"/>et super angulos excelsos. <l eID="gen31361" level="1"/>

** Zephaniah 1:17

Et tribulabo homines, et ambulabunt ut cæci, <l eID="gen31362" level="1"/> <l level="1" sID="gen31363"/>quia Domino peccaverunt ; <l eID="gen31363" level="1"/> <l level="1" sID="gen31364"/>et effundetur sanguis eorum sicut humus, <l eID="gen31364" level="1"/> <l level="1" sID="gen31365"/>et corpora eorum sicut stercora. <l eID="gen31365" level="1"/>

** Zephaniah 1:18

Sed et argentum eorum et aurum eorum non poterit liberare eos <l eID="gen31366" level="1"/> <l level="1" sID="gen31367"/>in die iræ Domini : <l eID="gen31367" level="1"/> <l level="1" sID="gen31368"/>in igne zeli ejus devorabitur omnis terra, <l eID="gen31368" level="1"/> <l level="1" sID="gen31369"/>quia consummationem cum festinatione faciet <l eID="gen31369" level="1"/> <l level="1" sID="gen31370"/>cunctis habitantibus terram.  <chapter eID="Zeph.1"/>

* Zephaniah 2

** Zephaniah 2:1

Convenite, congregamini, gens non amabilis, <l eID="gen31371" level="1"/>

** Zephaniah 2:2

priusquam pariat jussio quasi pulverem transeuntem diem, <l eID="gen31372" level="1"/> <l level="1" sID="gen31373"/>antequam veniat super vos ira furoris Domini, <l eID="gen31373" level="1"/> <l level="1" sID="gen31374"/>antequam veniat super vos dies indignationis Domini. <l eID="gen31374" level="1"/>

** Zephaniah 2:3

Quærite Dominum, omnes mansueti terræ, <l eID="gen31375" level="1"/> <l level="1" sID="gen31376"/>qui judicium ejus estis operati ; <l eID="gen31376" level="1"/> <l level="1" sID="gen31377"/>quærite justum, quærite mansuetum, <l eID="gen31377" level="1"/> <l level="1" sID="gen31378"/>si quomodo abscondamini in die furoris Domini. <l eID="gen31378" level="1"/>

** Zephaniah 2:4

Quia Gaza destructa erit, <l eID="gen31379" level="1"/> <l level="1" sID="gen31380"/>et Ascalon in desertum : <l eID="gen31380" level="1"/> <l level="1" sID="gen31381"/>Azotum in meridie ejicient, <l eID="gen31381" level="1"/> <l level="1" sID="gen31382"/>et Accaron eradicabitur. <l eID="gen31382" level="1"/>

** Zephaniah 2:5

Væ qui habitatis funiculum maris, gens perditorum ! <l eID="gen31383" level="1"/> <l level="1" sID="gen31384"/>verbum Domini super vos, Chanaan, terra Philisthinorum ; <l eID="gen31384" level="1"/> <l level="1" sID="gen31385"/>et disperdam te, ita ut non sit inhabitator. <l eID="gen31385" level="1"/>

** Zephaniah 2:6

Et erit funiculus maris requies pastorum, et caulæ pecorum ; <l eID="gen31386" level="1"/>

** Zephaniah 2:7

et erit funiculus ejus qui remanserit de domo Juda : ibi pascentur, <l eID="gen31387" level="1"/> <l level="1" sID="gen31388"/>in domibus Ascalonis ad vesperam requiescent, <l eID="gen31388" level="1"/> <l level="1" sID="gen31389"/>quia visitabit eos Dominus Deus eorum, <l eID="gen31389" level="1"/> <l level="1" sID="gen31390"/>et avertet captivitatem eorum. <l eID="gen31390" level="1"/>

** Zephaniah 2:8

Audivi opprobrium Moab, <l eID="gen31391" level="1"/> <l level="1" sID="gen31392"/>et blasphemias filiorum Ammon, <l eID="gen31392" level="1"/> <l level="1" sID="gen31393"/>quæ exprobraverunt populo meo, <l eID="gen31393" level="1"/> <l level="1" sID="gen31394"/>et magnificati sunt super terminos eorum. <l eID="gen31394" level="1"/>

** Zephaniah 2:9

Propterea vivo ego, dicit Dominus exercituum, Deus Israël,  quia Moab ut Sodoma erit,  et filii Ammon quasi Gomorrha :  siccitas spinarum, et acervi salis,  et desertum usque in æternum :  reliquiæ populi mei diripient eos,  et residui gentis meæ possidebunt illos. 

** Zephaniah 2:10

Hoc eis eveniet pro superbia sua,  quia blasphemaverunt et magnificati sunt  super populum Domini exercituum. 

** Zephaniah 2:11

Horribilis Dominus super eos,  et attenuabit omnes deos terræ :  et adorabunt eum viri de loco suo,  omnes insulæ gentium. 

** Zephaniah 2:12

Sed et vos, Æthiopes, interfecti gladio meo eritis. 

** Zephaniah 2:13

Et extendet manum suam super aquilonem, et perdet Assur,  et ponet speciosam in solitudinem,  et in invium, et quasi desertum. 

** Zephaniah 2:14

Et accubabunt in medio ejus greges, omnes bestiæ gentium ;  et onocrotalus et ericius in liminibus ejus morabuntur :  vox cantantis in fenestra,  corvus in superliminari,  quoniam attenuabo robur ejus. 

** Zephaniah 2:15

Hæc est civitas gloriosa habitans in confidentia,  quæ dicebat in corde suo :  Ego sum, et extra me non est alia amplius :  quomodo facta est in desertum cubile bestiæ ?  omnis qui transit per eam sibilabit,  et movebit manum suam.  

* Zephaniah 3

** Zephaniah 3:1

Væ provocatrix, et redempta civitas, columba ! 

** Zephaniah 3:2

non audivit vocem,  et non suscepit disciplinam ;  in Domino non est confisa,  ad Deum suum non appropinquavit. 

** Zephaniah 3:3

Principes ejus in medio ejus quasi leones rugientes ;  judices ejus lupi vespere, non relinquebant in mane. 

** Zephaniah 3:4

Prophetæ ejus vesani, viri infideles ;  sacerdotes ejus polluerunt sanctum,  injuste egerunt contra legem. 

** Zephaniah 3:5

Dominus justus in medio ejus non faciet iniquitatem ;  mane, mane judicium suum dabit in lucem, et non abscondetur ;  nescivit autem iniquus confusionem. 

** Zephaniah 3:6

Disperdidi gentes,  et dissipati sunt anguli earum ;  desertas feci vias eorum,  dum non est qui transeat ;  desolatæ sunt civitates eorum,  non remanente viro, neque ullo habitatore. 

** Zephaniah 3:7

Dixi : Attamen timebis me,  suscipies disciplinam ;  et non peribit habitaculum ejus,  propter omnia in quibus visitavi eam :  verumtamen diluculo surgentes corruperunt omnes cogitationes suas. 

** Zephaniah 3:8

Quapropter exspecta me, dicit Dominus,  in die resurrectionis meæ in futurum :  quia judicium meum ut congregem gentes,  et colligam regna,  et effundam super eos indignationem meam,  omnem iram furoris mei :  in igne enim zeli mei devorabitur omnis terra. 

** Zephaniah 3:9

Quia tunc reddam populis labium electum,  ut invocent omnes in nomine Domini,  et serviant ei humero uno. 

** Zephaniah 3:10

Ultra flumina Æthiopiæ, inde supplices mei ;  filii dispersorum meorum deferent munus mihi. 

** Zephaniah 3:11

In die illa non confunderis super cunctis adinventionibus tuis,  quibus prævaricata es in me,  quia tunc auferam de medio tui magniloquos superbiæ tuæ,  et non adjicies exaltari amplius in monte sancto meo. 

** Zephaniah 3:12

Et derelinquam in medio tui populum pauperem et egenum :  et sperabunt in nomine Domini. 

** Zephaniah 3:13

Reliquiæ Israël non facient iniquitatem,  nec loquentur mendacium,  et non invenietur in ore eorum lingua dolosa,  quoniam ipsi pascentur, et accubabunt,  et non erit qui exterreat. 

** Zephaniah 3:14

Lauda, filia Sion ; jubila, Israël :  lætare, et exsulta in omni corde, filia Jerusalem. 

** Zephaniah 3:15

Abstulit Dominus judicium tuum ;  avertit inimicos tuos.  Rex Israël Dominus in medio tui :  non timebis malum ultra. 

** Zephaniah 3:16

In die illa dicetur Jerusalem :  Noli timere ; Sion : Non dissolvantur manus tuæ. 

** Zephaniah 3:17

Dominus Deus tuus in medio tui fortis, ipse salvabit :  gaudebit super te in lætitia,  silebit in dilectione sua,  exsultabit super te in laude. 

** Zephaniah 3:18

Nugas, qui a lege recesserant,  congregabo, quia ex te erant :  ut non ultra habeas super eis opprobrium. 

** Zephaniah 3:19

Ecce ego interficiam omnes qui afflixerunt te in tempore illo :  et salvabo claudicantem,  et eam quæ ejecta fuerat congregabo :  et ponam eos in laudem, et in nomen,  in omni terra confusionis eorum, 

** Zephaniah 3:20

in tempore illo quo adducam vos,  et in tempore quo congregabo vos.  Dabo enim vos in nomen,  et in laudem omnibus populis terræ,  cum convertero captivitatem vestram coram oculis vestris,  dicit Dominus.    

